### ISSUE TITLE
Pixiv Sketch error message: httperror_seek_wrapper: HTTP Error 404: Not Found v20210822

### ISSUE THREAD

**Issue by SnakeEve** [Nandaka/PixivUtil2#1019]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

I found something, after the implementation of https://github.com/Nandaka/PixivUtil2/commit/e92b2a49d9618e5a41cfc04f3afc8f5c9e1e0975, https://github.com/Nandaka/PixivUtil2/commit/681a11ebb6ea1ee0a1dd61d12b0a271eca7fdd04 and https://github.com/Nandaka/PixivUtil2/commit/80e9db9be3498f98911a2acb45e900e6b7f1a1fb, every problem related with the recent implementation of Pixiv Sketch download has been solved. However one last thing, every my download session, when the download reaches an artist with a removed Pixiv Sketch image (my assumption), the downloader prints the following error below. The error message itself was not breaking the download, however i just want to inform that such error exists, and maybe this error might bring another issue in the future or something.

PS: If a list of artists that cause this issue is necessary, i will provide further

### Steps to Reproduce

1. Download until reaches an artist with deleted pixiv sketch, i think

**Expected behavior:** [What you expected to happen]

More streamlined error message, or anything that might prevent another unexpected issue in the future

**Actual behavior:** [What actually happened]

These following error happened

```
2021-10-01 04:40:13,160 - PixivUtil20210822 - DEBUG - using webrpc: https://www.pixiv.net/rpc/get_work.php?id=93069068
2021-10-01 04:40:13,177 - PixivUtil20210822 - DEBUG - Getting sketch artist detail from https://sketch.pixiv.net/api/users/@minttchocok05.json
2021-10-01 04:40:13,507 - PixivUtil20210822 - ERROR - Error at process_sketch_artists(): minttchocok05
2021-10-01 04:40:13,509 - PixivUtil20210822 - ERROR - Traceback (most recent call last):
  File "D:\Python\PixivUtil2\PixivSketchHandler.py", line 46, in process_sketch_artists
    artist = br.sketch_get_posts_by_artist_id(artist_id, end_page)
  File "D:\Python\PixivUtil2\PixivBrowserFactory.py", line 1054, in sketch_get_posts_by_artist_id
    response = self.getPixivSketchPage(url=url, referer=referer, x_requested_with=x_requested_with)
  File "D:\Python\PixivUtil2\PixivBrowserFactory.py", line 1092, in getPixivSketchPage
    p_res = self.open_with_retry(p_req)
  File "D:\Python\PixivUtil2\PixivBrowserFactory.py", line 208, in open_with_retry
    res = self.open(url, data, timeout)
  File "C:\Users\marce\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mechanize\_mechanize.py", line 257, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
  File "C:\Users\marce\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mechanize\_mechanize.py", line 313, in _mech_open
    raise response
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 404: Not Found
```

### Versions

20210822, master branch

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by Nandaka** [comment]
looks like so, the page `https://sketch.pixiv.net/@minttchocok05` doesn't return the normal sketch page.

**Comment by PatrickL546** [comment]
Created this before I saw this.
https://github.com/Nandaka/PixivUtil2/issues/1054

Sketch download seems to be fully broken
