### ISSUE TITLE
Can't download images "Error at process_image_bookmark" "No such file or directory"

### ISSUE THREAD

**Issue by AnsuzJeran** [Nandaka/PixivUtil2#1066]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

As usual i tried to Start the tool to download some images but i began to get this dead end that dont let me download
I Updated my Program
Flushing my DNS cache
Restart My PC
Tried a Semi Fresh install just copying pasting my 
Pixiv Log 
Login Cookie *Config File*
FFmpeg Settings *Config File*
Ugoria settings *Config File*
browsers
library info

I Belive i did read every fix posible and possible solution but point me in the right direction if i failed

### Steps to Reproduce

1. Open Program
2. download bookmarked/Private images
3. wait to read X number of bookmark pages usually 5, 8, 18 up to 40
4. error prevents me from downloading anything

**Expected behavior:**
Download Private Bookmarked images

**Actual behavior:**
Dead end where i can't download my Bookmarked private images

**Log Pasted**
--------------------------------------------------------------------------------------------------------------------------

PixivUtil20211104 - INFO - Source URL: https://www.pixiv.net/ajax/user/XXXXX/illusts/bookmarks?tag=&offset=192&limit=48&rest=hide
PixivUtil20211104 - ERROR - Error at process_image_bookmark(): (<class 'urllib.error.URLError'>, URLError(FileNotFoundError(2, 'No such file or directory')), <traceback object at 0x0370E168>)
2021-12-24 20:05:12,754 - PixivUtil20211104 - ERROR - Traceback (most recent call last):
  File "mechanize\_urllib2_fork.pyc", line 1229, in do_open
  File "http\client.pyc", line 1257, in request
  File "http\client.pyc", line 1303, in _send_request
  File "http\client.pyc", line 1252, in endheaders
  File "http\client.pyc", line 1012, in _send_output
  File "http\client.pyc", line 952, in send
  File "http\client.pyc", line 1426, in connect
  File "ssl.pyc", line 500, in wrap_socket
  File "ssl.pyc", line 1040, in _create
  File "ssl.pyc", line 1309, in do_handshake
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PixivBookmarkHandler.pyc", line 83, in process_image_bookmark
  File "PixivBookmarkHandler.pyc", line 369, in get_image_bookmark
  File "mechanize\_mechanize.pyc", line 257, in open
  File "mechanize\_mechanize.pyc", line 287, in _mech_open
  File "mechanize\_opener.pyc", line 193, in open
  File "mechanize\_urllib2_fork.pyc", line 425, in _open
  File "mechanize\_urllib2_fork.pyc", line 414, in _call_chain
  File "mechanize\_urllib2_fork.pyc", line 1276, in https_open
  File "mechanize\_urllib2_fork.pyc", line 1233, in do_open
urllib.error.URLError: <urlopen error [Errno 2] No such file or directory>

2021-12-24 20:05:12,778 - PixivUtil20211104 - ERROR - Unknown Error: <urlopen error [Errno 2] No such file or directory>
Traceback (most recent call last):
  File "mechanize\_urllib2_fork.pyc", line 1229, in do_open
  File "http\client.pyc", line 1257, in request
  File "http\client.pyc", line 1303, in _send_request
  File "http\client.pyc", line 1252, in endheaders
  File "http\client.pyc", line 1012, in _send_output
  File "http\client.pyc", line 952, in send
  File "http\client.pyc", line 1426, in connect
  File "ssl.pyc", line 500, in wrap_socket
  File "ssl.pyc", line 1040, in _create
  File "ssl.pyc", line 1309, in do_handshake
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PixivUtil2.py", line 1462, in main
  File "PixivUtil2.py", line 1154, in main_loop
  File "PixivUtil2.py", line 554, in menu_download_from_online_image_bookmark
  File "PixivBookmarkHandler.pyc", line 83, in process_image_bookmark
  File "PixivBookmarkHandler.pyc", line 369, in get_image_bookmark
  File "mechanize\_mechanize.pyc", line 257, in open
  File "mechanize\_mechanize.pyc", line 287, in _mech_open
  File "mechanize\_opener.pyc", line 193, in open
  File "mechanize\_urllib2_fork.pyc", line 425, in _open
  File "mechanize\_urllib2_fork.pyc", line 414, in _call_chain
  File "mechanize\_urllib2_fork.pyc", line 1276, in https_open
  File "mechanize\_urllib2_fork.pyc", line 1233, in do_open
urllib.error.URLError: <urlopen error [Errno 2] No such file or directory>
2021-12-24 20:05:12,784 - PixivUtil20211104 - ERROR - Unknown Error, please check the log file: (<class 'urllib.error.URLError'>, URLError(FileNotFoundError(2, 'No such file or directory')), <traceback object at 0x0370E0C8>)
2021-12-24 20:05:12,786 - PixivUtil20211104 - ERROR - Traceback (most recent call last):
  File "mechanize\_urllib2_fork.pyc", line 1229, in do_open
  File "http\client.pyc", line 1257, in request
  File "http\client.pyc", line 1303, in _send_request
  File "http\client.pyc", line 1252, in endheaders
  File "http\client.pyc", line 1012, in _send_output
  File "http\client.pyc", line 952, in send
  File "http\client.pyc", line 1426, in connect
  File "ssl.pyc", line 500, in wrap_socket
  File "ssl.pyc", line 1040, in _create
  File "ssl.pyc", line 1309, in do_handshake
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PixivUtil2.py", line 1462, in main
  File "PixivUtil2.py", line 1154, in main_loop
  File "PixivUtil2.py", line 554, in menu_download_from_online_image_bookmark
  File "PixivBookmarkHandler.pyc", line 83, in process_image_bookmark
  File "PixivBookmarkHandler.pyc", line 369, in get_image_bookmark
  File "mechanize\_mechanize.pyc", line 257, in open
  File "mechanize\_mechanize.pyc", line 287, in _mech_open
  File "mechanize\_opener.pyc", line 193, in open
  File "mechanize\_urllib2_fork.pyc", line 425, in _open
  File "mechanize\_urllib2_fork.pyc", line 414, in _call_chain
  File "mechanize\_urllib2_fork.pyc", line 1276, in https_open
  File "mechanize\_urllib2_fork.pyc", line 1233, in do_open
urllib.error.URLError: <urlopen error [Errno 2] No such file or directory>

------------------------------------------------------------------------------------------

Version - 20211104

**Comment by Nandaka** [comment]
do you run from exe file or from source code? do you extract the zip file?

Looks like a bug from the library itself. I can run it from the source code just fine.

**Comment by AnsuzJeran** [comment]
> do you run from exe file or from source code? do you extract the zip file?
> 
> Looks like a bug from the library itself. I can run it from the source code just fine.


From Exe
Library itself its unextracted

**Comment by Nandaka** [comment]
win7 or win10? I recommend you to run from source code (check the wiki page).

**Comment by AnsuzJeran** [comment]
> win7 or win10? I recommend you to run from source code (check the wiki page).

Win10
Ill check it as soon as i can  
Still want to see what problem i ran into

**Comment by Nandaka** [comment]
from the logging, it is thrown from this file
```
File "ssl.pyc", line 1309, in do_handshake
FileNotFoundError: [Errno 2] No such file or directory
```
which also not so clear
![image](https://user-images.githubusercontent.com/836867/147382074-63b253a2-3b10-4306-9acf-86ec848102e9.png)

I can only think it is due to missing `cacert.pem` or it somehow failed to load it. The compiled version got special handling for that, but it is only used for OAuth to handle cloudflare issue.

**Comment by AnsuzJeran** [comment]
> from the logging, it is thrown from this file
> 
> ```
> File "ssl.pyc", line 1309, in do_handshake
> FileNotFoundError: [Errno 2] No such file or directory
> ```
> 
> which also not so clear ![image](https://user-images.githubusercontent.com/836867/147382074-63b253a2-3b10-4306-9acf-86ec848102e9.png)
> 
> I can only think it is due to missing `cacert.pem` or it somehow failed to load it. The compiled version got special handling for that, but it is only used for OAuth to handle cloudflare issue.

course of action is the same?
to run from source i pressume?

**Comment by Nandaka** [comment]
I guess so, because I didn't get the error in my pc with either compiled or from source code.

**Comment by AnsuzJeran** [comment]
> I guess so, because I didn't get the error in my pc with either compiled or from source code.

Well whatever it was a clean windows reinstall fixed the problem
