### ISSUE TITLE
How to set username and password for proxy?

### ISSUE THREAD

**Issue by MonkAlex** [Nandaka/PixivUtil2#1071]
### Prerequisites

* [X] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [X] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [X] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Pixiv not allowed in Russia sometimes, so i open website using proxy.
My proxy require username-password, when i try PixivUtil2, get error "407 Proxy Authentication Required"

### Steps to Reproduce

1. Set http proxy with auth required
2. Run

**Expected behavior:** [What you expected to happen]
Any configuration to proxy?

**Actual behavior:** [What actually happened]
Just failed

**Log file:** [Attach the `pixivutil.log` file in the application folder, recommended to delete the old file, reproduce the issue, and upload the newly generated file here]
2022-01-07 14:34:44,333 - PixivUtil20211104 - INFO - Starting with argument: [E:\pixiv\PixivUtil2.exe].
2022-01-07 14:34:44,333 - PixivUtil20211104 - INFO - Setting log level to: DEBUG
2022-01-07 14:34:44,333 - PixivUtil20211104 - INFO - No default cookie jar available, creating... 
2022-01-07 14:34:44,333 - PixivUtil20211104 - INFO - Using Proxy: http://xxx.xx.xxx.xxx:3128
2022-01-07 14:34:57,069 - PixivUtil20211104 - ERROR - Error at open_with_retry(): (<class 'urllib.error.URLError'>, URLError(OSError('Tunnel connection failed: 407 Proxy Authentication Required')), <traceback object at 0x0421AEA8>)
2022-01-07 14:34:57,069 - PixivUtil20211104 - ERROR - Traceback (most recent call last):
  File "mechanize\_urllib2_fork.pyc", line 1229, in do_open
  File "http\client.pyc", line 1257, in request
  File "http\client.pyc", line 1303, in _send_request
  File "http\client.pyc", line 1252, in endheaders
  File "http\client.pyc", line 1012, in _send_output
  File "http\client.pyc", line 952, in send
  File "http\client.pyc", line 1419, in connect
  File "http\client.pyc", line 928, in connect
  File "http\client.pyc", line 907, in _tunnel
OSError: Tunnel connection failed: 407 Proxy Authentication Required

### Versions

PixivUtil20211104

**Comment by Nandaka** [comment]
```
  Proxy server address, use this format:
  - http://<username>:<password>@<proxy_server>:<port> or
  - socks5://<username>:<password>@<proxy_server>:<port> or
  - socks4://<username>:<password>@<proxy_server>:<port>
 ```

if your username/password got special character, it might be encoded using  url-encoding (you can use `https://meyerweb.com/eric/tools/dencoder/`)

**Comment by MonkAlex** [comment]
Work, thanks.
Skip this info in readme, sorry.
