### ISSUE TITLE
[Fanbox] Unknown Error Issue when download fanbox by "f1" or "f2" function

### ISSUE THREAD

**Issue by lazylazfo** [Nandaka/PixivUtil2#1094]
try to download fanbox by "f1" or "f2" function.
But error.

Traceback (most recent call last):
  File "PixivUtil2.py", line 1462, in main
  File "PixivUtil2.py", line 1189, in main_loop
  File "PixivUtil2.py", line 811, in menu_fanbox_download_from_list
  File "PixivFanboxHandler.pyc", line 50, in process_fanbox_artist_by_id
  File "PixivBrowserFactory.pyc", line 989, in fanboxGetPostsFromArtist
  File "PixivModelFanbox.pyc", line 490, in parsePosts
  File "PixivModelFanbox.pyc", line 67, in __init__
  File "PixivModelFanbox.pyc", line 109, in parsePost
KeyError: 'type'
Unknown Error, please check the log file: (<class 'KeyError'>, KeyError('type'), <traceback object at 0x04BD4288>)

Sorry for my bad english.

**Comment by ikkion** [comment]
I have the same problem. I tried on three different fanbox creators. Same problem on all.

**Comment by aksskl** [comment]
Same here. Tried beta1 just in case, no luck.

**Comment by britefire** [comment]
Can confirm, also happening here.

Same error is occurring whether it's downloading from supporting list, or given a single specific account to download.
A workaround that's working it seems is to download by individual post IDs instead of by artist.

**Comment by Miyuutsu** [comment]
I'm also confirming this issue on Linux using the current source code. No changes to application or system. Issue began sometime between 2022-03-09 18:29 EST and 2022-03-10 7:56 EST going by personal time stamps and when this thread appeared. It happens regardless of the artist chosen as well as regardless of if it's a paid tier or not. Seems API related since viewing the URL response it just shows `{"error":"general_error"}` despite pulling the supporting list correctly. https://api.fanbox.cc/plan.listSupporting

**Comment by DankeyBong** [comment]
I'm having the same issue. I've used the f2 option yesterday (2022-03-09) and it worked perfectly but now I'm having the exact same problem described above.

**Comment by LokiHades** [comment]
+1, same issue.

```
Traceback (most recent call last):
  File "PixivUtil2.py", line 1532, in main
  File "PixivUtil2.py", line 1259, in main_loop
  File "PixivUtil2.py", line 814, in menu_fanbox_download_from_list
  File "PixivFanboxHandler.pyc", line 50, in process_fanbox_artist_by_id
  File "PixivBrowserFactory.pyc", line 1005, in fanboxGetPostsFromArtist
  File "PixivModelFanbox.pyc", line 508, in parsePosts
  File "PixivModelFanbox.pyc", line 67, in __init__
  File "PixivModelFanbox.pyc", line 109, in parsePost
KeyError: 'type'
Unknown Error, please check the log file: (<class 'KeyError'>, KeyError('type'), <traceback object at 0x04B66548>)
```

**Comment by Nandaka** [comment]
Updated in the latest commit, and because I don't have any subscription with fanbox, so I can only test with free tier.

**Comment by ikkion** [comment]
Fix does not work. F2 does not download the content of the post only cover picture. Tested on several creators. Just says No Image available in post.

**Comment by aksskl** [comment]
> Fix does not work. F2 does not download the content of the post only cover picture. Tested on several creators. Just says No Image available in post.

Tested it just now, and that is correct. Only the cover image downloads. No Image available in post.

**Comment by DankeyBong** [comment]
Tested and I can confirm that downloading with F2 still does not work in beta2 and just says "No Image available in post". Downloading with F3 works.

**Comment by Nandaka** [comment]
can try the latest beta? it was reported in #1095

**Comment by Zekira** [comment]
> can try the latest beta? it was reported in #1095

Seems to be working fine for me, though I only tested F2 so far.

**Comment by DankeyBong** [comment]
F2 is fixed!
