### ISSUE TITLE
I can't download fanbox via type f1

### ISSUE THREAD

**Issue by bubbee23** [Nandaka/PixivUtil2#1096]
I can't download fanbox via type f1 in menu for week ago

When I type command to download form fanbox (f1). it start download normally and show error and auto close immediately.

When I download form artist id (not fanbox). It working fine and no problem.

I use Pixivutil2 ver.20210822 and I try lastest version. it same problem. 

ERROR show in log file like tihs.

-----------------------------------------------------------------------------------------------------------------------------------

2022-03-11 21:46:59,377 - PixivUtil20210822 - ERROR - Unknown Error, please check the log file: (<class 'KeyError'>, KeyError('type'), <traceback object at 0x03B91248>)
2022-03-11 21:46:59,378 - PixivUtil20210822 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 1388, in main
  File "PixivUtil2.py", line 1123, in main_loop
  File "PixivUtil2.py", line 783, in menu_fanbox_download_from_list
  File "PixivFanboxHandler.pyc", line 49, in process_fanbox_artist_by_id
  File "PixivBrowserFactory.pyc", line 978, in fanboxGetPostsFromArtist
  File "PixivModelFanbox.pyc", line 81, in parsePosts
  File "PixivModelFanbox.pyc", line 141, in __init__
  File "PixivModelFanbox.pyc", line 183, in parsePost
KeyError: 'type

[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/8232971/pixivutil.log)

Thank you for troubleshoot.

**Comment by nelooangeloo** [comment]
f4 is not working as well.
below is the log
------------------------------------------------------------------------------------------------------------------------

2022-03-11 23:33:45,765 - PixivUtil20211104 - DEBUG - Running from executable version for PixivOAuth
2022-03-11 23:33:45,766 - PixivUtil20211104 - DEBUG - browser.json location = D:\pixivutil20211104\browsers.json
2022-03-11 23:33:45,802 - PixivUtil20211104 - INFO - ###############################################################
2022-03-11 23:33:45,802 - PixivUtil20211104 - INFO - Starting with argument: [D:\pixivutil20211104\PixivUtil2.exe].
2022-03-11 23:33:45,803 - PixivUtil20211104 - INFO - Setting log level to: ERROR
2022-03-11 23:34:06,444 - PixivUtil20211104 - ERROR - Unknown Error, please check the log file: (<class 'KeyError'>, KeyError('type'), <traceback object at 0x03302E68>)
2022-03-11 23:34:06,445 - PixivUtil20211104 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 1462, in main
  File "PixivUtil2.py", line 1195, in main_loop
  File "PixivUtil2.py", line 811, in menu_fanbox_download_from_list
  File "PixivFanboxHandler.pyc", line 50, in process_fanbox_artist_by_id
  File "PixivBrowserFactory.pyc", line 989, in fanboxGetPostsFromArtist
  File "PixivModelFanbox.pyc", line 490, in parsePosts
  File "PixivModelFanbox.pyc", line 67, in __init__
  File "PixivModelFanbox.pyc", line 109, in parsePost
KeyError: 'type'

**Comment by Nandaka** [comment]
duplicates with #1094

**Comment by Nandaka** [comment]
try the latest beta?
