### ISSUE TITLE
Problem downloading from Fanbox

### ISSUE THREAD

**Issue by ScrewThisNoise** [Nandaka/PixivUtil2#1101]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Attempting to download from fanbox using option f1 gives an error.

### Steps to Reproduce

1. Run `PixivUtil2.exe -s f1 9999 -x` / run f1 in the app itself

**Expected behavior:** [What you expected to happen]

Downloading the contents

**Actual behavior:** [What actually happened]

┌──────────────────────────────────────────────────────────┐
│ PixivDownloader2 version 20211104                        │
│ https://github.com/Nandaka/PixivUtil2/releases           │
│ Donate at https://bit.ly/PixivUtilDonation               │
└──────────────────────────────────────────────────────────┘
Reading C:\Pixiv\config.ini ...
Configuration loaded.
Using default DB Path: C:\Pixiv\db.sqlite
Creating database... done.
Overwrite enabled.
Using Username: [removed]
Trying to log in with saved cookie
Login successful.
My User Id: [removed]
Premium User: True.
Trying to log in FANBOX with saved cookie
FANBOX Login successful.
Getting supporting artists from https://api.fanbox.cc/plan.listSupporting
Found 7 artist(s) in supporting list
[removed]
Reading C:\Pixiv\config.ini ...
Configuration loaded.
Getting artist information from https://api.fanbox.cc/creator.get?userId=[removed]
Member Url: https://www.pixiv.net/ajax/user/[removed]/profile/all
Processing FanboxArtist([removed]), page 1
Getting posts from https://api.fanbox.cc/post.listCreator?userId=[removed]&limit=10
Traceback (most recent call last):
  File "PixivUtil2.py", line 1462, in main
  File "PixivUtil2.py", line 1189, in main_loop
  File "PixivUtil2.py", line 811, in menu_fanbox_download_from_list
  File "PixivFanboxHandler.pyc", line 50, in process_fanbox_artist_by_id
  File "PixivBrowserFactory.pyc", line 989, in fanboxGetPostsFromArtist
  File "PixivModelFanbox.pyc", line 490, in parsePosts
  File "PixivModelFanbox.pyc", line 67, in __init__
  File "PixivModelFanbox.pyc", line 109, in parsePost
KeyError: 'type'
Unknown Error, please check the log file: (<class 'KeyError'>, KeyError('type'), <traceback object at 0x0355F588>)

### Versions

20211104

**Comment by ScrewThisNoise** [comment]
Disregard, issue is already reported in https://github.com/Nandaka/PixivUtil2/issues/1094, failed to find it using search, but found mention of it in the beta release notes. Apologies.
