### ISSUE TITLE
Permission Error when converting certain ugoira files

### ISSUE THREAD

**Issue by occhep** [Nandaka/PixivUtil2#1143]
I'm using the latest version. The problem above began just a few days ago. Some ugoira still work but some keep getting error code 9999. I also tried a few differrent ffmpeg.exe. Below is the log.

2022-08-02 06:34:53,078 - PixivUtil20220701 - INFO - Processing ugoira to webp...
2022-08-02 06:34:53,366 - PixivUtil20220701 - DEBUG - Procced to change C:/Users/[User Name]/AppData/Local/Temp/convert_ugoirax5pmcmj7\000045.jpg image for a pixel format with 3 components 
2022-08-02 06:34:53,367 - PixivUtil20220701 - INFO - [re_encode_image()] running with cmd: ffmpeg.exe -i C:/Users/[User Name]/AppData/Local/Temp/convert_ugoirax5pmcmj7\000045.jpg -pix_fmt gbrpf32be C:/Users/[User Name]/AppData/Local/Temp/convert_ugoirax5pmcmj7\000045_temp.jpg
2022-08-02 06:34:53,813 - PixivUtil20220701 - DEBUG - Start re_encoding image C:/Users/[User Name]/AppData/Local/Temp/convert_ugoirax5pmcmj7\000045.jpg
2022-08-02 06:34:55,702 - PixivUtil20220701 - ERROR - Error at process_image(): 100149648
2022-08-02 06:34:55,703 - PixivUtil20220701 - ERROR - Traceback (most recent call last):
  File "PixivHelper.pyc", line 1053, in convert_ugoira
  File "PixivHelper.pyc", line 1162, in check_image_encoding
  File "PixivHelper.pyc", line 1193, in re_encode_image
PixivException.PixivException: PixivException(9999 error, hasDumpPage=N)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PixivImageHandler.pyc", line 336, in process_image
  File "PixivDownloadHandler.pyc", line 406, in handle_ugoira
  File "PixivHelper.pyc", line 994, in ugoira2webp
  File "PixivHelper.pyc", line 1080, in convert_ugoira
  File "shutil.pyc", line 740, in rmtree
  File "shutil.pyc", line 618, in _rmtree_unsafe
  File "shutil.pyc", line 616, in _rmtree_unsafe
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:/Users/[User Name]/AppData/Local/Temp/convert_ugoirax5pmcmj7\\000126.jpg'

**Comment by Toyem** [comment]
This is an error that occurs in the new version of the program. It has already been reported in the #1141 and #1132 issues.
It occurs when the images in the gif alternate between black & white and color images. 
The bug has already been fixed on the python program of the project but the Windows executable will only be updated in the next version

If you use the python program, just download the latest version as explained in this post: https://github.com/Nandaka/PixivUtil2/issues/1141#issuecomment-1195880801
If you use the Windows executable, you will have to wait for the next version or try to generate the executable on your side.

**Comment by occhep** [comment]
Thanks. Guess I'm waiting for next update.
