### ISSUE TITLE
Fails to download valid image: 'NoneType' object has no attribute 'findAll'

### ISSUE THREAD

**Issue by NHOrus** [Nandaka/PixivUtil2#116]
Processing Image Id: 53913162
Image ID (53913162): 'NoneType' object has no attribute 'findAll'

**Comment by Nandaka** [comment]
It is working.

```
Input: 2
Image ids: 53913162
Processing Image Id: 53913162
Title: 混浴
Tags : R-18, うごイラ, 少女, 女の子, ロリ
Date : 2015-12-06 19:03:00
Mode : ugoira_view
Parsing bookmark page Bookmark Count : 328
Image URL : http://i3.pixiv.net/img-zip-ugoira/img/2015/12/06/19/03/01/53913162_ugoira1920x1080.zip
Filename  : D:\pd\Images\20160517\328 pon00000 53913162_ugoira1920x1080 - 混浴.zip
Checking local filename... Getting remote filesize...
Using Referer: http://www.pixiv.net/member_illust.php?mode=medium&illust_id=53913162
Start downloading... Using Referer: http://www.pixiv.net/member_illust.php?mode=medium&illust_id=53913162
Creating directory: D:\pd\Images\20160517
    441808 of    441808 Bytes  Completed in 1.135s (380.13 KiB/s)
 Image verified.

Creating ugoira archive => D:\pd\Images\20160517\328 pon00000 53913162_ugoira1920x1080 - 混浴.ugoira
Deleting zip file => D:\pd\Images\20160517\328 pon00000 53913162_ugoira1920x1080 - 混浴.zip
```

**Comment by yutsuku** [comment]
I have same issue with compiled release (20160513) for Windows. I think there is problem with logging in cause both generated error pages showed that I was **not** logged in.
```
C:\Users\moh\Downloads\pixivutil20160513>PixivUtil2.exe
PixivDownloader2 version 20160513
https://nandaka.wordpress.com/tag/pixiv-downloader/
Reading C:\Users\moh\Downloads\pixivutil20160513\config.ini ...
Error at loadConfig(): (<type 'exceptions.IOError'>, IOError(2, 'No such file or
 directory'), <traceback object at 0x025F0648>)
Some configuration have invalid value, replacing with the default value.
Writing config file... done.
done.
using default DB Path: C:\Users\moh\Downloads\pixivutil20160513\db.sqlite
Creating database... done.
Only process member where day last updated >= 7
Username ? <REMOVED>
Password ?
Log in using secure form.
Logged in
new cookie value: <REMOVED>
Writing config file... Backing up old config to config.ini.bak
done.
PixivDownloader2 version 20160513
https://nandaka.wordpress.com/tag/pixiv-downloader/
1. Download by member_id
2. Download by image_id
3. Download by tags
4. Download from list
5. Download from online user bookmark
6. Download from online image bookmark
7. Download from tags list
8. Download new illust from bookmark
9. Download by Title/Caption
10. Download by Tag and Member Id
11. Download Member Bookmark
12. Download by Group Id
------------------------
d. Manage database
e. Export online bookmark
m. Export online user bookmark
r. Reload config.ini
p. Print config.ini
x. Exit
Input: 2
Image ids: 57303253
Processing Image Id: 57303253
Image ID (57303253): 'NoneType' object has no attribute 'findAll'
Dumping html to: Error medium page for image 57303253.html
PixivDownloader2 version 20160513
https://nandaka.wordpress.com/tag/pixiv-downloader/
1. Download by member_id
2. Download by image_id
3. Download by tags
4. Download from list
5. Download from online user bookmark
6. Download from online image bookmark
7. Download from tags list
8. Download new illust from bookmark
9. Download by Title/Caption
10. Download by Tag and Member Id
11. Download Member Bookmark
12. Download by Group Id
------------------------
d. Manage database
e. Export online bookmark
m. Export online user bookmark
r. Reload config.ini
p. Print config.ini
x. Exit
Input: 1
Member ids: 6147118
Start Page (default=1):
End Page (default=0, 0 for no limit):
Processing Member Id: 6147118
Reading C:\Users\moh\Downloads\pixivutil20160513\config.ini ...
done.
Page  1
Member Url: http://www.pixiv.net/member_illust.php?id=6147118&p=1
Traceback (most recent call last):
  File "PixivUtil2.py", line 320, in process_member
  File "PixivModel.pyc", line 51, in __init__
  File "PixivModel.pyc", line 104, in ParseImages
AttributeError: 'NoneType' object has no attribute 'findAll'
Error at process_member(): (<type 'exceptions.AttributeError'>, AttributeError("
'NoneType' object has no attribute 'findAll'",), <traceback object at 0x035689E0
>)
Dumping html to: Error page for member 6147118.html
Traceback (most recent call last):
  File "PixivUtil2.py", line 1850, in main
  File "PixivUtil2.py", line 1636, in main_loop
  File "PixivUtil2.py", line 1298, in menu_download_by_member_id
  File "PixivUtil2.py", line 320, in process_member
  File "PixivModel.pyc", line 51, in __init__
  File "PixivModel.pyc", line 104, in ParseImages
AttributeError: 'NoneType' object has no attribute 'findAll'
press enter to exit.
```

**Comment by Nandaka** [comment]
I see, can you use cookie method for login for now?

**Comment by yutsuku** [comment]
Yes, I was able to log in and download single image / whole profile with cookie copy method. I guess this will have do for a workaround for now.

On a side note FAQ A. Usage, Q3, #2. *Go to Pixiv website and login, remember to enable [Remember Me]  check box.*
seems to be obsolete now since there is no check box in log in form on Pixiv website
