### ISSUE TITLE
Unknown Error, please check the log file: (<class 'KeyError'>, KeyError('coverImageUrl'), <traceback object at 0x0419F228>)

### ISSUE THREAD

**Issue by Hecatom** [Nandaka/PixivUtil2#1181]
### Prerequisites

* [y ] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [y ] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [y ] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

I am getting an unknown error when trying to download the list of all my supported artists with f1.
Just some hours ago it was working fine.

The only difference between some hours ago and now, is that I added a new artist to my support list, so dunno if that could be the cause

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]
The expected behavior would be to download all the artists on the supported list

**Actual behavior:** [What actually happened]

Unknown Error, please check the log file: (<class 'KeyError'>, KeyError('coverImageUrl'), <traceback object at 0x036BE848>)
press enter to exit.

**Log file:** [Attach the `pixivutil.log` file in the application folder, recommended to delete the old file, reproduce the issue, and upload the newly generated file here]
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/9848648/pixivutil.log)

### Versions
v20220924
You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by Hecatom** [comment]
Something to take not is that downloading normal pixiv galleries work, so is only on the fanbox side that the error is happening

**Comment by alg-wiki** [comment]
It basically does not recognize the key 'coverImageUrl'.
I think fanbox might've changed something. The key variable needs to be updated.

https://github.com/Nandaka/PixivUtil2/blob/master/PixivModelFanbox.py#L94

**Comment by alg-wiki** [comment]
Well looks like the whole JSON structure changed

**Comment by shinji257** [comment]
(For reference)
Example artist: 2029329
Example post: 4654957

This artist creates NSFW content although I think the posts themselves are ok... probably.  Access at your own risk.  The example post is accessible by all users and does not require supporting them.

**Comment by DisasterInbound** [comment]
Hello, I can confirm I started receiving this message today. 

I got the following error which seems to match with what alg-wiki said:

```
Traceback (most recent call last):
  File "PixivUtil2.py", line 1736, in main
  File "PixivUtil2.py", line 1468, in main_loop
  File "PixivUtil2.py", line 1000, in menu_fanbox_download_by_id
  File "PixivFanboxHandler.pyc", line 50, in process_fanbox_artist_by_id
  File "PixivBrowserFactory.pyc", line 1018, in fanboxGetPostsFromArtist
  File "PixivModelFanbox.pyc", line 566, in parsePosts
  File "PixivModelFanbox.pyc", line 67, in __init__
  File "PixivModelFanbox.pyc", line 94, in parsePost
KeyError: 'coverImageUrl'
Unknown Error, please check the log file: (<class 'KeyError'>, KeyError('coverImageUrl'), <traceback object at 0x009C0748>)
```

**Comment by shinji257** [comment]
As long as Nandaka is ok with it I can zip up a build using the latest code on this repo and post it here.  It will have the same version as the current one already released as I'm not going to update the constant so when Nankada does update you can go grab the official one.

I will let you know it does build a bit differently for whatever reason but works fine otherwise.

**Comment by KamenReader** [comment]
I'm fine running off my own build too.  I meant it more for everyone else, like Hecatom who had issues getting it to run earlier or those who might not want to fiddle with python in general.  I'm sure there are even others still who don't even go so far as to look at the Issues list and just check to see if a new release has been posted.  More of a convenience thing for the end users to push out a release, even if it's beta or something.

**Comment by shinji257** [comment]
Nandaka got a new build up for everyone to use and get the fix.
