### ISSUE TITLE
Login Issues

### ISSUE THREAD

**Issue by PerseusRex** [Nandaka/PixivUtil2#1209]
### Description

Can't login, receiving this error
![pixiv](https://user-images.githubusercontent.com/51503984/208014235-3671693d-7cf2-42c9-84a2-1cc5fef39732.PNG)

I already tried changing password, updating cookies, and changing useragent.

**Comment by Revemohl** [comment]
Reporting to say that I just got it too.

**Comment by RighteousAnger** [comment]
Glad I'm not the only one, tried inputting cookies values from Chrome and Firefox, it gives the same error. Can log in just fine on both browsers.

**Comment by criperro** [comment]
Same here, updated my password, PHPID and useragent still having the issue

**Comment by xlebun** [comment]
i too have it

**Comment by Hecatom** [comment]
Same.
Question, do you use vpns or does the problem happen by trying to login normally with the app?

**Comment by xlebun** [comment]
there's a pinned issue stating that matching the useragent with the browser's might help

**Comment by PatrickL546** [comment]
Seems like Pixiv did something. Pixivpy also have login issues

**Comment by xlebun** [comment]
okay, adjusting useragent and changing password with cookie didn't work at all. pixiv did something for sure

**Comment by PatrickL546** [comment]
Looks like this is what happened today https://www.pixiv.net/info.php?id=8986

**Comment by xlebun** [comment]
> Looks like this is what happened today https://www.pixiv.net/info.php?id=8986
doesn't look like this would be the cause, but anyway

**Comment by sgghostrider** [comment]
Probably pixiv updated their webpage/services and broke the utility, it was working fine several hours ago, it just suddenly stopped working overnight, so an update with a fix is required to adapt it to the changes i suppose... 😞

**Comment by Soonbum** [comment]
Oh, I saw this issue too.

**Comment by 524144** [comment]
Same here
Error at doLogin(): (<class 'mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib.error.HTTPError instance) at 0x38a66a0 whose wrapped object = <HTTPError 403: 'Forbidden'>>, <traceback object at 0x0389E488>)
Cannot Login!
I followed https://github.com/Nandaka/PixivUtil2/wiki#pixiv-login-using-cookie and changed my password, updating cookies, etc and still doesn't work. 
I also tried switching from chrome to firefox, updated my cookies and nope, the same.
like, what on earth is happening...

**Comment by gnarf1975** [comment]
Same here....

**Comment by shinji257** [comment]
Was just getting ready to come here and report the same.  Had to kill it since link to network drive went down and I didn't want it throwing a ton of errors client side.  Finally fixed it and it wouldn't login again even after updating user agent and cookies.  Good to know I'm not alone.

**Comment by h3ntaih3ro** [comment]
Same issue here, I hope it's fixed soon :(

**Comment by anonymous721** [comment]
For what it's worth, gallery-dl is still capable of downloading from Pixiv, including login authentication. Hopefully that implies that a fix here will be relatively straightforward.

**Comment by shinji257** [comment]
This was discussed in https://github.com/Nandaka/PixivUtil2/issues/814 as well.

**Comment by PatrickL546** [comment]
> For what it's worth, gallery-dl is still capable of downloading from Pixiv, including login authentication. Hopefully that implies that a fix here will be relatively straightforward.

Doesn't look like they're affected. I don't see any authentication changes in their commits.
This is their Pixiv OAuth, maybe we can use this if it works?
[oauth.py#L365](https://github.com/mikf/gallery-dl/blob/9ea521bec5f7deb39cabc10f1db617f5b19a8b04/gallery_dl/extractor/oauth.py#L365)

**Comment by cocokakao** [comment]
still???

**Comment by southernbear** [comment]
I tried the curl command below and got 200:

```sh
curl 'https://www.pixiv.net/' --output - -I -H 'Cookie: PHPSESSID=your_sesson' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0' -H 'Accept-Language: zh-TW,zh-CN;q=0.8,zh;q=0.7,en-US;q=0.5,en;q=0.3,ja;q=0.2'
```
and capture packets then I found curl use HTTP/2 and we still use HTTP/1.1

When I add ```--http1.1``` to curl, it return 403.

Note: ```Accept-Charset``` need to be replaced with ```Accept-Language``` or you will get 403.

**Comment by pablotron8** [comment]
Oh no! Same issue here...

**Comment by hatabbich** [comment]
oh... glad that it not my stuff only, was ready to reinstall Win already :D

**Comment by TechnoMasterBoy** [comment]
I'm also getting the same issue. I though it was because I was using outdated version pixivutil20211104
But then I updated to pixivutil20221029 (Latest as of right now) and the issue was still there.

**Comment by SeraXZa** [comment]
RIP. Same for me

**Comment by YTOAA** [comment]
This issue is not resolved

**Comment by Nandaka** [comment]
see https://github.com/Nandaka/PixivUtil2/issues/814, I don't plan to fix the login as cookie method is working. 
I do accept Pull Request if someone know how to do it.

**Comment by Hamuko** [comment]
The cookie method is working?

**Comment by skulkexpert** [comment]
The cookie method is definitely not working for me. I get the same problem as in the image posted by OP.

**Comment by TechnoMasterBoy** [comment]
> see #814, I don't plan to fix the login as cookie method is working. I do accept Pull Request if someone know how to do it.

No it doesn't... I've tried with and without cookies, aswell as with and without useragent, same exact error as OP.

**Comment by KuroChloe** [comment]
Reporting in too, getting this error and nothing gets rids of it. Did whole dance with password change and stuff, no dice.

**Comment by anonymous721** [comment]
The cookie method is exactly what I've been using and it is not working.

**Comment by MarqFJA87** [comment]
Same for me. I've already been using the cookie method for what's seemingly forever, and now it's stopped working.

**Comment by Nanoka** [comment]
> see #814, I don't plan to fix the login as cookie method is working. I do accept Pull Request if someone know how to do it.

Neither of the PHPSESSID value alone or the full cookie string works.
However removing the "ID_" from PHPSESSID in either of these will result in a "Login successful." message, followed by the "Unable to get User Id, please check your cookie." error, so I don't really know if its a successful login or just a mistake from the program.

**Comment by daniels1989** [comment]
> see #814, I don't plan to fix the login as cookie method is working. I do accept Pull Request if someone know how to do it.

Definitely not working. The traceback also specifically mentions the method "loginUsingCookie"

[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/10252854/pixivutil.log)

**Comment by aksskl** [comment]
Tried all I could, doesn't work for me either.

**Comment by shinji257** [comment]
> see #814, I don't plan to fix the login as cookie method is working. I do accept Pull Request if someone know how to do it.

Cookie method does not work. Check my gist where it mentions trying to login via cookie.

**Comment by matsumotokenji** [comment]
> see #814, I don't plan to fix the login as cookie method is working. I do accept Pull Request if someone know how to do it.

i can confirm that using cookie method is not working.

**Comment by PatrickL546** [comment]
> see #814, I don't plan to fix the login as cookie method is working. I do accept Pull Request if someone know how to do it.

Are you able to log in? I got 403 forbidden while in the middle of downloading, while logged in using cookies.

**Comment by PatrickL546** [comment]
![image](https://user-images.githubusercontent.com/75874561/208286691-742807ed-a7af-4fce-a01e-788840890576.png)
Username/Password login error. Website has changed stuff

**Comment by Hecatom** [comment]
> see #814, I don't plan to fix the login as cookie method is working. I do accept Pull Request if someone know how to do it.

Hmmm, I tried both methods, and neither is working 🤷

**Comment by PatrickL546** [comment]
> For what it's worth, gallery-dl is still capable of downloading from Pixiv, including login authentication. Hopefully that implies that a fix here will be relatively straightforward.

They use OAuth for login maybe this can have that as an option for login? https://github.com/Nandaka/PixivUtil2/issues/1211

**Comment by YTOAA** [comment]
> #814 를 참조하십시오 . 쿠키 방식이 작동하므로 로그인을 수정할 계획이 없습니다. 풀 리퀘스트 방법을 아는 사람이 있으면 풀 리퀘스트를 수락합니다.

You are not logged in by cookie method.

**Comment by Wesley107772** [comment]
The issue seems to lie with the useragent. I'm by no means experienced with python, but after some fiddling around I got it to work a few times.
What I settled for in the end was this:

In PixivBrowserFactory.py:
1. I added this as a dependency:
https://pypi.org/project/fake-useragent/

2.  I commented out line 160 and 163, putting in their place
`self.addheaders = [('User-agent', UserAgent().random)]`

This way a random useragent is used instead of the one from the config file.
You will still encounter a lot of errors, but eventually it should work.

I am not sure whether removing the utf-8 fix on line 163 is completely necessary, though through many tests I couldn't get it working with that enabled.
Although this is a very cruddy and only half-functional "fix" I could make a PR if you want.

**Comment by Hamuko** [comment]
My first thought from southernbear's and Wesley107772's comments might be that Cloudflare might be blocking HTTP/1.1 requests from browsers that are expected to send HTTP/2 requests. Would be interesting to find what kind of an User-Agent you need to use in order to get HTTP/1.1 to pass.

**Comment by Nanoka** [comment]
Commenting out line 162 from PixivBrowserFactory.py and using just "Mozilla/5.0" as user agent seems to work about 50% of the time.

**Comment by shinji257** [comment]
Confirm the 50% part so far with that change.  I have a built version that seems to work as a stop gap until someone figures out a way to get it to work 100% of the time.  Oauth might be the way.

**Comment by mugi-jiichan** [comment]
The fake-useragent didn't do it for me. However shortening the useragent down to "Mozilla/5.0" while commenting out line 162 `self.addheaders += [('Accept-Charset', 'utf-8')]` just did the trick for now...

**Comment by 524144** [comment]
Now I need to learn how to use gallery-dl to download on fanbox :/

**Comment by MarqFJA87** [comment]
> Now I need to learn how to use gallery-dl to download on fanbox :/

It's not that hard if you understand how to use the config file (and yes, there are instructions for this to get you started), and then follow the instructions for the cookie method (which is required for Fanbox and a few other sites, but normally isn't). It's just unwieldy regarding Pixiv when compared to the convenience of PixivUtil2.

That said, if you find yourself overwhelmed, don't be afraid to ask in the Issues section; that's how I learned some of the stuff that I couldn't figure out myself.

**Comment by 524144** [comment]
> > Now I need to learn how to use gallery-dl to download on fanbox :/
> 
> It's not that hard if you understand how to use the config file (and yes, there are instructions for this to get you started), and then follow the instructions for the cookie method (which is required for Fanbox and a few other sites, but normally isn't). It's just unwieldy regarding Pixiv when compared to the convenience of PixivUtil2.
> 
> That said, if you find yourself overwhelmed, don't be afraid to ask in the Issues section; that's how I learned some of the stuff that I couldn't figure out myself.

Thank you, this means a lot to me, definitely a big boost in my confidence.

**Comment by criperro** [comment]
Sad there is still no fix :(

For now only JDownloader has been the only I've been able to download the artworks from an artist, although I noticed that sometimes it skips some artworks.

**Comment by Nandaka** [comment]
as mentioned by @Hamuko and others, looks like due to Cloudflare HTTP/2, I have no idea how to bypass it beside using proxy for now...

**Comment by PatrickL546** [comment]
Tried out this proxy "socks4://50.63.13.3:21280" but still error 403

**Comment by Hecatom** [comment]
> Same for me. I've already been using the cookie method for what's seemingly forever, and now it's stopped working.
> 
> I should also note that the OP had clearly stated that the cookie method wasn't working for them, and several early replies reported the same problem.
> 
> Currently making do with gallery-dl until this is fixed.

Sorry, but could you point me out to where can i find the info needed to make gallery-dl download from fanbox? since the help doesn't mention it, and the issues I have found don't really enter into details about it.

**Comment by nomakewan** [comment]
> The fake-useragent didn't do it for me (linux, running the recent source code from two days).
> 
> However shortening the useragent down to "Mozilla/5.0" while commenting out line 162 `self.addheaders += [('Accept-Charset', 'utf-8')]` just did the trick for now...
> 
> _edit:_ Half an hour later, it just stops working while running PU within taglist mode. Error 403, again.

Can confirm this worked on my end as well, even working with much, much older source (October 29). It will no doubt stop working later just as yours did, but as a temporary workaround until a proper fix can be implemented, I thank you.

**Comment by PatrickL546** [comment]
> > Same for me. I've already been using the cookie method for what's seemingly forever, and now it's stopped working.
> > I should also note that the OP had clearly stated that the cookie method wasn't working for them, and several early replies reported the same problem.
> > Currently making do with gallery-dl until this is fixed.
> 
> Sorry, but could you point me out to where can i find the info needed to make gallery-dl download from fanbox? since the help doesn't mention it, and the issues I have found don't really enter into details about it.

![image](https://user-images.githubusercontent.com/75874561/208353178-e0e71c3a-f21d-455b-a17f-93097c0c1629.png)

**Comment by Nandaka** [comment]
haizz, now I see this when I visited the pixiv website.
![image](https://user-images.githubusercontent.com/836867/208356458-3ecb3ec8-36a5-4c22-b19f-116ec76f7322.png)

**Comment by cocokakao** [comment]
I can't keep up with the way you guys modified it Can someone tell me the details?

**Comment by Hamuko** [comment]
Does someone happen to have an old Windows 7 installation with Internet Explorer kicking about? Asking because apparently that [might not even support HTTP/2](https://caniuse.com/http2), so I'm wondering if you can
a) Access Pixiv on a HTTP/1.1-only browser.
b) If you could reuse cookies with that User-Agent.

Otherwise some sort of HTTP/2 support has been around for quite a while now across the browser space.

**Comment by Nandaka** [comment]
not a real fix, based on @mugi-jiichan said, sometimes I can pass the check after commenting out one of the lines and changing the user agent.

**Comment by PatrickL546** [comment]
> Does someone happen to have an old Windows 7 installation with Internet Explorer kicking about? Asking because apparently that [might not even support HTTP/2](https://caniuse.com/http2), so I'm wondering if you can a) Access Pixiv on a HTTP/1.1-only browser. b) If you could reuse cookies with that User-Agent.
> 
> Otherwise some sort of HTTP/2 support has been around for quite a while now across the browser space.

quick test from this website shows this
![image](https://user-images.githubusercontent.com/75874561/208358977-84179a60-6af0-4aed-9ddc-b6a6de8d255c.png)

**Comment by DisasterInbound** [comment]
Hello, I'm also here with another "Same 403 error and issue happened to me" but for now I'll just patiently wait for a fix.

I prefer using PixivUtil but if anyone is in a hurry to download Fanbox content, you could use [Atelier Misaka](https://github.com/endlessmisaka/ateliermisaka).

It's easy to set up and use.
I have been using for more than a year for Patreon and Fantia. I tried it with Fanbox for the first time and it worked perfectly. 

It uses a Chromium browser to login and download so maybe(?) it won't have the same issue with the useragent and HTTP/2 like what happened here but feel free to correct me if I'm wrong.

**Comment by qiukeren** [comment]
change session or token or reset password: validated not work

change vpn / ip : validated not work

change ua: theoretical not work, and tested not work ,  and bare `Mozilla/5.0` leads to an infinite loop.

change UA like referer/Accept-Encoding/Accept-Language/sec-ch-ua-platform so on: validated not work

TODO: check http 2.0 support for mechanize.

**Comment by qiuker521** [comment]
seems mechanize does not support HTTP/2

**Comment by Nandaka** [comment]
tried to use httpx for http2 support, but I got blocked by cloudflare...
switched to use cloudscrapper to bypass the cloudflare (looks like ok), but I think it still use http/1.1

created new branch https://github.com/Nandaka/PixivUtil2/tree/http2 please note most likely a lot of stuff still broken, but at least mode 1 is working

**Comment by qiuker521** [comment]
> tried to use httpx for http2 support, but I got blocked by cloudflare... switched to use cloudscrapper to bypass the cloudflare (looks like ok), but I think it still use http/1.1
> 
> created new branch https://github.com/Nandaka/PixivUtil2/tree/http2 please note most likely a lot of stuff still broken, but at least mode 1 is working

it works, but requires much work as:

```diff

+++ b/PixivBookmarkHandler.py
@@ -366,8 +366,10 @@ def get_bookmarks(caller, config, hide, start_page=1, end_page=0, member_id=None
         PixivHelper.print_and_log('info', f"Source URL: {url}")
 
         page = br.open_with_retry(url)
-        page_str = page.read().decode('utf8')
-        page.close()
+        page_str = page.text
+        #page_str = page.read().decode('utf8')
+        #page.close()
```

**Comment by qiuker521** [comment]
What's more, commit b65b3f62d78f5a7b805de95f946ee581f4291d42 set UA to `Mozilla/5.0` with no other suffixes is a bad idea.

Suggest this:

![image](https://user-images.githubusercontent.com/22740352/208430391-b8685de9-130b-46b6-b844-ba9322526286.png)

**Comment by fireattack** [comment]
> What's more, commit [b65b3f6](https://github.com/Nandaka/PixivUtil2/commit/b65b3f62d78f5a7b805de95f946ee581f4291d42) set UA to `Mozilla/5.0` with no other suffixes is a bad idea.

But it didn't. 

It just asks the user to set to that, and that's because it (at the moment) somehow works better than a legitimate UA.

**Comment by Nandaka** [comment]
> What's more, commit [b65b3f6](https://github.com/Nandaka/PixivUtil2/commit/b65b3f62d78f5a7b805de95f946ee581f4291d42) set UA to `Mozilla/5.0` with no other suffixes is a bad idea.
> 
> Suggest this:
> 
> ![image](https://user-images.githubusercontent.com/22740352/208430391-b8685de9-130b-46b6-b844-ba9322526286.png)

that commit doesn't change the user agent, just to comment out some lines as mentioned in https://github.com/Nandaka/PixivUtil2/issues/1209#issuecomment-1356866484

**Comment by YTOAA** [comment]
Is there a perfect solution at the moment?

**Comment by shinji257** [comment]
> Is there a perfect solution at the moment?

Not yet.

On a side note I got reminded (thank you Fanbox) that there is already an oauth mechanism in PixivUtil2 but I don't know exactly what triggers it.  It asks to go through an oauth flow when it needs to get something and (I guess) it can't get it.  Can we trigger that for when you get a 403 error during login?

**Comment by bluerthanever** [comment]
funny result i got from tests in fiddler:
the original request headers from Pixivutil2, which result in 403 errors are in the following orders:
```
Accept-Encoding, Cookie, User-Agent, Accept-Charset, Host, Connection
```
but when i changed the orders and added and removed some headers to the following orders:
```
Host, User-Agent, Accept, Accept-Encoding, Accept-Charset, Cookie
```
it worked.

I added `Accept: */*` and removed `Connection: close`, Seems crucial to the requests.
but i am not sure how to change the orders of the headers.

just a lil something i found out about.

**Comment by fireattack** [comment]
Isn't it more about you added and removed some? How can you tell that the order matters?

**Comment by bluerthanever** [comment]
> Isn't it more about you added and removed some? How can you tell that the order matters?

i tried changing the orders. trust me i think it's strange too

**Comment by fireattack** [comment]
I believe you, but your own words are "changed the orders and added and removed some". 

You need to give the minimal reproducible steps. If merely chaning order works, then just get ride of "add and remove some".

**Comment by bluerthanever** [comment]
> I believe you, but your own words are "changed the orders and added and removed some".
> 
> You need to give the minimal reproducible steps. If merely chaning order works, then just get ride of "add and remove some".

...hmm, because merely changing the orders doesn't work? it needs to be both. at least that's what i got.

i am just offering what i found out. if you have doubts maybe you should try it yourself?

**Comment by bluerthanever** [comment]
i just wanna save the work of saying "i changed the orders a lil bit, and it didn't work, so i added this, and it didn't work either, so i removed this"

**Comment by fireattack** [comment]
Sorry my bad, I was just wandering if you just add and remove (without chaning the order), would it work. Because I never heard that the order would matter in anyway.

Either way, I did test it, but it didn't work here in curl or Python `requests`.

Would you mind to post the full request header (sans cookies) for others to try?

**Comment by fireattack** [comment]
After digging this a little bit, according to https://curl.se/docs/todo.html#Rearrange_request_header_order, the order does matter when it is used for servers as some kind of anti-bot measures.

And curl can't garuntee to follow the header order as how the users give (not sure about requests, or mechanize which we're using).

**Comment by Nandaka** [comment]
@bluerthanever  maybe you can wrap the url in request object and set the headers here?

https://github.com/Nandaka/PixivUtil2/blob/master/PixivBrowserFactory.py#L206

**Comment by bluerthanever** [comment]
the thing is i am not sure how to change the order of headers in `mechanize.Browser`. seems complicated

maybe i'll look into it. for now i just bypassed the login check and am just using fanbox functions.

**Comment by fireattack** [comment]
I cannot make it work in anyway even following the order:

```
* ALPN: offers http/1.1
* ALPN: server accepted http/1.1
> GET / HTTP/1.1
> Host: www.pixiv.net
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0
> Accept: */*
> Accept-Encoding: identity
> Accept-Charset: utf-8
> Cookie: PHPSESSID=***
>
* schannel: failed to decrypt data, need more data
* Mark bundle as not supporting multiuse
< HTTP/1.1 403 Forbidden
HTTP/1.1 403 Forbidden
```

But the old trick of removing Accept-Charset and changing UA to `Mozilla/5.0` still works.

I also found another trick:

fetching "https://pixiv.net" (WITHOUT www.) while feeding in `Host: www.pixiv.net` will get it work (200, not 301) without any specific headers:
```
curl -X GET -H "Host: www.pixiv.net" -H "Cookie: PHPSESSID=**" "https://pixiv.net" 
```
and it's actually logged in if cookie is given.

**Comment by bluerthanever** [comment]
@Nandaka  btw, i looked over another repository whose name i'm not gonna mention yet.

i think they didn't use web cookies or web pages to crape all the things, instead they use refresh_token, an `Authorization` header and some v1 apis which i think may be apis used in apps. like "https://app-api.pixiv.net/v1/user/illusts?user_id=xxx"

but they don't have sketch or novel.

**Comment by PatrickL546** [comment]
> I cannot make it work in anyway even following the order:
> 
> ```
> * ALPN: offers http/1.1
> * ALPN: server accepted http/1.1
> > GET / HTTP/1.1
> > Host: www.pixiv.net
> > User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0
> > Accept: */*
> > Accept-Encoding: identity
> > Accept-Charset: utf-8
> > Cookie: PHPSESSID=***
> >
> * schannel: failed to decrypt data, need more data
> * Mark bundle as not supporting multiuse
> < HTTP/1.1 403 Forbidden
> HTTP/1.1 403 Forbidden
> ```
> 
> But the old trick of removing `Accept-Charset` and changing UA to `Mozilla/5.0` still works.
> 
> I also found another trick:
> 
> fetching "https://pixiv.net" (WITHOUT [www](http://www).) while feeding in `Host: www.pixiv.net` will get it work (200, not 301) without any specific headers:
> 
> ```
> curl -X GET -H "Host: www.pixiv.net" -H "Cookie: PHPSESSID=**" "https://pixiv.net" 
> ```
> 
> and it's actually logged in if cookie is given.

Followed this, and it's not 100% but it does work from time to time

**Comment by Nandaka** [comment]
@bluerthanever wont it fix the HTTP/2 issue, as far as I know this is part of cloudflare feature?

**Comment by KamenReader** [comment]
> maybe i'll look into it. for now i just bypassed the login check and am just using fanbox functions.

... that works?  _tries it_  By George, it does!  For anyone who wants to run off of source, you can replace your PixivBrowserFactory.py file from the current release with the attached one.  Note that when you get the OAuth prompt, make sure to follow the instructions precisely.  Don't simply click through the login prompt before doing the other steps.

For those who don't want to run off source and are feeling adventurous, I built a Windows executable version using pyinstaller and tossed the whole thing into an attachment here too.  The actual .exe size is quite a bit larger than the usual, I assume due to different build parameters, so if that's sus to you for some reason, feel free to stick to the source version.

Oh, and make sure you're not using %artist% and are instead using %fanbox_name% for your fanbox directories.  Since accessing the Pixiv side of things gives a 403, the artist name can't be retrieved.
[PixivBrowserFactory.zip](https://github.com/Nandaka/PixivUtil2/files/10267116/PixivBrowserFactory.zip)
[pixivutil2.zip](https://github.com/Nandaka/PixivUtil2/files/10267138/pixivutil2.zip)

**Comment by Nandaka** [comment]
@KamenReader can you also check https://github.com/Nandaka/PixivUtil2/tree/http2 branch with fanbox? At least the pixiv side is working so far.

**Comment by AgentThirteen** [comment]
With the plethora of 5xx errors that preceded the changes, it was predictable there was some kind of panic or mass bot activity that forced pixiv to take action.

@Nandaka https://github.com/Nandaka/PixivUtil2/commit/2fe5bb1e4dddc7b80c7bd950d1cd1e5290c53397 does not work with pixiv here, it fatals immediately with:
````
Traceback (most recent call last):
  File "pixivutil2.py", line 1772, in <module>
    main()
  File "pixivutil2.py", line 1626, in main
    __br__ = PixivBrowserFactory.getBrowser(config=__config__)
  File "PixivBrowserFactory.py", line 1304, in getBrowser
    _browser = PixivBrowser(defaultConfig, defaultCookieJar)
  File "PixivBrowserFactory.py", line 114, in __init__
    cookies = (dict(i.split('=', 1) for i in self._config.cookie.split('; ')))
ValueError: dictionary update sequence element #0 has length 1; 2 is required
````
Any cookie changes to `config.ini` required? Thank you.

**Comment by Nandaka** [comment]
ah, need to paste the full cookie string, not only the session id.
![image](https://user-images.githubusercontent.com/836867/208694091-31400393-4da3-4903-a087-51ba465c3398.png)

**Comment by bluerthanever** [comment]
> @bluerthanever wont it fix the HTTP/2 issue, as far as I know this is part of cloudflare feature?

it's also based on python, and i don't see any http2 modules or anything that says it supports http2....
so i guess it's not about http2?


i tried it this afternoon with fiddler and it worked.

**Comment by Hamuko** [comment]
API endpoints might have less strict Cloudflare protections than non-API endpoints.

**Comment by gnarf1975** [comment]
I've just tried . I've logged in. Now all of a sudden it works again. 

![2022-12-20](https://user-images.githubusercontent.com/31275885/208735628-b21e87e3-c5df-48be-8aca-40d1193f2c41.png)

**Comment by Hamuko** [comment]
Same for me. Downloading files right now. Haven't done anything to my local environment. Guessing it's a configuration change with Pixiv/Cloudflare.

**Comment by DarkKuroi** [comment]
Suddenly it works again. I only refresh cookie in ini file 4 days ago (it won't helped) and just waited 4 days. Din't do anything else.

**Comment by Revemohl** [comment]
Didn't suddenly start working here though, neither with my old password/cookie nor with the ones I just got.

**Comment by PatrickL546** [comment]
Can confirm my old install starts working again

**Comment by MarqFJA87** [comment]
It's working for me again, and I haven't changed a single thing in my settings or files. I guess Pixiv has downgraded their Cloudflare security setting to the previous normal.

**Comment by TechnoMasterBoy** [comment]
Works here too all of a sudden.

**Comment by cglmrfreeman** [comment]
Wtf is pixiv doing, lol

**Comment by QPUNeptune** [comment]
ayyy lmao it really works again bruh

**Comment by KamenReader** [comment]
> @KamenReader can you also check https://github.com/Nandaka/PixivUtil2/tree/http2 branch with fanbox? At least the pixiv side is working so far.

Tried out the http2 branch.  Looks like it's being blocked by Cloudflare version 2, which cloudscraper doesn't work with.  I've attached the log.
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/10274251/pixivutil.log)

This problem, even if it seems to be working again for some people, seems to perfectly mirror an issue that gallery-dl had, right down to the "suddenly working again" and going "back to not working" (and various people reporting sucess with proxies and others having no success with proxies, etc.): [gallery-dl Issue #1922](https://github.com/mikf/gallery-dl/issues/1922)  It's marked as fixed now, but I don't know that it ever really was "fixed" entirely.  An alternative downloader for Patreon, https://github.com/AlexCSDev/PatreonDownloader, uses a small Chromium instance to complete the Cloudflare Captcha challenge.  Something similar may be required here.

**Comment by baraghiffari** [comment]
Can confirm, it's working again suddenly without doing anything after the last one

**Comment by shinji257** [comment]
> > @KamenReader can you also check https://github.com/Nandaka/PixivUtil2/tree/http2 branch with fanbox? At least the pixiv side is working so far.
> 
> Tried out the http2 branch. Looks like it's being blocked by Cloudflare version 2, which cloudscraper doesn't work with. I've attached the log. [pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/10274251/pixivutil.log)
> 
> This problem, even if it seems to be working again for some people, seems to perfectly mirror an issue that gallery-dl had with Patreon, right down to the "suddenly working again" and going "back to not working" (and various people reporting sucess with proxies and others having no success with proxies, etc.): [gallery-dl Issue #1922](https://github.com/mikf/gallery-dl/issues/1922) It's marked as fixed now, but I don't know that it ever really was "fixed" entirely. An alternative downloader for Patreon, https://github.com/AlexCSDev/PatreonDownloader, uses a small Chromium instance to complete the Cloudflare Captcha challenge. Something similar may be required here.
> 
> Edit: @anonymous721 mentioned earlier that gallery-dl is still working for Pixiv in general. Looks like they're using an OAuth token, just like Fanbox uses in PixivUtil2 in its workaround, so using OAuth for Pixiv in general is probably unavoidable.

Yup.  I remember the issue with PatreonDownloader but I kind of figured that this was some kind of bot protect that triggered and they were flagging all the connections for a while.  Even still we should probably setup some kind of fallback for Pixiv to go and use OAuth when the standard login flow fails or in situations where it gets a 403 error.

**Comment by h3ntaih3ro** [comment]
Just checked, it's working for me again too.

**Comment by hehequya** [comment]
any one know how to fix this:  <HTTPError 429: 'Too Many Requests'>>

**Comment by PatrickL546** [comment]
@hehequya Just slow down the download, `downloadDelay = 5` or more

**Comment by Nandaka** [comment]
Looks like it works again using master branch for me.

**Comment by PatrickL546** [comment]
@Nandaka Will [This](https://github.com/Nandaka/PixivUtil2/commit/b65b3f62d78f5a7b805de95f946ee581f4291d42) be reverted? I've been using the release before that and when login worked again, never had a problem.

**Comment by Nandaka** [comment]
well, I don't see any differences so I think I'll leave it there
