### ISSUE TITLE
[http2] Endless loop with Artist Info: (<class 'TypeError'>, TypeError('list indices must be integers or slices, not str')

### ISSUE THREAD

**Issue by AgentThirteen** [Nandaka/PixivUtil2#1212]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Utility loops on `Error at processing Artist Info: (<class 'TypeError'>, TypeError('list indices must be integers or slices, not str')` until forcefully closed. This only happens with certain artists.

### Steps to Reproduce

Example artist ids: 98192, 3676772 (NSFW)
1. Option 1, use example artist id
2. Wait until the utility loops then terminate it before it fills the log

**Expected behavior:** Download from artist

**Actual behavior:** Endless loop, the utility must be terminated by the user

**Log file:**
````
[...]
****,404 - PixivUtil20221029 - ERROR - Error at processing Artist Info: (<class 'TypeError'>, TypeError('list indices must be integers or slices, not str')
****,435 - PixivUtil20221029 - ERROR - Error at processing Artist Info: (<class 'TypeError'>, TypeError('list indices must be integers or slices, not str')
****,467 - PixivUtil20221029 - ERROR - Error at processing Artist Info: (<class 'TypeError'>, TypeError('list indices must be integers or slices, not str')
[...]
````

### Versions

https://github.com/Nandaka/PixivUtil2/commit/2fe5bb1e4dddc7b80c7bd950d1cd1e5290c53397

**Comment by Nandaka** [comment]
weird, I tested it and I got the proper message in 2fe5bb1e4dddc7b80c7bd950d1cd1e5290c53397
![image](https://user-images.githubusercontent.com/836867/208715942-39c9f0c5-babc-41cb-8f43-07a64956f2af.png)

**Comment by AgentThirteen** [comment]
Thank you for the reply.

Please try with example artist 98192. The error returned is different (artist not found), I guess this is because that one error isn't caught. I will edit the issue to reflect that it only applies to such artists.

I tried with https://github.com/Nandaka/PixivUtil2/commit/3d48f6c335829cefced7e45ea669211bb89c6ff1 and got this:
````
Member Url: https://www.pixiv.net/ajax/user/98192/profile/all
Error at processing Artist Info: (<class 'TypeError'>, TypeError('list indices must be integers or slices, not str'), <traceback object at 0x0000018F9DDCC940>)
Traceback (most recent call last):
  File "PixivArtistHandler.py", line 68, in process_member
    (artist, list_page) = PixivBrowserFactory.getBrowser().getMemberPage(member_id, page, bookmark, tags, r18mode=config.r18mode, throw_empty_error=True)
  File "PixivBrowserFactory.py", line 838, in getMemberPage
    self.getMemberInfoWhitecube(member_id, artist, bookmark)
  File "PixivBrowserFactory.py", line 764, in getMemberInfoWhitecube
    artist.ParseBackground(info_ajax)
  File "PixivArtist.py", line 138, in ParseBackground
    self.artistId = root["userId"]
TypeError: list indices must be integers or slices, not str
````

The error from the browser is `ユーザーが見つかりませんでした` instead of `該当ユーザーは既に退会したか、存在しないユーザーIDです。`

The log was posted, it doesn't have any more information other than that error, should I put it on `VERBOSE`?
