### ISSUE TITLE
Option 15 - Novel Series ID, crash

### ISSUE THREAD

**Issue by Slowbreaker** [Nandaka/PixivUtil2#1234]
Using latest commit version > 5d0b370
If I try to download a whole Novel series it throw an error, but no error if I download the Series one Novel at a time.
I censored some part with * for privacy reason.

_INFO - Novel Series mode (15).
INFO - Novel Series IDs: ['*******']
INFO - Processing Novel Series: ********
ERROR - Unknown Error: 'seriesContents'
Traceback (most recent call last):
  File "c:\pixivutil2\PixivUtil2.py", line 1738, in main
    np_is_valid, op_is_valid, selection = main_loop(ewd, op_is_valid, selection, np_is_valid, args, options)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\pixivutil2\PixivUtil2.py", line 1436, in main_loop
    menu_download_by_novel_series_id(op_is_valid, args, options)
  File "c:\pixivutil2\PixivUtil2.py", line 708, in menu_download_by_novel_series_id
    PixivNovelHandler.process_novel_series(sys.modules[__name__],
  File "c:\pixivutil2\PixivNovelHandler.py", line 103, in process_novel_series
    novel_series = caller.__br__.getNovelSeriesContent(novel_series, current_page=page)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\pixivutil2\PixivBrowserFactory.py", line 1207, in getNovelSeriesContent
    novel_series.parse_series_content(response, current_page)
  File "c:\pixivutil2\PixivNovel.py", line 165, in parse_series_content
    self.series_list.extend(js["body"]["seriesContents"])
                            ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'seriesContents'
ERROR - Unknown Error, please check the log file: (<class 'KeyError'>, KeyError('seriesContents'), <traceback object at 0x000002002E318240>)_

**Comment by Slowbreaker** [comment]
Sorry been on vacation and I just saw this fix.

I tested with multiples authors and it works correctly now.

Thanks :)
