### ISSUE TITLE
Images No Longer Loading on Pixiv Website

### ISSUE THREAD

**Issue by SakiSakiSakiSakiSaki** [Nandaka/PixivUtil2#1236]
So I left PixivUtil2 (pixivutil202305) running for about 2 days, downloading about 20,000 likes worth of images (50,000 images). During and after the runtime completed, I noticed that whenever I tried to access Pixiv through Chrome, artworks would not load. They would all look like this:

![image](https://user-images.githubusercontent.com/41088844/220053506-c9ffb478-f30a-4a29-848b-174b2dfeeb97.png)

I'm not sure why this is. The front page loads fine for me, but individual artworks no longer load. I'm able to use Pixix fine on Firefox, but not on Chrome, the browser I got my PHPSESSID value from. Logging out doesn't change anything.

Seeing as though it's tangentiallly related to Pixivutil2, and I'm wondering if anyone has come across this, and if there's a way I can fix this?

I have already cleared all of the cookies on my Chrome browser, this did not help.

Edit: Seems like I'm unable to run the program after changing my cookie value to one from Firefox. The log gives the follow errors:

```log
2023-02-20 03:44:22,094 - PixivUtil20230105 - INFO - Premium User: False.
2023-02-20 03:44:22,094 - PixivUtil20230105 - WARNING - R-18G is disabled from pixiv website settings.
2023-02-20 03:44:22,094 - PixivUtil20230105 - INFO - Locale = /en
2023-02-20 03:44:25,710 - PixivUtil20230105 - INFO - User's Image Bookmark mode (6).
2023-02-20 03:44:30,304 - PixivUtil20230105 - INFO - Importing user's bookmarked image from page 0
2023-02-20 03:44:30,305 - PixivUtil20230105 - INFO - Source URL: https://www.pixiv.net/ajax/user/18482074/illusts/bookmarks?tag=&offset=-48&limit=48&rest=show
2023-02-20 03:44:30,637 - PixivUtil20230105 - ERROR - Error at process_image_bookmark(): (<class 'mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib.error.HTTPError instance) at 0x1dd334c6200 whose wrapped object = <HTTPError 400: 'Bad Request'>>, <traceback object at 0x000001DD3346B100>)
2023-02-20 03:44:30,642 - PixivUtil20230105 - ERROR - Unknown Error: HTTP Error 400: Bad Request
Traceback (most recent call last):
  File "PixivUtil2.py", line 1738, in main
  File "PixivUtil2.py", line 1418, in main_loop
  File "PixivUtil2.py", line 574, in menu_download_from_online_image_bookmark
  File "PixivBookmarkHandler.py", line 79, in process_image_bookmark
  File "PixivBookmarkHandler.py", line 425, in get_image_bookmark
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 400: Bad Request
2023-02-20 03:44:30,643 - PixivUtil20230105 - ERROR - Unknown Error, please check the log file: (<class 'mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib.error.HTTPError instance) at 0x1dd334c6200 whose wrapped object = <HTTPError 400: 'Bad Request'>>, <traceback object at 0x000001DD334E5D80>)
```

**Comment by PatrickL546** [comment]
It's the server limiting you, nothing you can do about it except wait, or maybe changing your IP and use an alt account or something. Excessive usage will get you blocked for a while.

**Comment by PatrickL546** [comment]
For me it is sometimes 10 min before it allows me to view it again, sometimes 30 min or more. 

Can't really tell what happens for the error, maybe relog to get new cookies and use that?
