### ISSUE TITLE
Login cookie issue

### ISSUE THREAD

**Issue by cocokakao** [Nandaka/PixivUtil2#1239]
I reinstalled it. 
I logged in and replaced the cookie, but the same phrase came out.

-------------------------------------------------------------------------------------

Trying to log in with saved cookie
Error at doLogin(): (<class 'mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib.error.HTTPError instance) at 0x1e0f201f250 whose wrapped object = <HTTPError 403: 'Forbidden'>>, <traceback object at 0x000001E0F01B7800>)
Traceback (most recent call last):
  File "PixivUtil2.py", line 1524, in doLogin
  File "PixivBrowserFactory.py", line 347, in loginUsingCookie
  File "PixivBrowserFactory.py", line 207, in open_with_retry
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 403: Forbidden

Cannot Login!
press enter to exit.

**Comment by Osprey-Hawk** [comment]
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/10846747/pixivutil.log)
I'm having the same issue.  I attached my own log with my login censored.

**Comment by xWTF** [comment]
The login request to `https://www.pixiv.net/en/` is failing:
```
Trying to log in with saved cookie

send: b'CONNECT www.pixiv.net:443 HTTP/1.0\r\n'
send: b'\r\n'
send: b'GET /en HTTP/1.1\r\nAccept-Encoding: identity\r\nCookie: PHPSESSID=[REDACTED]\r\nUser-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36\r\nHost: www.pixiv.net\r\nConnection: close\r\n\r\n'

reply: 'HTTP/1.1 302 Found\r\n'
header: Date: Tue, 28 Feb 2023 [REDACTED] GMT
header: Content-Type: text/html; charset=UTF-8
header: Content-Length: 0
header: Connection: close
header: vary: User-Agent
header: x-host-time: 109
header: x-xss-protection: 1; mode=block
header: set-cookie: first_visit_datetime_pc=[REDACTED]; expires=Thu, 27-Feb-2025 [REDACTED] GMT; Max-Age=63072000; path=/; secure
header: location: /en/
header: strict-transport-security: max-age=31536000
header: x-frame-options: SAMEORIGIN
header: CF-Cache-Status: DYNAMIC
header: Set-Cookie: __cf_bm=[REDACTED]; path=/; expires=Tue, 28-Feb-23 [REDACTED] GMT; domain=.pixiv.net; HttpOnly; Secure; SameSite=None
header: Server: cloudflare
header: CF-RAY: [REDACTED]
header: alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400

send: b'CONNECT www.pixiv.net:443 HTTP/1.0\r\n'
send: b'\r\n'
send: b'GET /en/ HTTP/1.1\r\nAccept-Encoding: identity\r\nCookie: PHPSESSID=[REDACTED]; first_visit_datetime_pc=[REDACTED]; __cf_bm=[REDACTED]\r\nUser-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36\r\nHost: www.pixiv.net\r\nConnection: close\r\n\r\n'

reply: 'HTTP/1.1 403 Forbidden\r\n'
header: Date: Tue, 28 Feb 2023 [REDACTED] GMT
header: Content-Type: text/html; charset=UTF-8
header: Transfer-Encoding: chunked
header: Connection: close
header: Permissions-Policy: accelerometer=(),autoplay=(),camera=(),clipboard-read=(),clipboard-write=(),fullscreen=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()
header: Referrer-Policy: same-origin
header: X-Frame-Options: SAMEORIGIN
header: Cache-Control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
header: Expires: Thu, 01 Jan 1970 00:00:01 GMT
header: Vary: Accept-Encoding
header: Server: cloudflare
header: CF-RAY: [REDACTED]
header: alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
```

A temporary workaround is to modify [PixivBrowserFactory.py](https://github.com/Nandaka/PixivUtil2/blob/master/PixivBrowserFactory.py) `loginUsingCookie` method to:
- Load the cookie
- Set `self._myId`
- Set `self._isPremium`
- Return true directly without sending the request.

Other functionalities (fanbox login, download) seems to be working atm.

**Comment by biggestsonicfan** [comment]
Wow I was just using it moments ago, if you had the utility still running, it would work, but now it won't.

**Comment by matsumotokenji** [comment]
same getting HTTP Error 403: Forbidden

**Comment by Nanoka** [comment]
maybe related to #1209 as the solution i found that time seems to work now as well
change the useragent string to just "Mozilla/5.0" and it should work (try again if it fails)

**Comment by gnarf1975** [comment]
> maybe related to #1209 as the solution i found that time seems to work now as well change the useragent string to just "Mozilla/5.0" and it should work (try again if it fails)

Doesn't work for me

**Comment by halcatt** [comment]
> maybe related to #1209 as the solution i found that time seems to work now as well change the useragent string to just "Mozilla/5.0" and it should work (try again if it fails)

Best answer! Should be highlighted

**Comment by DisasterInbound** [comment]
> maybe related to #1209 as the solution i found that time seems to work now as well change the useragent string to just "Mozilla/5.0" and it should work (try again if it fails)

I can also confirm it worked. I deleted the rest of the text and only kept Mozilla/5.0 and I logged in this time

**Comment by Osprey-Hawk** [comment]
Can confirm.  Worked perfectly.  I tested it prior to modifying the INI and it had the error.  With the change it had no issues.

**Comment by PatrickL546** [comment]
Have a feeling Cloudflare is the problem, could be a coincidence that another thing I use also got issues at the same time.

The User-agent workaround does work.

**Comment by Uraratan** [comment]
[Network]
useProxy = False
proxyAddress = 
useragent = Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36
useRobots = True
timeout = 60
retry = 3
retryWait = 5
downloadDelay = 2
checkNewVersion = True
notifyBetaVersion = True
openNewVersion = True
enableSSLVerification = True

is what default settings is i guess ?

**Comment by dragontamer8740** [comment]
Setting user-agent to just `Mozilla/5.0` works.

**Comment by VeggieJay** [comment]
> maybe related to #1209 as the solution i found that time seems to work now as well change the useragent string to just "Mozilla/5.0" and it should work (try again if it fails)

works

**Comment by na3i09** [comment]
Changing user-agent doesn't work for me while running from source on linux. Still get the 403 error.

**Comment by PatrickL546** [comment]
@na3i09 "useragent = Mozilla/5.0" did you use that? if so, idk other workaround

**Comment by na3i09** [comment]
> @na3i09 "useragent = Mozilla/5.0" did you use that? if so, idk other workaround

yeah, no dice when using the source version.

**Comment by Nanoka** [comment]
> Changing user-agent doesn't work for me while running from source on linux. Still get the 403 error.

Try changing `https://www.pixiv.net/en` to `https://www.pixiv.net` in PixivBrowserFactory.py line 347:
https://github.com/Nandaka/PixivUtil2/blob/master/PixivBrowserFactory.py#L347

**Comment by elina7** [comment]
useragent = Mozilla / 5.0 is not work
useragent = Mozilla/5.0 is working

**Comment by capSAR273** [comment]
I still cannot log in using the session cookie and the proper user agent.

**Comment by PatrickL546** [comment]
Created a pull request https://github.com/Nandaka/PixivUtil2/pull/1281 Hopefully fixes http:403 forbidden and people's confusion

**Comment by JojoWalks** [comment]
MAN, this thread is making zero sense to me. I cant keep up

**Comment by xWTF** [comment]
> MAN, this thread is making zero sense to me. I cant keep up

Hi, please kindly stop posting non-constructive comments that disturbs everyone subscribed to this issue or repo.

Also, I would appreciate it if you can stop downvoting a solution that has expired for nearly a year ¯\\_(ツ)_/¯.

I've already pointed out that you should use the solution by Nanoka, which worked very well. My automation script run twice a day and never fails since I switched to that solution.

![image](https://github.com/Nandaka/PixivUtil2/assets/31540475/da45b3b4-4853-4d9e-9e03-2c5b88de8b2b)

**Comment by AndrewHack242** [comment]
I'm having this issue now, just pulled main down to try to fix it, but it is persisting. I've logged out and back in to re-aquire my cookie from firefox multiple times but it continues to give me this error.

I had the thought that I may be populating the cookie incorrectly, but if I change the last character to make it invalid I get a different error: 
```
Error at doLogin(): (<class 'mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib.error.HTTPError instance) at 0x7f5785b98d40 whose wrapped object = <HTTPError 302: 'The HTTP server returned a redirect error that would lead to an infinite loop.\nThe last 30x error message was:\nFound'>>, <traceback object at 0x7f5785b3a000>) 
Traceback (most recent call last):
  File "/home/ahack/programming/PixivUtil2/PixivUtil2.py", line 1527, in doLogin
    result = __br__.loginUsingCookie()
  File "/home/ahack/programming/PixivUtil2/PixivBrowserFactory.py", line 354, in loginUsingCookie
    res = self.open_with_retry('https://www.pixiv.net')  # + self._locale)
  File "/home/ahack/programming/PixivUtil2/PixivBrowserFactory.py", line 208, in open_with_retry
    res = self.open(url, data, timeout)
  File "/home/ahack/programming/PixivUtil2/venv/lib/python3.10/site-packages/mechanize/_mechanize.py", line 257, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
  File "/home/ahack/programming/PixivUtil2/venv/lib/python3.10/site-packages/mechanize/_mechanize.py", line 313, in _mech_open
    raise response
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 302: The HTTP server returned a redirect error that would lead to an infinite loop.
The last 30x error message was:
Found
```
So it seems like my cookie is correct and then something else is causing it to fail.

I have tried both 
useragent = Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0
 which was copied out of my browser and
useragent = Mozilla/5.0
to no avail

**Comment by Uraratan** [comment]
Nandaka, on pixiv fanbox i keep etting this 

Configuration loaded.
Trying to log in FANBOX with saved cookie
Error getting FANBOX artist by id: 8594243 ==> Failed FANBOX Cloudflare CAPTCHA challenge, please check your cookie and user-agent settings.

i re appied 
cf_clearance
cf_bm
cookieFanbox

the default pixiv worksfine just fanbox not and i have no clue what i do wrong 

the view cookies i use this addon "cookie editor"

i have no clue what this cloudfare thing is

**Comment by biggestsonicfan** [comment]
@Uraratan This is an issue for Pixiv logins, not Fanbox. Your issue is a duplicate of #1361 and #1371. I suggest searching through existing issues before simply posting under a pinned issue.

**Comment by JeurseLightYokai** [comment]
Sorry to bring back this http:403 forbidden issue but fixing useragent didn't fix the issue here:
- I checked my cookies and cf multiple times: restarted a new session, restarted the browser, starting over the cookie maneuver. so it is not a cookie related issue
- Changed useragent with: useragent = Mozilla/5.0 as suggested in every issues opened on this topic, tried again with correct cookies and it **didn't** fix the issue
- tried switching multiple times useragent. I'm still stuck with the same Error
- note that the issue appeared again since I updated all requirements using: pip install --upgrade --force-reinstall -r requirements.txt
I've looked a bit at all issues related on this error and didn't find another solution.
First time commenting on github, no idea how to use it properly so sorry if I missed something or did things wrong.

**Comment by jirat-sumitanun** [comment]
> Sorry to bring back this http:403 forbidden issue but fixing useragent didn't fix the issue here:
> 
> * I checked my cookies and cf multiple times: restarted a new session, restarted the browser, starting over the cookie maneuver. so it is not a cookie related issue
> * Changed useragent with: useragent = Mozilla/5.0 as suggested in every issues opened on this topic, tried again with correct cookies and it **didn't** fix the issue
> * tried switching multiple times useragent. I'm still stuck with the same Error
> * note that the issue appeared again since I updated all requirements using: pip install --upgrade --force-reinstall -r requirements.txt
>   I've looked a bit at all issues related on this error and didn't find another solution.
>   First time commenting on github, no idea how to use it properly so sorry if I missed something or did things wrong.

I will share my method and it work for me
first, change your pixiv language to japanese and logout
second, login back and get your "PHPSESSID"

I try change language back but it not work, you have to stay in japanese language to use it

**Comment by codingbyme495** [comment]
@jirat-sumitanun 
@Virtualvortex857 
thanks you very much guys, changing the language to japanese worked for me, it's indeed really strange though

**Comment by redblack01** [comment]
exe version:
Unable to get User Id, please check your cookie.
Please follow the instruction in https://github.com/Nandaka/PixivUtil2/issues/814#issuecomment-711182644
Error at doLogin(): (<class 'PixivException.PixivException'>, PixivException('Unable to get User Id, please check your cookie.'), <traceback object at 0x00000211AA6163C0>)
Traceback (most recent call last):
  File "PixivUtil2.py", line 1527, in doLogin
  File "PixivBrowserFactory.py", line 371, in loginUsingCookie
  File "PixivBrowserFactory.py", line 604, in getMyId
PixivException.PixivException: PixivException(100 Unable to get User Id, please check your cookie., hasDumpPage=Y)

Cannot Login!

source code version:
Unable to get User Id, please check your cookie.
Please follow the instruction in https://github.com/Nandaka/PixivUtil2/issues/814#issuecomment-711182644
Error at doLogin(): (<class 'PixivException.PixivException'>, PixivException('Unable to get User Id, please check your cookie.'), <traceback object at 0x000002DED80BAF80>)
Traceback (most recent call last):
  File "E:\PixivUtil2\PixivUtil2.py", line 1527, in doLogin
    result = __br__.loginUsingCookie()
  File "E:\PixivUtil2\PixivBrowserFactory.py", line 371, in loginUsingCookie
    self.getMyId(parsed_str)
    ~~~~~~~~~~~~^^^^^^^^^^^^
  File "E:\PixivUtil2\PixivBrowserFactory.py", line 604, in getMyId
    raise PixivException("Unable to get User Id, please check your cookie.", errorCode=PixivException.NOT_LOGGED_IN, htmlPage=parsed)
PixivException.PixivException: PixivException(100 Unable to get User Id, please check your cookie., hasDumpPage=Y)

Cannot Login!

-------------------------------------
fixes I tried:

-changing password
-changing language and location to japanese
- fix useragent to correct version
- fix useragent to mozilla/5.0
- delete first part from cookie (XXXXXXX_)
- cf_clearance and cf_bm from firefox browser
- cf_clearance and cf_bm to fanbox cookie
- change "https://pixiv.net/en" to "https://pixiv.net/" in pixivbrowserfactory.py

I tried fixes above multiple times on both version and renewed my cookie every time, only to get the same result.

**Comment by JeurseLightYokai** [comment]
@jirat-sumitanun
@Virtualvortex857 
Sorry but changing language to japanese did not work for me, same error. I've also tried updating cookies, cf_bm, cf_clearance as you did with fanbox cookies, and I've tried to modify cookies hundreds of times in different ways, I still get the same error. no maatter which version I am using.

**Comment by jirat-sumitanun** [comment]
> [@jirat-sumitanun](https://github.com/jirat-sumitanun) [@Virtualvortex857](https://github.com/Virtualvortex857) Sorry but changing language to japanese did not work for me, same error. I've also tried updating cookies, cf_bm, cf_clearance as you did with fanbox cookies, and I've tried to modify cookies hundreds of times in different ways, I still get the same error. no maatter which version I am using.

The thing I do is change language to japanese and get new "PHPSESSID".
That's all, I didn't change anything either

**Comment by JeurseLightYokai** [comment]
Finally got to fix the issue.
For those who are still stuck with this error despite having tried everything listed above:

-First, follow these instructions: https://github.com/Nandaka/PixivUtil2/issues/1386#issuecomment-2536949391

then, if you are stuck with: "TypeError: can't multiply sequence by non-int of type 'str'"

-Follow these instructions: #1404 

Hope this will help you.

**Comment by Flandre5carlet** [comment]
> Unable to get User Id, please check your cookie. Please follow the instruction in [#814 (comment)](https://github.com/Nandaka/PixivUtil2/issues/814#issuecomment-711182644) Error at doLogin(): (<class 'PixivException.PixivException'>, PixivException('Unable to get User Id, please check your cookie.'), <traceback object at 0x000002DED80BAF80>) Traceback (most recent call last): File "E:\PixivUtil2\PixivUtil2.py", line 1527, in doLogin result = **br**.loginUsingCookie() File "E:\PixivUtil2\PixivBrowserFactory.py", line 371, in loginUsingCookie self.getMyId(parsed_str) ~~~~~~~~~~~~^^^^^^^^^^^^ File "E:\PixivUtil2\PixivBrowserFactory.py", line 604, in getMyId raise PixivException("Unable to get User Id, please check your cookie.", errorCode=PixivException.NOT_LOGGED_IN, htmlPage=parsed) PixivException.PixivException: PixivException(100 Unable to get User Id, please check your cookie., hasDumpPage=Y)
> 
> Cannot Login!
> 
> fixes I tried:
> 
> * changing password
> * changing language and location to japanese
> * fix useragent to correct version
> * fix useragent to mozilla/5.0
> * delete first part from cookie (XXXXXXX_)
> * cf_clearance and cf_bm from firefox browser
> * cf_clearance and cf_bm to fanbox cookie
> * change "https://pixiv.net/en" to "https://pixiv.net/" in pixivbrowserfactory.py
> 
> I tried fixes above multiple times on both version and renewed my cookie every time, only to get the same result.

Same thing for me. Tried every single thing I did to make it work beforehand, but none of it does anything, and I always get the "Unable to get User Id" message.

**Comment by kyanhluong** [comment]
I did all of that and it didn't work either
For anyone need it working in a pinch, hardcode your pixiv id in a mean time :
In file PixivBrowserFactory.py and line 601 change from `if self._myId == 0:` to `self._myId = <your piviv id> #if self._myId == 0:`
And comment out from line 602 to line 604

**Comment by memedoggo** [comment]
```
Error at doLogin(): (<class 'mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib.error.HTTPError instance) at 0x1e87fa6c050 whose wrapped object = <HTTPError 403: 'Forbidden'>>, <traceback object at 0x000001E87FA88E40>)
Traceback (most recent call last):
  File "E:\pixivdownloader\PixivUtil2.py", line 1558, in doLogin
    result = __br__.loginUsingCookie()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pixivdownloader\PixivBrowserFactory.py", line 359, in loginUsingCookie
    res = self.open_with_retry('https://www.pixiv.net')  # + self._locale)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pixivdownloader\PixivBrowserFactory.py", line 211, in open_with_retry
    res = self.open(url, data, timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Roaming\Python\Python312\site-packages\mechanize\_mechanize.py", line 257, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Roaming\Python\Python312\site-packages\mechanize\_mechanize.py", line 313, in _mech_open
    raise response
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 403: Forbidden

Cannot Login!
```
tried with cookies, doesn't work..
