### ISSUE TITLE
Fanbox F1 Error

### ISSUE THREAD

**Issue by gnarf1975** [Nandaka/PixivUtil2#1267]
Traceback (most recent call last):
  File "PixivUtil2.py", line 1738, in main
  File "PixivUtil2.py", line 1467, in main_loop
  File "PixivUtil2.py", line 916, in menu_fanbox_download_from_list
ValueError: invalid literal for int() with base 10: 'XXXXXXX'
Unknown Error, please check the log file: (<class 'ValueError'>, ValueError("invalid literal for int() with base 10: 'siro2051887'"), <traceback object at 0x00000226785C1B80>)
press enter to exit.

**Comment by PatrickL546** [comment]
dupe of https://github.com/Nandaka/PixivUtil2/issues/1265
