### ISSUE TITLE
Login Issue. 

### ISSUE THREAD

**Issue by AltonFarder** [Nandaka/PixivUtil2#1279]
Yes I did read through Login Issues - December 2022 #1209. People claiming they are not logging in then suddenly they are logged in. Didn't help. I've been trying to get this software to work for the past 6 hours no joke. Firstly I faced the same issue as [Echo-Yggdrasil] on How Do You Use This Program? #242, were the application was not appearing or clicking and instantly vanishing. 

THen after muddling about I finally got that done only to find I can't log in. The error message is as follows:

Error at login(): (<type 'exceptions.KeyError'>, KeyError('pixivAccount.postKey',), <traceback object at 0x03EBCEE0>)
Error at doLogin(): (<type 'exceptions.KeyError'>, KeyError('pixivAccount.postKey',), <traceback object at 0x03EBCE90>)
Cannot Login!

People are saying to reset cookies. like on this youtube video comment: https://www.youtube.com/watch?v=tT3c1RuEK9o which seems to be the only video guide out there from years ago, but doesn't work. Please help me I've got a splitting headache from trying to get this to work I just want to use this software.

**Comment by PatrickL546** [comment]
https://github.com/Nandaka/PixivUtil2/issues/1227  
https://github.com/Nandaka/PixivUtil2/issues/1271
You missed this.

**Comment by AltonFarder** [comment]
Okay just to write what steps I've taken. 

I got the same error. And then 

I followed the steps to add the cookie to the config file. After adding the value from the "" after the PHPSESSID.  

Got this message:

Trying to log in with saved cookie
Error at doLogin(): (<class 'mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib.error.HTTPError instance) at 0x142881c8b80 whose wrapped object = <HTTPError 403: 'Forbidden'>>, <traceback object at 0x0000014286A43C40>)
Traceback (most recent call last):
  File "PixivUtil2.py", line 1524, in doLogin
  File "PixivBrowserFactory.py", line 347, in loginUsingCookie
  File "PixivBrowserFactory.py", line 207, in open_with_retry
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 403: Forbidden

Cannot Login!
press enter to exit.


------------


And then looking further down I saw this: 

![image](https://github.com/Nandaka/PixivUtil2/assets/138168896/6313c237-92b5-42b5-9f2b-130fc159237f)

Are we expected to go into the software's code and edit this? Which file do I open? It doesn't let me edit the main application

![image](https://github.com/Nandaka/PixivUtil2/assets/138168896/9893d277-f1ed-4a88-83b0-7b280e9f3091)

**Comment by AltonFarder** [comment]
Sorry I just want this to work. And it appears assumptions are made both in the installation 

since this isn't a bit of software that just simply runs after you install it. And people are going to keep writing in spending hours trying to fix this issue going through all the documents and guessing. I'll try to explain where I am lost. 

From the latest version: https://github.com/Nandaka/PixivUtil2/releases

There is Pixivutil202305
Source code (Zip)
Source Code 

The Pixivutil202305 has the application that you can run but the password doesn't load. The source code has the files you can open in Py but no application. Also the configs appear to be different in both. That's also confusing. Are they the same and it's this bit here:

![image](https://github.com/Nandaka/PixivUtil2/assets/138168896/198d91f9-a988-4ac0-bf43-849b65971fde)

And so I'll add in the cookies part as instructed, to then get the same error message that appeared on the tutorial ( https://github.com/Nandaka/PixivUtil2/issues/1271 left by [UpscaleAnon], to then search changing the useragent? 

Which I assume would be here:

![image](https://github.com/Nandaka/PixivUtil2/assets/138168896/c8dab8ec-d7fd-41de-8827-96d893287360)

And guess to remove everything but Firefox?

Thank you for taking the time to read

**Comment by PatrickL546** [comment]
If you are using the [pixivutil202305.zip](https://github.com/Nandaka/PixivUtil2/releases/download/v20230105/pixivutil202305.zip). Download and extract it. Run `PixivUtil2.exe`, it should look like this 
![image](https://github.com/Nandaka/PixivUtil2/assets/75874561/16d37295-c5bf-42a2-ad15-63a748052e0c)

Open `config.ini` and use the useragent workaround.
![image](https://github.com/Nandaka/PixivUtil2/assets/75874561/c4e257a2-6978-4b41-81d7-5b6474eb18b0)

And add your cookies. (see readme.md)
![image](https://github.com/Nandaka/PixivUtil2/assets/75874561/863cabe8-c33f-4264-a6b8-afcc272fcbc5)

# Source code
If you want to enable Username/Password login you can use this. [Source code (zip)](https://github.com/Nandaka/PixivUtil2/archive/refs/tags/v20230105.zip) 
It should be the same steps as before but instead of `.exe` it's `.py` (see readme.md) on how to use source code version
To enable the Username/Password login, open `PixivUtil2.py` in a text editor and go to this section

![image](https://github.com/Nandaka/PixivUtil2/assets/75874561/5cd87691-cd45-4387-a5a2-03fac562fc1e)

Remove the `#` on the last 2 option and it should try to login with username and password.

![image](https://github.com/Nandaka/PixivUtil2/assets/75874561/f2d6f6cd-05f8-4522-9e33-9634a3eca1cd)

**Comment by AltonFarder** [comment]
Okay I'm going to have to give this a try tomorrow, thanks for continuously replying.

**Comment by kody180** [comment]
This is so ridiculously complex. Jdownloader2 already has working pixiv, but that program is bloated with complexity with the file naming custom.

**Comment by PatrickL546** [comment]
> This is so ridiculously complex. Jdownloader2 already has working pixiv, but that program is bloated with complexity with the file naming custom.

How so? The workaround just takes, opening a text file and removing most of one line of text.

**Comment by AltonFarder** [comment]
There is no Config.ini in that ZIP folder. 
![image](https://github.com/Nandaka/PixivUtil2/assets/138168896/c212edc5-4692-478b-bff0-6f8ef0d19615)

**Comment by AltonFarder** [comment]
I followed the non source ZIP code and got it to work, thanks. For anyone reading this, make sure to attempt to log in to create the config.ini !

Now just need to figure out how to use it. Thanks again Patrick I appreciate your patience with me.

**Comment by kotflinte** [comment]
try adding the username  and cookie string  either as   "USER"  ,   "COOKIE"  or  without the "" brackets - 
without worked for me so 

username = abc
password = def
cookie = xxxxxxx_xyz

**Comment by intelstellar** [comment]
> try adding the username and cookie string either as "USER" , "COOKIE" or without the "" brackets - without worked for me so
> 
> username = abc password = def cookie = xxxxxxx_xyz

it doesn't work for me, but when i try removing the text after Mozilla/5.0 is "(Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36", then fill my username & cookie, it works again
