### ISSUE TITLE
There's no application executable file

### ISSUE THREAD

**Issue by vveaboo** [Nandaka/PixivUtil2#1292]
### Prerequisites

* [ yeah ] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [ yeah ] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [ yeah ] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

It seems that there is no application executable downloading the latest master version, so I can't really run the code using windows terminal. Is there a solution to that besides trying to run it using python?

**Comment by PatrickL546** [comment]
This is the newest release version with executable. 
[pixivutil202305.zip](https://github.com/Nandaka/PixivUtil2/releases/download/v20230105/pixivutil202305.zip)

You can find it in the release page, and find assets at the bottom, you'll find the executable zip file.

**Comment by Mac-Gyver14** [comment]
is there any way to get this to work on a pc with word?

**Comment by biggestsonicfan** [comment]
> is there any way to get this to work on a pc with word?

Like... Microsoft Word? I'm not sure what you mean here...

**Comment by Mac-Gyver14** [comment]
when I try to download and open the program it states that it doesn't work with windows 11

**Comment by PatrickL546** [comment]
@Mac-Gyver14 Did you try downloading this?

> This is the newest release version with executable. [pixivutil202305.zip](https://github.com/Nandaka/PixivUtil2/releases/download/v20230105/pixivutil202305.zip)
> 
> ![image](https://user-images.githubusercontent.com/75874561/266094307-2732170a-f53d-4ce2-b91f-6685f84af21e.png)
> 
> You can find it in the release page, and find assets at the bottom, you'll find the executable zip file. https://github.com/Nandaka/PixivUtil2/releases/releases/latest

**Comment by anon1593** [comment]
> when I try to download and open the program it states that it doesn't work with windows 11

Do you have Python installed?

**Comment by Nandaka** [comment]
also do you have another PC to test, it shouldn't require Python.
After extracting and running `PixivUtil2.exe` it will load console window and it will ask for username/password, but won't work due to login changes in pixiv and you need add the cookie values (see readme.txt)

**Comment by Mac-Gyver14** [comment]
I see thanks for all the feed back everyone.

**Comment by Mac-Gyver14** [comment]
got it to work, thanks everyone. y'll have ben a great help.

**Comment by Mac-Gyver14** [comment]
okay now I'm getting this message every time I try to get it to work: (************Press enter to exit) I'm not sure why it's not working if y'll could give me some feed back that would be great.

**Comment by PatrickL546** [comment]
> also do you have another PC to test, it shouldn't require Python. After extracting and running `PixivUtil2.exe` it will load console window and it will ask for username/password, but won't work due to login changes in pixiv and you need add the cookie values (see readme.txt)

Did you use cookie login as said above?

```
Q3. I cannot login to Pixiv!
    - Check your password.
    - Try to login to the Pixiv Website.
    - Try to use the config.ini on the [Authentication] section.
    - Check your date and time setting (e.g.: https://www.timeanddate.com/)
    - Disable Daylight Saving Time and try again.
    - Copy your session values from browser:
      1. Open Firefox.
      2. Go to Pixiv website and login, remember to enable [Remember Me]
          check box.
      3. Press F12 to open Developer Tools, and select the Storage tab.
      4. Click the Cookies and select for the pixiv.net.
      5. Look for Cookie named = PHPSESSID.
      6. Copy the content value. https://imgur.com/a/BppHOoQ
      7. Open config.ini, go to [Authentication] section, paste the value
         to cookie. https://imgur.com/VB2g3qn
```

**Comment by Mac-Gyver14** [comment]
ok so I did that and I came back with this long error code: (Any feed back on what I did wrong would be great)

Trying to log in with saved cookie
Error at doLogin(): (<class 'mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib.error.HTTPError instance) at 0x20f89256170 whose wrapped object = <HTTPError 403: 'Forbidden'>>, <traceback object at 0x0000020F8740FCC0>)
Traceback (most recent call last):
  File "PixivUtil2.py", line 1524, in doLogin
  File "PixivBrowserFactory.py", line 347, in loginUsingCookie
  File "PixivBrowserFactory.py", line 207, in open_with_retry
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 403: Forbidden

Cannot Login!

**Comment by PatrickL546** [comment]
Go to config.ini, open with notepad. At the top change UserAgent to `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0` If it doesn't work try `Mozilla/5.0`

**Comment by Mac-Gyver14** [comment]
thank you so much PatrickL546 with your help I finely got it to work. thanks so much and God Bless. 🙏🙏🙏
