### ISSUE TITLE
Error 301

### ISSUE THREAD

**Issue by dioporcos** [Nandaka/PixivUtil2#1303]
Since yesterday, when i try to open pixivutil 2 i get this error, tried updating my cookies but nothing changes

Error at doLogin(): (<class 'mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib.error.HTTPError instance) at 0x1bedc78dbd0 whose wrapped object = <HTTPError 301: 'The HTTP server returned a redirect error that would lead to an infinite loop.\nThe last 30x error message was:\nMoved Permanently'>>, <traceback object at 0x000001BEDB0EDFC0>)
Traceback (most recent call last):
  File "PixivUtil2.py", line 1524, in doLogin
  File "PixivBrowserFactory.py", line 347, in loginUsingCookie
    """  Log in to Pixiv using saved cookie, return True if success """
  File "PixivBrowserFactory.py", line 207, in open_with_retry
    except urllib.error.HTTPError:
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 301: The HTTP server returned a redirect error that would lead to an infinite loop.
The last 30x error message was:
Moved Permanently

Cannot Login!

**Comment by Snkea** [comment]
Trying to log in with saved cookie
Error at doLogin(): (<class 'mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib.error.HTTPError instance) at 0x2533d066050 whose wrapped object = <HTTPError 301: 'The HTTP server returned a redirect error that would lead to an infinite loop.\nThe last 30x error message was:\nMoved Permanently'>>, <traceback object at 0x000002533B8BD680>)
Traceback (most recent call last):
  File "PixivUtil2.py", line 1524, in doLogin
  File "PixivBrowserFactory.py", line 347, in loginUsingCookie
  File "PixivBrowserFactory.py", line 207, in open_with_retry
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 301: The HTTP server returned a redirect error that would lead to an infinite loop.
The last 30x error message was:
Moved Permanently

Cannot Login! same error here, its seem to happen right after whatever was going on with pixiv, alot of stuff is all fuck up and not working like it used to

**Comment by Butterfly-Dragon** [comment]
same here!

**Comment by Litoba** [comment]
same here...!

**Comment by mocukie** [comment]
change pixiv account language to english, then update cookies

**Comment by baraghiffari** [comment]
It happens to me, but just by changing my cookie to a new one fix it

**Comment by baraghiffari** [comment]
Nevermind, for whatever reason it stopped working again even after i relog my account or by try changing my language

**Comment by Butterfly-Dragon** [comment]
any news?

**Comment by hamc09** [comment]
If logging out and logging back in for new cookies doesn't fix this, see [here](https://github.com/Nandaka/PixivUtil2/issues/1302#issuecomment-1872959903).

**Comment by Romangelo** [comment]
Tried everything. Still not working.
