### ISSUE TITLE
[Fanbox] f1 f2 getting post id api error

### ISSUE THREAD

**Issue by aksskl** [Nandaka/PixivUtil2#1361]
Started getting an error today when using f1 and f2. Tried using the latest master and windows executable and both can't get post ids for fanbox accounts.

`Unknown Error, please check the log file: (<class 'TypeError'>, TypeError('list indices must be integers or slices, not str'), <traceback object at 0x0000022DA217B0C0>)`

f3 works, downloading using fanbox post id works. Pixiv downloads seem fine too, after a quick test.

The error seems to happen when getting the post ids for fanbox accounts.

**Comment by emerladCoder** [comment]
Yeah, the next page is no longer returned by the `post.listCreator` api call. Instead that just returns a List of posts.

To get the paging it will be necessary to call `post.paginateCreator` first which will return a list of all page URLs. Then we can increment through those page URLs as the next page instead.

I have a fix applied in my local files (PixivModelFanbox.py and PixivBrowserFactory.py). If someone wants to reference those and make an update. I'm at work atm, don't have time to do a full pull request etc.
[PixivUtil.zip](https://github.com/user-attachments/files/16531982/PixivUtil.zip)

**Comment by LordBarsdale** [comment]
Where do those files go?

**Comment by emerladCoder** [comment]
> Where do those files go?

These are source files, you would need to download the source files, replace/update the two provided files, then run from source using Python as mentioned in the main readme. 

Running from source code:
- Python 3.8.0+ (https://www.python.org/)
- Additional library listed in requirements.txt
- IDE Environment: see https://github.com/Nandaka/PixivUtil2/wiki/IDE-Enviroment-(Windows)

You have to have python installed, install the requirements.txt using PIP and then run the python file `PixivUtil2.py` instead of using the executable version from the releases.

**Comment by vampiricwulf** [comment]
@emerladCoder Combining that with https://github.com/Nandaka/PixivUtil2/issues/1352#issuecomment-2227002669 fixes the current fanbox issues. Thanks!

**Comment by Butterfly-Dragon** [comment]
hmmmm....  @emerladCoder nope, that did not fix it for me even combining it with the changes mentioned by vampiricwulf. What am i doing wrong? Or are you still having these problems too?

**Comment by TheDoc69** [comment]
I still got an error in my case 
`2024-08-09 19:09:02,513 - PixivUtil20240703 - ERROR - Unknown Error: object of type 'int' has no len()
Traceback (most recent call last):
  File "d:\python__\PixivUtil2.py", line 1745, in main
    np_is_valid, op_is_valid, selection = main_loop(ewd, op_is_valid, selection, np_is_valid, args, options)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python__\PixivUtil2.py", line 1467, in main_loop
    menu_fanbox_download_from_list(op_is_valid, PixivModelFanbox.FanboxArtist.SUPPORTING, args, options)
  File "d:\python__\PixivUtil2.py", line 945, in menu_fanbox_download_from_list
    PixivFanboxHandler.process_fanbox_artist_by_id(sys.modules[__name__],
  File "d:\python__\PixivFanboxHandler.py", line 50, in process_fanbox_artist_by_id
    posts = br.fanboxGetPostsFromArtist(artist, next_url)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python__\PixivBrowserFactory.py", line 1048, in fanboxGetPostsFromArtist
    posts = artist.parsePosts(response)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python__\PixivModelFanbox.py", line 599, in parsePosts
    if self.PageIndex < len(self.Pages):
                        ^^^^^^^^^^^^^^^
TypeError: object of type 'int' has no len()`

Modifying line 526 of PixivModelFanbox.py provided by emeraldCoder removed this error  
I changed "Pages = None"  to "Pages = [0]"
I don't know if it has any other consequence (maybe not getting all posts), but I managed to download all the posts from 2 weeks ago (my last update) with no error using f1 and f2.

**Comment by LordBarsdale** [comment]
Anyone want to explain how to do this for us stupids?

**Comment by Butterfly-Dragon** [comment]
> Anyone want to explain how to do this for us stupids?

https://github.com/user-attachments/files/16531982/PixivUtil.zip

https://github.com/Nandaka/PixivUtil2/issues/1361#issuecomment-2275990761

https://github.com/emerladCoder explained it but i still can't get it to work

**Comment by vartiens** [comment]
@emerladCoder Thanks for the fix. Works swiftly for me - I used pixiv.net (Korean) to login so didn't have any issues there.

**Comment by lazylazfo** [comment]
I still haven't solved this problem... A graduate of humanities college, I just pray for a new version to come out every day😭😭

**Comment by lazylazfo** [comment]
I finally succeeded in solving this problem!! Thank you!!

**Comment by aksskl** [comment]
The fix works, but while I was testing there seems to be an issue with fanbox accounts that have zero posts.

`IndexError('list index out of range'`

**Comment by dazzlekor** [comment]
> 마침내 이 문제를 해결하는 데 성공했습니다!! 감사합니다!!

I still haven't solved this problem. How did you solve it?

**Comment by lazylazfo** [comment]
> I still haven't solved this problem. How did you solve it?

https://github.com/Nandaka/PixivUtil2
Download master code by zip file. 
After that, remove the test folder.
And convert [PixivUtil2.py]file as a exe file. (You have to use Python)

**Comment by dazzlekor** [comment]
> > 저는 아직 이 문제를 해결하지 못했습니다. 어떻게 처리하셨나요?
> 
> https://github.com/Nandaka/PixivUtil2 zip 파일로 마스터 코드를 다운로드합니다. 다음 테스트 폴더를 제거합니다. 그리고 [PixivUtil2.py] 파일을 exe 파일로 변환합니다. (Python을 보내드립니다)

This converted executable will be terminated immediately. "cmd: pip installer PixivUtil2.py"

**Comment by DisasterInbound** [comment]
Anyone knows how to fix [this error](https://github.com/Nandaka/PixivUtil2/issues/1361#issuecomment-2302958558)?

**Comment by aksskl** [comment]
@DisasterInbound Change pixiv's website language to Japanese.

**Comment by beta52ojy** [comment]
I'm still not getting it to work, am I doing something wrong?
→ Installed pyinstaller,
→ Download master code by zip file. After that, remove the test folder.
→ Type "pyinstalle PixivUtil2.py" in the address bar of Windows Explorer
→ Exe file is created but does nothing.


> > I still haven't solved this problem. How did you solve it?
> 
> https://github.com/Nandaka/PixivUtil2 Download master code by zip file. After that, remove the test folder. And convert [PixivUtil2.py]file as a exe file. (You have to use Python)

**Comment by LordBarsdale** [comment]
When will these fixes be added to the main exe?

**Comment by esserius** [comment]
Any chance this will get added to an update?

**Comment by icedstick** [comment]
I will donate $15 to @Nandaka if all of these fixes are applied to the main PixivUtil2.exe before the end of this month! Hope that provides a little encouragement 😭

**Comment by LockNear** [comment]
Can someone just upload there compiled master.exe ? I compiled exe's multiple times and they all kept closing immediately when I start them.

**Comment by TheSonic03** [comment]
> I'm still not getting it to work, am I doing something wrong? → Installed pyinstaller, → Download master code by zip file. After that, remove the test folder. → Type "pyinstalle PixivUtil2.py" in the address bar of Windows Explorer → Exe file is created but does nothing.
> 
> > > I still haven't solved this problem. How did you solve it?
> > 
> > 
> > https://github.com/Nandaka/PixivUtil2 Download master code by zip file. After that, remove the test folder. And convert [PixivUtil2.py]file as a exe file. (You have to use Python)

The command is "pyinstaller PixivUtil2.py", you missed the "r"

**Comment by LordBarsdale** [comment]
Can anyone just upload the fixed complied files/folders/program to a mega or google drive folder?
