### ISSUE TITLE
f2. Download by artist/creator id (FANBOX) doesnt´t Work

### ISSUE THREAD

**Issue by gnarf1975** [Nandaka/PixivUtil2#1371]
f2. Download by artist/creator id (FANBOX) doesnt´t Work

I get this Error:

Unknown Error, please check the log file: (<class 'TypeError'>, TypeError('list indices must be integers or slices, not str'), <traceback object at 0x000002F49C8A33C0>)

**Comment by AvocadoFlour** [comment]
> pip install --upgrade --force-reinstall -r requirements.txt

Did this, it has changed nothing; Still getting 
```
Getting posts from https://api.fanbox.cc/post.listCreator?creatorId=maud0210&limit=10
Traceback (most recent call last):
  File "PixivUtil2.py", line 1745, in main
  File "PixivUtil2.py", line 1469, in main_loop
  File "PixivUtil2.py", line 1001, in menu_fanbox_download_by_id
  File "PixivFanboxHandler.py", line 50, in process_fanbox_artist_by_id
  File "PixivBrowserFactory.py", line 1048, in fanboxGetPostsFromArtist
  File "PixivModelFanbox.py", line 575, in parsePosts
TypeError: list indices must be integers or slices, not str
Unknown Error, please check the log file: (<class 'TypeError'>, TypeError('list indices must be integers or slices, not str'), <traceback object at 0x0000022340608500>)
press enter to exit.
```

![image](https://github.com/user-attachments/assets/5ff622d1-e677-4dbc-8e38-1fb933b8cdff)

**Comment by biggestsonicfan** [comment]
@AvocadoFlour Attach a log?
