### ISSUE TITLE
Several Errors Related to Fanbox

### ISSUE THREAD

**Issue by BookReader101** [Nandaka/PixivUtil2#1380]
### Prerequisites

* [Yes] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [Yes] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [Yes] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Cannot download from Fanbox. Basically followed all the steps to update my cookies, updated to the latest version, used firefox to grab the cloudflare cookies, and after several errors I got the program functional, but the fanbox does not work for the old version or the latest release. Not sure about running from the source code, I probably didn't do it right but it produces a similar yet different error related to cookies or something. 
Downloading individual posts actually works on the latest release version, but the other options result in the error.

### Steps to Reproduce

1. Get fresh cookies.
2. Run PixivUtil2.exe/.py
3. Do operation f1, f2, f4, f5, f6

**Expected behavior:** For the downloads to happen.

**Actual behavior:** Multiple error messages.
(LATEST RELEASE ERROR AFTER INPUT F1)
- Traceback (most recent call last):
  File "PixivUtil2.py", line 1745, in main
  File "PixivUtil2.py", line 1467, in main_loop
  File "PixivUtil2.py", line 945, in menu_fanbox_download_from_list
  File "PixivFanboxHandler.py", line 50, in process_fanbox_artist_by_id
  File "PixivBrowserFactory.py", line 1048, in fanboxGetPostsFromArtist
  File "PixivModelFanbox.py", line 575, in parsePosts
TypeError: list indices must be integers or slices, not str
Unknown Error, please check the log file: (<class 'TypeError'>, TypeError('list indices must be integers or slices, not str'), <traceback object at 0x0000020E89E74D40>)

(OLD VERSION ERROR AFTER INPUT F1)
- Input: f1
End Page (default is 0) =
Trying to log in FANBOX with saved cookie
Not logged in to FANBOX, trying to update FANBOX cookie...
Traceback (most recent call last):
  File "PixivUtil2.py", line 1462, in main
  File "PixivUtil2.py", line 1189, in main_loop
  File "PixivUtil2.py", line 786, in menu_fanbox_download_from_list
  File "PixivBrowserFactory.pyc", line 884, in fanboxGetArtistList
  File "PixivBrowserFactory.pyc", line 396, in fanbox_is_logged_in
  File "PixivBrowserFactory.pyc", line 389, in fanboxLoginUsingCookie
  File "PixivBrowserFactory.pyc", line 414, in updateFanboxCookie
Exception: Could not get pixivAccount.postKey while trying to log into fanbox.cc with given pixiv.net cookie
Unknown Error, please check the log file: (<class 'Exception'>, Exception('Could not get pixivAccount.postKey while trying to log into fanbox.cc with given pixiv.net cookie'), <traceback object at 0x04945E88>)

(LATEST MASTER ERROR ON STARTUP)
- Username login is broken, use Cookies to log in.
See Q3. at https://github.com/Nandaka/PixivUtil2?tab=readme-ov-file#a-usage
Trying to log in with saved cookie
Error at doLogin(): (<class 'mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib.error.HTTPError instance) at 0x1773e11d130 whose wrapped object = <HTTPError 403: 'Forbidden'>>, <traceback object at 0x000001773E13ABC0>)
Traceback (most recent call last):
  File "C:\Logs\Auxillary Logs\APPLE\Backup\PROD\PixivUtil2-master\PixivUtil2-master\PixivUtil2.py", line 1558, in doLogin
    result = __br__.loginUsingCookie()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Logs\Auxillary Logs\APPLE\Backup\PROD\PixivUtil2-master\PixivUtil2-master\PixivBrowserFactory.py", line 352, in loginUsingCookie
    res = self.open_with_retry('https://www.pixiv.net')  # + self._locale)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Logs\Auxillary Logs\APPLE\Backup\PROD\PixivUtil2-master\PixivUtil2-master\PixivBrowserFactory.py", line 208, in open_with_retry
    res = self.open(url, data, timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pinkc\AppData\Local\Programs\Python\Python312\Lib\site-packages\mechanize\_mechanize.py", line 257, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pinkc\AppData\Local\Programs\Python\Python312\Lib\site-packages\mechanize\_mechanize.py", line 313, in _mech_open
    raise response
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 403: Forbidden

Cannot Login!

**Log file:** 
[pixivutil.log](https://github.com/user-attachments/files/17320986/pixivutil.log) (latest release)
[pixivutil.log](https://github.com/user-attachments/files/17320998/pixivutil.log) (old version 20211104)
[pixivutil.log](https://github.com/user-attachments/files/17321003/pixivutil.log) (latest master)

### Versions
latest release version 20240703
original version 20211104
latest master version 20240703

**Comment by Darkrider000** [comment]
same issue

**Comment by N-SPC700** [comment]
Having the same issue with Fanbox as well.

**Comment by biggestsonicfan** [comment]
Everyone try upgrading your pip requirements: `pip install --upgrade --force-reinstall -r requirements.txt`

I was just able to download Fanbox using version 20240703.

**Comment by esserius** [comment]
I tried that @biggestsonicfan it did not work and produced the same error as above.

**Comment by biggestsonicfan** [comment]
@esserius Can you attach a log?

**Comment by esserius** [comment]
[pixivutil.log](https://github.com/user-attachments/files/17940901/pixivutil.log)
Attached

**Comment by biggestsonicfan** [comment]
@esserius Your log seems to indicate you can't log into pixiv, not fanbox. Have you updated your pixiv cookies?

**Comment by esserius** [comment]
The executable version of the master works in Windows, I can login without issue. However, f1 and f2 are broken

**Comment by biggestsonicfan** [comment]
Of course the executable version won't work, it doesn't have the updated dependencies. The log you uploaded shows it was run as a script.

**Comment by esserius** [comment]
Given that it's working for you I wonder if there's something about Windows-based python that's borking it.

**Comment by HamsterExAstris** [comment]
I'm experiencing the on-startup issue laid out above with both the Windows EXE and with Python 3.10 in WSL, both using version 20240703.
