### ISSUE TITLE
daylastupdated error

### ISSUE THREAD

**Issue by Unknown7001** [Nandaka/PixivUtil2#1381]
When i set daylastupdated = 0

I get this error:

"
Processing from database.
Error at selectAllMember(): (<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'strip'"), <traceback object at 0x0000019985599E80>)
failed
Error at process_list(): (<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'strip'"), <traceback object at 0x0000019985599F80>)
Failed
Traceback (most recent call last):
  File "PixivUtil2.py", line 1745, in main
  File "PixivUtil2.py", line 1414, in main_loop
  File "PixivUtil2.py", line 498, in menu_download_from_list
  File "PixivListHandler.py", line 22, in process_list
  File "PixivDBManager.py", line 469, in selectAllMember
  File "PixivListItem.py", line 19, in __init__
AttributeError: 'NoneType' object has no attribute 'strip'
Unknown Error, please check the log file: (<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'strip'"), <traceback object at 0x000001998559A080>)
press enter to exit.
"

Thank you

**Comment by Unknown7001** [comment]
> What are you hoping to accomplish by setting `daylastupdated ` to `0`?

I want to be able to update all the pixiv members to the latest post at any time.

**Comment by biggestsonicfan** [comment]
It looks like the error is hitting here:
https://github.com/Nandaka/PixivUtil2/blob/d2e774d61d2b6b29f08a47233afe52dd18373576/PixivListItem.py#L19

Is your dbPath set correctly?

**Comment by Unknown7001** [comment]
I didnt set anything for dbPath. Its still the default setting

`dbPath = `

**Comment by biggestsonicfan** [comment]
`daylastupdated` is not when the Pixiv artist last updated, but when you last attempted to downloaded from the artist. To do this, it checks the database to see when you last downloaded an image from that person. Without a database, you can not use `daylastupdated`.
