### ISSUE TITLE
getaddrinfo failed

### ISSUE THREAD

**Issue by whinette** [Nandaka/PixivUtil2#151]
Hello,

I have problems since the new release:

`Source URL: http://www.pixiv.net/bookmark.php?type=user&p=10
Error at process_bookmark(): (<class 'urllib2.URLError'>, URLError(gaierror(11002, 'getaddrinfo failed'),), <traceback object at 0x041BB170>)
Traceback (most recent call last):
  File "PixivUtil2.py", line 1875, in main
  File "PixivUtil2.py", line 1664, in main_loop
  File "PixivUtil2.py", line 1467, in menu_download_from_online_user_bookmark
  File "PixivUtil2.py", line 1036, in process_bookmark
  File "PixivUtil2.py", line 1019, in get_bookmarks
  File "mechanize\_mechanize.pyc", line 203, in open
  File "mechanize\_mechanize.pyc", line 230, in _mech_open
  File "mechanize\_opener.pyc", line 193, in open
  File "mechanize\_urllib2_fork.pyc", line 344, in _open
  File "mechanize\_urllib2_fork.pyc", line 332, in _call_chain
  File "mechanize\_urllib2_fork.pyc", line 1142, in http_open
  File "mechanize\_urllib2_fork.pyc", line 1118, in do_open
URLError: <urlopen error [Errno 11002] getaddrinfo failed>
press enter to exit.`

Also when launched from command line through crontab

`2016-10-04 02:08:38,894 - PixivUtil20160927 - ERROR - Error at process_new_illust_from_bookmark(): (<class 'urllib2.URLError'>, URLError(gaierror(11002, 'getaddrinfo failed'),), <traceback object at 0x0D523BC0>)
Traceback (most recent call last):
  File "PixivUtil2.py", line 1083, in process_new_illust_from_bookmark
  File "mechanize\_mechanize.pyc", line 203, in open
  File "mechanize\_mechanize.pyc", line 230, in _mech_open
  File "mechanize\_opener.pyc", line 193, in open
  File "mechanize\_urllib2_fork.pyc", line 344, in _open
  File "mechanize\_urllib2_fork.pyc", line 332, in _call_chain
  File "mechanize\_urllib2_fork.pyc", line 1142, in http_open
  File "mechanize\_urllib2_fork.pyc", line 1118, in do_open
URLError: <urlopen error [Errno 11002] getaddrinfo failed>
2016-10-04 02:08:38,894 - PixivUtil20160927 - ERROR - Unknown Error: <urlopen error [Errno 11002] getaddrinfo failed>
Traceback (most recent call last):
  File "PixivUtil2.py", line 1875, in main
  File "PixivUtil2.py", line 1670, in main_loop
  File "PixivUtil2.py", line 1537, in menu_download_new_illust_from_bookmark
  File "PixivUtil2.py", line 1083, in process_new_illust_from_bookmark
  File "mechanize\_mechanize.pyc", line 203, in open
  File "mechanize\_mechanize.pyc", line 230, in _mech_open
  File "mechanize\_opener.pyc", line 193, in open
  File "mechanize\_urllib2_fork.pyc", line 344, in _open
  File "mechanize\_urllib2_fork.pyc", line 332, in _call_chain
  File "mechanize\_urllib2_fork.pyc", line 1142, in http_open
  File "mechanize\_urllib2_fork.pyc", line 1118, in do_open
URLError: <urlopen error [Errno 11002] getaddrinfo failed>
2016-10-04 02:08:38,921 - PixivUtil20160927 - INFO - EXIT: -1`

**Comment by Nandaka** [comment]
> getaddrinfo failed

this is network error, check your dns/internet connection/proxy settings in config.ini.

**Comment by whinette** [comment]
I had problems with my isp...
