### ISSUE TITLE
Crash if no images are found for user

### ISSUE THREAD

**Issue by whinette** [Nandaka/PixivUtil2#155]
```
Traceback (most recent call last):
  File "PixivUtil2.py", line 470, in process_member
UnboundLocalError: local variable 'image_id' referenced before assignment
Error at process_member(): (<type 'exceptions.UnboundLocalError'>, UnboundLocalError("local variable 'image_id' referenced before assignment",), <traceback object at 0x03FC6850>)
Dumping html to: Error page for member 3071610.html
Error at process_bookmark(): (<type 'exceptions.UnboundLocalError'>, UnboundLocalError("local variable 'image_id' referenced before assignment",), <traceback object at 0x03FB3D28>)
Traceback (most recent call last):
  File "PixivUtil2.py", line 1875, in main
  File "PixivUtil2.py", line 1664, in main_loop
  File "PixivUtil2.py", line 1467, in menu_download_from_online_user_bookmark
  File "PixivUtil2.py", line 1042, in process_bookmark
  File "PixivUtil2.py", line 470, in process_member
UnboundLocalError: local variable 'image_id' referenced before assignment
press enter to exit.
```

**Comment by Nandaka** [comment]
looks like dupes with #152

**Comment by whinette** [comment]
Looks like it indeed.

**Comment by Nandaka** [comment]
should be fixed in https://github.com/Nandaka/PixivUtil2/releases/tag/v20161012

**Comment by whinette** [comment]
It is. Enjoy a little donation!
