### ISSUE TITLE
Create GIF error

### ISSUE THREAD

**Issue by vampiricwulf** [Nandaka/PixivUtil2#162]
```
2016-10-26 07:37:49,651 - PixivUtil20161012 - INFO - Image id mode.
2016-10-26 07:37:52,980 - PixivUtil20161012 - DEBUG - Sanitized Filename: /cygdrive/e/4chi/鮎/59634275 - Timeless.zip
2016-10-26 07:37:52,980 - PixivUtil20161012 - INFO - Using Referer: http://www.pixiv.net/member_illust.php?mode=medium&illust_id=59634275
2016-10-26 07:37:53,256 - PixivUtil20161012 - INFO - Using Referer: http://www.pixiv.net/member_illust.php?mode=medium&illust_id=59634275
2016-10-26 07:37:57,640 - PixivUtil20161012 - INFO -  done.
2016-10-26 07:37:57,640 - PixivUtil20161012 - INFO - Creating ugoira archive => /cygdrive/e/4chi/鮎/59634275 - Timeless.ugoira
2016-10-26 07:37:57,650 - PixivUtil20161012 - INFO - Deleting zip file => /cygdrive/e/4chi/鮎/59634275 - Timeless.zip
2016-10-26 07:37:57,651 - PixivUtil20161012 - INFO - processing ugoira...
2016-10-26 07:37:57,784 - PixivUtil20161012 - ERROR - Error at process_image(): (<type 'exceptions.ValueError'>, ValueError("Could not find a format to read the specified file in mode 'i'",), <traceback object at 0x6fffca06878>)
2016-10-26 07:37:57,784 - PixivUtil20161012 - ERROR - Error at process_image(): 59634275
Traceback (most recent call last):
  File "/cygdrive/c/PixivUtil2/PixivUtil2.py", line 692, in process_image
    PixivHelper.ugoira2gif(ugo_name, gif_filename)
  File "/cygdrive/c/PixivUtil2/PixivHelper.py", line 655, in ugoira2gif
    images.append(imageio.imread(temp_folder + "/" + info["file"]))
  File "/usr/lib/python2.7/site-packages/imageio/core/functions.py", line 185, in imread
    reader = read(uri, format, 'i', **kwargs)
  File "/usr/lib/python2.7/site-packages/imageio/core/functions.py", line 108, in get_reader
    'in mode %r' % mode)
ValueError: Could not find a format to read the specified file in mode 'i'
2016-10-26 07:37:57,784 - PixivUtil20161012 - DEBUG - Sanitized Filename: Error medium page for image 59634275.html
2016-10-26 07:37:58,010 - PixivUtil20161012 - ERROR - Dumping html to: Error medium page for image 59634275.html
2016-10-26 07:37:58,012 - PixivUtil20161012 - ERROR - Unknown Error: Could not find a format to read the specified file in mode 'i'
Traceback (most recent call last):
  File "/cygdrive/c/PixivUtil2/PixivUtil2.py", line 1879, in main
    np_is_valid, op_is_valid, selection = main_loop(ewd, mode, op_is_valid, selection, np_is_valid, args)
  File "/cygdrive/c/PixivUtil2/PixivUtil2.py", line 1662, in main_loop
    menu_download_by_image_id(mode, op_is_valid, args)
  File "/cygdrive/c/PixivUtil2/PixivUtil2.py", line 1358, in menu_download_by_image_id
    process_image(mode, None, int(image_id))
  File "/cygdrive/c/PixivUtil2/PixivUtil2.py", line 692, in process_image
    PixivHelper.ugoira2gif(ugo_name, gif_filename)
  File "/cygdrive/c/PixivUtil2/PixivHelper.py", line 655, in ugoira2gif
    images.append(imageio.imread(temp_folder + "/" + info["file"]))
  File "/usr/lib/python2.7/site-packages/imageio/core/functions.py", line 185, in imread
    reader = read(uri, format, 'i', **kwargs)
  File "/usr/lib/python2.7/site-packages/imageio/core/functions.py", line 108, in get_reader
    'in mode %r' % mode)
ValueError: Could not find a format to read the specified file in mode 'i'
```

**Comment by Nandaka** [comment]
```/cygdrive/e/4chi/```

Are you using Cygwin? I think it is not supported by the image library.

It is ok on my Windows PC + running the script directly.
![image](https://cloud.githubusercontent.com/assets/836867/19733662/3d723524-9bd7-11e6-8790-88dc32f107e4.png)

**Comment by vampiricwulf** [comment]
Yes, I'm using cygwin. I guess I should take the time to set up shortcuts with regular cmd 😞 .

**Comment by vampiricwulf** [comment]
I wish there was an easy convert between bash and batch scripts.
