### ISSUE TITLE
AttributeError: 'method_descriptor' object has no attribute 'today'

### ISSUE THREAD

**Issue by NHOrus** [Nandaka/PixivUtil2#165]
```
Checking local filename... 
Traceback (most recent call last):
  File "PixivUtil2.py", line 687, in process_image
    PixivHelper.writeUrlInDescription(image, __config__.urlBlacklistRegex, __config__.urlDumpFilename)
  File "/home/nho/workshop/PixivUtil2/PixivHelper.py", line 636, in writeUrlInDescription
    filename = datetime.date.today().strftime(filenamePattern) + ".txt"
AttributeError: 'method_descriptor' object has no attribute 'today'
Error at process_image(): (<type 'exceptions.AttributeError'>, AttributeError("'method_descriptor' object has no attribute 'today'",), <traceback object at 0x7f1b359afa28>) 
Dumping html to: Error medium page for image 59621214.html 
Stuff happened, trying again after 2 second ( 2 )
Traceback (most recent call last):
  File "PixivUtil2.py", line 403, in process_member
    result = process_image(mode, artist, image_id, user_dir, bookmark, title_prefix=title_prefix)  # Yavos added dir-argument to pass
  File "PixivUtil2.py", line 687, in process_image
    PixivHelper.writeUrlInDescription(image, __config__.urlBlacklistRegex, __config__.urlDumpFilename)
  File "/home/nho/workshop/PixivUtil2/PixivHelper.py", line 636, in writeUrlInDescription
    filename = datetime.date.today().strftime(filenamePattern) + ".txt"
AttributeError: 'method_descriptor' object has no attribute 'today
'```

It's normal UI.

**Comment by Nandaka** [comment]
try the latest commit.

**Comment by NHOrus** [comment]
It appears to be working.
