### ISSUE TITLE
Can't download pictures anymore (9000 with log file)

### ISSUE THREAD

**Issue by maxjame5432** [Nandaka/PixivUtil2#185]
I don't know why I can't download any image. error log below.

Thank you for help

```
2017-01-03 15:03:34,223 - PixivUtil20161205 - INFO - Using Referer: http://www.pixiv.net/member_illust.php?mode=medium&illust_id=59509791
2017-01-03 15:03:51,209 - PixivUtil20161205 - ERROR - Error at download_image(): (<class 'httplib.BadStatusLine'>, BadStatusLine("''",), <traceback object at 0x04132260>) at http://i4.pixiv.net/img-original/img/2016/10/17/03/30/11/59509791_p0.jpg (9000)
2017-01-03 15:03:51,209 - PixivUtil20161205 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 84, in download_image
  File "mechanize\_mechanize.pyc", line 199, in open_novisit
  File "mechanize\_mechanize.pyc", line 230, in _mech_open
  File "mechanize\_opener.pyc", line 193, in open
  File "mechanize\_urllib2_fork.pyc", line 344, in _open
  File "mechanize\_urllib2_fork.pyc", line 332, in _call_chain
  File "mechanize\_urllib2_fork.pyc", line 1142, in http_open
  File "mechanize\_urllib2_fork.pyc", line 1116, in do_open
  File "httplib.pyc", line 1074, in getresponse
  File "httplib.pyc", line 415, in begin
  File "httplib.pyc", line 379, in _read_status
BadStatusLine: ''

2017-01-03 15:03:55,220 - PixivUtil20161205 - INFO - Using Referer: http://www.pixiv.net/member_illust.php?mode=medium&illust_id=59509791
2017-01-03 15:04:07,421 - PixivUtil20161205 - ERROR - Error at download_image(): (<class 'httplib.BadStatusLine'>, BadStatusLine("''",), <traceback object at 0x04132620>) at http://i4.pixiv.net/img-original/img/2016/10/17/03/30/11/59509791_p0.jpg (9000)
2017-01-03 15:04:07,423 - PixivUtil20161205 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 84, in download_image
  File "mechanize\_mechanize.pyc", line 199, in open_novisit
  File "mechanize\_mechanize.pyc", line 230, in _mech_open
  File "mechanize\_opener.pyc", line 193, in open
  File "mechanize\_urllib2_fork.pyc", line 344, in _open
  File "mechanize\_urllib2_fork.pyc", line 332, in _call_chain
  File "mechanize\_urllib2_fork.pyc", line 1142, in http_open
  File "mechanize\_urllib2_fork.pyc", line 1116, in do_open
  File "httplib.pyc", line 1074, in getresponse
  File "httplib.pyc", line 415, in begin
  File "httplib.pyc", line 379, in _read_status
BadStatusLine: ''

2017-01-03 15:04:11,423 - PixivUtil20161205 - INFO - Using Referer: http://www.pixiv.net/member_illust.php?mode=medium&illust_id=59509791
2017-01-03 15:04:23,479 - PixivUtil20161205 - ERROR - Error at download_image(): (<class 'httplib.BadStatusLine'>, BadStatusLine("''",), <traceback object at 0x041321C0>) at http://i4.pixiv.net/img-original/img/2016/10/17/03/30/11/59509791_p0.jpg (9000)
2017-01-03 15:04:23,479 - PixivUtil20161205 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 84, in download_image
  File "mechanize\_mechanize.pyc", line 199, in open_novisit
  File "mechanize\_mechanize.pyc", line 230, in _mech_open
  File "mechanize\_opener.pyc", line 193, in open
  File "mechanize\_urllib2_fork.pyc", line 344, in _open
  File "mechanize\_urllib2_fork.pyc", line 332, in _call_chain
  File "mechanize\_urllib2_fork.pyc", line 1142, in http_open
  File "mechanize\_urllib2_fork.pyc", line 1116, in do_open
  File "httplib.pyc", line 1074, in getresponse
  File "httplib.pyc", line 415, in begin
  File "httplib.pyc", line 379, in _read_status
BadStatusLine: ''

2017-01-03 15:04:23,480 - PixivUtil20161205 - ERROR - Error at process_image(): (<class 'httplib.BadStatusLine'>, BadStatusLine("''",), <traceback object at 0x04134A30>)
2017-01-03 15:04:23,480 - PixivUtil20161205 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 679, in process_image
  File "PixivUtil2.py", line 84, in download_image
  File "mechanize\_mechanize.pyc", line 199, in open_novisit
  File "mechanize\_mechanize.pyc", line 230, in _mech_open
  File "mechanize\_opener.pyc", line 193, in open
  File "mechanize\_urllib2_fork.pyc", line 344, in _open
  File "mechanize\_urllib2_fork.pyc", line 332, in _call_chain
  File "mechanize\_urllib2_fork.pyc", line 1142, in http_open
  File "mechanize\_urllib2_fork.pyc", line 1116, in do_open
  File "httplib.pyc", line 1074, in getresponse
  File "httplib.pyc", line 415, in begin
  File "httplib.pyc", line 379, in _read_status
BadStatusLine: ''

2017-01-03 15:04:23,480 - PixivUtil20161205 - ERROR - Error at process_image(): 59509791
Traceback (most recent call last):
  File "PixivUtil2.py", line 679, in process_image
  File "PixivUtil2.py", line 84, in download_image
  File "mechanize\_mechanize.pyc", line 199, in open_novisit
  File "mechanize\_mechanize.pyc", line 230, in _mech_open
  File "mechanize\_opener.pyc", line 193, in open
  File "mechanize\_urllib2_fork.pyc", line 344, in _open
  File "mechanize\_urllib2_fork.pyc", line 332, in _call_chain
  File "mechanize\_urllib2_fork.pyc", line 1142, in http_open
  File "mechanize\_urllib2_fork.pyc", line 1116, in do_open
  File "httplib.pyc", line 1074, in getresponse
  File "httplib.pyc", line 415, in begin
  File "httplib.pyc", line 379, in _read_status
BadStatusLine: ''
2017-01-03 15:04:23,482 - PixivUtil20161205 - DEBUG - Sanitized Filename: Error medium page for image 59509791.html
2017-01-03 15:04:23,492 - PixivUtil20161205 - ERROR - Dumping html to: Error medium page for image 59509791.html
2017-01-03 15:04:23,492 - PixivUtil20161205 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 679, in process_image
  File "PixivUtil2.py", line 84, in download_image
  File "mechanize\_mechanize.pyc", line 199, in open_novisit
  File "mechanize\_mechanize.pyc", line 230, in _mech_open
  File "mechanize\_opener.pyc", line 193, in open
  File "mechanize\_urllib2_fork.pyc", line 344, in _open
  File "mechanize\_urllib2_fork.pyc", line 332, in _call_chain
  File "mechanize\_urllib2_fork.pyc", line 1142, in http_open
  File "mechanize\_urllib2_fork.pyc", line 1116, in do_open
  File "httplib.pyc", line 1074, in getresponse
  File "httplib.pyc", line 415, in begin
  File "httplib.pyc", line 379, in _read_status
BadStatusLine: ''
```

**Comment by Nandaka** [comment]
```BadStatusLine: ''``` >> Network issue
