### ISSUE TITLE
Incomplete read when exporting bookmarks

### ISSUE THREAD

**Issue by whinette** [Nandaka/PixivUtil2#194]
It happens every times I export my bm with option 'e'. The page seems random. I have no others problems connecting to pixiv.net

Exporting page 22
Source URL: http://www.pixiv.net/bookmark.php?type=user&p=22
Error at export_bookmark(): (<class 'httplib.IncompleteRead'>, IncompleteRead(7021 bytes read, 1171 more expected), <traceback object at 0x04F82508>)
Traceback (most recent call last):
  File "PixivUtil2.py", line 1862, in main
  File "PixivUtil2.py", line 1667, in main_loop
  File "PixivUtil2.py", line 1558, in menu_export_online_bookmark
  File "PixivUtil2.py", line 1031, in export_bookmark
  File "PixivUtil2.py", line 994, in get_bookmarks
  File "mechanize\_mechanize.pyc", line 203, in open
  File "mechanize\_mechanize.pyc", line 249, in _mech_open
  File "mechanize\_mechanize.pyc", line 308, in _set_response
  File "mechanize\_html.pyc", line 629, in set_response
  File "mechanize\_response.pyc", line 190, in read
  File "socket.pyc", line 351, in read
  File "httplib.pyc", line 549, in read
  File "httplib.pyc", line 609, in _read_chunked
  File "httplib.pyc", line 666, in _safe_read
IncompleteRead: IncompleteRead(7021 bytes read, 1171 more expected)

**Comment by Nandaka** [comment]
not sure why, but it is the error returned from the http library, which mean got connection issue to the server.

If you are using firewall? If possible try to use different computer/isp?

**Comment by whinette** [comment]
With another ISP and another os on another day: it works.

Could you implement a retry on error or a graceful exit? A hiccup should not fails the whole process I think.
