### ISSUE TITLE
New versions dont work

### ISSUE THREAD

**Issue by fontanellee** [Nandaka/PixivUtil2#205]
New version of 20170220 dosnt work for me. Program`s window opens for a sec and closes. The same for all newish versions including pixivutil20161231.  I ddnt check all of them but Pixivutil20160807-beta1( and older versions) work fine. Log file for v.20170220 :
2017-02-21 15:38:12,384 - PixivUtil20170220 - INFO - ###############################################################
2017-02-21 15:38:12,384 - PixivUtil20170220 - INFO - Starting...
2017-02-21 15:38:12,421 - PixivUtil20170220 - ERROR - Error at loadConfig()
Traceback (most recent call last):
  File "PixivConfig.pyc", line 103, in loadConfig
  File "PixivHelper.pyc", line 303, in OpenTextFile
  File "codecs.pyc", line 884, in open
IOError: [Errno 2] No such file or directory: u'D:\\\u041d\u043e\u0432\u0430\u044f \u043f\u0430\u043f\u043a\u0430 (2)\\pixivutil20170220\\config.ini'
2017-02-21 15:38:12,426 - PixivUtil20170220 - INFO - Setting log level to: DEBUG
2017-02-21 15:38:12,426 - PixivUtil20170220 - INFO - No default cookie jar available, creating... 
2017-02-21 15:38:26,671 - PixivUtil20170220 - INFO - ###############################################################
2017-02-21 15:38:26,673 - PixivUtil20170220 - INFO - Starting...
2017-02-21 15:38:26,677 - PixivUtil20170220 - INFO - Setting log level to: DEBUG
2017-02-21 15:38:26,678 - PixivUtil20170220 - INFO - No default cookie jar available, creating... 
and so on.

**Comment by Nandaka** [comment]
can you save the app to a folder without special characters, e.g. ```c:\pixivutil\```

**Comment by fontanellee** [comment]
It works. Thank you.

**Comment by Nandaka** [comment]
it failed to open the config.ini when the apps is extracted to folder with special character.

Not sure why it detect the config path to
```u'D:\\u041d\u043e\u0432\u0430\u044f \u043f\u0430\u043f\u043a\u0430 (2)\pixivutil20170220\config.ini'``` ==> parsed to ```D:\u041dовая папка (2)\pixivutil20170220\config.ini``` where I think it should be in ```u'D:\\\u041d\u043e\u0432\u0430\u044f \u043f\u0430\u043f\u043a\u0430 (2)\pixivutil20170220\config.ini'``` (got extra \ after D:\) ==> parsed to ```D:\Новая папка (2)\pixivutil20170220\config.ini```
