### ISSUE TITLE
urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed

### ISSUE THREAD

**Issue by Aergernis** [Nandaka/PixivUtil2#215]
Hi,

i'm getting some SSL errors on some pictures, but i can open them in browser.

`Checking local filename... Getting remote filesize...
Using Referer: http://www.pixiv.net/member_illust.php?mode=medium&illust_id=56808088
[download_image()] URL Error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)> at https://i1.pixiv.net/img-original/img/2016/05/10/00/01/19/56808088_p4.jpg
Traceback (most recent call last):
  File "PixivUtil2.py", line 84, in download_image
  File "mechanize\_mechanize.pyc", line 199, in open_novisit
  File "mechanize\_mechanize.pyc", line 230, in _mech_open
  File "mechanize\_opener.pyc", line 193, in open
  File "mechanize\_urllib2_fork.pyc", line 344, in _open
  File "mechanize\_urllib2_fork.pyc", line 332, in _call_chain
  File "mechanize\_urllib2_fork.pyc", line 1170, in https_open
  File "mechanize\_urllib2_fork.pyc", line 1118, in do_open
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
Error at download_image(): (<class 'urllib2.URLError'>, URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),), <traceback object at 0x03785E18>) at https://i1.pixiv.net/img-original/img/2016/05/10/00/01/19/56808088_p4.jpg (9002)
Retrying [3]...
1 2 3 4`

**Comment by Nandaka** [comment]
Can you try it on different pc first?

Or perform full antivirus scanning on your PC, some malware might cause this. Refer to Issue #214

**Comment by StringDown** [comment]
Same issue, happened quite suddenly

**Comment by Nandaka** [comment]
@StringDown can you try on different pc/isp?
