### ISSUE TITLE
Fail to download new illust bookmar_new_illust.php

### ISSUE THREAD

**Issue by Saulofein** [Nandaka/PixivUtil2#221]
First thanks for your hard work,
then here is the issue:
fails to download new illust after downloading a few ones (2times tested and failed randomly after 5-10 download)

<<<<8. Download new illust from bookmarked members (...)
start page : default
end page : 41 (pages of the latest submission, manually checked on browser)>>>>

multiple errors shown in log but here is the last Message in log: 
****2017-04-11 12:15:16,516 - PixivUtil20170411 - ERROR - Unknown Error: ''
Traceback (most recent call last):
  File "PixivUtil2.py", line 1876, in main
  File "PixivUtil2.py", line 1671, in main_loop
  File "PixivUtil2.py", line 1538, in menu_download_new_illust_from_bookmark
  File "PixivUtil2.py", line 1081, in process_new_illust_from_bookmark
  File "PixivUtil2.py", line 682, in process_image
  File "PixivUtil2.py", line 161, in download_image
  File "mechanize\_mechanize.pyc", line 199, in open_novisit
  File "mechanize\_mechanize.pyc", line 230, in _mech_open
  File "mechanize\_opener.pyc", line 193, in open
  File "mechanize\_urllib2_fork.pyc", line 344, in _open
  File "mechanize\_urllib2_fork.pyc", line 332, in _call_chain
  File "mechanize\_urllib2_fork.pyc", line 1170, in https_open
  File "mechanize\_urllib2_fork.pyc", line 1116, in do_open
  File "httplib.pyc", line 1074, in getresponse
  File "httplib.pyc", line 415, in begin
  File "httplib.pyc", line 379, in _read_status
BadStatusLine: ''

****2017-04-11 12:49:09,882 - PixivUtil20170411 - ERROR - Error at process_new_illust_from_bookmark(): (<type 'exceptions.UnicodeDecodeError'>, UnicodeDecodeError('utf8', 'URLError: <urlopen error [Errno 10054] Une connexion existante a d\xfb \xeatre ferm\xe9e par l\x92h\xf4te distant>\n', 66, 67, 'invalid start byte'), <traceback object at 0x036CE7D8>)
Traceback (most recent call last):
  File "PixivUtil2.py", line 1081, in process_new_illust_from_bookmark
  File "PixivUtil2.py", line 682, in process_image
  File "PixivUtil2.py", line 239, in download_image
  File "traceback.pyc", line 128, in print_exception
  File "traceback.pyc", line 13, in _print
  File "win_unicode_console\streams.pyc", line 254, in write
  File "encodings\utf_8.pyc", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfb in position 66: invalid start byte
2017-04-11 12:49:09,884 - PixivUtil20170411 - ERROR - Unknown Error: 'utf8' codec can't decode byte 0xfb in position 66: invalid start byte
Traceback (most recent call last):
  File "PixivUtil2.py", line 1876, in main
  File "PixivUtil2.py", line 1671, in main_loop
  File "PixivUtil2.py", line 1538, in menu_download_new_illust_from_bookmark
  File "PixivUtil2.py", line 1081, in process_new_illust_from_bookmark
  File "PixivUtil2.py", line 682, in process_image
  File "PixivUtil2.py", line 239, in download_image
  File "traceback.pyc", line 128, in print_exception
  File "traceback.pyc", line 13, in _print
  File "win_unicode_console\streams.pyc", line 254, in write
  File "encodings\utf_8.pyc", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfb in position 66: invalid start byte

**Comment by Nandaka** [comment]
> BadStatusLine: ''
> URLError

network issue, looks like the server return empty response.

> UnicodeDecodeError

failed to decode the error message from python `Une connexion existante a d\xfb \xeatre ferm\xe9e par l\x92h\xf4te distant`, looks like also network issue? Google translate said: An existing connection was forcibly closed by the remote host

check you network connection/try different isp?

**Comment by Saulofein** [comment]
Thank you very much for quick reply!!!


I tried a different thing : a reboot + full exclusion from avast and spybot + running it alone without µtorrent or any other download

It worked then on the second try successfully from page 1 to 42.


so ""problem solved"", thanks again!!!

________________________________
De : Nandaka <notifications@github.com>
Envoyé : mardi 11 avril 2017 14:24:37
À : Nandaka/PixivUtil2
Cc : Saulofein; Author
Objet : Re: [Nandaka/PixivUtil2] Fail to download new illust bookmar_new_illust.php (#221)


BadStatusLine: ''
URLError

network issue, looks like the server return empty response.

UnicodeDecodeError

failed to decode the error message from python Une connexion existante a d\xfb \xeatre ferm\xe9e par l\x92h\xf4te distant, looks like also network issue? Google translate said: An existing connection was forcibly closed by the remote host

check you network connection/try different isp?
