### ISSUE TITLE
Error when saving image info: [...]sketch-icon

### ISSUE THREAD

**Issue by whinette** [Nandaka/PixivUtil2#226]
Using last master from github.
https://www.pixiv.net/member_illust.php?mode=medium&illust_id=62755156

Full log:

2017-05-08 18:00:50,909 - PixivUtil20170411 - ERROR - Error when saving image info: /mnt/Pixiv/26173 bonten/几＠例大祭M05a/sketch-icon - [寄稿] 例大祭１４ 『可愛いカトゥーンの幻想郷』.txt, file is saved to: 62755156.txt
Traceback (most recent call last):
  File "/PixivUtil2/PixivModel.py", line 584, in WriteInfo
    info = codecs.open(filename, 'wb', encoding='utf-8')
  File "/usr/local/lib/python2.7/codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: u'/mnt/Pixiv/26173 bonten/\u51e0\uff20\u4f8b\u5927\u796dM05a/sketch-icon - [\u5bc4\u7a3f] \u4f8b\u5927\u796d\uff11\uff14 \u300e\u53ef\u611b\u3044\u30ab\u30c8\u30a5\u30fc\u30f3\u306e\u5e7b\u60f3\u90f7\u300f.txt'
2017-05-08 18:00:51,133 - PixivUtil20170411 - INFO - Source URL: http://www.pixiv.net/bookmark_new_illust.php?p=92
2017-05-08 18:01:02,276 - PixivUtil20170411 - ERROR - Error when saving image info: /mnt/Pixiv/26173 bonten/几＠例大祭M05a/R-18/sketch-icon - [寄稿] 例大祭１４ 『オカイモノガタリ』.txt, file is saved to: 62754736.txt
Traceback (most recent call last):
  File "/PixivUtil2/PixivModel.py", line 584, in WriteInfo
    info = codecs.open(filename, 'wb', encoding='utf-8')
  File "/usr/local/lib/python2.7/codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: u'/mnt/Pixiv/26173 bonten/\u51e0\uff20\u4f8b\u5927\u796dM05a/R-18/sketch-icon - [\u5bc4\u7a3f] \u4f8b\u5927\u796d\uff11\uff14 \u300e\u30aa\u30ab\u30a4\u30e2\u30ce\u30ac\u30bf\u30ea\u300f.txt'
2017-05-08 18:01:10,631 - PixivUtil20170411 - ERROR - Error when saving image info: /mnt/Pixiv/26173 bonten/几＠例大祭M05a/sketch-icon - [寄稿] 例大祭１４ 『おかいものがたり』.txt, file is saved to: 62754637.txt
Traceback (most recent call last):
  File "/PixivUtil2/PixivModel.py", line 584, in WriteInfo
    info = codecs.open(filename, 'wb', encoding='utf-8')
  File "/usr/local/lib/python2.7/codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: u'/mnt/Pixiv/26173 bonten/\u51e0\uff20\u4f8b\u5927\u796dM05a/sketch-icon - [\u5bc4\u7a3f] \u4f8b\u5927\u796d\uff11\uff14 \u300e\u304a\u304b\u3044\u3082\u306e\u304c\u305f\u308a\u300f.txt'

**Comment by whinette** [comment]
The image is not downloaded and the image info does not follow the rules (imgnumber - imgname)

Valid example: 59426187_p8 - 秋季例大祭新刊 『オオカミだって赤ずきん』.jpg.txt
This error generates: sketch-icon - [寄稿] 例大祭１４ 『おかいものがたり』.txt

**Comment by whinette** [comment]
Looks like same issue as https://github.com/Nandaka/PixivUtil2/issues/224

**Comment by Nandaka** [comment]
dupes with #224
