### ISSUE TITLE
Pixiv Util crashes if network temporarily unavailable while scanning user.

### ISSUE THREAD

**Issue by awiebe** [Nandaka/PixivUtil2#237]
My internet went out temporarily, and rather than failing gracefully after 4 retries, pixiv util crashed horribly.  It seems to have proceeded even though it failed to get some data, and then crashed because of a null reference. I would recommend that the default behaviour here be to retry indefinitely, or wait for user input to retry again.

-----
```
Member ID ([redacted]): 9005 'Failed to get page: ' 
Traceback (most recent call last):
  File "PixivUtil2.py", line 354, in process_member
    if list_page is not None:
UnboundLocalError: local variable 'list_page' referenced before assignment
Error at process_member(): (<type 'exceptions.UnboundLocalError'>, UnboundLocalError("local variable 'list_page' referenced before assignment",), <traceback object at 0x10bfa7dd0>) 
Cannot dump page for member_id:[redacted]
Error at process_bookmark(): (<type 'exceptions.UnboundLocalError'>, UnboundLocalError("local variable 'list_page' referenced before assignment",), <traceback object at 0x10bfa7e18>)
Traceback (most recent call last):
  File "PixivUtil2.py", line 1876, in main
    np_is_valid, op_is_valid, selection = main_loop(ewd, mode, op_is_valid, selection, np_is_valid, args)
  File "PixivUtil2.py", line 1665, in main_loop
    menu_download_from_online_user_bookmark(mode, op_is_valid, args)
  File "PixivUtil2.py", line 1468, in menu_download_from_online_user_bookmark
    process_bookmark(mode, hide, start_page, end_page)
  File "PixivUtil2.py", line 1031, in process_bookmark
    process_member(mode, item.memberId, item.path)
  File "PixivUtil2.py", line 508, in process_member
    if list_page is not None:
UnboundLocalError: local variable 'list_page' referenced before assignment
press enter to exit.

```

**Comment by Nandaka** [comment]
I'll fix the unbound error, but most likely it will just go back to main page for the behaviour.
