### ISSUE TITLE
Crash when trying to backup my own gallery

### ISSUE THREAD

**Issue by Latexity** [Nandaka/PixivUtil2#262]
Due to a layout change on Pixiv, when I try to download anything from my own gallery, pixivutil2 crashes.

The crash seems to happen because it calls to the manage page and not the gallery home page.

Since the manage page does not display the artist name or show an avatar, there is no file for pixivutil to download and therefore, it crashes. :(

**Comment by Nandaka** [comment]
can you provide the log file? You can delete the old log file, recreate the crash, and then upload the ```pixivutil.log``` here.

**Comment by Latexity** [comment]
2017-09-21 00:51:46,417 - PixivUtil20170813-beta1 - INFO - ###############################################################
2017-09-21 00:51:46,417 - PixivUtil20170813-beta1 - INFO - Starting...
2017-09-21 00:51:46,420 - PixivUtil20170813-beta1 - INFO - Setting log level to: DEBUG
2017-09-21 00:51:46,420 - PixivUtil20170813-beta1 - INFO - No default cookie jar available, creating... 
2017-09-21 00:51:46,421 - PixivUtil20170813-beta1 - INFO - Using default factory (mechanize 3.x ?)
2017-09-21 00:51:46,421 - PixivUtil20170813-beta1 - INFO - using default DB Path: I:\pixivutil\db.sqlite
2017-09-21 00:51:46,424 - PixivUtil20170813-beta1 - INFO - Only process member where day last updated >= 7
2017-09-21 00:51:46,424 - PixivUtil20170813-beta1 - INFO - Using Username: latexity
2017-09-21 00:51:46,424 - PixivUtil20170813-beta1 - INFO - Trying to log with saved cookie
2017-09-21 00:51:49,561 - PixivUtil20170813-beta1 - INFO - Login successfull.
2017-09-21 00:51:49,561 - PixivUtil20170813-beta1 - INFO - Logged in using cookie
2017-09-21 00:51:59,349 - PixivUtil20170813-beta1 - INFO - Member id mode.
2017-09-21 00:52:04,773 - PixivUtil20170813-beta1 - INFO - Processing Member Id: 539661
2017-09-21 00:52:04,789 - PixivUtil20170813-beta1 - INFO - Member Url: https://www.pixiv.net/member_illust.php?id=539661&p=1
2017-09-21 00:52:06,565 - PixivUtil20170813-beta1 - ERROR - Error at process_member(): (<type 'exceptions.IndexError'>, IndexError('list index out of range',), <traceback object at 0x03E30260>)
2017-09-21 00:52:06,565 - PixivUtil20170813-beta1 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 389, in process_member
  File "PixivHelper.pyc", line 344, in createAvatarFilename
  File "PixivHelper.pyc", line 138, in makeFilename
IndexError: list index out of range

2017-09-21 00:52:06,565 - PixivUtil20170813-beta1 - ERROR - Error at process_member(): 539661
Traceback (most recent call last):
  File "PixivUtil2.py", line 389, in process_member
  File "PixivHelper.pyc", line 344, in createAvatarFilename
  File "PixivHelper.pyc", line 138, in makeFilename
IndexError: list index out of range
2017-09-21 00:52:06,565 - PixivUtil20170813-beta1 - DEBUG - Sanitized Filename: Error page for member 539661.html
2017-09-21 00:52:06,586 - PixivUtil20170813-beta1 - ERROR - Dumping html to: Error page for member 539661.html
2017-09-21 00:52:06,586 - PixivUtil20170813-beta1 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 389, in process_member
  File "PixivHelper.pyc", line 344, in createAvatarFilename
  File "PixivHelper.pyc", line 138, in makeFilename
IndexError: list index out of range

2017-09-21 00:52:06,591 - PixivUtil20170813-beta1 - ERROR - Unknown Error: list index out of range
Traceback (most recent call last):
  File "PixivUtil2.py", line 1884, in main
  File "PixivUtil2.py", line 1661, in main_loop
  File "PixivUtil2.py", line 1311, in menu_download_by_member_id
  File "PixivUtil2.py", line 389, in process_member
  File "PixivHelper.pyc", line 344, in createAvatarFilename
  File "PixivHelper.pyc", line 138, in makeFilename
IndexError: list index out of range
2017-09-21 00:52:08,292 - PixivUtil20170813-beta1 - INFO - EXIT: -1
2017-09-21 00:52:08,293 - PixivUtil20170813-beta1 - INFO - ###############################################################

**Comment by Nandaka** [comment]
I assume, you are member=539661?
Can you upload ```Error page for member 539661.html``` here? I don't have any uploaded artwork, so I cannot really test your case.

**Comment by Nandaka** [comment]
another way is by creating dummy account and do the download via that account.
Your private images won't be visible though.

**Comment by Latexity** [comment]
![untitled-1](https://user-images.githubusercontent.com/32127599/30733050-e46868aa-9f3a-11e7-812f-15921ba8b720.png)

Since I cannot upload html files, here is a screenshot of the error page cleaned for privacy (black boxes) 

When trying to download from your own page, it calls to the artist "manage" page. On the "manage" page there are no name or avatar image displayed in the upper left. So, when pixivutil2 tries to download that information like it does for an artist main page, the program crashes because the data it is looking for is not there.

**Comment by Nandaka** [comment]
You can upload after zipping it. Please note that the application is not supporting to download your own artwork yet. I can code to skip the avatar, but other small differences might break the app again.

The alternative is by creating dummy account and download your own artwork using that account.

**Comment by Latexity** [comment]
I understand now. :) I will have to make a dummy account then

[Error page for member 539661.zip](https://github.com/Nandaka/PixivUtil2/files/1323730/Error.page.for.member.539661.zip)

Here is the html error file in case it will help you better with finding the problem

**Comment by Nandaka** [comment]
Should be fixed with limitation (member info will not be downloaded). 

It is recommended to use another account to download the images.
