### ISSUE TITLE
Problem with adding blacklist tags

### ISSUE THREAD

**Issue by redkman** [Nandaka/PixivUtil2#291]
So I created a simple blacklist_tags.txt, added one japanese tag per line, saved using UTF-8 and put in the PixivUtil2-master folder. I also changed useblacklisttags = True in config.ini and restarted the program when I got an error: File doesn’t exists or no permission to read: blacklist_tags.txt

Here is the log file:
2017-12-26 12:51:24,097 - PixivUtil20171226 - INFO - ###############################################################
2017-12-26 12:51:24,097 - PixivUtil20171226 - INFO - Starting...
2017-12-26 12:51:24,099 - PixivUtil20171226 - INFO - Setting log level to: DEBUG
2017-12-26 12:51:24,100 - PixivUtil20171226 - INFO - No default cookie jar available, creating... 
2017-12-26 12:51:24,100 - PixivUtil20171226 - INFO - Using default factory (mechanize 3.x ?)
2017-12-26 12:51:24,107 - PixivUtil20171226 - INFO - using default DB Path: /Applications/PixivUtil2-master/db.sqlite
2017-12-26 12:51:24,108 - PixivUtil20171226 - INFO - Only process member where day last updated >= 7
2017-12-26 12:51:24,108 - PixivUtil20171226 - ERROR - File doesn't exists or no permission to read: blacklist_tags.txt
2017-12-26 12:51:24,110 - PixivUtil20171226 - ERROR - Traceback (most recent call last):
  File "/Applications/PixivUtil2-master/PixivUtil2.py", line 1867, in main
    __blacklistTags = PixivTags.parseTagsList("blacklist_tags.txt")
  File "/Applications/PixivUtil2-master/PixivModel.py", line 1075, in parseTagsList
    PixivException.FILE_NOT_EXISTS_OR_NO_READ_PERMISSION)
PixivException: 4001 "File doesn't exists or no permission to read: blacklist_tags.txt"

2017-12-26 12:51:26,985 - PixivUtil20171226 - INFO - EXIT: 4001
2017-12-26 12:51:26,985 - PixivUtil20171226 - INFO - ###############################################################
2017-12-26 13:00:51,271 - PixivUtil20171226 - INFO - ###############################################################
2017-12-26 13:00:51,271 - PixivUtil20171226 - INFO - Starting...
2017-12-26 13:00:51,273 - PixivUtil20171226 - INFO - Setting log level to: DEBUG
2017-12-26 13:00:51,273 - PixivUtil20171226 - INFO - No default cookie jar available, creating... 
2017-12-26 13:00:51,273 - PixivUtil20171226 - INFO - Using default factory (mechanize 3.x ?)
2017-12-26 13:00:51,280 - PixivUtil20171226 - INFO - using default DB Path: /Applications/PixivUtil2-master/db.sqlite
2017-12-26 13:00:51,281 - PixivUtil20171226 - INFO - Only process member where day last updated >= 7
2017-12-26 13:00:51,281 - PixivUtil20171226 - ERROR - File doesn't exists or no permission to read: blacklist_tags.txt
2017-12-26 13:00:51,282 - PixivUtil20171226 - ERROR - Traceback (most recent call last):
  File "/Applications/PixivUtil2-master/PixivUtil2.py", line 1867, in main
    __blacklistTags = PixivTags.parseTagsList("blacklist_tags.txt")
  File "/Applications/PixivUtil2-master/PixivModel.py", line 1075, in parseTagsList
    PixivException.FILE_NOT_EXISTS_OR_NO_READ_PERMISSION)
PixivException: 4001 "File doesn't exists or no permission to read: blacklist_tags.txt"

2017-12-26 13:00:52,647 - PixivUtil20171226 - INFO - EXIT: 4001
2017-12-26 13:00:52,647 - PixivUtil20171226 - INFO - ###############################################################

Other than that, I still downloaded images just fine. Thanks for the awesome script.

**Comment by Nandaka** [comment]
I assume you save the blacklist in the ```/Applications/PixivUtil2-master/blacklist_tags.txt```?

Are you running from the python script or from the compiled/exe file? Are you using windows?
Looks like the error message is slightly different from what I get if I delete the file
```File doesn't exists or no permission to read: blacklist_tags.txt```

If you are using linux, try to chmod 666 to the file?

**Comment by redkman** [comment]
You solved the problem for me. Yes, I am running the script with terminal from a mac. Added the line chmod a+rwx ~/blacklist_tags.txt and now the blacklist works like a charms. Thanks a lot!
