### ISSUE TITLE
Overflow Error

### ISSUE THREAD

**Issue by LieXXX** [Nandaka/PixivUtil2#293]
Trying to grab the 3448714 tag from Pixiv and this image throws an error.

```
OverflowError: cannot fit 'long' into an index-sized integer
Error at download_image(): (<type 'exceptions.OverflowError'>, OverflowError("cannot fit 'long' into an index-sized integer",), <traceback object at 0x03A73080>) at https://i.pximg.net/img-original/img/2009/03/14/18/12/39/3448714_p0.jpg (9000)
Traceback (most recent call last):
  File "PixivUtil2.py", line 688, in process_image
  File "PixivUtil2.py", line 177, in download_image
  File "PIL\Image.pyc", line 2559, in open
  File "PIL\Image.pyc", line 2549, in _open_core
  File "PIL\JpegImagePlugin.pyc", line 764, in jpeg_factory
  File "PIL\ImageFile.pyc", line 102, in __init__
  File "PIL\JpegImagePlugin.pyc", line 338, in _open
  File "PIL\JpegImagePlugin.pyc", line 123, in APP
  File "PIL\JpegImagePlugin.pyc", line 416, in _getexif
  File "PIL\JpegImagePlugin.pyc", line 463, in _getexif
  File "PIL\TiffImagePlugin.pyc", line 716, in load
OverflowError: cannot fit 'long' into an index-sized integer
Error at process_image(): (<type 'exceptions.OverflowError'>, OverflowError("cannot fit 'long' into an index-sized integer",), <traceback object at 0x03887DF0>)
Dumping html to: Error medium page for image 3448714.html
Error at process_tags(): (<type 'exceptions.OverflowError'>, OverflowError("cannot fit 'long' into an index-sized integer",), <traceback object at 0x03B4BAD0>)
Dumping html to: Error page for search tags %E6%9D%B1%E6%96%B9.html
Traceback (most recent call last):
  File "PixivUtil2.py", line 1895, in main
  File "PixivUtil2.py", line 1676, in main_loop
  File "PixivUtil2.py", line 1392, in menu_download_by_tags
  File "PixivUtil2.py", line 846, in process_tags
  File "PixivUtil2.py", line 688, in process_image
  File "PixivUtil2.py", line 177, in download_image
  File "PIL\Image.pyc", line 2559, in open
  File "PIL\Image.pyc", line 2549, in _open_core
  File "PIL\JpegImagePlugin.pyc", line 764, in jpeg_factory
  File "PIL\ImageFile.pyc", line 102, in __init__
  File "PIL\JpegImagePlugin.pyc", line 338, in _open
  File "PIL\JpegImagePlugin.pyc", line 123, in APP
  File "PIL\JpegImagePlugin.pyc", line 416, in _getexif
  File "PIL\JpegImagePlugin.pyc", line 463, in _getexif
  File "PIL\TiffImagePlugin.pyc", line 716, in load
OverflowError: cannot fit 'long' into an index-sized integer
press enter to exit.
```

**Comment by Nandaka** [comment]
It is from the PIL library. Set `verifyImage` to false in config.ini

It is caused by corrupted images being uploaded by the artist.
```UserWarning: Possibly corrupt EXIF data```
