### ISSUE TITLE
can't download from my bookmark

### ISSUE THREAD

**Issue by sv2korea** [Nandaka/PixivUtil2#300]
here is my log. i used 20171216 and 20171127 version.

2018-01-05 15:36:33,799 - PixivUtil20171127 - INFO - ###############################################################
2018-01-05 15:36:33,799 - PixivUtil20171127 - INFO - Starting...
2018-01-05 15:36:33,815 - PixivUtil20171127 - ERROR - Error at loadConfig()
Traceback (most recent call last):
  File "PixivConfig.pyc", line 107, in loadConfig
  File "PixivHelper.pyc", line 310, in OpenTextFile
  File "codecs.pyc", line 896, in open
IOError: [Errno 2] No such file or directory: u'Z:\\sv2korea\\pixivutil\\config.ini'
2018-01-05 15:36:33,845 - PixivUtil20171127 - INFO - Setting log level to: DEBUG
2018-01-05 15:36:33,845 - PixivUtil20171127 - INFO - No default cookie jar available, creating... 
2018-01-05 15:36:33,861 - PixivUtil20171127 - INFO - using default DB Path: Z:\sv2korea\pixivutil\db.sqlite
2018-01-05 15:36:34,220 - PixivUtil20171127 - INFO - Only process member where day last updated >= 7
2018-01-05 15:36:42,424 - PixivUtil20171127 - INFO - Logging in...
2018-01-05 15:36:44,220 - PixivUtil20171127 - INFO - Logging in, return url: https://accounts.pixiv.net/api/login?lang=en
2018-01-05 15:36:44,220 - PixivUtil20171127 - INFO - {"error":false,"message":"","body":{"success":{"return_to":"https:\/\/www.pixiv.net"}}}
2018-01-05 15:36:44,220 - PixivUtil20171127 - INFO - new cookie value: 1273571_0f45db9215a752fd08e87ed88e14f615
2018-01-05 15:36:47,253 - PixivUtil20171127 - INFO - Member Bookmark mode.
2018-01-05 15:36:52,456 - PixivUtil20171127 - INFO - Processing Member Id: 1273571
2018-01-05 15:36:52,565 - PixivUtil20171127 - INFO - Member Url: https://www.pixiv.net/bookmark.php?id=1273571&p=1&tag=
2018-01-05 15:36:54,282 - PixivUtil20171127 - ERROR - Cannot parse artist info, dumping to Dump for [pixiv] Bookmarks UnknownProfile for None.html
2018-01-05 15:36:54,282 - PixivUtil20171127 - ERROR - None

2018-01-05 15:36:54,282 - PixivUtil20171127 - DEBUG - Sanitized Filename: Dump for [pixiv] Bookmarks UnknownProfile for None.html
2018-01-05 15:36:54,392 - PixivUtil20171127 - DEBUG - Getting image page: 66653648
2018-01-05 15:36:56,627 - PixivUtil20171127 - ERROR - Error at process_image(): (<type 'exceptions.TypeError'>, TypeError('coercing to Unicode: need string or buffer, NoneType found',), <traceback object at 0x06094A58>)
2018-01-05 15:36:56,642 - PixivUtil20171127 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 674, in process_image
  File "PixivHelper.pyc", line 149, in makeFilename
TypeError: coercing to Unicode: need string or buffer, NoneType found

2018-01-05 15:36:56,642 - PixivUtil20171127 - ERROR - Error at process_image(): 66653648
Traceback (most recent call last):
  File "PixivUtil2.py", line 674, in process_image
  File "PixivHelper.pyc", line 149, in makeFilename
TypeError: coercing to Unicode: need string or buffer, NoneType found
2018-01-05 15:36:56,642 - PixivUtil20171127 - DEBUG - Sanitized Filename: Error medium page for image 66653648.html
2018-01-05 15:36:56,657 - PixivUtil20171127 - ERROR - Dumping html to: Error medium page for image 66653648.html
2018-01-05 15:36:56,657 - PixivUtil20171127 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 674, in process_image
  File "PixivHelper.pyc", line 149, in makeFilename
TypeError: coercing to Unicode: need string or buffer, NoneType found

2018-01-05 15:36:56,657 - PixivUtil20171127 - ERROR - Error at process_member(): (<type 'exceptions.TypeError'>, TypeError('coercing to Unicode: need string or buffer, NoneType found',), <traceback object at 0x06094378>) Member Id: 1273571
Traceback (most recent call last):
  File "PixivUtil2.py", line 444, in process_member
  File "PixivUtil2.py", line 674, in process_image
  File "PixivHelper.pyc", line 149, in makeFilename
TypeError: coercing to Unicode: need string or buffer, NoneType found
2018-01-05 15:36:58,658 - PixivUtil20171127 - DEBUG - Getting image page: 66653648
2018-01-05 15:37:01,032 - PixivUtil20171127 - ERROR - Error at process_image(): (<type 'exceptions.TypeError'>, TypeError('coercing to Unicode: need string or buffer, NoneType found',), <traceback object at 0x060EBD28>)
2018-01-05 15:37:01,049 - PixivUtil20171127 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 674, in process_image
  File "PixivHelper.pyc", line 149, in makeFilename
TypeError: coercing to Unicode: need string or buffer, NoneType found

2018-01-05 15:37:01,049 - PixivUtil20171127 - ERROR - Error at process_image(): 66653648
Traceback (most recent call last):
  File "PixivUtil2.py", line 674, in process_image
  File "PixivHelper.pyc", line 149, in makeFilename
TypeError: coercing to Unicode: need string or buffer, NoneType found
2018-01-05 15:37:01,049 - PixivUtil20171127 - DEBUG - Sanitized Filename: Error medium page for image 66653648.html
2018-01-05 15:37:01,049 - PixivUtil20171127 - ERROR - Dumping html to: Error medium page for image 66653648.html
2018-01-05 15:37:01,065 - PixivUtil20171127 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 674, in process_image
  File "PixivHelper.pyc", line 149, in makeFilename
TypeError: coercing to Unicode: need string or buffer, NoneType found

2018-01-05 15:37:01,065 - PixivUtil20171127 - ERROR - Error at process_member(): (<type 'exceptions.TypeError'>, TypeError('coercing to Unicode: need string or buffer, NoneType found',), <traceback object at 0x060EB710>) Member Id: 1273571
Traceback (most recent call last):
  File "PixivUtil2.py", line 444, in process_member
  File "PixivUtil2.py", line 674, in process_image
  File "PixivHelper.pyc", line 149, in makeFilename
TypeError: coercing to Unicode: need string or buffer, NoneType found
2018-01-05 15:37:03,065 - PixivUtil20171127 - DEBUG - Getting image page: 66653648
2018-01-05 15:37:05,174 - PixivUtil20171127 - ERROR - Error at process_image(): (<type 'exceptions.TypeError'>, TypeError('coercing to Unicode: need string or buffer, NoneType found',), <traceback object at 0x05410990>)
2018-01-05 15:37:05,174 - PixivUtil20171127 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 674, in process_image
  File "PixivHelper.pyc", line 149, in makeFilename
TypeError: coercing to Unicode: need string or buffer, NoneType found

2018-01-05 15:37:05,174 - PixivUtil20171127 - ERROR - Error at process_image(): 66653648
Traceback (most recent call last):
  File "PixivUtil2.py", line 674, in process_image
  File "PixivHelper.pyc", line 149, in makeFilename
TypeError: coercing to Unicode: need string or buffer, NoneType found
2018-01-05 15:37:05,174 - PixivUtil20171127 - DEBUG - Sanitized Filename: Error medium page for image 66653648.html
2018-01-05 15:37:05,204 - PixivUtil20171127 - ERROR - Dumping html to: Error medium page for image 66653648.html
2018-01-05 15:37:05,220 - PixivUtil20171127 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 674, in process_image
  File "PixivHelper.pyc", line 149, in makeFilename
TypeError: coercing to Unicode: need string or buffer, NoneType found

2018-01-05 15:37:05,220 - PixivUtil20171127 - ERROR - Error at process_member(): (<type 'exceptions.TypeError'>, TypeError('coercing to Unicode: need string or buffer, NoneType found',), <traceback object at 0x054103F0>) Member Id: 1273571
Traceback (most recent call last):
  File "PixivUtil2.py", line 444, in process_member
  File "PixivUtil2.py", line 674, in process_image
  File "PixivHelper.pyc", line 149, in makeFilename
TypeError: coercing to Unicode: need string or buffer, NoneType found
2018-01-05 15:37:07,236 - PixivUtil20171127 - DEBUG - Getting image page: 66653648
2018-01-05 15:37:09,532 - PixivUtil20171127 - ERROR - Error at process_image(): (<type 'exceptions.TypeError'>, TypeError('coercing to Unicode: need string or buffer, NoneType found',), <traceback object at 0x05BA1558>)
2018-01-05 15:37:09,532 - PixivUtil20171127 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 674, in process_image
  File "PixivHelper.pyc", line 149, in makeFilename
TypeError: coercing to Unicode: need string or buffer, NoneType found

2018-01-05 15:37:09,532 - PixivUtil20171127 - ERROR - Error at process_image(): 66653648
Traceback (most recent call last):
  File "PixivUtil2.py", line 674, in process_image
  File "PixivHelper.pyc", line 149, in makeFilename
TypeError: coercing to Unicode: need string or buffer, NoneType found
2018-01-05 15:37:09,549 - PixivUtil20171127 - DEBUG - Sanitized Filename: Error medium page for image 66653648.html
2018-01-05 15:37:09,549 - PixivUtil20171127 - ERROR - Dumping html to: Error medium page for image 66653648.html
2018-01-05 15:37:09,549 - PixivUtil20171127 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 674, in process_image
  File "PixivHelper.pyc", line 149, in makeFilename
TypeError: coercing to Unicode: need string or buffer, NoneType found

2018-01-05 15:37:09,565 - PixivUtil20171127 - ERROR - Error at process_member(): (<type 'exceptions.TypeError'>, TypeError('coercing to Unicode: need string or buffer, NoneType found',), <traceback object at 0x05BA1AF8>) Member Id: 1273571
Traceback (most recent call last):
  File "PixivUtil2.py", line 444, in process_member
  File "PixivUtil2.py", line 674, in process_image
  File "PixivHelper.pyc", line 149, in makeFilename
TypeError: coercing to Unicode: need string or buffer, NoneType found
2018-01-05 15:37:11,581 - PixivUtil20171127 - DEBUG - Getting image page: 66653648
2018-01-05 15:37:13,720 - PixivUtil20171127 - ERROR - Error at process_image(): (<type 'exceptions.TypeError'>, TypeError('coercing to Unicode: need string or buffer, NoneType found',), <traceback object at 0x05C83328>)
2018-01-05 15:37:13,720 - PixivUtil20171127 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 674, in process_image
  File "PixivHelper.pyc", line 149, in makeFilename
TypeError: coercing to Unicode: need string or buffer, NoneType found

2018-01-05 15:37:13,736 - PixivUtil20171127 - ERROR - Error at process_image(): 66653648
Traceback (most recent call last):
  File "PixivUtil2.py", line 674, in process_image
  File "PixivHelper.pyc", line 149, in makeFilename
TypeError: coercing to Unicode: need string or buffer, NoneType found
2018-01-05 15:37:13,736 - PixivUtil20171127 - DEBUG - Sanitized Filename: Error medium page for image 66653648.html
2018-01-05 15:37:13,736 - PixivUtil20171127 - ERROR - Dumping html to: Error medium page for image 66653648.html
2018-01-05 15:37:13,752 - PixivUtil20171127 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 674, in process_image
  File "PixivHelper.pyc", line 149, in makeFilename
TypeError: coercing to Unicode: need string or buffer, NoneType found

2018-01-05 15:37:13,752 - PixivUtil20171127 - ERROR - Giving up image_id: 66653648
2018-01-05 15:37:13,752 - PixivUtil20171127 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 444, in process_member
  File "PixivUtil2.py", line 674, in process_image
  File "PixivHelper.pyc", line 149, in makeFilename
TypeError: coercing to Unicode: need string or buffer, NoneType found

i runned under windows 10.1709. some month ago i works well(i don't remember whether it was before upgrade to 1709 or not)

**Comment by Nandaka** [comment]
I assume ```1273571``` is your own user id? It is not supported to download your own works as the purpose of the application is to download others.

Try to create new user and use it to download your own images?

**Comment by sv2korea** [comment]
yes, but it works well about a few month ago. as your answer, it is curious that why it works in the past. ?_?

as your answer, i'll try by new account and reply here. thanks.

**Comment by Nandaka** [comment]
most likely because they changed something...

**Comment by sv2korea** [comment]
i made new account and use that in pixivutil2. but it doesn't work, too. there is same error message. :(

and here is file that you want.

[Error medium page for image 66653648.zip](https://github.com/Nandaka/PixivUtil2/files/1606743/Error.medium.page.for.image.66653648.zip)

**Comment by Nandaka** [comment]
Can you upload your filename format in the config.ini?

**Comment by sv2korea** [comment]
though it was in just default status...

[Settings]
filenameformat = %artist% (%member_id%)\%urlFilename% - %title%
filenamemangaformat = %artist% (%member_id%)\%urlFilename% - %title%
filenameinfoformat = %artist% (%member_id%)\%urlFilename% - %title%

**Comment by Nandaka** [comment]
Can you try option 6. Download from bookmarked images (bookmark.php)?

**Comment by sv2korea** [comment]
i don't tried as i just use option 12(or 11. Download Member's Bookmarked Images). it works well before.

i'll try that and answer here whether it works or not. thanks.

**Comment by sv2korea** [comment]
though it takes many time(as i am bookmarked too much :( ), it works. thanks.

**Comment by Nandaka** [comment]
yeah, some differences if you try to download your own images as the webpage will have different layout (e.g. manage page). I'll put an error if someone else try to download their own images and notify them to use option 6.
