### ISSUE TITLE
Unicode Error

### ISSUE THREAD

**Issue by LieXXX** [Nandaka/PixivUtil2#305]
Entering ```多々良小傘``` returns an error with unicode.

```
Tags: 多々良小傘
Traceback (most recent call last):
  File "PixivUtil2.py", line 1913, in main
  File "PixivUtil2.py", line 1679, in main_loop
  File "PixivUtil2.py", line 1303, in menu
  File "win_unicode_console\raw_input.pyc", line 100, in raw_input
EOFError```

**Comment by Nandaka** [comment]
are you using japanese locale?

**Comment by LieXXX** [comment]
Yes

**Comment by Nandaka** [comment]
Looks like win_unicode library issue, I'll log this on their github.

Only specific words cause this error. For time being, you can use Option 7 to download from tags list.

**Comment by Nandaka** [comment]
can you check https://github.com/Nandaka/PixivUtil2/releases/tag/v20180118

**Comment by LieXXX** [comment]
Looks like it is working now. Thank you.
