### ISSUE TITLE
Error on startup with proxy

### ISSUE THREAD

**Issue by with0out** [Nandaka/PixivUtil2#313]
Possibly related to [235](https://github.com/Nandaka/PixivUtil2/issues/235).
My OS is Debian, python version is 2.7.14.
It works fine without setting proxy, when I try to use socks proxy, exception occurs.

**config.ini**

> useproxy = True
> proxyaddress = socks5://127.0.0.1:6789

**Console Output**

```
$ python PixivUtil2.py -x -s 2 12345678
PixivDownloader2 version 20180118
...
Reading /home/.../PixivUtil2/config.ini ...
done.
Traceback (most recent call last):
  File "PixivUtil2.py", line 2002, in <module>
    main()
  File "PixivUtil2.py", line 1875, in main
    __br__ = PixivBrowserFactory.getBrowser(config=__config__)
  File "/home/.../PixivUtil2/PixivBrowserFactory.py", line 521, in getBrowser
    _browser = PixivBrowser(defaultConfig, defaultCookieJar)
  File "/home/.../PixivUtil2/PixivBrowserFactory.py", line 44, in __init__
    self._configureBrowser(config)
  File "/home/.../PixivUtil2/PixivBrowserFactory.py", line 64, in _configureBrowser
    socks.wrapmodule(urllib)
AttributeError: 'module' object has no attribute 'wrapmodule'
```

**Comment by Nandaka** [comment]
try to install the - socksipy-branch 1.02?

or paste this to the same folder with the script?
[socks.zip](https://github.com/Nandaka/PixivUtil2/files/1675642/socks.zip)

**Comment by with0out** [comment]
Oh sorry!
It's my proxy that's causing problem, I changed to an other proxy now it's fine.

**Comment by bluerthanever** [comment]
Hey. Mr. Nandaka. Sorry to interrupt, but I run into the same issue here with a socks5 proxy.
I tried to put the socks.py you provided in previous reply in the folder, but it ran into another error, which happens when it tries to get all the fanbox posts from an artist:

`Found 12 supported artist(s) 
[63680, 218421, 415138, 598317, 1350179, 1359780, 1766900, 1972225, 3838557, 3962174, 5625368, 10145955]
Processing 63680, page 1 
Getting posts from https://www.pixiv.net/ajax/fanbox/creator?userId=63680 
Traceback (most recent call last):
Using OAuth to retrieve member info for: 63680 
  File "F:/PixivUtil2-20191111/PixivUtil2.py", line 2483, in main
    np_is_valid, op_is_valid, selection = main_loop(ewd, op_is_valid, selection, np_is_valid, args)
  File "F:/PixivUtil2-20191111/PixivUtil2.py", line 2225, in main_loop
    menu_fanbox_download_supported_artist(op_is_valid, args)
  File "F:/PixivUtil2-20191111/PixivUtil2.py", line 1927, in menu_fanbox_download_supported_artist
    processFanboxArtist(artist_id, end_page)
  File "F:/PixivUtil2-20191111/PixivUtil2.py", line 1936, in processFanboxArtist
    result_artist = __br__.fanboxGetPostsFromArtist(artist_id, next_url)
  File "F:\PixivUtil2-20191111\PixivBrowserFactory.py", line 652, in fanboxGetPostsFromArtist
    self.getMemberInfoWhitecube(artist_id, pixivArtist)
  File "F:\PixivUtil2-20191111\PixivBrowserFactory.py", line 437, in getMemberInfoWhitecube
    login_response = self._oauth_manager.login()
  File "F:\PixivUtil2-20191111\PixivOAuth.py", line 97, in login
    verify=self._validate_ssl)
  File "D:\Program Files\Python\Python27\lib\site-packages\requests\api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "D:\Program Files\Python\Python27\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Program Files\Python\Python27\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Program Files\Python\Python27\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "D:\Program Files\Python\Python27\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "D:\Program Files\Python\Python27\lib\site-packages\urllib3\connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "D:\Program Files\Python\Python27\lib\site-packages\urllib3\connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "D:\Program Files\Python\Python27\lib\site-packages\urllib3\connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "D:\Program Files\Python\Python27\lib\site-packages\urllib3\connection.py", line 334, in connect
    conn = self._new_conn()
  File "D:\Program Files\Python\Python27\lib\site-packages\urllib3\contrib\socks.py", line 90, in _new_conn
    conn = socks.create_connection(
AttributeError: 'module' object has no attribute 'create_connection'`


If I remove the socks.py file, then this happens as initiation:
"D:\Program Files\Python\Python27\python.exe" F:/PixivUtil2-20191111/PixivUtil2.py
Traceback (most recent call last):
  File "F:/PixivUtil2-20191111/PixivUtil2.py", line 2509, in <module>
PixivDownloader2 version 20191111
https://github.com/Nandaka/PixivUtil2/releases
Donate at https://bit.ly/PixivUtilDonation
Reading F:\PixivUtil2-20191111\config.ini ...
done.
    main()
  File "F:/PixivUtil2-20191111/PixivUtil2.py", line 2348, in main
    __br__ = PixivBrowserFactory.getBrowser(config=__config__)
  File "F:\PixivUtil2-20191111\PixivBrowserFactory.py", line 672, in getBrowser
    _browser = PixivBrowser(defaultConfig, defaultCookieJar)
  File "F:\PixivUtil2-20191111\PixivBrowserFactory.py", line 69, in __init__
    self._configureBrowser(config)
  File "F:\PixivUtil2-20191111\PixivBrowserFactory.py", line 98, in _configureBrowser
    socks.wrapmodule(urllib)
AttributeError: 'module' object has no attribute 'wrapmodule'

Process finished with exit code 1


But everything seems fine if I use the exe files from release. This is really confusing... Would you mind help me out here? I tried uninstalling and then installing socksipy-branch, socks, and pysocks ect, which all didn't work.
