### ISSUE TITLE
New Unicode problem?

### ISSUE THREAD

**Issue by zoram999** [Nandaka/PixivUtil2#316]
As of currently, no picture can be downloaded; whenever the app attempts to do so, an error message appears, followed by immediate closure. Worked fine until at least 12 hours prior. I'm not using non-Unicode mode on my PC. Extracts from logs follow.

---

Attempt with option 1

2018-02-19 09:58:43,220 - PixivUtil20171226 - INFO - Member id mode.
2018-02-19 09:58:45,155 - PixivUtil20171226 - INFO - Member IDs: [1430914]
2018-02-19 09:58:45,158 - PixivUtil20171226 - INFO - Processing Member Id: 1430914
2018-02-19 09:58:45,237 - PixivUtil20171226 - INFO - Member Url: https://www.pixiv.net/member_illust.php?id=1430914&p=1
2018-02-19 09:58:47,482 - PixivUtil20171226 - ERROR - Error at process_member(): (<type 'exceptions.TypeError'>, TypeError('coercing to Unicode: need string or buffer, NoneType found',), <traceback object at 0x054DC710>)
2018-02-19 09:58:47,482 - PixivUtil20171226 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 393, in process_member
  File "PixivHelper.pyc", line 351, in createAvatarFilename
  File "PixivHelper.pyc", line 149, in makeFilename
TypeError: coercing to Unicode: need string or buffer, NoneType found

2018-02-19 09:58:47,482 - PixivUtil20171226 - ERROR - Error at process_member(): 1430914
Traceback (most recent call last):
  File "PixivUtil2.py", line 393, in process_member
  File "PixivHelper.pyc", line 351, in createAvatarFilename
  File "PixivHelper.pyc", line 149, in makeFilename
TypeError: coercing to Unicode: need string or buffer, NoneType found
2018-02-19 09:58:47,483 - PixivUtil20171226 - DEBUG - Sanitized Filename: Error page for member 1430914.html
2018-02-19 09:58:47,720 - PixivUtil20171226 - ERROR - Dumping html to: Error page for member 1430914.html
2018-02-19 09:58:47,720 - PixivUtil20171226 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 393, in process_member
  File "PixivHelper.pyc", line 351, in createAvatarFilename
  File "PixivHelper.pyc", line 149, in makeFilename
TypeError: coercing to Unicode: need string or buffer, NoneType found

2018-02-19 09:58:47,726 - PixivUtil20171226 - ERROR - Unknown Error: coercing to Unicode: need string or buffer, NoneType found
Traceback (most recent call last):
  File "PixivUtil2.py", line 1913, in main
  File "PixivUtil2.py", line 1682, in main_loop
  File "PixivUtil2.py", line 1325, in menu_download_by_member_id
  File "PixivUtil2.py", line 393, in process_member
  File "PixivHelper.pyc", line 351, in createAvatarFilename
  File "PixivHelper.pyc", line 149, in makeFilename
TypeError: coercing to Unicode: need string or buffer, NoneType found

---

Attempt with option 8

2018-02-19 10:06:32,924 - PixivUtil20171226 - INFO - New Illust from Bookmark mode.
2018-02-19 10:06:33,299 - PixivUtil20171226 - INFO - Source URL: https://www.pixiv.net/bookmark_new_illust.php?p=1
2018-02-19 10:06:35,325 - PixivUtil20171226 - DEBUG - Getting image page: 67357245
2018-02-19 10:06:41,382 - PixivUtil20171226 - ERROR - Error at process_image(): (<type 'exceptions.TypeError'>, TypeError('coercing to Unicode: need string or buffer, NoneType found',), <traceback object at 0x05A35738>)
2018-02-19 10:06:41,382 - PixivUtil20171226 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 674, in process_image
  File "PixivHelper.pyc", line 149, in makeFilename
TypeError: coercing to Unicode: need string or buffer, NoneType found

2018-02-19 10:06:41,384 - PixivUtil20171226 - ERROR - Error at process_image(): 67357245
Traceback (most recent call last):
  File "PixivUtil2.py", line 674, in process_image
  File "PixivHelper.pyc", line 149, in makeFilename
TypeError: coercing to Unicode: need string or buffer, NoneType found
2018-02-19 10:06:41,384 - PixivUtil20171226 - DEBUG - Sanitized Filename: Error medium page for image 67357245.html
2018-02-19 10:06:41,549 - PixivUtil20171226 - ERROR - Dumping html to: Error medium page for image 67357245.html
2018-02-19 10:06:41,549 - PixivUtil20171226 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 674, in process_image
  File "PixivHelper.pyc", line 149, in makeFilename
TypeError: coercing to Unicode: need string or buffer, NoneType found

2018-02-19 10:06:41,549 - PixivUtil20171226 - ERROR - Error at process_new_illust_from_bookmark(): (<type 'exceptions.TypeError'>, TypeError('coercing to Unicode: need string or buffer, NoneType found',), <traceback object at 0x05A39A30>)
Traceback (most recent call last):
  File "PixivUtil2.py", line 1095, in process_new_illust_from_bookmark
  File "PixivUtil2.py", line 674, in process_image
  File "PixivHelper.pyc", line 149, in makeFilename
TypeError: coercing to Unicode: need string or buffer, NoneType found
2018-02-19 10:06:41,565 - PixivUtil20171226 - ERROR - Unknown Error: coercing to Unicode: need string or buffer, NoneType found
Traceback (most recent call last):
  File "PixivUtil2.py", line 1913, in main
  File "PixivUtil2.py", line 1696, in main_loop
  File "PixivUtil2.py", line 1563, in menu_download_new_illust_from_bookmark
  File "PixivUtil2.py", line 1095, in process_new_illust_from_bookmark
  File "PixivUtil2.py", line 674, in process_image
  File "PixivHelper.pyc", line 149, in makeFilename
TypeError: coercing to Unicode: need string or buffer, NoneType found

---

Attempt with option 2

2018-02-19 09:55:57,213 - PixivUtil20171226 - INFO - Image id mode.
2018-02-19 09:55:58,878 - PixivUtil20171226 - DEBUG - Getting image page: 67355099
2018-02-19 09:56:01,362 - PixivUtil20171226 - ERROR - Error at process_image(): (<type 'exceptions.TypeError'>, TypeError('coercing to Unicode: need string or buffer, NoneType found',), <traceback object at 0x0543CC88>)
2018-02-19 09:56:01,364 - PixivUtil20171226 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 674, in process_image
  File "PixivHelper.pyc", line 149, in makeFilename
TypeError: coercing to Unicode: need string or buffer, NoneType found

2018-02-19 09:56:01,364 - PixivUtil20171226 - ERROR - Error at process_image(): 67355099
Traceback (most recent call last):
  File "PixivUtil2.py", line 674, in process_image
  File "PixivHelper.pyc", line 149, in makeFilename
TypeError: coercing to Unicode: need string or buffer, NoneType found
2018-02-19 09:56:01,364 - PixivUtil20171226 - DEBUG - Sanitized Filename: Error medium page for image 67355099.html
2018-02-19 09:56:01,657 - PixivUtil20171226 - ERROR - Dumping html to: Error medium page for image 67355099.html
2018-02-19 09:56:01,657 - PixivUtil20171226 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 674, in process_image
  File "PixivHelper.pyc", line 149, in makeFilename
TypeError: coercing to Unicode: need string or buffer, NoneType found

2018-02-19 09:56:01,740 - PixivUtil20171226 - ERROR - Unknown Error: coercing to Unicode: need string or buffer, NoneType found
Traceback (most recent call last):
  File "PixivUtil2.py", line 1913, in main
  File "PixivUtil2.py", line 1684, in main_loop
  File "PixivUtil2.py", line 1361, in menu_download_by_image_id
  File "PixivUtil2.py", line 674, in process_image
  File "PixivHelper.pyc", line 149, in makeFilename
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by Nandaka** [comment]
Please use the latest version and try again.

**Comment by LieXXX** [comment]
working now for me.

**Comment by zoram999** [comment]
20180219-beta1 works, thanks. I'm used to check just the blog, I'll have to check more frequently for updates.
