### ISSUE TITLE
Files checking: zip file for ugoira not created. Error on deletion.

### ISSUE THREAD

**Issue by whinette** [Nandaka/PixivUtil2#318]
```
2018-02-19 12:51:20,931 - PixivUtil20180219-beta1 - ERROR - Giving up image_id: 63344072
2018-02-19 12:51:20,932 - PixivUtil20180219-beta1 - ERROR - Traceback (most recent call last):
  File "/mnt/c/PixivUtil2_manual/PixivUtil2.py", line 491, in process_member
    result = process_image(artist, image_id, user_dir, bookmark, title_prefix=title_prefix)  # Yavos added dir-argument to pass
  File "/mnt/c/PixivUtil2_manual/PixivUtil2.py", line 741, in process_image
    os.utime(filename, (ts, ts))
OSError: [Errno 2] No such file or directory: "/mnt/z/Pixiv/4359729 amiwa38/SAI\xe3\x81\xa7\xe3\x81\x8a\xe7\xb5\xb5\xe6\x8f\x8f\xe3\x81\x8d\xe7\xb6\x99\xe7\xb6\x9a\xe4\xb8\xad/63344072_ugoira1920x1080 - FGOMAAAASH\xe3\x80\x80DERECTOR'S CUT.zip"
```

With latest version. Link to the ugoira: https://www.pixiv.net/member_illust.php?mode=medium&illust_id=63344072

I'm verifying all my files, it looks like the zip isn't recreated if the ugoira is present?

```
PixivDownloader2 version 20180219-beta1
https://github.com/Nandaka/PixivUtil2/releases
Donate at https://bit.ly/PixivUtilDonation
1. Download by member_id
2. Download by image_id
3. Download by tags
4. Download from list
5. Download from bookmarked artists (bookmark.php?type=user)
6. Download from bookmarked images (bookmark.php)
7. Download from tags list
8. Download new illust from bookmarked members (bookmark_new_illust.php)
9. Download by Title/Caption
10. Download by Tag and Member Id
11. Download Member Bookmark
12. Download by Group Id
------------------------
d. Manage database
e. Export online bookmark
m. Export online user bookmark
r. Reload config.ini
p. Print config.ini
x. Exit
Input: 2
Image ids: 63344072
Processing Image Id: 63344072
Member Name  : SAIでお絵描き継続中
Member Avatar: https://i.pximg.net/user-profile/img/2017/07/19/00/35/09/12882667_a0c6e294bb2ef621541131e86a9ba073_170.jpg
Member Token : amiwa38
Title: FGOMAAAASH　DERECTOR&#039;S CUT
Tags : うごイラ, FGO
Date : 2017-06-12 00:49:00
Mode : ugoira_view
Image URL : https://i.pximg.net/img-zip-ugoira/img/2017/06/12/00/49/54/63344072_ugoira1920x1080.zip
Filename  : /mnt/z/Pixiv/4359729 amiwa38/SAIでお絵描き継続中/63344072_ugoira1920x1080 - FGOMAAAASH　DERECTOR'S CUT.zip
Getting remote filesize...
Using Referer: https://www.pixiv.net/member_illust.php?mode=medium&illust_id=63344072
Remote filesize = 1.44 MiB (1504729 Bytes)
        File exist! (Identical Size)
Traceback (most recent call last):
  File "PixivUtil2.py", line 741, in process_image
    os.utime(filename, (ts, ts))
OSError: [Errno 2] No such file or directory: "/mnt/z/Pixiv/4359729 amiwa38/SAI\xe3\x81\xa7\xe3\x81\x8a\xe7\xb5\xb5\xe6\x8f\x8f\xe3\x81\x8d\xe7\xb6\x99\xe7\xb6\x9a\xe4\xb8\xad/63344072_ugoira1920x1080 - FGOMAAAASH\xe3\x80\x80DERECTOR'S CUT.zip"
Error at process_image(): (<type 'exceptions.OSError'>, OSError(2, 'No such file or directory'), <traceback object at 0x7ffc595ec5f0>)
Dumping html to: Error medium page for image 63344072.html
Traceback (most recent call last):
  File "PixivUtil2.py", line 1987, in main
    np_is_valid, op_is_valid, selection = main_loop(ewd, op_is_valid, selection, np_is_valid, args)
  File "PixivUtil2.py", line 1763, in main_loop
    menu_download_by_image_id(op_is_valid, args)
  File "PixivUtil2.py", line 1433, in menu_download_by_image_id
    process_image(None, int(image_id))
  File "PixivUtil2.py", line 741, in process_image
    os.utime(filename, (ts, ts))
OSError: [Errno 2] No such file or directory: "/mnt/z/Pixiv/4359729 amiwa38/SAI\xe3\x81\xa7\xe3\x81\x8a\xe7\xb5\xb5\xe6\x8f\x8f\xe3\x81\x8d\xe7\xb6\x99\xe7\xb6\x9a\xe4\xb8\xad/63344072_ugoira1920x1080 - FGOMAAAASH\xe3\x80\x80DERECTOR'S CUT.zip"
press enter to exit.```

**Comment by Nandaka** [comment]
If the file previously already downloaded, it will not redownload the file again if the file size is the same. I think it got extra validation for ugoira, as there is some modification to the original zip file to insert the js.file for ugoira format.
Also it will delete the original zip file if you set ```deletezipfile = True``` in config.ini.

I'll add a file exists check before it do the os.utime for now.
