### ISSUE TITLE
HTTP 404 error

### ISSUE THREAD

**Issue by LieXXX** [Nandaka/PixivUtil2#330]
```
Image #1685
Image Id: 84940
Bookmark Count: 7
Processing Image Id: 84940
Member Name  : 星乃だーつ
Member Avatar: https://i.pximg.net/user-profile/img/2017/05/22/06/55/09/12591735_72dacb3e5f19a4f545b7bc43b42f889b_170.jpg
Member Token : darts
Title: ハロウィン魔理沙
Tags : 魔理沙, はいてない, 東方, ハロウィン
Date : 2007-10-15 13:52:00
Mode : bigNew
Image URL : https://i.pximg.net/img-original/img/2007/10/15/13/52/34/84940_p0.jpg
Filename  : G:\Pixiv Downloads\2277\魔理沙,はいてない,東方,ハロウィン\84940.jpg
Checking local filename... Start downloading... Using Referer: https://www.pixiv.net/member_illust.php?mode=medium&illust_id=84940
[download_image()] HTTP Error: HTTP Error 404: Not Found at https://i.pximg.net/img-original/img/2007/10/15/13/52/34/84940_p0.jpg
Traceback (most recent call last):
  File "PixivUtil2.py", line 741, in process_image
WindowsError: [Error 3] The system cannot find the path specified: u'G:\\Pixiv Downloads\\2277\\\u9b54\u7406\u6c99,\u306f\u3044\u3066\u306a\u3044,\u6771\u65b9,\u30cf\u30ed\u30a6\u30a3\u30f3\\84940.jpg'
Error at process_image(): (<type 'exceptions.WindowsError'>, WindowsError(3, 'The system cannot find the path specified'), <traceback object at 0x03DA4918>)
Dumping html to: Error medium page for image 84940.html
Error at process_tags(): (<type 'exceptions.WindowsError'>, WindowsError(3, 'The system cannot find the path specified'), <traceback object at 0x03C8D850>)
Dumping html to: Error page for search tags %E6%9D%B1%E6%96%B9.html
Traceback (most recent call last):
  File "PixivUtil2.py", line 1987, in main
  File "PixivUtil2.py", line 1765, in main_loop
  File "PixivUtil2.py", line 1472, in menu_download_by_tags
  File "PixivUtil2.py", line 899, in process_tags
  File "PixivUtil2.py", line 741, in process_image
WindowsError: [Error 3] The system cannot find the path specified: u'G:\\Pixiv Downloads\\2277\\\u9b54\u7406\u6c99,\u306f\u3044\u3066\u306a\u3044,\u6771\u65b9,\u30cf\u30ed\u30a6\u30a3\u30f3\\84940.jpg'
press enter to exit.
```

I cannot remember if I had this issue before or not. I was downloading a tag and came across this one not loading.

**Comment by Nandaka** [comment]
Well, the page image is not loaded so the server does return 404. https://www.pixiv.net/member_illust.php?mode=medium&illust_id=84940

Which version you are using? Ensure you are using the latest version: https://github.com/Nandaka/PixivUtil2/releases

**Comment by LieXXX** [comment]
The image itself is broken on pixiv. I am unable to see what it is on anything I try. Are you able to see it?

**Comment by Nandaka** [comment]
Nope, it also return 404 error, meaning the file doesn't exists anymore. Are you using beta2 or older version?

**Comment by LieXXX** [comment]
I was on Beta 1. I just downloaded the new version.

If I searched for Touhou and that error came up,  the program would close. If I searched for 東方 and that image came up, the program would stay open with the error. This was Beta 1.

**Comment by Nandaka** [comment]
Weird, tried to download using beta2. It should output something like this:

```
Image URL : https://i.pximg.net/img-original/img/2007/10/15/13/52/34/84940_p0.jpg
Filename  : C:\Temp\Pixiv2\2277 darts\20071015 84940_p0 - ハロウィン魔理沙.jpg
Start downloading... Using Referer: https://www.pixiv.net/member_illust.php?mode=medium&illust_id=84940
[download_image()] HTTP Error: HTTP Error 404: Not Found at https://i.pximg.net/img-original/img/2007/10/15/13/52/34/84940_p0.jpg
Image url not found/failed to download: 84940
```

**Comment by Nandaka** [comment]
can you upload the log file generate from beta2?
