### ISSUE TITLE
Failing to initialize...

### ISSUE THREAD

**Issue by momoe** [Nandaka/PixivUtil2#379]
I've tried downloading the latest release and am getting this error. Can you help pinpoint the problem? 
```
[momoe@momoe-pc PixivUtil2-20180607]$ python2 PixivUtil2.py 
Traceback (most recent call last):
  File "PixivUtil2.py", line 73, in <module>
    import PixivBrowserFactory
  File "/home/momoe/PixivUtil2-20180607/PixivBrowserFactory.py", line 21, in <module>
    import PixivModelWhiteCube
  File "/home/momoe/PixivUtil2-20180607/PixivModelWhiteCube.py", line 7, in <module>
    import demjson
ImportError: No module named demjson
```

**Comment by momoe** [comment]
Update: was able to fix it with `pip2 install demjson --user`
