### ISSUE TITLE
[Linux] TypeError: coercing to Unicode: need string or buffer, NoneType found

### ISSUE THREAD

**Issue by greyspammer-tir** [Nandaka/PixivUtil2#385]
### Description

When trying to download, I get the following error:

```
Input: 1
Member ids: 6958100
Start Page (default=1):
End Page (default=0, 0 for no limit):
Member IDs: [6958100]
Processing Member Id: 6958100
Reading /home/user/PixivUtil2-master/config.ini ...
done.
Page  1
Member Url: https://www.pixiv.net/member_illust.php?id=6958100&p=1
Member Name  : ToniBabelony
Member Avatar: https://i.pximg.net/user-profile/img/2018/05/24/20/12/54/14270543_b466b535c8259a6eb4a870ff2b5f13ac_170.png
Member Token : None
Traceback (most recent call last):
  File "PixivUtil2.py", line 391, in process_member
    avatar_filename = PixivHelper.createAvatarFilename(artist, target_dir)
  File "/home/user/PixivUtil2-master/PixivHelper.py", line 344, in createAvatarFilename
    appendExtension=False)
  File "/home/user/PixivUtil2-master/PixivHelper.py", line 144, in makeFilename
    nameFormat = nameFormat.replace('%member_token%', artistInfo.artistToken)
TypeError: coercing to Unicode: need string or buffer, NoneType found
Error at process_member(): (<type 'exceptions.TypeError'>, TypeError('coercing to Unicode: need string or buffer, NoneType found',), <traceback object at 0x7fc0c0d26fc8>)
Dumping html to: Error page for member 6958100.html
Traceback (most recent call last):
  File "PixivUtil2.py", line 1895, in main
    np_is_valid, op_is_valid, selection = main_loop(ewd, mode, op_is_valid, selection, np_is_valid, args)
  File "PixivUtil2.py", line 1672, in main_loop
    menu_download_by_member_id(mode, op_is_valid, args)
  File "PixivUtil2.py", line 1317, in menu_download_by_member_id
    process_member(mode, member_id, page=page, end_page=end_page)
  File "PixivUtil2.py", line 391, in process_member
    avatar_filename = PixivHelper.createAvatarFilename(artist, target_dir)
  File "/home/user/PixivUtil2-master/PixivHelper.py", line 344, in createAvatarFilename
    appendExtension=False)
  File "/home/user/PixivUtil2-master/PixivHelper.py", line 144, in makeFilename
    nameFormat = nameFormat.replace('%member_token%', artistInfo.artistToken)
TypeError: coercing to Unicode: need string or buffer, NoneType found
press enter to exit.
```

I'm using Ubuntu 16.04 LTS with the most recent release of PixivUtil (20180702). The requirements are met. The same setup worked flawlessly a couple of months ago. The only change is the recent PixivUtil update (and the usual Ubuntu security fixes). The environment variables mentioned in Q4 of the FAQ are set correctly.

A quick under Windows shows that the problem does not exist there.

Attached is the error page created by PixivUtil.

[Error page for member 6958100.zip](https://github.com/Nandaka/PixivUtil2/files/2194965/Error.page.for.member.6958100.zip)

**Comment by Nandaka** [comment]
for some reason, the member token cannot be resolved from the logging
![image](https://user-images.githubusercontent.com/836867/42725712-ee569be8-87ba-11e8-8263-10cb13bd9cb6.png)

Can you try to copy the session value in config.ini from your windows pc to linux pc and see what is the result?

**Comment by greyspammer-tir** [comment]
Copying the config.ini from the Windows version didn't help. But on a hunch, I moved the old installation of PixivUtil aside and made a new, clean install from scratch, only taking the config.ini and my list.txt from the old install. Now it works as it should. So maybe there was some issue with the old installation.

Sorry to have bothered you. I should have thought of that before. My bad.
