### ISSUE TITLE
Got error when downloading images by image_id

### ISSUE THREAD

**Issue by examplelewis** [Nandaka/PixivUtil2#388]
I used the following image_ids: 69572423, 69698506

and their pixiv website are:

https://www.pixiv.net/member_illust.php?mode=medium&illust_id=69572423
https://www.pixiv.net/member_illust.php?mode=medium&illust_id=69698506

then I got some error.

The content in pixivutil.log :

2018-07-25 11:28:25,375 - PixivUtil20180702 - INFO - ###############################################################
2018-07-25 11:28:25,375 - PixivUtil20180702 - INFO - Starting...
2018-07-25 11:28:25,385 - PixivUtil20180702 - INFO - Setting log level to: DEBUG
2018-07-25 11:28:25,385 - PixivUtil20180702 - INFO - No default cookie jar available, creating... 
2018-07-25 11:28:25,388 - PixivUtil20180702 - INFO - Using Proxy: 127.0.0.1:1081
2018-07-25 11:28:25,391 - PixivUtil20180702 - INFO - Using default DB Path: C:\Users\Mercury\Documents\Tool\pixivutil\db.sqlite
2018-07-25 11:28:25,395 - PixivUtil20180702 - INFO - Only process members where the last update is >= 7 days ago
2018-07-25 11:28:25,397 - PixivUtil20180702 - INFO - Using Username: 564542431hydr
2018-07-25 11:28:25,397 - PixivUtil20180702 - INFO - Trying to log in with saved cookie
2018-07-25 11:28:33,203 - PixivUtil20180702 - INFO - Login successful.
2018-07-25 11:28:33,203 - PixivUtil20180702 - INFO - Logged in using cookie
2018-07-25 11:28:33,223 - PixivUtil20180702 - INFO - My User Id: 20425387.
2018-07-25 11:28:34,816 - PixivUtil20180702 - INFO - Image id mode.
2018-07-25 11:28:36,828 - PixivUtil20180702 - DEBUG - Getting image page: 69572423
2018-07-25 11:28:39,838 - PixivUtil20180702 - DEBUG - New UI Mode
2018-07-25 11:28:40,217 - PixivUtil20180702 - ERROR - Image ID (69572423): 'extra'
2018-07-25 11:28:40,217 - PixivUtil20180702 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 627, in process_image
  File "PixivBrowserFactory.pyc", line 337, in getImagePage
  File "PixivModelWhiteCube.pyc", line 156, in __init__
  File "PixivModelWhiteCube.pyc", line 51, in __init__
  File "PixivModelWhiteCube.pyc", line 69, in ParseInfo
KeyError: 'extra'

2018-07-25 11:28:40,217 - PixivUtil20180702 - ERROR - Stack Trace: (<type 'exceptions.KeyError'>, KeyError('extra',), <traceback object at 0x03E4D4B8>)
2018-07-25 11:28:40,217 - PixivUtil20180702 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 627, in process_image
  File "PixivBrowserFactory.pyc", line 337, in getImagePage
  File "PixivModelWhiteCube.pyc", line 156, in __init__
  File "PixivModelWhiteCube.pyc", line 51, in __init__
  File "PixivModelWhiteCube.pyc", line 69, in ParseInfo
KeyError: 'extra'

**Comment by Nandaka** [comment]
try https://github.com/Nandaka/PixivUtil2/releases/tag/v20170726

**Comment by Nosgoroth** [comment]
A word of warning: you used 2017 as the year in the name of this release; it's 2018! (The zip is named correctly)

**Comment by Nandaka** [comment]
Welp 😅 , updated

**Comment by examplelewis** [comment]
Thanks, It's solved.
