### ISSUE TITLE
Crash when attempting to download from artist id (Error 31)

### ISSUE THREAD

**Issue by qazwsxdonjon** [Nandaka/PixivUtil2#396]
When I attempt to download by artist id it crashes. It seems to be a windows error, but I haven't found any solution it yet.

2018-08-05 19:19:22,664 - PixivUtil20180726 - INFO - Member id mode.
2018-08-05 19:19:48,523 - PixivUtil20180726 - INFO - Member IDs: [736905]
2018-08-05 19:19:48,523 - PixivUtil20180726 - INFO - Processing Member Id: 736905
2018-08-05 19:19:48,536 - PixivUtil20180726 - INFO - Member Url: https://www.pixiv.net/member_illust.php?id=736905&p=1
2018-08-05 19:19:49,795 - PixivUtil20180726 - ERROR - Unknown Error: [Error 31] A device attached to the system is not functioning.
Traceback (most recent call last):
  File "PixivUtil2.py", line 2074, in main
  File "PixivUtil2.py", line 1826, in main_loop
  File "PixivUtil2.py", line 1422, in menu_download_by_member_id
  File "PixivUtil2.py", line 594, in process_member
  File "PixivHelper.pyc", line 447, in print_and_log
  File "PixivHelper.pyc", line 254, in safePrint
  File "win_unicode_console\streams.pyc", line 256, in write
  File "win_unicode_console\streams.pyc", line 216, in write
  File "win_unicode_console\streams.pyc", line 165, in write
WindowsError: [Error 31] A device attached to the system is not functioning.
2018-08-05 19:19:49,796 - PixivUtil20180726 - INFO - EXIT: -1
2018-08-05 19:19:49,796 - PixivUtil20180726 - INFO - ###############################################################

**Comment by Nandaka** [comment]
Are you running from script or from executables? What is the windows version/bit?

**Comment by qazwsxdonjon** [comment]
Executable. Version 2018,07,26

**Comment by Nandaka** [comment]
Not sure why, are you changed registry code page to 65001?
Refer to https://stackoverflow.com/a/51252456 (not sure if related).

I don't have Win7 to test, but can you try on another PC?

**Comment by qazwsxdonjon** [comment]
I don't think I've changed the registry code page. I'll try to install Windows 10 on a partition tomorrow and see if the problem persists.

**Comment by qazwsxdonjon** [comment]
Seems to be a Windows problem. Everything is working fine after installing Windows 10 on a separate drive.

**Comment by Nandaka** [comment]
Yeah, I suspect because I compile the py using win10, maybe some dll is not compatible with win7 anymore.

You can always try to run from the source code in Win7 by following instructions at https://github.com/Nandaka/PixivUtil2/wiki
