### ISSUE TITLE
Japanese characters in program directory causes UnicodeDecodeError

### ISSUE THREAD

**Issue by Cak3lies** [Nandaka/PixivUtil2#426]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description
On Windows 10 x64, latest version (pixivutil20181008)

Just as the title states. I first tried running it from my downloads folder, and got this error:
>UnicodeDecodeError: 'utf8' codec can't decode byte 0x83 in position 9: invalid start byte

I attempted to reproduce it with japanese folders at root directory, and successfully did. This is the full log of a test:

>PixivDownloader2 version 20181008
https://github.com/Nandaka/PixivUtil2/releases
Donate at https://bit.ly/PixivUtilDonation
Reading C:\テスト\config.ini ...
done.
Traceback (most recent call last):
  File "PixivUtil2.py", line 2258, in <module>
  File "PixivUtil2.py", line 2120, in main
  File "PixivHelper.pyc", line 323, in toUnicode
UnicodeDecodeError: 'utf8' codec can't decode byte 0x83 in position 3: invalid start byte

The byte it can't decode is position 3, exactly where the Japanese character appears in the directory.
I've avoided this by moving the program into my dedicated portable programs folder, but it's still an issue nonetheless, and wanted to let you know.

_Off-topic, but thank you very much for your work! I've used your program since 2015, but haven't been using Pixiv recently. I've gotten back into using it again, and came here to be pleasantly suprised that you still actively update it. Amazing work!_

**Comment by Cak3lies** [comment]
I've successfully solved the issue. I actually already had Japanese locale set on my PC, but I had to check the "Use Unicode UTF-8" in order to get it to work. I've had some issues with other programs too, so hopefully this will fix that too. Thanks for the help!
