### ISSUE TITLE
Error at processing Artist Info: (<type 'exceptions.TypeError'>, TypeError("'NoneType' object has no attribute '__getitem__'",)

### ISSUE THREAD

**Issue by whinette** [Nandaka/PixivUtil2#429]
I have this problem since today. Python version: 2.7.12:
This also happens when downloading with option 8 (new stuff from followed users). But some items are downloading and I do not comprehend the logic behind (some mangas works, other not, same for single images).
```python

Input: 1
Member ids: 6544502
Start Page (default=1): 1
End Page (default=0, 0 for no limit): 1
Member IDs: [6544502]
Processing Member Id: 6544502
End Page: 1
Reading /mnt/c/PixivUtil2/config.ini ...
done.
Page  1
Member Url: https://www.pixiv.net/ajax/user/6544502/profile/all
Traceback (most recent call last):
  File "PixivUtil2.py", line 438, in process_member
    (artist, list_page) = PixivBrowserFactory.getBrowser().getMemberPage(member_id, page, bookmark, tags)
  File "/mnt/c/PixivUtil2/PixivBrowserFactory.py", line 508, in getMemberPage
    self.getMemberInfoWhitecube(member_id, artist, bookmark)
  File "/mnt/c/PixivUtil2/PixivBrowserFactory.py", line 421, in getMemberInfoWhitecube
    artist.ParseBackground(info_ajax)
  File "/mnt/c/PixivUtil2/PixivModelWhiteCube.py", line 101, in ParseBackground
    self.artistBackground = payload["body"]["background"]["url"]
TypeError: 'NoneType' object has no attribute '__getitem__'
Error at processing Artist Info: (<type 'exceptions.TypeError'>, TypeError("'NoneType' object has no attribute '__getitem__'",), <traceback object at 0x7fab46d2f710>)
Member Url: https://www.pixiv.net/ajax/user/6544502/profile/all
Traceback (most recent call last):
  File "PixivUtil2.py", line 438, in process_member
    (artist, list_page) = PixivBrowserFactory.getBrowser().getMemberPage(member_id, page, bookmark, tags)
  File "/mnt/c/PixivUtil2/PixivBrowserFactory.py", line 508, in getMemberPage
    self.getMemberInfoWhitecube(member_id, artist, bookmark)
  File "/mnt/c/PixivUtil2/PixivBrowserFactory.py", line 421, in getMemberInfoWhitecube
    artist.ParseBackground(info_ajax)
  File "/mnt/c/PixivUtil2/PixivModelWhiteCube.py", line 101, in ParseBackground
    self.artistBackground = payload["body"]["background"]["url"]
TypeError: 'NoneType' object has no attribute '__getitem__'
Error at processing Artist Info: (<type 'exceptions.TypeError'>, TypeError("'NoneType' object has no attribute '__getitem__'",), <traceback object at 0x7fab46f41b00>)
Member Url: https://www.pixiv.net/ajax/user/6544502/profile/all
Traceback (most recent call last):
  File "PixivUtil2.py", line 438, in process_member
    (artist, list_page) = PixivBrowserFactory.getBrowser().getMemberPage(member_id, page, bookmark, tags)
  File "/mnt/c/PixivUtil2/PixivBrowserFactory.py", line 508, in getMemberPage
    self.getMemberInfoWhitecube(member_id, artist, bookmark)
  File "/mnt/c/PixivUtil2/PixivBrowserFactory.py", line 421, in getMemberInfoWhitecube
    artist.ParseBackground(info_ajax)
  File "/mnt/c/PixivUtil2/PixivModelWhiteCube.py", line 101, in ParseBackground
    self.artistBackground = payload["body"]["background"]["url"]
TypeError: 'NoneType' object has no attribute '__getitem__'
Error at processing Artist Info: (<type 'exceptions.TypeError'>, TypeError("'NoneType' object has no attribute '__getitem__'",), <traceback object at 0x7fab475e44d0>)
Member Url: https://www.pixiv.net/ajax/user/6544502/profile/all
Traceback (most recent call last):
  File "PixivUtil2.py", line 438, in process_member
    (artist, list_page) = PixivBrowserFactory.getBrowser().getMemberPage(member_id, page, bookmark, tags)
  File "/mnt/c/PixivUtil2/PixivBrowserFactory.py", line 508, in getMemberPage
    self.getMemberInfoWhitecube(member_id, artist, bookmark)
  File "/mnt/c/PixivUtil2/PixivBrowserFactory.py", line 421, in getMemberInfoWhitecube
    artist.ParseBackground(info_ajax)
  File "/mnt/c/PixivUtil2/PixivModelWhiteCube.py", line 101, in ParseBackground
    self.artistBackground = payload["body"]["background"]["url"]
TypeError: 'NoneType' object has no attribute '__getitem__'
Error at processing Artist Info: (<type 'exceptions.TypeError'>, TypeError("'NoneType' object has no attribute '__getitem__'",), <traceback object at 0x7fab46d18dd0>)
Member Url: https://www.pixiv.net/ajax/user/6544502/profile/all
Traceback (most recent call last):
  File "PixivUtil2.py", line 438, in process_member
    (artist, list_page) = PixivBrowserFactory.getBrowser().getMemberPage(member_id, page, bookmark, tags)
  File "/mnt/c/PixivUtil2/PixivBrowserFactory.py", line 508, in getMemberPage
    self.getMemberInfoWhitecube(member_id, artist, bookmark)
  File "/mnt/c/PixivUtil2/PixivBrowserFactory.py", line 421, in getMemberInfoWhitecube
    artist.ParseBackground(info_ajax)
  File "/mnt/c/PixivUtil2/PixivModelWhiteCube.py", line 101, in ParseBackground
    self.artistBackground = payload["body"]["background"]["url"]
TypeError: 'NoneType' object has no attribute '__getitem__'
Error at processing Artist Info: (<type 'exceptions.TypeError'>, TypeError("'NoneType' object has no attribute '__getitem__'",), <traceback object at 0x7fab46d18d88>)
Member Url: https://www.pixiv.net/ajax/user/6544502/profile/all
Traceback (most recent call last):
  File "PixivUtil2.py", line 438, in process_member
    (artist, list_page) = PixivBrowserFactory.getBrowser().getMemberPage(member_id, page, bookmark, tags)
  File "/mnt/c/PixivUtil2/PixivBrowserFactory.py", line 508, in getMemberPage
    self.getMemberInfoWhitecube(member_id, artist, bookmark)
  File "/mnt/c/PixivUtil2/PixivBrowserFactory.py", line 421, in getMemberInfoWhitecube
    artist.ParseBackground(info_ajax)
  File "/mnt/c/PixivUtil2/PixivModelWhiteCube.py", line 101, in ParseBackground
    self.artistBackground = payload["body"]["background"]["url"]
TypeError: 'NoneType' object has no attribute '__getitem__'
Error at processing Artist Info: (<type 'exceptions.TypeError'>, TypeError("'NoneType' object has no attribute '__getitem__'",), <traceback object at 0x7fab46d187a0>)
Member Url: https://www.pixiv.net/ajax/user/6544502/profile/all
Traceback (most recent call last):
  File "PixivUtil2.py", line 438, in process_member
    (artist, list_page) = PixivBrowserFactory.getBrowser().getMemberPage(member_id, page, bookmark, tags)
  File "/mnt/c/PixivUtil2/PixivBrowserFactory.py", line 508, in getMemberPage
    self.getMemberInfoWhitecube(member_id, artist, bookmark)
  File "/mnt/c/PixivUtil2/PixivBrowserFactory.py", line 421, in getMemberInfoWhitecube
    artist.ParseBackground(info_ajax)
  File "/mnt/c/PixivUtil2/PixivModelWhiteCube.py", line 101, in ParseBackground
    self.artistBackground = payload["body"]["background"]["url"]
TypeError: 'NoneType' object has no attribute '__getitem__'
Error at processing Artist Info: (<type 'exceptions.TypeError'>, TypeError("'NoneType' object has no attribute '__getitem__'",), <traceback object at 0x7fab46d18128>)
Member Url: https://www.pixiv.net/ajax/user/6544502/profile/all
Traceback (most recent call last):
  File "PixivUtil2.py", line 438, in process_member
    (artist, list_page) = PixivBrowserFactory.getBrowser().getMemberPage(member_id, page, bookmark, tags)
  File "/mnt/c/PixivUtil2/PixivBrowserFactory.py", line 508, in getMemberPage
    self.getMemberInfoWhitecube(member_id, artist, bookmark)
  File "/mnt/c/PixivUtil2/PixivBrowserFactory.py", line 421, in getMemberInfoWhitecube
    artist.ParseBackground(info_ajax)
  File "/mnt/c/PixivUtil2/PixivModelWhiteCube.py", line 101, in ParseBackground
    self.artistBackground = payload["body"]["background"]["url"]
TypeError: 'NoneType' object has no attribute '__getitem__'
Error at processing Artist Info: (<type 'exceptions.TypeError'>, TypeError("'NoneType' object has no attribute '__getitem__'",), <traceback object at 0x7fab46d14b90>)
Member Url: https://www.pixiv.net/ajax/user/6544502/profile/all
Traceback (most recent call last):
  File "PixivUtil2.py", line 438, in process_member
    (artist, list_page) = PixivBrowserFactory.getBrowser().getMemberPage(member_id, page, bookmark, tags)
  File "/mnt/c/PixivUtil2/PixivBrowserFactory.py", line 508, in getMemberPage
    self.getMemberInfoWhitecube(member_id, artist, bookmark)
  File "/mnt/c/PixivUtil2/PixivBrowserFactory.py", line 421, in getMemberInfoWhitecube
    artist.ParseBackground(info_ajax)
  File "/mnt/c/PixivUtil2/PixivModelWhiteCube.py", line 101, in ParseBackground
    self.artistBackground = payload["body"]["background"]["url"]
TypeError: 'NoneType' object has no attribute '__getitem__'
Error at processing Artist Info: (<type 'exceptions.TypeError'>, TypeError("'NoneType' object has no attribute '__getitem__'",), <traceback object at 0x7fab46d142d8>)
```

**Comment by Nandaka** [comment]
try latest commit?

**Comment by whinette** [comment]
Perfect, ty
