### ISSUE TITLE
Question: Ugoira Requirements

### ISSUE THREAD

**Issue by jrdp18** [Nandaka/PixivUtil2#451]
### Prerequisites

* [Yes] Did you read FAQ section?
* [Yes] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Is there any requisite for creating ugoira? I set `createugoira` and `creategif` to True but I don't see any. The linked thread in the [readme](http://www.bandisoft.com/forum/viewtopic.php?f=8&t=3359) is missing.

**Comment by jrdp18** [comment]
It got it now. Tried a clean download when I changed some settings in [Debug].
If the zip is present, it won't make an ugoira. I was originally renaming the zip, clean up the database, rename back the zip, then redownload it, it recognizes that the zip is there and skips making ugoira.

**Comment by Nandaka** [comment]
ah, you can try to set `deleteZipFile = True` in the config.ini then?

**Comment by jrdp18** [comment]
I don't actually want to delete the zip file. I was just trying trigger it to create ugoira with already downloaded zips.

**Comment by Nandaka** [comment]
I see, try to set `alwaysCheckFileSize = True` with `createugoira = True`?

**Comment by jrdp18** [comment]
It just said `File exist! (Identical Size)`.
```
alwayscheckfilesize = True
writeimageinfo = True
writeugoirainfo = False
createugoira = True
deletezipfile = False
creategif = True
createapng = False
deleteugoira = False
createwebm = False
```
So I download an ugoira. Then I deleted the ugiora, gif, and metadata text file. I renamed the zip, cleaned the database, then renamed back the zip. Proceeded to download it, it recognizes the zip, also creates the metadata textfile, but skips the ugiora and gif.

**Comment by Nandaka** [comment]
hmm, maybe need to treat Existing File with Indentical Size as completed download, so it will try to recreate the ugoira/gif/webm.

https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L828

**Comment by jrdp18** [comment]
Works good!

Although if it doesn't have a record in the db (new db or merged folders), it gets this kind of error. The zip file has that error but images are fine.
```
Input: 2
Image ids: 65807318
Processing Image Id: 65807318
Member Name  : ???
Member Avatar: https://i.pximg.net/user-profile/img/2015/11/04/17/38/47/10075209
_2a3a0b839ebb1aaf28f5680566786cbb.jpg
Member Token : nayabuki
Member Background : https://i.pximg.net/c/1920x960_80_a2_g5/background/img/2018/
10/27/21/16/57/8323676_3b51226feeaebc805475f756949d33aa.jpg
Title: ????
Tags : ????, ?????, ??????????????
Date : 2017-11-08 13:24:30+00:00
Mode : ugoira_view
Image URL : https://i.pximg.net/img-zip-ugoira/img/2017/11/08/22/24/30/65807318_
ugoira1920x1080.zip
Filename  : N:\RAWS\`Pixiv\nayabuki (8323676)\65807318 - ????.zip
Start downloading... Using Referer: https://www.pixiv.net/member_illust.php?mode
=medium&illust_id=65807318
 [||||||||||||||||||||] 496.64 KiB of 496.64 KiB  Completed in 0.796s (623.92 Ki
B/s)
Traceback (most recent call last):
  File "PixivUtil2.py", line 236, in download_image
  File "PixivUtil2.py", line 340, in perform_download
  File "PixivHelper.pyc", line 647, in downloadImage
WindowsError: [Error 183] Cannot create a file when that file already exists
Error at download_image(): (<type 'exceptions.WindowsError'>, WindowsError(183,
'Cannot create a file when that file already exists'), <traceback object at 0x04
93D800>) at https://i.pximg.net/img-zip-ugoira/img/2017/11/08/22/24/30/65807318_
ugoira1920x1080.zip (9000)
Retrying [1]... 1 2 3 4
Start downloading... Using Referer: https://www.pixiv.net/member_illust.php?mode
=medium&illust_id=65807318
 [||||||||||||||||||||] 496.64 KiB of 496.64 KiB  Completed in 0.674s (736.85 Ki
B/s)
Traceback (most recent call last):
  File "PixivUtil2.py", line 236, in download_image
  File "PixivUtil2.py", line 340, in perform_download
  File "PixivHelper.pyc", line 647, in downloadImage
WindowsError: [Error 183] Cannot create a file when that file already exists
Error at download_image(): (<type 'exceptions.WindowsError'>, WindowsError(183,
'Cannot create a file when that file already exists'), <traceback object at 0x04
941850>) at https://i.pximg.net/img-zip-ugoira/img/2017/11/08/22/24/30/65807318_
ugoira1920x1080.zip (9000)
Retrying [2]... 1 2 3 4
Start downloading... Using Referer: https://www.pixiv.net/member_illust.php?mode
=medium&illust_id=65807318
 [||||||||||||||||||||] 496.64 KiB of 496.64 KiB  Completed in 0.864s (574.81 Ki
B/s)
Traceback (most recent call last):
  File "PixivUtil2.py", line 236, in download_image
  File "PixivUtil2.py", line 340, in perform_download
  File "PixivHelper.pyc", line 647, in downloadImage
WindowsError: [Error 183] Cannot create a file when that file already exists
Error at download_image(): (<type 'exceptions.WindowsError'>, WindowsError(183,
'Cannot create a file when that file already exists'), <traceback object at 0x04
952198>) at https://i.pximg.net/img-zip-ugoira/img/2017/11/08/22/24/30/65807318_
ugoira1920x1080.zip (9000)
Retrying [3]... 1 2 3 4
Start downloading... Using Referer: https://www.pixiv.net/member_illust.php?mode
=medium&illust_id=65807318
 [||||||||||||||||||||] 496.64 KiB of 496.64 KiB  Completed in 0.956s (519.49 Ki
B/s)
Traceback (most recent call last):
  File "PixivUtil2.py", line 236, in download_image
  File "PixivUtil2.py", line 340, in perform_download
  File "PixivHelper.pyc", line 647, in downloadImage
WindowsError: [Error 183] Cannot create a file when that file already exists
Error at download_image(): (<type 'exceptions.WindowsError'>, WindowsError(183,
'Cannot create a file when that file already exists'), <traceback object at 0x04
910B98>) at https://i.pximg.net/img-zip-ugoira/img/2017/11/08/22/24/30/65807318_
ugoira1920x1080.zip (9000)
Traceback (most recent call last):
  File "PixivUtil2.py", line 794, in process_image
  File "PixivUtil2.py", line 236, in download_image
  File "PixivUtil2.py", line 340, in perform_download
  File "PixivHelper.pyc", line 647, in downloadImage
WindowsError: [Error 183] Cannot create a file when that file already exists
Error at process_image(): 65807318
Exception: (<type 'exceptions.WindowsError'>, WindowsError(183, 'Cannot create a
 file when that file already exists'), <traceback object at 0x04912418>)
Dumping html to: Error medium page for image 65807318.html
Traceback (most recent call last):
  File "PixivUtil2.py", line 2268, in main
  File "PixivUtil2.py", line 2003, in main_loop
  File "PixivUtil2.py", line 1507, in menu_download_by_image_id
  File "PixivUtil2.py", line 794, in process_image
  File "PixivUtil2.py", line 236, in download_image
  File "PixivUtil2.py", line 340, in perform_download
  File "PixivHelper.pyc", line 647, in downloadImage
WindowsError: [Error 183] Cannot create a file when that file already exists
press enter to exit.
```

**Comment by jrdp18** [comment]
I'll wait for an exe

**Comment by jrdp18** [comment]
@bloodypala Are you talking about the zip file? Use `useblacklisttags` with `うごイラ`.

**Comment by bloodypala** [comment]
@jrdp18 i have made a blacklist_tags.txt  file and added the line うごイラ to it then saved it as UTF-8 but still nothing happen it say file doesnt exist or no permission to read blacklist_tags.txt ( this happens when i change the config for useblacklisttags from = false to = true).

**Comment by itsmenmd** [comment]
> @bloodypala Are you talking about the zip file? Use `useblacklisttags` with `うごイラ`.
im con fig like this
`[Ugoira]
writeugoirainfo = False
createugoira = False
deletezipfile = True
creategif = False
createapng = False
deleteugoira = True
createwebm = False
createwebp = False`
i try with useblacklisttags but it still download zip file how i can ignore it and skip ugoira file, so i can easy to download ugoira later

**Comment by itsmenmd** [comment]
> ah, you can try to set `deleteZipFile = True` in the config.ini then?

i try set it but it still no delete and it be write in database.
