### ISSUE TITLE
Removed IDs - "Error at processing Artist Info"

### ISSUE THREAD

**Issue by reyaz006** [Nandaka/PixivUtil2#466]
```
2019-01-31 12:49:58,000 - PixivUtil20190120 - INFO - Member Url: https://www.pixiv.net/ajax/user/3567511/profile/all
2019-01-31 12:49:59,506 - PixivUtil20190120 - ERROR - Error at processing Artist Info: (<class 'mechanize._response.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib2.HTTPError instance) at 0x55a34c8 whose wrapped object = <closeable_response at 0x55a8d28 whose fp = <response_seek_wrapper at 0x55a4198 whose wrapped object = <closeable_response at 0x55a4af8 whose fp = <socket._fileobject object at 0x055A0EB0>>>>>, <traceback object at 0x055A4B48>)
2019-01-31 12:49:59,506 - PixivUtil20190120 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 413, in process_member
  File "PixivBrowserFactory.pyc", line 523, in getMemberPage
  File "mechanize\_mechanize.pyc", line 254, in open
  File "mechanize\_mechanize.pyc", line 310, in _mech_open
httperror_seek_wrapper: HTTP Error 404: Not Found
```

Seems like something got changed in server data for removed artists.

**Comment by reyaz006** [comment]
Can we have a binary release with current fixes some day soon? I just can't proceed without deleting every single removed artist from my long list otherwise.
