### ISSUE TITLE
NameError: global name 'jsPost' is not defined

### ISSUE THREAD

**Issue by HAEA2** [Nandaka/PixivUtil2#475]
### Prerequisites

* [ X] Did you read FAQ section?
* [ X] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description
Program prints

Traceback (most recent call last):
  File "PixivUtil2.py", line 2277, in main
  File "PixivUtil2.py", line 2047, in main_loop
  File "PixivUtil2.py", line 1932, in menu_fanbox_download_by_artist_id
  File "PixivUtil2.py", line 1809, in processFanboxArtist
  File "PixivBrowserFactory.pyc", line 676, in fanboxGetPostsFromArtist
  File "PixivModelFanbox.pyc", line 50, in __init__
  File "PixivModelFanbox.pyc", line 66, in parsePosts
  File "PixivModelFanbox.pyc", line 114, in __init__
  File "PixivModelFanbox.pyc", line 189, in parseBody
  File "PixivModelFanbox.pyc", line 198, in getEmbedData
NameError: global name 'jsPost' is not defined

On fanbox pages that have a post using embedMap (the program simply said unsupported before support was added)

**Comment by Nandaka** [comment]
can you give me the sample json page? Currently only twitter is supported (because I don't have enough sample for the fanbox embed type).
https://www.pixiv.net/ajax/fanbox/creator?userId=32244225 << replace with the creator id.
https://www.pixiv.net/ajax/fanbox/post?postId=296073 << replace with the post id.

**Comment by HAEA2** [comment]
[fanbox.zip](https://github.com/Nandaka/PixivUtil2/files/2978940/fanbox.zip)
