### ISSUE TITLE
A bug when downloading fanbox content.

### ISSUE THREAD

**Issue by marierose147** [Nandaka/PixivUtil2#487]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Unable to download fanbox content. The program is wrong and quits automatically.

### Steps to Reproduce

Open the program and type f1 to download the fanbox content.

**Expected behavior:** Run normally and download.

**Actual behavior:** Program error

> 2019-04-19 21:55:27,851 - PixivUtil20190416 - INFO - ###############################################################
2019-04-19 21:55:27,851 - PixivUtil20190416 - INFO - Starting...
2019-04-19 21:55:27,852 - PixivUtil20190416 - INFO - Setting log level to: DEBUG
2019-04-19 21:55:27,852 - PixivUtil20190416 - INFO - No default cookie jar available, creating... 
2019-04-19 21:55:27,852 - PixivUtil20190416 - INFO - Using default factory (mechanize 3.x ?)
2019-04-19 21:55:27,854 - PixivUtil20190416 - INFO - Using Proxy: scoks5://127.0.0.1:1080
2019-04-19 21:55:33,174 - PixivUtil20190416 - INFO - Using default DB Path: E:\BaiduYunDownload\pixivutil20190416\db.sqlite
2019-04-19 21:55:33,174 - PixivUtil20190416 - INFO - Only process members where the last update is >= 7 days ago
2019-04-19 21:55:33,174 - PixivUtil20190416 - INFO - Using Username: ***
2019-04-19 21:55:33,176 - PixivUtil20190416 - INFO - Trying to log in with saved cookie
2019-04-19 21:55:37,565 - PixivUtil20190416 - INFO - Login successful.
2019-04-19 21:55:37,565 - PixivUtil20190416 - INFO - Logged in using cookie
2019-04-19 21:55:37,581 - PixivUtil20190416 - INFO - My User Id: ***.
2019-04-19 21:56:07,378 - PixivUtil20190416 - INFO - Download FANBOX by Artist ID mode.
2019-04-19 21:56:08,552 - PixivUtil20190416 - ERROR - Unknown Error: invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "PixivUtil2.py", line 2285, in main
  File "PixivUtil2.py", line 2055, in main_loop
  File "PixivUtil2.py", line 1938, in menu_fanbox_download_by_artist_id
ValueError: invalid literal for int() with base 10: ''
2019-04-19 21:56:15,914 - PixivUtil20190416 - INFO - EXIT: -1
2019-04-19 21:56:15,914 - PixivUtil20190416 - INFO - ###############################################################

### Versions

This problem exists from the 20190416 version to the 20190429-beta4 version.

**Comment by NHOrus** [comment]
you may want to put some number in how many pages you want to download
