### ISSUE TITLE
Cannot log in with cookie. - /mypage.php 301 redirects to /

### ISSUE THREAD

**Issue by daniels1989** [Nandaka/PixivUtil2#496]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

When PixivUtil tries to login using a cookie it breaks because pixiv.net/mypage.php now 301 redirects to pixiv.net. Removing the cookie from the config file works, but will break the program again on next use.

### Latest trace

2019-06-07 17:54:05,203 - PixivUtil20190606 - INFO - Trying to log in with saved cookie
2019-06-07 17:54:15,112 - PixivUtil20190606 - ERROR - Error at doLogin(): (<class 'mechanize._response.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib2.HTTPError instance) at 0x482af80 whose wrapped object = <closeable_response at 0x48a3210 whose fp = <response_seek_wrapper at 0x489cc88 whose wrapped object = <closeable_response at 0x489ca80 whose fp = <socket._fileobject object at 0x0488BD70>>>>>, <traceback object at 0x04830210>)
2019-06-07 17:54:15,112 - PixivUtil20190606 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 2102, in doLogin
  File "PixivBrowserFactory.pyc", line 234, in loginUsingCookie
  File "PixivBrowserFactory.pyc", line 145, in open_with_retry
  File "mechanize\_mechanize.pyc", line 253, in open
  File "mechanize\_mechanize.pyc", line 309, in _mech_open
httperror_seek_wrapper: HTTP Error 301: The HTTP server returned a redirect error that would lead to an infinite loop.
The last 30x error message was:
Moved Permanently

2019-06-07 17:54:15,114 - PixivUtil20190606 - ERROR - Cannot Login!
2019-06-07 17:54:15,114 - PixivUtil20190606 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 2299, in main
  File "PixivUtil2.py", line 2109, in doLogin
PixivException: 1005 Cannot Login!, hasDumpPage=N

**Comment by Nandaka** [comment]
Weird, works on my side (both script and compiled version). IT doesn't show redirect error.

```
2019-06-08 00:23:09,193 - PixivUtil20190606 - INFO - Starting with argument: [D:\...\PixivUtil2.exe].
2019-06-08 00:23:09,194 - PixivUtil20190606 - INFO - Setting log level to: DEBUG
2019-06-08 00:23:09,194 - PixivUtil20190606 - INFO - No default cookie jar available, creating... 
2019-06-08 00:23:09,194 - PixivUtil20190606 - INFO - Using default factory (mechanize 3.x ?)
2019-06-08 00:23:09,690 - PixivUtil20190606 - INFO - Using default DB Path: D:\...\db.sqlite
2019-06-08 00:23:09,691 - PixivUtil20190606 - INFO - Using local timezone: +08:00
2019-06-08 00:23:09,693 - PixivUtil20190606 - INFO - Using Username: ...
2019-06-08 00:23:09,693 - PixivUtil20190606 - INFO - Trying to log in with saved cookie
2019-06-08 00:23:11,885 - PixivUtil20190606 - INFO - Login successful.
2019-06-08 00:23:11,885 - PixivUtil20190606 - INFO - Logged in using cookie
```

**Comment by daniels1989** [comment]
Huh, very weird. Perhaps they briefly f'ed something up, as the trace does mention getting stuck in a 301 loop. Everything seems to be working fine again now, consider the solved.
