### ISSUE TITLE
works_dat_fmt

### ISSUE THREAD

**Issue by Qwerty-Space** [Nandaka/PixivUtil2#497]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

It crashes when reading the date

### Steps to Reproduce

1. [First Step]
`filenameformat = %artist% (%member_id%)\%works_date_fmt{%Y-%m-%d}% %title%\%urlFilename%`

2. [Second Step]
Download artist

**Expected behavior:** [What you expected to happen]
For it to download

**Actual behavior:** [What actually happened]
```
Member ids: 7160763
Start Page (default=1):
End Page (default=0, 0 for no limit):
Member IDs: [7160763]
Processing Member Id: 7160763
Reading E:\Programs\PixivUtil2\config.ini ...
done.
Page  1
Member Url: https://www.pixiv.net/ajax/user/7160763/profile/all
Member Name  : 天通
Member Avatar: https://i.pximg.net/user-profile/img/2018/04/28/14/56/56/14151308_15673d5e41f91c2dbcebd7e42e71ba15.jpg
Member Token : masaki1117
Member Background : no_background
Processing images from 1 to 80 of 80
Traceback (most recent call last):
  File "PixivUtil2.py", line 455, in process_member
  File "PixivHelper.pyc", line 359, in createAvatarFilename
  File "PixivHelper.pyc", line 169, in makeFilename
ValueError: year=1 is before 1900; the datetime strftime() methods require year >= 1900
Error at process_member(): (<type 'exceptions.ValueError'>, ValueError('year=1 is before 1900; the datetime strftime() methods require year >= 1900',), <traceback object at 0x03EC8A58>)
Dumping html to: Error page for member 7160763 at page 1.html
Traceback (most recent call last):
  File "PixivUtil2.py", line 2302, in main
  File "PixivUtil2.py", line 2024, in main_loop
  File "PixivUtil2.py", line 1451, in menu_download_by_member_id
  File "PixivUtil2.py", line 455, in process_member
  File "PixivHelper.pyc", line 359, in createAvatarFilename
  File "PixivHelper.pyc", line 169, in makeFilename
ValueError: year=1 is before 1900; the datetime strftime() methods require year >= 1900
```

### Versions
20190606
You can get this information from executing `PixivUtil2.py --help`.

**Comment by Qwerty-Space** [comment]
Ah, I think the problem was that the `avatarnameformat` inherits the `filenameformat`.  Added a custom avatarnameformat, and it seems to be working
