### ISSUE TITLE
Fanbox failure

### ISSUE THREAD

**Issue by NHOrus** [Nandaka/PixivUtil2#503]
### Prerequisites

* [*] Did you read FAQ section?
* [*] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Fanbox download fails with
```
2019-06-24 07:57:15,194 - PixivUtil20190617-beta1 - INFO - Using Referer: https://www.pixiv.net/fanbox/creator/226267/post/434108
2019-06-24 07:57:16,421 - PixivUtil20190617-beta1 - ERROR - [download_image()] HTTP Error: HTTP Error 500: Internal Server Error at https://fanbox.pixiv.net/images/post/434108/gPkICV0QOlaNuCgqc5j7BU0R.jpeg
2019-06-24 07:57:16,421 - PixivUtil20190617-beta1 - ERROR - Traceback (most recent call last):
  File "E:\conf\pixiv\pixivutil\PixivUtil2.py", line 148, in download_image
    file_size = get_remote_filesize(url, referer)
  File "E:\conf\pixiv\pixivutil\PixivUtil2.py", line 120, in get_remote_filesize
    res = __br__.open_novisit(req)
  File "C:\Users\nho\AppData\Roaming\Python\Python27\site-packages\mechanize\_mechanize.py", line 238, in open_novisit
    url_or_request, data, visit=False, timeout=timeout)
  File "C:\Users\nho\AppData\Roaming\Python\Python27\site-packages\mechanize\_mechanize.py", line 309, in _mech_open
    raise response
httperror_seek_wrapper: HTTP Error 500: Internal Server Error

2019-06-24 07:57:16,426 - PixivUtil20190617-beta1 - ERROR - Error at download_image(): (<class 'mechanize._response.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib2.HTTPError instance) at 0xac91dc8L whose wrapped object = <closeable_response at 0xacaa3c8L whose fp = <response_seek_wrapper at 0xacaa6c8L whose wrapped object = <closeable_response at 0xacaa708L whose fp = <socket._fileobject object at 0x000000000ABC6F48>>>>>, <traceback object at 0x000000000ACAA408>) at https://fanbox.pixiv.net/images/post/434108/gPkICV0QOlaNuCgqc5j7BU0R.jpeg (9002)
2019-06-24 07:57:16,426 - PixivUtil20190617-beta1 - ERROR - Traceback (most recent call last):
  File "E:\conf\pixiv\pixivutil\PixivUtil2.py", line 148, in download_image
    file_size = get_remote_filesize(url, referer)
  File "E:\conf\pixiv\pixivutil\PixivUtil2.py", line 120, in get_remote_filesize
    res = __br__.open_novisit(req)
  File "C:\Users\nho\AppData\Roaming\Python\Python27\site-packages\mechanize\_mechanize.py", line 238, in open_novisit
    url_or_request, data, visit=False, timeout=timeout)
  File "C:\Users\nho\AppData\Roaming\Python\Python27\site-packages\mechanize\_mechanize.py", line 309, in _mech_open
    raise response
httperror_seek_wrapper: HTTP Error 500: Internal Server Error

2019-06-24 07:57:30,427 - PixivUtil20190617-beta1 - INFO - Using Referer: https://www.pixiv.net/fanbox/creator/226267/post/434108
2019-06-24 07:57:31,677 - PixivUtil20190617-beta1 - ERROR - [download_image()] HTTP Error: HTTP Error 500: Internal Server Error at https://fanbox.pixiv.net/images/post/434108/gPkICV0QOlaNuCgqc5j7BU0R.jpeg
2019-06-24 07:57:31,677 - PixivUtil20190617-beta1 - ERROR - Traceback (most recent call last):
  File "E:\conf\pixiv\pixivutil\PixivUtil2.py", line 148, in download_image
    file_size = get_remote_filesize(url, referer)
  File "E:\conf\pixiv\pixivutil\PixivUtil2.py", line 120, in get_remote_filesize
    res = __br__.open_novisit(req)
  File "C:\Users\nho\AppData\Roaming\Python\Python27\site-packages\mechanize\_mechanize.py", line 238, in open_novisit
    url_or_request, data, visit=False, timeout=timeout)
  File "C:\Users\nho\AppData\Roaming\Python\Python27\site-packages\mechanize\_mechanize.py", line 309, in _mech_open
    raise response
httperror_seek_wrapper: HTTP Error 500: Internal Server Error

2019-06-24 07:57:31,680 - PixivUtil20190617-beta1 - ERROR - Error at download_image(): (<class 'mechanize._response.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib2.HTTPError instance) at 0xac91b28L whose wrapped object = <closeable_response at 0xacaa248L whose fp = <response_seek_wrapper at 0xacaaf48L whose wrapped object = <closeable_response at 0xacaa508L whose fp = <socket._fileobject object at 0x000000000C5A67C8>>>>>, <traceback object at 0x000000000ACAA1C8>) at https://fanbox.pixiv.net/images/post/434108/gPkICV0QOlaNuCgqc5j7BU0R.jpeg (9002)
2019-06-24 07:57:31,681 - PixivUtil20190617-beta1 - ERROR - Traceback (most recent call last):
  File "E:\conf\pixiv\pixivutil\PixivUtil2.py", line 148, in download_image
    file_size = get_remote_filesize(url, referer)
  File "E:\conf\pixiv\pixivutil\PixivUtil2.py", line 120, in get_remote_filesize
    res = __br__.open_novisit(req)
  File "C:\Users\nho\AppData\Roaming\Python\Python27\site-packages\mechanize\_mechanize.py", line 238, in open_novisit
    url_or_request, data, visit=False, timeout=timeout)
  File "C:\Users\nho\AppData\Roaming\Python\Python27\site-packages\mechanize\_mechanize.py", line 309, in _mech_open
    raise response
httperror_seek_wrapper: HTTP Error 500: Internal Server Error

2019-06-24 07:57:31,684 - PixivUtil20190617-beta1 - ERROR - Unknown Error: HTTP Error 500: Internal Server Error
Traceback (most recent call last):
  File "E:\conf\pixiv\pixivutil\PixivUtil2.py", line 2303, in main
    np_is_valid, op_is_valid, selection = main_loop(ewd, op_is_valid, selection, np_is_valid, args)
  File "E:\conf\pixiv\pixivutil\PixivUtil2.py", line 2060, in main_loop
    menu_fanbox_download_supported_artist(op_is_valid, args)
  File "E:\conf\pixiv\pixivutil\PixivUtil2.py", line 1810, in menu_fanbox_download_supported_artist
    processFanboxArtist(artist_id, end_page)
  File "E:\conf\pixiv\pixivutil\PixivUtil2.py", line 1859, in processFanboxArtist
    processFanboxImages(post, result_artist)
  File "E:\conf\pixiv\pixivutil\PixivUtil2.py", line 1912, in processFanboxImages
    __config__.backupOldFile)
  File "E:\conf\pixiv\pixivutil\PixivUtil2.py", line 148, in download_image
    file_size = get_remote_filesize(url, referer)
  File "E:\conf\pixiv\pixivutil\PixivUtil2.py", line 120, in get_remote_filesize
    res = __br__.open_novisit(req)
  File "C:\Users\nho\AppData\Roaming\Python\Python27\site-packages\mechanize\_mechanize.py", line 238, in open_novisit
    url_or_request, data, visit=False, timeout=timeout)
  File "C:\Users\nho\AppData\Roaming\Python\Python27\site-packages\mechanize\_mechanize.py", line 309, in _mech_open
    raise response
httperror_seek_wrapper: HTTP Error 500: Internal Server Error
```

Attempt to download image in browser results in text "failed to thumbnailing" instead of image.
Attempt to try manually view image from the page resulted in same text.

### Steps to Reproduce

Start fanbox download with f1

**Expected behavior:** 
Download completed successfully, skipping erroneous image.

**Actual behavior:**
PixivUtil2 panics and stops.

### Versions

20190617-beta1

**Comment by NHOrus** [comment]
Any updates or ability to skip the bad fanbox response?

**Comment by NHOrus** [comment]
```
Checking local filename... Getting remote filesize...
Using Referer: https://www.pixiv.net/fanbox/creator/226267/post/434108
[download_image()] HTTP Error: HTTP Error 500: Internal Server Error at https://fanbox.pixiv.net/images/post/434108/9tS1Gidk7sThIVGmRcNWPiwy.jpeg
Traceback (most recent call last):
  File "PixivUtil2.py", line 148, in download_image
    file_size = get_remote_filesize(url, referer)
  File "PixivUtil2.py", line 120, in get_remote_filesize
    res = __br__.open_novisit(req)
  File "/home/nho/.local/lib/python2.7/site-packages/mechanize/_mechanize.py", line 238, in open_novisit
    url_or_request, data, visit=False, timeout=timeout)
  File "/home/nho/.local/lib/python2.7/site-packages/mechanize/_mechanize.py", line 309, in _mech_open
    raise response
httperror_seek_wrapper: HTTP Error 500: Internal Server Error
Error at download_image(): (<class 'mechanize._response.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib2.HTTPError instance) at 0x7ff5a575f738 whose wrapped object = <closeable_response at 0x7ff5a5757cb0 whose fp = <response_seek_wrapper at 0x7ff5a5757ab8 whose wrapped object = <closeable_response at 0x7ff5a5757a70 whose fp = <socket._fileobject object at 0x7ff5a578f450>>>>>, <traceback object at 0x7ff5a5757bd8>) at https://fanbox.pixiv.net/images/post/434108/9tS1Gidk7sThIVGmRcNWPiwy.jpeg (9002)
Traceback (most recent call last):
  File "PixivUtil2.py", line 2303, in main
    np_is_valid, op_is_valid, selection = main_loop(ewd, op_is_valid, selection, np_is_valid, args)
  File "PixivUtil2.py", line 2060, in main_loop
    menu_fanbox_download_supported_artist(op_is_valid, args)
  File "PixivUtil2.py", line 1810, in menu_fanbox_download_supported_artist
    processFanboxArtist(artist_id, end_page)
  File "PixivUtil2.py", line 1859, in processFanboxArtist
    processFanboxImages(post, result_artist)
  File "PixivUtil2.py", line 1912, in processFanboxImages
    __config__.backupOldFile)
  File "PixivUtil2.py", line 148, in download_image
    file_size = get_remote_filesize(url, referer)
  File "PixivUtil2.py", line 120, in get_remote_filesize
    res = __br__.open_novisit(req)
  File "/home/nho/.local/lib/python2.7/site-packages/mechanize/_mechanize.py", line 238, in open_novisit
    url_or_request, data, visit=False, timeout=timeout)
  File "/home/nho/.local/lib/python2.7/site-packages/mechanize/_mechanize.py", line 309, in _mech_open
    raise response
httperror_seek_wrapper: HTTP Error 500: Internal Server Error
```

**Comment by NHOrus** [comment]
Sadly, this is little help. There's not just image size missing, but image itself.

```
Local file exists: E:\conf\pixiv\226267\434108_p3_c53oxaJpfcD5DjhyZQxrdogZ - シャーリー抱き枕ほしい。.jpeg
2019-07-12 22:13:44,319 - PixivUtil20190712 - INFO - Using Referer: https://www.pixiv.net/fanbox/creator/226267/post/434108
2019-07-12 22:13:45,838 - PixivUtil20190712 - INFO - 	No file size information!
2019-07-12 22:13:45,839 - PixivUtil20190712 - INFO - Using Referer: https://www.pixiv.net/fanbox/creator/226267/post/434108
2019-07-12 22:13:47,108 - PixivUtil20190712 - ERROR - [download_image()] HTTP Error: HTTP Error 500: Internal Server Error at https://fanbox.pixiv.net/images/post/434108/9tS1Gidk7sThIVGmRcNWPiwy.jpeg
2019-07-12 22:13:47,111 - PixivUtil20190712 - ERROR - Traceback (most recent call last):
  File "E:\conf\pixiv\pixivutil\PixivUtil2.py", line 214, in download_image
    (downloadedSize, filename) = perform_download(url, file_size, filename, overwrite, referer)
  File "E:\conf\pixiv\pixivutil\PixivUtil2.py", line 315, in perform_download
    res = __br__.open_novisit(req)
  File "C:\Users\nho\AppData\Roaming\Python\Python27\site-packages\mechanize\_mechanize.py", line 238, in open_novisit
    url_or_request, data, visit=False, timeout=timeout)
  File "C:\Users\nho\AppData\Roaming\Python\Python27\site-packages\mechanize\_mechanize.py", line 309, in _mech_open
    raise response
httperror_seek_wrapper: HTTP Error 500: Internal Server Error

2019-07-12 22:13:47,114 - PixivUtil20190712 - ERROR - Error at download_image(): (<class 'mechanize._response.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib2.HTTPError instance) at 0xc836ee8L whose wrapped object = <closeable_response at 0xc881f48L whose fp = <response_seek_wrapper at 0xc881408L whose wrapped object = <closeable_response at 0xc881ac8L whose fp = <socket._fileobject object at 0x000000000C848390>>>>>, <traceback object at 0x000000000C881288>) at https://fanbox.pixiv.net/images/post/434108/9tS1Gidk7sThIVGmRcNWPiwy.jpeg (9002)
2019-07-12 22:13:47,114 - PixivUtil20190712 - ERROR - Traceback (most recent call last):
  File "E:\conf\pixiv\pixivutil\PixivUtil2.py", line 214, in download_image
    (downloadedSize, filename) = perform_download(url, file_size, filename, overwrite, referer)
  File "E:\conf\pixiv\pixivutil\PixivUtil2.py", line 315, in perform_download
    res = __br__.open_novisit(req)
  File "C:\Users\nho\AppData\Roaming\Python\Python27\site-packages\mechanize\_mechanize.py", line 238, in open_novisit
    url_or_request, data, visit=False, timeout=timeout)
  File "C:\Users\nho\AppData\Roaming\Python\Python27\site-packages\mechanize\_mechanize.py", line 309, in _mech_open
    raise response
httperror_seek_wrapper: HTTP Error 500: Internal Server Error

2019-07-12 22:14:01,115 - PixivUtil20190712 - INFO - Using Referer: https://www.pixiv.net/fanbox/creator/226267/post/434108
2019-07-12 22:14:02,377 - PixivUtil20190712 - INFO - 	No file size information!
2019-07-12 22:14:02,378 - PixivUtil20190712 - INFO - Using Referer: https://www.pixiv.net/fanbox/creator/226267/post/434108
2019-07-12 22:14:03,605 - PixivUtil20190712 - ERROR - [download_image()] HTTP Error: HTTP Error 500: Internal Server Error at https://fanbox.pixiv.net/images/post/434108/9tS1Gidk7sThIVGmRcNWPiwy.jpeg
2019-07-12 22:14:03,605 - PixivUtil20190712 - ERROR - Traceback (most recent call last):
  File "E:\conf\pixiv\pixivutil\PixivUtil2.py", line 214, in download_image
    (downloadedSize, filename) = perform_download(url, file_size, filename, overwrite, referer)
  File "E:\conf\pixiv\pixivutil\PixivUtil2.py", line 315, in perform_download
    res = __br__.open_novisit(req)
  File "C:\Users\nho\AppData\Roaming\Python\Python27\site-packages\mechanize\_mechanize.py", line 238, in open_novisit
    url_or_request, data, visit=False, timeout=timeout)
  File "C:\Users\nho\AppData\Roaming\Python\Python27\site-packages\mechanize\_mechanize.py", line 309, in _mech_open
    raise response
httperror_seek_wrapper: HTTP Error 500: Internal Server Error

2019-07-12 22:14:03,608 - PixivUtil20190712 - ERROR - Error at download_image(): (<class 'mechanize._response.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib2.HTTPError instance) at 0xcda8528L whose wrapped object = <closeable_response at 0xcd947c8L whose fp = <response_seek_wrapper at 0xcd94608L whose wrapped object = <closeable_response at 0xcd945c8L whose fp = <socket._fileobject object at 0x000000000CD91930>>>>>, <traceback object at 0x000000000CD94708>) at https://fanbox.pixiv.net/images/post/434108/9tS1Gidk7sThIVGmRcNWPiwy.jpeg (9002)
2019-07-12 22:14:03,608 - PixivUtil20190712 - ERROR - Traceback (most recent call last):
  File "E:\conf\pixiv\pixivutil\PixivUtil2.py", line 214, in download_image
    (downloadedSize, filename) = perform_download(url, file_size, filename, overwrite, referer)
  File "E:\conf\pixiv\pixivutil\PixivUtil2.py", line 315, in perform_download
    res = __br__.open_novisit(req)
  File "C:\Users\nho\AppData\Roaming\Python\Python27\site-packages\mechanize\_mechanize.py", line 238, in open_novisit
    url_or_request, data, visit=False, timeout=timeout)
  File "C:\Users\nho\AppData\Roaming\Python\Python27\site-packages\mechanize\_mechanize.py", line 309, in _mech_open
    raise response
httperror_seek_wrapper: HTTP Error 500: Internal Server Error

2019-07-12 22:14:17,611 - PixivUtil20190712 - INFO - Using Referer: https://www.pixiv.net/fanbox/creator/226267/post/434108
2019-07-12 22:14:18,855 - PixivUtil20190712 - INFO - 	No file size information!
2019-07-12 22:14:18,858 - PixivUtil20190712 - INFO - Using Referer: https://www.pixiv.net/fanbox/creator/226267/post/434108
2019-07-12 22:14:20,081 - PixivUtil20190712 - ERROR - [download_image()] HTTP Error: HTTP Error 500: Internal Server Error at https://fanbox.pixiv.net/images/post/434108/9tS1Gidk7sThIVGmRcNWPiwy.jpeg
2019-07-12 22:14:20,081 - PixivUtil20190712 - ERROR - Traceback (most recent call last):
  File "E:\conf\pixiv\pixivutil\PixivUtil2.py", line 214, in download_image
    (downloadedSize, filename) = perform_download(url, file_size, filename, overwrite, referer)
  File "E:\conf\pixiv\pixivutil\PixivUtil2.py", line 315, in perform_download
    res = __br__.open_novisit(req)
  File "C:\Users\nho\AppData\Roaming\Python\Python27\site-packages\mechanize\_mechanize.py", line 238, in open_novisit
    url_or_request, data, visit=False, timeout=timeout)
  File "C:\Users\nho\AppData\Roaming\Python\Python27\site-packages\mechanize\_mechanize.py", line 309, in _mech_open
    raise response
httperror_seek_wrapper: HTTP Error 500: Internal Server Error

2019-07-12 22:14:20,085 - PixivUtil20190712 - ERROR - Error at download_image(): (<class 'mechanize._response.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib2.HTTPError instance) at 0xc8365e8L whose wrapped object = <closeable_response at 0xc937488L whose fp = <response_seek_wrapper at 0xc9372c8L whose wrapped object = <closeable_response at 0xc937288L whose fp = <socket._fileobject object at 0x000000000C848390>>>>>, <traceback object at 0x000000000C9373C8>) at https://fanbox.pixiv.net/images/post/434108/9tS1Gidk7sThIVGmRcNWPiwy.jpeg (9002)
2019-07-12 22:14:20,085 - PixivUtil20190712 - ERROR - Traceback (most recent call last):
  File "E:\conf\pixiv\pixivutil\PixivUtil2.py", line 214, in download_image
    (downloadedSize, filename) = perform_download(url, file_size, filename, overwrite, referer)
  File "E:\conf\pixiv\pixivutil\PixivUtil2.py", line 315, in perform_download
    res = __br__.open_novisit(req)
  File "C:\Users\nho\AppData\Roaming\Python\Python27\site-packages\mechanize\_mechanize.py", line 238, in open_novisit
    url_or_request, data, visit=False, timeout=timeout)
  File "C:\Users\nho\AppData\Roaming\Python\Python27\site-packages\mechanize\_mechanize.py", line 309, in _mech_open
    raise response
httperror_seek_wrapper: HTTP Error 500: Internal Server Error

2019-07-12 22:14:34,086 - PixivUtil20190712 - INFO - Using Referer: https://www.pixiv.net/fanbox/creator/226267/post/434108
2019-07-12 22:14:35,348 - PixivUtil20190712 - INFO - 	No file size information!
2019-07-12 22:14:35,349 - PixivUtil20190712 - INFO - Using Referer: https://www.pixiv.net/fanbox/creator/226267/post/434108
2019-07-12 22:14:36,598 - PixivUtil20190712 - ERROR - [download_image()] HTTP Error: HTTP Error 500: Internal Server Error at https://fanbox.pixiv.net/images/post/434108/9tS1Gidk7sThIVGmRcNWPiwy.jpeg
2019-07-12 22:14:36,598 - PixivUtil20190712 - ERROR - Traceback (most recent call last):
  File "E:\conf\pixiv\pixivutil\PixivUtil2.py", line 214, in download_image
    (downloadedSize, filename) = perform_download(url, file_size, filename, overwrite, referer)
  File "E:\conf\pixiv\pixivutil\PixivUtil2.py", line 315, in perform_download
    res = __br__.open_novisit(req)
  File "C:\Users\nho\AppData\Roaming\Python\Python27\site-packages\mechanize\_mechanize.py", line 238, in open_novisit
    url_or_request, data, visit=False, timeout=timeout)
  File "C:\Users\nho\AppData\Roaming\Python\Python27\site-packages\mechanize\_mechanize.py", line 309, in _mech_open
    raise response
httperror_seek_wrapper: HTTP Error 500: Internal Server Error

2019-07-12 22:14:36,601 - PixivUtil20190712 - ERROR - Error at download_image(): (<class 'mechanize._response.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib2.HTTPError instance) at 0xc836768L whose wrapped object = <closeable_response at 0xcda2788L whose fp = <response_seek_wrapper at 0xcda2d48L whose wrapped object = <closeable_response at 0xcda2d08L whose fp = <socket._fileobject object at 0x000000000CD91930>>>>>, <traceback object at 0x000000000CDA2F08>) at https://fanbox.pixiv.net/images/post/434108/9tS1Gidk7sThIVGmRcNWPiwy.jpeg (9002)
2019-07-12 22:14:36,601 - PixivUtil20190712 - ERROR - Traceback (most recent call last):
  File "E:\conf\pixiv\pixivutil\PixivUtil2.py", line 214, in download_image
    (downloadedSize, filename) = perform_download(url, file_size, filename, overwrite, referer)
  File "E:\conf\pixiv\pixivutil\PixivUtil2.py", line 315, in perform_download
    res = __br__.open_novisit(req)
  File "C:\Users\nho\AppData\Roaming\Python\Python27\site-packages\mechanize\_mechanize.py", line 238, in open_novisit
    url_or_request, data, visit=False, timeout=timeout)
  File "C:\Users\nho\AppData\Roaming\Python\Python27\site-packages\mechanize\_mechanize.py", line 309, in _mech_open
    raise response
httperror_seek_wrapper: HTTP Error 500: Internal Server Error

2019-07-12 22:14:36,605 - PixivUtil20190712 - ERROR - Unknown Error: HTTP Error 500: Internal Server Error
Traceback (most recent call last):
  File "E:\conf\pixiv\pixivutil\PixivUtil2.py", line 2334, in main
    np_is_valid, op_is_valid, selection = main_loop(ewd, op_is_valid, selection, np_is_valid, args)
  File "E:\conf\pixiv\pixivutil\PixivUtil2.py", line 2091, in main_loop
    menu_fanbox_download_supported_artist(op_is_valid, args)
  File "E:\conf\pixiv\pixivutil\PixivUtil2.py", line 1841, in menu_fanbox_download_supported_artist
    processFanboxArtist(artist_id, end_page)
  File "E:\conf\pixiv\pixivutil\PixivUtil2.py", line 1890, in processFanboxArtist
    processFanboxImages(post, result_artist)
  File "E:\conf\pixiv\pixivutil\PixivUtil2.py", line 1943, in processFanboxImages
    __config__.backupOldFile)
  File "E:\conf\pixiv\pixivutil\PixivUtil2.py", line 214, in download_image
    (downloadedSize, filename) = perform_download(url, file_size, filename, overwrite, referer)
  File "E:\conf\pixiv\pixivutil\PixivUtil2.py", line 315, in perform_download
    res = __br__.open_novisit(req)
  File "C:\Users\nho\AppData\Roaming\Python\Python27\site-packages\mechanize\_mechanize.py", line 238, in open_novisit
    url_or_request, data, visit=False, timeout=timeout)
  File "C:\Users\nho\AppData\Roaming\Python\Python27\site-packages\mechanize\_mechanize.py", line 309, in _mech_open
    raise response
httperror_seek_wrapper: HTTP Error 500: Internal Server Error
```

**Comment by Nandaka** [comment]
can you pull the latest commit and retry?

**Comment by NHOrus** [comment]
It works. Thank you.
