### ISSUE TITLE
Error when trying to download r18 with lists

### ISSUE THREAD

**Issue by TidusFH** [Nandaka/PixivUtil2#520]
Prerequisites
 **Did you read FAQ section?**
Yes
 **Did you test with the latest releases or commit ?**
Yes

**Description**

2019-09-05 12:46:17,448 - PixivUtil20190712 - INFO - Member Url: https://www.pixiv.net/ajax/user/10163/illustmanga/tag?tag=R-18&offset=0&limit=48
2019-09-05 12:46:18,747 - PixivUtil20190712 - DEBUG - {"error":false,"message":"","body":{"works":[],"total":0,"zoneConfig":{"header":{"url":"https:\/\/pixon.ads-pixiv.net\/show?zone_id=header\u0026format=js\u0026s=1\u0026up=0\u0026a=24\u0026ng=w\u0026l=en\u0026uri=%2Fajax%2Fuser%2F_PARAM_%2Fillustmanga%2Ftag\u0026is_spa=1\u0026K=140d803d6959c\u0026ab_test_digits_first=9\u0026ab_test_digits_second=5\u0026Yuid=MFhyEwU\u0026suid=Pg6p2ocdlznsvevew\u0026num=5d712dcb979"},"footer":{"url":"https:\/\/pixon.ads-pixiv.net\/show?zone_id=footer\u0026format=js\u0026s=1\u0026up=0\u0026a=24\u0026ng=w\u0026l=en\u0026uri=%2Fajax%2Fuser%2F_PARAM_%2Fillustmanga%2Ftag\u0026is_spa=1\u0026K=140d803d6959c\u0026ab_test_digits_first=9\u0026ab_test_digits_second=5\u0026Yuid=MFhyEwU\u0026suid=Pg6p2ocdm5g48ccs8\u0026num=5d712dcb167"},"logo":{"url":"https:\/\/pixon.ads-pixiv.net\/show?zone_id=logo_side\u0026format=js\u0026s=1\u0026up=0\u0026a=24\u0026ng=w\u0026l=en\u0026uri=%2Fajax%2Fuser%2F_PARAM_%2Fillustmanga%2Ftag\u0026is_spa=1\u0026K=140d803d6959c\u0026ab_test_digits_first=9\u0026ab_test_digits_second=5\u0026Yuid=MFhyEwU\u0026suid=Pg6p2ocdm864t2reb\u0026num=5d712dcb158"},"500x500":{"url":"https:\/\/pixon.ads-pixiv.net\/show?zone_id=bigbanner\u0026format=js\u0026s=1\u0026up=0\u0026a=24\u0026ng=w\u0026l=en\u0026uri=%2Fajax%2Fuser%2F_PARAM_%2Fillustmanga%2Ftag\u0026is_spa=1\u0026K=140d803d6959c\u0026ab_test_digits_first=9\u0026ab_test_digits_second=5\u0026Yuid=MFhyEwU\u0026suid=Pg6p2ocdmasxdijmb\u0026num=5d712dcb775"}},"extraData":{"meta":{"title":"#R-18 - shirakaba\u0027s illustrations\/manga - pixiv","description":"pixiv","canonical":"https:\/\/www.pixiv.net\/member_illust.php?id=10163\u0026tag=R-18","ogp":{"description":"\u30df\u30af\u30ed\u5fae\u7c92\u5b50\r\nhttp:\/\/twitter.com\/srkb\r\n\r\n\r\n\r\nbonenod\u25cfgmail.com \r\n(\u25cf\u2192\uff20)\r\n\u5fa1\u7528\u306e\u65b9\u306f\u3053\u3061\u3089\u3078\u304a\u9858\u3044\u3057\u307e\u3059\u3002","image":"https:\/\/i.pximg.net\/c\/200x200\/user-profile\/img\/2016\/08\/18\/03\/56\/50\/11367123_035c3d7f5ed4b3c3214d0040d1aa73d3_170.png","title":"shirakaba - pixiv","type":"article"},"twitter":{"description":"\u30df\u30af\u30ed\u5fae\u7c92\u5b50\r\nhttp:\/\/twitter.com\/srkb\r\n\r\n\r\n\r\nbonenod\u25cfgmail.com \r\n(\u25cf\u2192\uff20)\r\n\u5fa1\u7528\u306e\u65b9\u306f\u3053\u3061\u3089\u3078\u304a\u9858\u3044\u3057\u307e\u3059\u3002","image":"https:\/\/i.pximg.net\/c\/200x200\/user-profile\/img\/2016\/08\/18\/03\/56\/50\/11367123_035c3d7f5ed4b3c3214d0040d1aa73d3_170.png","title":"shirakaba - pixiv","card":"summary"}}}}}
2019-09-05 12:46:18,769 - PixivUtil20190712 - INFO - Using OAuth to retrieve member info for: 10163
2019-09-05 12:46:18,769 - PixivUtil20190712 - DEBUG - Getting member information: 10163
2019-09-05 12:46:18,769 - PixivUtil20190712 - INFO - Login to OAuth using username and password.
2019-09-05 12:46:20,430 - PixivUtil20190712 - DEBUG - 400: {"has_error":true,"errors":{"system":{"message":"access_denied","code":1508}}}
2019-09-05 12:46:20,430 - PixivUtil20190712 - ERROR - {"has_error":true,"errors":{"system":{"message":"access_denied","code":1508}}}
2019-09-05 12:46:20,430 - PixivUtil20190712 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 2285, in main
  File "subprocess.pyc", line 390, in __init__
  File "subprocess.pyc", line 640, in _execute_child
WindowsError: [Error 2]: The system cannot find the file specified

2019-09-05 12:46:20,447 - PixivUtil20190712 - ERROR - Error at process_member(): (<type 'exceptions.AttributeError'>, AttributeError("'module' object has no attribute 'OAUTH_LOGIN_ISSUE'",), <traceback object at 0x03E5EAF8>)
2019-09-05 12:46:20,447 - PixivUtil20190712 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 423, in process_member
  File "PixivBrowserFactory.pyc", line 504, in getMemberPage
  File "PixivBrowserFactory.pyc", line 415, in getMemberInfoWhitecube
  File "PixivOAuth.pyc", line 108, in login
AttributeError: 'module' object has no attribute 'OAUTH_LOGIN_ISSUE' 

**[Description of the bug or feature]**
I can't actually download anything whe i'm using r18 mode but only when i try to use lists, if i try to download individually i'm still able to download it and when i'm not in r18 mode i can download lists just fine

**Steps to Reproduce**
1. Enable r18 mode
2. Try to download from a list

**Actual behavior: [What actually happened]**
Errors

Versions
You can get this information from executing PixivUtil2.py --help.
PixivDownloader2 version 20190712

Regarding the "The system cannot find the file specified" i believe its because of ffmpeg that i don't use since i'm not downloading ugoiras

**Comment by Nandaka** [comment]
```
019-09-05 12:46:18,769 - PixivUtil20190712 - INFO - Login to OAuth using username and password.
2019-09-05 12:46:20,430 - PixivUtil20190712 - DEBUG - 400: {"has_error":true,"errors":{"system":{"message":"access_denied","code":1508}}}
2019-09-05 12:46:20,430 - PixivUtil20190712 - ERROR - {"has_error":true,"errors":{"system":{"message":"access_denied","code":1508}}}
```
check your username/password in config.ini.

**Comment by TidusFH** [comment]
> ```
> 019-09-05 12:46:18,769 - PixivUtil20190712 - INFO - Login to OAuth using username and password.
> 2019-09-05 12:46:20,430 - PixivUtil20190712 - DEBUG - 400: {"has_error":true,"errors":{"system":{"message":"access_denied","code":1508}}}
> 2019-09-05 12:46:20,430 - PixivUtil20190712 - ERROR - {"has_error":true,"errors":{"system":{"message":"access_denied","code":1508}}}
> ```
> 
> check your username/password in config.ini.

I didnt work but i managed to make it work, dont ask me why but i thought of seeing what would happen if put some tag or simple decide to put an space when the prompt ask me for it and i put a single space where the tag is asked

I have no clue why i had tried to do everything clean download it and redo everything checked my info , changed my info on pixiv, but in the end only by doing that it worked

And it also really only showed to do is with the r18mode in the normal mode i just ignore the tag question as a whole


But i will keep looking i might have done something else and just didnt notice
