### ISSUE TITLE
UnboundLocalError: local variable 'photoshop' referenced before assignment

### ISSUE THREAD

**Issue by PixivAddict** [Nandaka/PixivUtil2#528]
I didnt find an open ticket when I searched photoshop, so I hope its new:

Checking local filename... Getting remote filesize...
Using Referer: https://www.pixiv.net/member_illust.php?mode=medium&illust_id=71535278
Remote filesize = 137.23 KiB (140527 Bytes)
Start downloading... Using Referer: https://www.pixiv.net/member_illust.php?mode=medium&il
lust_id=71535278
 [||||||||||||||||||||] 137.23 KiB of 137.23 KiB  Completed in 1.64s (83.68 KiB/s)
 Image invalid, deleting...
Traceback (most recent call last):
  File "PixivUtil2.py", line 230, in download_image
  File "PIL\Image.pyc", line 2690, in open
  File "PIL\Image.pyc", line 2676, in _open_core
  File "PIL\JpegImagePlugin.pyc", line 783, in jpeg_factory
  File "PIL\ImageFile.pyc", line 103, in __init__
  File "PIL\JpegImagePlugin.pyc", line 373, in _open
  File "PIL\JpegImagePlugin.pyc", line 139, in APP
UnboundLocalError: local variable 'photoshop' referenced before assignment
Error at download_image(): (<type 'exceptions.UnboundLocalError'>, UnboundLocalError("loca
l variable 'photoshop' referenced before assignment",), <traceback object at 0x03C82AA8>)
at https://i.pximg.net/img-original/img/2018/11/06/21/09/00/71535278_p0.jpg (9000)

**Comment by Nandaka** [comment]
looks like library problem, set `verifyimage = False` in config.ini for time being.
