### ISSUE TITLE
Crash on password protected zip

### ISSUE THREAD

**Issue by Thomasedv** [Nandaka/PixivUtil2#540]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
Used latest release. See version below

### Description

Got error that zip file is encrypted and that an image can't be extracted.

### Steps to Reproduce

1. Enable image verification in the config.ini
2. Download zip file that is encrypted with a password (f1 mode used, fanbox)

**Expected behavior:**

Zip file to remain intact, or images to be extracted. Download

**Actual behavior:**

Crashes as images inside the zip can't be accessed without a password.

```
Traceback (most recent call last):
  File "PixivUtil2.py", line 270, in download_image
  File "zipfile.pyc", line 901, in testzip
  File "zipfile.pyc", line 993, in open
RuntimeError: File cover.jpg is encrypted, password required for extraction
Error at download_image(): (<type 'exceptions.RuntimeError'>, RuntimeError('File cover.jpg is encrypted, password required for extraction',), <traceback object at 0x042BE030>) at [REDACTED link for privacy reasons] (9000)
Traceback (most recent call last):
  File "PixivUtil2.py", line 2369, in main
  File "PixivUtil2.py", line 2126, in main_loop
  File "PixivUtil2.py", line 1876, in menu_fanbox_download_supported_artist
  File "PixivUtil2.py", line 1925, in processFanboxArtist
  File "PixivUtil2.py", line 1978, in processFanboxImages
  File "PixivUtil2.py", line 270, in download_image
  File "zipfile.pyc", line 901, in testzip
  File "zipfile.pyc", line 993, in open
RuntimeError: File cover.jpg is encrypted, password required for extraction
press enter to exit.
```

**Workaround**

Disable verification of images. 
Personally, i enabled the verificaiton just to be on the safe side. Either way, not a big deal for me. However, i wanted to report the error in case you just wanna catch the error and just print that verification is skipped in this case. 

### Versions
PixivDownloader2 version 20190919

**Comment by Nandaka** [comment]
do you have the post id that I can use to replicate just in case?
