### ISSUE TITLE
Sooo... I was trying to download pics from FANBOX

### ISSUE THREAD

**Issue by ThunderIsBest** [Nandaka/PixivUtil2#549]
Basically what it types is:

2019-10-31 07:11:19,153 - PixivUtil20181006-alpha2 - INFO - Processing 1092867, page 1
2019-10-31 07:11:19,154 - PixivUtil20181006-alpha2 - INFO - Getting posts from https://www.pixiv.net/ajax/fanbox/creator?userId=1092867
2019-10-31 07:11:21,920 - PixivUtil20181006-alpha2 - DEBUG - Getting member information: 1092867
2019-10-31 07:11:23,434 - PixivUtil20181006-alpha2 - ERROR - Unknown Error: 'message'
Traceback (most recent call last):
  File "PixivUtil2.py", line 2229, in main
  File "PixivUtil2.py", line 2006, in main_loop
  File "PixivUtil2.py", line 1896, in menu_fanbox_download_by_artist_id
  File "PixivUtil2.py", line 1801, in processFanboxArtist
  File "PixivBrowserFactory.pyc", line 641, in fanboxGetPostsFromArtist
  File "PixivBrowserFactory.pyc", line 423, in getMemberInfoWhitecube
KeyError: 'message'

eh... so...?

**Comment by ThunderIsBest** [comment]
https://www.pixiv.net/fanbox/creator/1092867
tried to download from this artist
sorry if it's basic for someone :D
i dunno coding :D

**Comment by ThunderIsBest** [comment]
nvm. got it working
wanted to ask
you can't download restricted posts?
like will it work someday?

**Comment by Nandaka** [comment]
nope, it is server side restriction. You need to subscribe to their FANBOX.
