### ISSUE TITLE
Fanbox: TypeError: int() argument must be a string, a bytes-like object or a number, not 'none-type'

### ISSUE THREAD

**Issue by NHOrus** [Nandaka/PixivUtil2#579]
Latest git, instead of downloading, getting this:

```
Traceback (most recent call last):
  File "PixivUtil2.py", line 162, in download_image
    file_size = get_remote_filesize(url, referer)
  File "PixivUtil2.py", line 109, in get_remote_filesize
    file_size = int(res.info()['Content-Length'])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Error at download_image(): (<class 'TypeError'>, TypeError("int() argument must be a string, a bytes-like object or a number, not 'NoneType'"), <traceback object at 0x7f1d93e96f48>) at https://fanbox.pixiv.net/images/post/649997/Np09socbI8w5dDbFWjTEa7xq.jpeg (9000)
Traceback (most recent call last):
  File "PixivUtil2.py", line 2399, in main
    np_is_valid, op_is_valid, selection = main_loop(ewd, op_is_valid, selection, np_is_valid, args)
  File "PixivUtil2.py", line 2144, in main_loop
    menu_fanbox_download_supported_artist(op_is_valid, args)
  File "PixivUtil2.py", line 1890, in menu_fanbox_download_supported_artist
    processFanboxArtist(artist_id, end_page)
  File "PixivUtil2.py", line 1942, in processFanboxArtist
    processFanboxImages(post, result_artist)
  File "PixivUtil2.py", line 1995, in processFanboxImages
    __config__.backupOldFile)
  File "PixivUtil2.py", line 162, in download_image
    file_size = get_remote_filesize(url, referer)
  File "PixivUtil2.py", line 109, in get_remote_filesize
    file_size = int(res.info()['Content-Length'])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by Nandaka** [comment]
using python3?

**Comment by NHOrus** [comment]
Yes, python 3.7. Option 4 ran successfully, option F1 produced error.

**Comment by Nandaka** [comment]
looks like they remove the header for `['Content-Length']`

**Comment by NHOrus** [comment]
I tried again. Now it gets user pages, but doesn't get content:
```
2019-11-30 01:44:29,296 - PixivUtil20191118 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 443, in process_member
    (artist, list_page) = PixivBrowserFactory.getBrowser().getMemberPage(member_id, page, bookmark, tags)
  File "/home/nho/workshop/PixivUtil2/PixivBrowserFactory.py", line 554, in getMemberPage
    artist = PixivArtist(member_id, response, False, offset, limit)
  File "/home/nho/workshop/PixivUtil2/PixivArtist.py", line 40, in __init__
    raise PixivException(payload["message"], errorCode=PixivException.OTHER_MEMBER_ERROR, htmlPage=page)
PixivException.PixivException: 1003 User has left pixiv or the user ID does not exist., hasDumpPage=Y

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PixivUtil2.py", line 454, in process_member
    PixivHelper.dump_html("Dump for " + str(member_id) + " Error Code " + str(ex.errorCode) + ".html", list_page)
  File "/home/nho/workshop/PixivUtil2/PixivHelper.py", line 422, in dump_html
    dump = open(filename, 'wb', encoding="utf-8")
ValueError: binary mode doesn't take an encoding argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PixivUtil2.py", line 624, in process_member
    PixivHelper.dump_html(dump_filename, list_page)
  File "/home/nho/workshop/PixivUtil2/PixivHelper.py", line 422, in dump_html
    dump = open(filename, 'wb', encoding="utf-8")
ValueError: binary mode doesn't take an encoding argument

2019-11-30 01:44:31,307 - PixivUtil20191118 - ERROR - Error at process_member(): (<class 'ValueError'>, ValueError("binary mode doesn't take an encoding argument"), <traceback object at 0x7fea313565c8>)
2019-11-30 01:44:31,307 - PixivUtil20191118 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 443, in process_member
    (artist, list_page) = PixivBrowserFactory.getBrowser().getMemberPage(member_id, page, bookmark, tags)
  File "/home/nho/workshop/PixivUtil2/PixivBrowserFactory.py", line 554, in getMemberPage
    artist = PixivArtist(member_id, response, False, offset, limit)
  File "/home/nho/workshop/PixivUtil2/PixivArtist.py", line 40, in __init__
    raise PixivException(payload["message"], errorCode=PixivException.OTHER_MEMBER_ERROR, htmlPage=page)
PixivException.PixivException: 1003 User has left pixiv or the user ID does not exist., hasDumpPage=Y

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PixivUtil2.py", line 454, in process_member
    PixivHelper.dump_html("Dump for " + str(member_id) + " Error Code " + str(ex.errorCode) + ".html", list_page)
  File "/home/nho/workshop/PixivUtil2/PixivHelper.py", line 422, in dump_html
    dump = open(filename, 'wb', encoding="utf-8")
ValueError: binary mode doesn't take an encoding argument
```

Python 3, still.

**Comment by Nandaka** [comment]
do you get the latest commit? The logging still shows the old code.
![image](https://user-images.githubusercontent.com/836867/69896935-938efe00-12f9-11ea-909b-ee7263370334.png)
https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L113


![image](https://user-images.githubusercontent.com/836867/69896942-b0c3cc80-12f9-11ea-8fff-e70b35996d3a.png)
This one need to change the code.
```python
dump = open(filename, 'w', encoding="utf-8")
```
https://github.com/Nandaka/PixivUtil2/blob/master/PixivHelper.py#L422

**Comment by NHOrus** [comment]
I think yes, last upstream commit is `b192287 (origin/master, origin/HEAD) set bs4 to use html5lib`

Cleared python bytecode cache. No help.

```
Checking local filename... Getting remote filesize...
Using Referer: https://www.pixiv.net/fanbox/creator/4820/post/685302
        No file size information!
Remote filesize = -1 B (-1 Bytes)
Start downloading... Using Referer: https://www.pixiv.net/fanbox/creator/4820/post/685302
Traceback (most recent call last):
  File "PixivUtil2.py", line 225, in download_image
    (downloadedSize, filename_save) = perform_download(url, file_size, filename_save, overwrite, referer)
  File "PixivUtil2.py", line 340, in perform_download
    file_size = int(res.info()['Content-Length'])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Error at download_image(): (<class 'TypeError'>, TypeError("int() argument must be a string, a bytes-like object or a number, not 'NoneType'"), <traceback object at 0x7f6a57d22148>) at https://fanbox.pixiv.net/images/post/685302/0XdD1cdGJxsxXlhwq5nOGsmV.jpeg (9000)
Traceback (most recent call last):
  File "PixivUtil2.py", line 2404, in main
    np_is_valid, op_is_valid, selection = main_loop(ewd, op_is_valid, selection, np_is_valid, args)
  File "PixivUtil2.py", line 2149, in main_loop
    menu_fanbox_download_supported_artist(op_is_valid, args)
  File "PixivUtil2.py", line 1895, in menu_fanbox_download_supported_artist
    processFanboxArtist(artist_id, end_page)
  File "PixivUtil2.py", line 1947, in processFanboxArtist
    processFanboxImages(post, result_artist)
  File "PixivUtil2.py", line 2000, in processFanboxImages
    __config__.backupOldFile)
  File "PixivUtil2.py", line 225, in download_image
    (downloadedSize, filename_save) = perform_download(url, file_size, filename_save, overwrite, referer)
  File "PixivUtil2.py", line 340, in perform_download
    file_size = int(res.info()['Content-Length'])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

It points to different site, https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L340

**Comment by Nandaka** [comment]
looks like I missed that 😄
