### ISSUE TITLE
1002 (suspended users) provokes crash 

### ISSUE THREAD

**Issue by whinette** [Nandaka/PixivUtil2#580]
python 3.7 ;)
Happens with option 1 or 5.
Suspended users provoques crashes.

Exemple user: 668238

Log:

```
Input: 1
Member ids: 668238
Start Page (default=1):
End Page (default=0, 0 for no limit):
Member IDs: [668238]
Processing Member Id: 668238
Reading /mnt/c/PixivUtil2/config.ini ...
done.
Page  1
Member Url: https://www.pixiv.net/ajax/user/668238/profile/all
Member ID (668238): 1002 This user account has been suspended., hasDumpPage=Y
Traceback (most recent call last):
  File "/mnt/c/PixivUtil2/PixivBrowserFactory.py", line 480, in getMemberInfoWhitecube
    info_ajax_str = self.open_with_retry(url_ajax).read()
  File "/mnt/c/PixivUtil2/PixivBrowserFactory.py", line 147, in open_with_retry
    return self.open(url, data, timeout)
  File "/home/whinette/.local/lib/python3.7/site-packages/mechanize/_mechanize.py", line 253, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
  File "/home/whinette/.local/lib/python3.7/site-packages/mechanize/_mechanize.py", line 309, in _mech_open
    raise response
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PixivUtil2.py", line 443, in process_member
    (artist, list_page) = PixivBrowserFactory.getBrowser().getMemberPage(member_id, page, bookmark, tags)
  File "/mnt/c/PixivUtil2/PixivBrowserFactory.py", line 557, in getMemberPage
    self.getMemberInfoWhitecube(member_id, artist, bookmark)
  File "/mnt/c/PixivUtil2/PixivBrowserFactory.py", line 506, in getMemberInfoWhitecube
    msg, errorCode=PixivException.USER_ID_SUSPENDED, htmlPage=errorMessage)
PixivException.PixivException: 1002 This user account has been suspended., hasDumpPage=Y

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PixivUtil2.py", line 454, in process_member
    PixivHelper.dump_html("Dump for " + str(member_id) + " Error Code " + str(ex.errorCode) + ".html", list_page)
  File "/mnt/c/PixivUtil2/PixivHelper.py", line 422, in dump_html
    dump = open(filename, 'wb', encoding="utf-8")
ValueError: binary mode doesn't take an encoding argument
Error at process_member(): (<class 'ValueError'>, ValueError("binary mode doesn't take an encoding argument"), <traceback object at 0x7f162a5ad7d0>)
Cannot dump page for member_id: 668238
Traceback (most recent call last):
  File "/mnt/c/PixivUtil2/PixivBrowserFactory.py", line 480, in getMemberInfoWhitecube
    info_ajax_str = self.open_with_retry(url_ajax).read()
  File "/mnt/c/PixivUtil2/PixivBrowserFactory.py", line 147, in open_with_retry
    return self.open(url, data, timeout)
  File "/home/whinette/.local/lib/python3.7/site-packages/mechanize/_mechanize.py", line 253, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
  File "/home/whinette/.local/lib/python3.7/site-packages/mechanize/_mechanize.py", line 309, in _mech_open
    raise response
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PixivUtil2.py", line 443, in process_member
    (artist, list_page) = PixivBrowserFactory.getBrowser().getMemberPage(member_id, page, bookmark, tags)
  File "/mnt/c/PixivUtil2/PixivBrowserFactory.py", line 557, in getMemberPage
    self.getMemberInfoWhitecube(member_id, artist, bookmark)
  File "/mnt/c/PixivUtil2/PixivBrowserFactory.py", line 506, in getMemberInfoWhitecube
    msg, errorCode=PixivException.USER_ID_SUSPENDED, htmlPage=errorMessage)
PixivException.PixivException: 1002 This user account has been suspended., hasDumpPage=Y

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PixivUtil2.py", line 2404, in main
    np_is_valid, op_is_valid, selection = main_loop(ewd, op_is_valid, selection, np_is_valid, args)
  File "PixivUtil2.py", line 2114, in main_loop
    menu_download_by_member_id(op_is_valid, args)
  File "PixivUtil2.py", line 1528, in menu_download_by_member_id
    process_member(member_id, page=page, end_page=end_page, title_prefix=prefix)
  File "PixivUtil2.py", line 454, in process_member
    PixivHelper.dump_html("Dump for " + str(member_id) + " Error Code " + str(ex.errorCode) + ".html", list_page)
  File "/mnt/c/PixivUtil2/PixivHelper.py", line 422, in dump_html
    dump = open(filename, 'wb', encoding="utf-8")
ValueError: binary mode doesn't take an encoding argument
press enter to exit.
```

**Comment by whinette** [comment]
It stills occur, though the stacktrace is different.
```
Page  1
Member Url: https://www.pixiv.net/ajax/user/668238/profile/all
Member ID (668238): 1002 This user account has been suspended., hasDumpPage=Y
Traceback (most recent call last):
  File "/mnt/c/PixivUtil2/PixivBrowserFactory.py", line 480, in getMemberInfoWhitecube
    info_ajax_str = self.open_with_retry(url_ajax).read()
  File "/mnt/c/PixivUtil2/PixivBrowserFactory.py", line 147, in open_with_retry
    return self.open(url, data, timeout)
  File "/home/whinette/.local/lib/python3.7/site-packages/mechanize/_mechanize.py", line 253, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
  File "/home/whinette/.local/lib/python3.7/site-packages/mechanize/_mechanize.py", line 309, in _mech_open
    raise response
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PixivUtil2.py", line 445, in process_member
    (artist, list_page) = PixivBrowserFactory.getBrowser().getMemberPage(member_id, page, bookmark, tags)
  File "/mnt/c/PixivUtil2/PixivBrowserFactory.py", line 557, in getMemberPage
    self.getMemberInfoWhitecube(member_id, artist, bookmark)
  File "/mnt/c/PixivUtil2/PixivBrowserFactory.py", line 506, in getMemberInfoWhitecube
    msg, errorCode=PixivException.USER_ID_SUSPENDED, htmlPage=errorMessage)
PixivException.PixivException: 1002 This user account has been suspended., hasDumpPage=Y

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PixivUtil2.py", line 456, in process_member
    PixivHelper.dump_html("Dump for " + str(member_id) + " Error Code " + str(ex.errorCode) + ".html", list_page)
  File "/mnt/c/PixivUtil2/PixivHelper.py", line 423, in dump_html
    dump.write(str(html_text))
TypeError: a bytes-like object is required, not 'str'
Error at process_member(): (<class 'TypeError'>, TypeError("a bytes-like object is required, not 'str'"), <traceback object at 0x7f874d11d1e0>)
Cannot dump page for member_id: 668238
Traceback (most recent call last):
  File "/mnt/c/PixivUtil2/PixivBrowserFactory.py", line 480, in getMemberInfoWhitecube
    info_ajax_str = self.open_with_retry(url_ajax).read()
  File "/mnt/c/PixivUtil2/PixivBrowserFactory.py", line 147, in open_with_retry
    return self.open(url, data, timeout)
  File "/home/whinette/.local/lib/python3.7/site-packages/mechanize/_mechanize.py", line 253, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
  File "/home/whinette/.local/lib/python3.7/site-packages/mechanize/_mechanize.py", line 309, in _mech_open
    raise response
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PixivUtil2.py", line 445, in process_member
    (artist, list_page) = PixivBrowserFactory.getBrowser().getMemberPage(member_id, page, bookmark, tags)
  File "/mnt/c/PixivUtil2/PixivBrowserFactory.py", line 557, in getMemberPage
    self.getMemberInfoWhitecube(member_id, artist, bookmark)
  File "/mnt/c/PixivUtil2/PixivBrowserFactory.py", line 506, in getMemberInfoWhitecube
    msg, errorCode=PixivException.USER_ID_SUSPENDED, htmlPage=errorMessage)
PixivException.PixivException: 1002 This user account has been suspended., hasDumpPage=Y

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PixivUtil2.py", line 2406, in main
    np_is_valid, op_is_valid, selection = main_loop(ewd, op_is_valid, selection, np_is_valid, args)
  File "PixivUtil2.py", line 2116, in main_loop
    menu_download_by_member_id(op_is_valid, args)
  File "PixivUtil2.py", line 1530, in menu_download_by_member_id
    process_member(member_id, page=page, end_page=end_page, title_prefix=prefix)
  File "PixivUtil2.py", line 456, in process_member
    PixivHelper.dump_html("Dump for " + str(member_id) + " Error Code " + str(ex.errorCode) + ".html", list_page)
  File "/mnt/c/PixivUtil2/PixivHelper.py", line 423, in dump_html
    dump.write(str(html_text))
TypeError: a bytes-like object is required, not 'str'
press enter to exit.
```

**Comment by Nandaka** [comment]
can you change `dump.write(str(html_text))` to `dump.write(html_text)`  and test?

**Comment by whinette** [comment]
Yes, it does work.
