### ISSUE TITLE
str object has no attribute get_full_url

### ISSUE THREAD

**Issue by Ikkoru** [Nandaka/PixivUtil2#593]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Downloading from bookmarked artists (5; Private bookmarks (y); default; default) fails after some time with the following error:
![Untitled](https://user-images.githubusercontent.com/58905922/70862008-9a647480-1f79-11ea-96e0-d8882faafce4.png)

### Versions

Clean install of v20191214.

**Comment by Nandaka** [comment]
How many artists do you have in the bookmarks? Looks like it run out of memory when building the list.

**Comment by Ikkoru** [comment]
A lot... Let me check.
7225.

**Comment by bnick23** [comment]
I ran into what I'm guessing is the same error a couple of times when running a larger (around 150 ids) download using option 1. 

![PixivDownloaderMemoryError2](https://user-images.githubusercontent.com/24767475/70972487-bc5a1600-20a3-11ea-9096-a73cc89d1998.jpg)

Version 20191215

**Comment by Nandaka** [comment]
ya, looks like it got some memory leak which I'm not sure where....

**Comment by Nandaka** [comment]
commenting for myself, might be related: https://benbernardblog.com/tracking-down-a-freaky-python-memory-leak-part-2/

**Comment by NHOrus** [comment]
May be same problem?
```
2019-12-17 01:55:18,260 - PixivUtil20191214 - INFO - Member ID (6466199): 9005 Failed to get page: https://www.pixiv.net/ajax/user/6466199/profile/all, please check your internet connection/firewall/antivirus., hasDumpPage=N, pageData=None
2019-12-17 01:55:18,260 - PixivUtil20191214 - INFO - Processing Member Id: 3166900
2019-12-17 01:55:18,291 - PixivUtil20191214 - INFO - Member Url: https://www.pixiv.net/ajax/user/3166900/profile/all
2019-12-17 01:56:00,308 - PixivUtil20191214 - ERROR - Error at open_with_retry(): (<class 'ssl.SSLError'>, SSLError(65, '[SSL] malloc failure (_ssl.c:3014)'), <traceback object at 0x00291DC8>)
2019-12-17 01:56:00,309 - PixivUtil20191214 - ERROR - Traceback (most recent call last):
  File "PixivBrowserFactory.pyc", line 147, in open_with_retry
  File "mechanize\_mechanize.pyc", line 253, in open
  File "mechanize\_mechanize.pyc", line 283, in _mech_open
  File "mechanize\_opener.pyc", line 193, in open
  File "mechanize\_urllib2_fork.pyc", line 426, in _open
  File "mechanize\_urllib2_fork.pyc", line 414, in _call_chain
  File "mechanize\_urllib2_fork.pyc", line 1276, in https_open
  File "mechanize\_urllib2_fork.pyc", line 1189, in do_open
  File "http\client.pyc", line 1383, in __init__
  File "ssl.pyc", line 576, in create_default_context
  File "ssl.pyc", line 399, in __new__
ssl.SSLError: [SSL] malloc failure (_ssl.c:3014)
```

**Comment by NHOrus** [comment]
It began as
```
2019-12-16 01:57:07,605 - PixivUtil20191214 - ERROR - Downloaded file incomplete!  12124160 of  15276342 Bytes
2019-12-16 01:57:07,606 - PixivUtil20191214 - ERROR - Traceback (most recent call last):
  File "PixivHelper.pyc", line 595, in download_image
  File "mechanize\_response.pyc", line 208, in read
MemoryError

2019-12-16 01:57:07,606 - PixivUtil20191214 - ERROR - Filename = E:\conf\pixiv\2456307\76640495 - 活動一周年☆_1.png
2019-12-16 01:57:07,607 - PixivUtil20191214 - ERROR - Traceback (most recent call last):
  File "PixivHelper.pyc", line 595, in download_image
  File "mechanize\_response.pyc", line 208, in read
MemoryError

2019-12-16 01:57:07,607 - PixivUtil20191214 - ERROR - URL      = https://i.pximg.net/img-original/img/2019/09/06/00/02/02/76640495_p1.png
2019-12-16 01:57:07,607 - PixivUtil20191214 - ERROR - Traceback (most recent call last):
  File "PixivHelper.pyc", line 595, in download_image
  File "mechanize\_response.pyc", line 208, in read
MemoryError

2019-12-16 01:57:07,625 - PixivUtil20191214 - ERROR - Error at download_image(): (<class 'MemoryError'>, MemoryError(), <traceback object at 0x111B0760>) at https://i.pximg.net/img-original/img/2019/09/06/00/02/02/76640495_p1.png (9000)
2019-12-16 01:57:07,625 - PixivUtil20191214 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 225, in download_image
    (downloadedSize, filename_save) = perform_download(url, file_size, filename_save, overwrite, referer)
  File "PixivUtil2.py", line 346, in perform_download
    (downloadedSize, filename) = PixivHelper.download_image(url, filename, res, file_size, overwrite)
  File "PixivHelper.pyc", line 595, in download_image
  File "mechanize\_response.pyc", line 208, in read
MemoryError

2019-12-16 01:57:21,630 - PixivUtil20191214 - INFO - Using Referer: https://www.pixiv.net/artworks/76640495
2019-12-16 01:57:22,945 - PixivUtil20191214 - INFO - Using Referer: https://www.pixiv.net/artworks/76640495
2019-12-16 01:57:29,566 - PixivUtil20191214 - ERROR - Downloaded file incomplete!  12124160 of  15276342 Bytes
2019-12-16 01:57:29,566 - PixivUtil20191214 - ERROR - Traceback (most recent call last):
  File "PixivHelper.pyc", line 595, in download_image
  File "mechanize\_response.pyc", line 208, in read
MemoryError

2019-12-16 01:57:29,566 - PixivUtil20191214 - ERROR - Filename = E:\conf\pixiv\2456307\76640495 - 活動一周年☆_1.png
2019-12-16 01:57:29,567 - PixivUtil20191214 - ERROR - Traceback (most recent call last):
  File "PixivHelper.pyc", line 595, in download_image
  File "mechanize\_response.pyc", line 208, in read
MemoryError

2019-12-16 01:57:29,567 - PixivUtil20191214 - ERROR - URL      = https://i.pximg.net/img-original/img/2019/09/06/00/02/02/76640495_p1.png
2019-12-16 01:57:29,567 - PixivUtil20191214 - ERROR - Traceback (most recent call last):
  File "PixivHelper.pyc", line 595, in download_image
  File "mechanize\_response.pyc", line 208, in read
MemoryError
```

**Comment by Nandaka** [comment]
can you try to add `res.close()` between line https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L339 and https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L340?

**Comment by Nandaka** [comment]
upgrading to py3.8 can reduce the leak somehow (testing in progress)

**Comment by Nandaka** [comment]
yap, running ok so far, but it requires python 3.8, which doesn't have py2exe package yet.

**Comment by Nandaka** [comment]
updated in https://github.com/Nandaka/PixivUtil2/releases/tag/v21091218

**Comment by NHOrus** [comment]
Tried to test, failed due to internet dying. Expect results tomorrow.

**Comment by Ikkoru** [comment]
Seems like it's fixed. Will edit this message or post a new one when all the program runs to completion.
