### ISSUE TITLE
Bad magic number in 'apng'

### ISSUE THREAD

**Issue by vampiricwulf** [Nandaka/PixivUtil2#621]
### Prerequisites

* [x] Read FAQ
* [x] [commit](https://github.com/Nandaka/PixivUtil2/commits/1207938f9919ad6097f24824bbe02dc11a1f8f43 "latest commit")

### Description

```
# py -3 "PixivUtil2.py"
Traceback (most recent call last):
  File "PixivUtil2.py", line 23, in <module>
    import PixivBrowserFactory
  File "C:\PixivUtil2\PixivBrowserFactory.py", line 19, in <module>
    import PixivHelper
  File "C:\PixivUtil2\PixivHelper.py", line 26, in <module>
    from apng import APNG
ImportError: bad magic number in 'apng': b'\x03\xf3\r\n'
```

### Steps to Reproduce

1. Try to run .py

**Expected behavior:** It runs

**Actual behavior:** Bad magic number

**Comment by vampiricwulf** [comment]
Fixed it by deleted all .pyc in folder.
