### ISSUE TITLE
Can't open downloader

### ISSUE THREAD

**Issue by Litoba** [Nandaka/PixivUtil2#628]
### Prerequisites

* [Y] Did you read FAQ section?
* [Y] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

I opened downloader, but soon After the Error message came out, program to shut down.

Error message ->
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>

### Versions

It is the same with any version.

**Comment by Nandaka** [comment]
> urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>

Means the application cannot resolve the dns of the pixiv website.
Ensure you can open the pixiv website from your pc, also check your antivirus/firewall if they block the internet access for the program.

**Comment by Litoba** [comment]
my pc can open pixiv website.
I checked Windows Defender, but firewall not block the downloader...
Could the installed program cause problems?
For example, Microsoft Visual C++?
Just in case, in detail addition the contents of pixivutil ->

2020-01-27 05:46:25,730 - PixivUtil20200112 - INFO - ###############################################################
2020-01-27 05:46:25,730 - PixivUtil20200112 - INFO - Starting with argument: [K:\W.T.C\pixiv\Pixiv downloader\pixivutil20200112\PixivUtil2.exe].
2020-01-27 05:46:25,734 - PixivUtil20200112 - INFO - Setting log level to: DEBUG
2020-01-27 05:46:25,734 - PixivUtil20200112 - INFO - No default cookie jar available, creating... 
2020-01-27 05:46:37,798 - PixivUtil20200112 - ERROR - Error at open_with_retry(): (<class 'urllib.error.URLError'>, URLError(gaierror(11001, 'getaddrinfo failed')), <traceback object at 0x0FC463C8>)
2020-01-27 05:46:37,799 - PixivUtil20200112 - ERROR - Traceback (most recent call last):
  File "mechanize\_urllib2_fork.pyc", line 1229, in do_open
  File "http\client.pyc", line 1230, in request
  File "http\client.pyc", line 1276, in _send_request
  File "http\client.pyc", line 1225, in endheaders
  File "http\client.pyc", line 1004, in _send_output
  File "http\client.pyc", line 944, in send
  File "http\client.pyc", line 1392, in connect
  File "http\client.pyc", line 915, in connect
  File "socket.pyc", line 787, in create_connection
  File "socket.pyc", line 914, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PixivBrowserFactory.pyc", line 169, in open_with_retry
  File "mechanize\_mechanize.pyc", line 253, in open
  File "mechanize\_mechanize.pyc", line 283, in _mech_open
  File "mechanize\_opener.pyc", line 193, in open
  File "mechanize\_urllib2_fork.pyc", line 425, in _open
  File "mechanize\_urllib2_fork.pyc", line 414, in _call_chain
  File "mechanize\_urllib2_fork.pyc", line 1276, in https_open
  File "mechanize\_urllib2_fork.pyc", line 1233, in do_open
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>

**Comment by Nandaka** [comment]
Are you running using proxy? Looking the error message and search it online, looks like it is the cause https://stackoverflow.com/questions/7334199/getaddrinfo-failed-what-does-that-mean

**Comment by Litoba** [comment]
I found the cause of the problem.
As certain program are run, seem to have touched on the proxy settings.
LAN Settings -> Auto Configuration -> 'Automatically detect settings' Turn Off or Checking.
Whenever the program was turned on, there was a problem, so I touched that part and it was solved.
 caused the problem program -> ezTrans XP
Thanks you for Solution :)
