### ISSUE TITLE
Changes to pixivFANBOX broke the script. API returns 404 for all creators.

### ISSUE THREAD

**Issue by AgentThirteen** [Nandaka/PixivUtil2#641]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Starting from today, pixivFANBOX no longer uses the same page or protocol in the API.

Script fatals with a 404 upon trying to fetch
`https://www.pixiv.net/ajax/fanbox/index` for `f1` or
`https://www.pixiv.net/ajax/fanbox/creator?userId=*` for `f2`.

### Debugging info

Browser test with subscription, listing all XHRs:
```
GET XHR https://fanbox.pixiv.net/api/creator.get [HTTP/2.0 200 OK]
GET XHR https://fanbox.pixiv.net/api/plan.listCreator [HTTP/2.0 200 OK]
GET XHR https://fanbox.pixiv.net/api/post.listCreator [HTTP/2.0 200 OK]
GET XHR https://fanbox.pixiv.net/api/tag.getFeatured [HTTP/2.0 200 OK]
GET XHR https://fanbox.pixiv.net/api/bell.countUnread [HTTP/2.0 200 OK]
GET XHR https://fanbox.pixiv.net/api/post.info [HTTP/2.0 200 OK]
```

JSON response using current links:
`{"error":true,"message":"Couldn't find requested page","body":[]}`
regardless of whether the target user has a FANBOX set along with one or more selectable plans and regardless of any subscription status from the caller, even as a guest.

Python traceback, using Python 3.8.1 and untouched script:
```
Traceback (most recent call last):
  File "pixivutil2.py", line 2442, in main
    np_is_valid, op_is_valid, selection = main_loop(ewd, op_is_valid, selection, np_is_valid, args)
  File "pixivutil2.py", line 2179, in main_loop
    menu_fanbox_download_by_artist_id(op_is_valid, args)
  File "pixivutil2.py", line 2062, in menu_fanbox_download_by_artist_id
    processFanboxArtist(artist_id, end_page)
  File "pixivutil2.py", line 1929, in processFanboxArtist
    result_artist = __br__.fanboxGetPostsFromArtist(artist_id, next_url)
  File "*\PixivBrowserFactory.py", line 727, in fanboxGetPostsFromArtist
    res = self.open_with_retry(req)
  File "*\PixivBrowserFactory.py", line 169, in open_with_retry
    return self.open(url, data, timeout)
  File "*\lib\site-packages\mechanize\_mechanize.py", line 257, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
  File "*\lib\site-packages\mechanize\_mechanize.py", line 313, in _mech_open
    raise response
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 404: Not Found
press enter to exit.
```

### Steps to Reproduce

1. Use `f1` or `f2`
2. Script fails with 404 JSON response and fatals

**Expected behavior:** `f1` or `f2` should fetch the pages and return at least 1 result.

**Actual behavior:** Both `f1` and `f2` fatal right after trying to fetch the pages.

### Versions

Latest commit a496d9a
`20200125 - 2020 did not start well and will not end well`

**Comment by Nandaka** [comment]
Hmm, I don't have any followed fanbox so might be a bit difficult to test.

Can you check the latest commit to try? Hopefully they didn't change the json structure.

**Comment by NHOrus** [comment]
Sadly, doesn't work.
{code}
Getting supported artists from https://fanbox.pixiv.net/api/plan.listSupporting
Traceback (most recent call last):
  File "PixivUtil2.py", line 2448, in main
    np_is_valid, op_is_valid, selection = main_loop(ewd, op_is_valid, selection, np_is_valid, args)
  File "PixivUtil2.py", line 2183, in main_loop
    menu_fanbox_download_supported_artist(op_is_valid, args)
  File "PixivUtil2.py", line 1913, in menu_fanbox_download_supported_artist
    result = __br__.fanboxGetSupportedUsers()
  File "/home/nho/workshop/PixivUtil2/PixivBrowserFactory.py", line 702, in fanboxGetSupportedUsers
    res = self.open_with_retry(url)
  File "/home/nho/workshop/PixivUtil2/PixivBrowserFactory.py", line 169, in open_with_retry
    return self.open(url, data, timeout)
  File "/home/nho/.local/lib/python3.7/site-packages/mechanize/_mechanize.py", line 253, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
  File "/home/nho/.local/lib/python3.7/site-packages/mechanize/_mechanize.py", line 309, in _mech_open
    raise response
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 400: Bad Request
{code}

Attached is json from plan.listSupporting

[plan.listSupporting.txt](https://github.com/Nandaka/PixivUtil2/files/4256909/plan.listSupporting.txt)

**Comment by NHOrus** [comment]
Apologizing, this content is NSFW.

Adding two consequential requests and responses to post.listCreator

```
https://fanbox.pixiv.net/api/post.listCreator?userId=91029&limit=10
```
[plan.listSupporting.txt](https://github.com/Nandaka/PixivUtil2/files/4256937/plan.listSupporting.txt)

```
https://fanbox.pixiv.net/api/post.listCreator?userId=91029&maxPublishedDatetime=2019-07-25%2004%3A27%3A54&maxId=481268&limit=10
```
[post.listCreator.2.txt](https://github.com/Nandaka/PixivUtil2/files/4256945/post.listCreator.2.txt)

```
Post with download:
```
https://fanbox.pixiv.net/api/post.info?postId=685832
```

[post.info.1.txt](https://github.com/Nandaka/PixivUtil2/files/4256959/post.info.1.txt)

Post with multiple images:

```
https://fanbox.pixiv.net/api/post.info?postId=855025
```

[post.info.2.txt](https://github.com/Nandaka/PixivUtil2/files/4256971/post.info.2.txt)

**Comment by NHOrus** [comment]
There's complex cookie structire. e.g
```
tag_view_ranking=0xsDLqCEW6~qWFESUmfEs~LVSDGaCAdn~DADQycFGB0~QKeXYK2oSR~xa5-CDAPro~aKhT3n4RHZ~MM6RXH_rlN~KN7uxuR89w~CmMil8exOo~Ie2c51_4Sp~RTJMXD26Ak~2-q1CV6LVL~Lt-oEicbBr~LLyDB5xskQ~ETjPkL0e6r~n39RQWfHku~RcahSSzeRf~TWrozby2UO~iFcW6hPGPU~EGefOqA6KB~m3EJRa33xU~G-44hwuIPi~abNIEh2zTB~BtXd1-LPRH~5oPIfUbtd6~_hSAdpN9rx~QL2G1t5h_V~YHRjLHL-7q~u8McsBs7WV~liM64qjhwQ~8NpFhmNqI1~D9BseuUB5Z~-Z_uXeR9KM~JptCrLOjcb~XyXh-Zf46-~6BaeaGq33S~CrFcrMFJzz~BSkdEJ73Ii~y8GNntYHsi~Tg1PbOMGRv~-StjcwdYwv~Ti1gvrVQFO~edF4CoWy9T~EUwzYuPRbU~Txs9grkeRc~vSWEvTeZc6~6o6m4yJCaj~0jyux9PxkH~-M68AYIG8m~zIv0cf5VVk~5-q4dVSeQE~3gc3uGrU1V~3mvlXxwzlR~q3eUobDMJW~YTKjYV1RQx~y0H0q1mN2T~pulAFAgyK9~DU9jLF-LB5~rsl20PjZs_~28gdfFXlY7~8MumIwvLOk~WcTW9TCOx9~jsuXqE_4cM~5x8LwWziLw~h9fEA3tOFb~jfnUZgnpFl~HY55MqmzzQ~bXMh6mBhl8~VI5zumpdp0~-98s6o2-Rp~EZQqoW9r8g~pYlUxeIoeg~NEmH3z9luA~8PDkVxzRxX~IEelj7HCPz~qEsMl4UVLQ~0RGtdYkK6L~fN7lpKqRmz~QM0rfezNVP~6293srEnwa~FqVQndhufZ~Nj9Bt-JWdN~-jxw_sxnha~59dAqNEUGJ~pfmo5NN164~engSCj5XFq~lRxin4V3-v~zlAh6PuhMT~LgZr3tCQBC~OqLruLZh_X~ITVapWvXyh~faHcYIP1U0~HBlflqJjBZ~YhqxtePwNx~0CaTbfGZYk~ZbY3NtP948~ywOV8k6vrd~yS_WrRrWFi~ehFkU8vOq9
```
```
module_orders_mypage=%5B%7B%22name%22%3A%22sketch_live%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22tag_follow%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22recommended_illusts%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22everyone_new_illusts%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22following_new_illusts%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22mypixiv_new_illusts%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22spotlight%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22fanbox%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22featured_tags%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22contests%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22user_events%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22sensei_courses%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22booth_follow_items%22%2C%22visible%22%3Atrue%7D%5D
```

**Comment by Nandaka** [comment]
> Adding two consequential requests and responses to post.listCreator

wrong json attached? it is from plan.listSupporting.txt

**Comment by NHOrus** [comment]
Sorry. Two consequential requests to post.listCreator ( equivalent to scrolling down)

```
https://fanbox.pixiv.net/api/post.listCreator?userId=1094478&limit=10
cookie: p_ab_id=9; p_ab_id_2=7; p_ab_d_id=502027686; __utmc=235335808; __utmz=235335808.1571404651.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); privacy_policy_agreement=1; PHPSESSID=.....; c_type=30; a_type=0; b_type=1; d_type=2%2C4%2C8; module_orders_mypage=%5B%7B%22name%22%3A%22sketch_live%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22tag_follow%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22recommended_illusts%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22everyone_new_illusts%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22following_new_illusts%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22mypixiv_new_illusts%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22spotlight%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22fanbox%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22featured_tags%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22contests%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22user_events%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22sensei_courses%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22booth_follow_items%22%2C%22visible%22%3Atrue%7D%5D; __utma=235335808.51441439.1571404651.1571404651.1575260431.2; __utmv=235335808.|2=login%20ever=no=1^3=plan=normal=1^5=gender=male=1^6=user_id=2163948=1^9=p_ab_id=9=1^10=p_ab_id_2=7=1^11=lang=en=1; howto_recent_view_history=79139738; tag_view_ranking=0xsDLqCEW6~qWFESUmfEs~LVSDGaCAdn~DADQycFGB0~QKeXYK2oSR~xa5-CDAPro~aKhT3n4RHZ~MM6RXH_rlN~KN7uxuR89w~CmMil8exOo~Ie2c51_4Sp~RTJMXD26Ak~2-q1CV6LVL~Lt-oEicbBr~LLyDB5xskQ~ETjPkL0e6r~n39RQWfHku~RcahSSzeRf~TWrozby2UO~iFcW6hPGPU~EGefOqA6KB~m3EJRa33xU~G-44hwuIPi~abNIEh2zTB~BtXd1-LPRH~5oPIfUbtd6~_hSAdpN9rx~QL2G1t5h_V~YHRjLHL-7q~u8McsBs7WV~liM64qjhwQ~8NpFhmNqI1~D9BseuUB5Z~-Z_uXeR9KM~JptCrLOjcb~XyXh-Zf46-~6BaeaGq33S~CrFcrMFJzz~BSkdEJ73Ii~y8GNntYHsi~Tg1PbOMGRv~-StjcwdYwv~Ti1gvrVQFO~edF4CoWy9T~EUwzYuPRbU~Txs9grkeRc~vSWEvTeZc6~6o6m4yJCaj~0jyux9PxkH~-M68AYIG8m~zIv0cf5VVk~5-q4dVSeQE~3gc3uGrU1V~3mvlXxwzlR~q3eUobDMJW~YTKjYV1RQx~y0H0q1mN2T~pulAFAgyK9~DU9jLF-LB5~rsl20PjZs_~28gdfFXlY7~8MumIwvLOk~WcTW9TCOx9~jsuXqE_4cM~5x8LwWziLw~h9fEA3tOFb~jfnUZgnpFl~HY55MqmzzQ~bXMh6mBhl8~VI5zumpdp0~-98s6o2-Rp~EZQqoW9r8g~pYlUxeIoeg~NEmH3z9luA~8PDkVxzRxX~IEelj7HCPz~qEsMl4UVLQ~0RGtdYkK6L~fN7lpKqRmz~QM0rfezNVP~6293srEnwa~FqVQndhufZ~Nj9Bt-JWdN~-jxw_sxnha~59dAqNEUGJ~pfmo5NN164~engSCj5XFq~lRxin4V3-v~zlAh6PuhMT~LgZr3tCQBC~OqLruLZh_X~ITVapWvXyh~faHcYIP1U0~HBlflqJjBZ~YhqxtePwNx~0CaTbfGZYk~ZbY3NtP948~ywOV8k6vrd~yS_WrRrWFi~ehFkU8vOq9
```
[post.listCreator.1.txt](https://github.com/Nandaka/PixivUtil2/files/4257420/post.listCreator.1.txt)

```
https://fanbox.pixiv.net/api/post.listCreator?userId=1094478&maxPublishedDatetime=2019-12-23%2001%3A16%3A41&maxId=724788&limit=10
p_ab_id=9; p_ab_id_2=7; p_ab_d_id=502027686; __utmc=235335808; __utmz=235335808.1571404651.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); privacy_policy_agreement=1; PHPSESSID=.....; c_type=30; a_type=0; b_type=1; d_type=2%2C4%2C8; module_orders_mypage=%5B%7B%22name%22%3A%22sketch_live%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22tag_follow%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22recommended_illusts%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22everyone_new_illusts%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22following_new_illusts%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22mypixiv_new_illusts%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22spotlight%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22fanbox%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22featured_tags%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22contests%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22user_events%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22sensei_courses%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22booth_follow_items%22%2C%22visible%22%3Atrue%7D%5D; __utma=235335808.51441439.1571404651.1571404651.1575260431.2; __utmv=235335808.|2=login%20ever=no=1^3=plan=normal=1^5=gender=male=1^6=user_id=2163948=1^9=p_ab_id=9=1^10=p_ab_id_2=7=1^11=lang=en=1; howto_recent_view_history=79139738; tag_view_ranking=0xsDLqCEW6~qWFESUmfEs~LVSDGaCAdn~DADQycFGB0~QKeXYK2oSR~xa5-CDAPro~aKhT3n4RHZ~MM6RXH_rlN~KN7uxuR89w~CmMil8exOo~Ie2c51_4Sp~RTJMXD26Ak~2-q1CV6LVL~Lt-oEicbBr~LLyDB5xskQ~ETjPkL0e6r~n39RQWfHku~RcahSSzeRf~TWrozby2UO~iFcW6hPGPU~EGefOqA6KB~m3EJRa33xU~G-44hwuIPi~abNIEh2zTB~BtXd1-LPRH~5oPIfUbtd6~_hSAdpN9rx~QL2G1t5h_V~YHRjLHL-7q~u8McsBs7WV~liM64qjhwQ~8NpFhmNqI1~D9BseuUB5Z~-Z_uXeR9KM~JptCrLOjcb~XyXh-Zf46-~6BaeaGq33S~CrFcrMFJzz~BSkdEJ73Ii~y8GNntYHsi~Tg1PbOMGRv~-StjcwdYwv~Ti1gvrVQFO~edF4CoWy9T~EUwzYuPRbU~Txs9grkeRc~vSWEvTeZc6~6o6m4yJCaj~0jyux9PxkH~-M68AYIG8m~zIv0cf5VVk~5-q4dVSeQE~3gc3uGrU1V~3mvlXxwzlR~q3eUobDMJW~YTKjYV1RQx~y0H0q1mN2T~pulAFAgyK9~DU9jLF-LB5~rsl20PjZs_~28gdfFXlY7~8MumIwvLOk~WcTW9TCOx9~jsuXqE_4cM~5x8LwWziLw~h9fEA3tOFb~jfnUZgnpFl~HY55MqmzzQ~bXMh6mBhl8~VI5zumpdp0~-98s6o2-Rp~EZQqoW9r8g~pYlUxeIoeg~NEmH3z9luA~8PDkVxzRxX~IEelj7HCPz~qEsMl4UVLQ~0RGtdYkK6L~fN7lpKqRmz~QM0rfezNVP~6293srEnwa~FqVQndhufZ~Nj9Bt-JWdN~-jxw_sxnha~59dAqNEUGJ~pfmo5NN164~engSCj5XFq~lRxin4V3-v~zlAh6PuhMT~LgZr3tCQBC~OqLruLZh_X~ITVapWvXyh~faHcYIP1U0~HBlflqJjBZ~YhqxtePwNx~0CaTbfGZYk~ZbY3NtP948~ywOV8k6vrd~yS_WrRrWFi~ehFkU8vOq9

```
[post.listCreator.2.txt](https://github.com/Nandaka/PixivUtil2/files/4257426/post.listCreator.2.txt)

And post.listCreator.2.txt here is a raw response, without formatting.

**Comment by Nandaka** [comment]
can you try latest commit? going to sleep now 😄

**Comment by NHOrus** [comment]
It doesn't dump stack trace and die, at least.

**Comment by AgentThirteen** [comment]
Thank you both. Testing results. All testing states are OK.

Checking global supported state: OK
Checking post restrictions: OK
Fetching all posts: OK
Comparing files: OK
Saving new files: OK

It looks like we can close this one already. Feel free to reopen if you find something wrong.

**Comment by NHOrus** [comment]
Beta 2 with final trace?

**Comment by Nandaka** [comment]
updated: https://github.com/Nandaka/PixivUtil2/releases/tag/v20200228
