### ISSUE TITLE
Linux Syntax Error, not starting

### ISSUE THREAD

**Issue by soli18** [Nandaka/PixivUtil2#642]
Git cloned PixivUtil2-20200226-beta1 

File "PixivUtil2.py", line 56
    print("\b \b", end="")

SyntaxError: invalid syntax

**Comment by NHOrus** [comment]
Are you sure you running pixivutil with Python3?26 февр. 2020 г. 23:37 пользователь soli18 <notifications@github.com> написал:Git cloned PixivUtil2-20200226-beta1
File "PixivUtil2.py", line 56
print("\b \b", end="")
SyntaxError: invalid syntax

**Comment by soli18** [comment]
Oh did it upgrade to use py3, was still using py2.

Anyway,

X@X:~/Pixiv/PixivUtil2-20200226-beta1$ python3 PixivUtil2.py
Traceback (most recent call last):
  File "PixivUtil2.py", line 19, in <module>
    import mechanize
ModuleNotFoundError: No module named 'mechanize'
X@X:~/Pixiv/PixivUtil2-20200226-beta1$ pip install requirements.txt
Collecting requirements.txt
  Could not find a version that satisfies the requirement requirements.txt (from versions: )
No matching distribution found for requirements.txt

**Comment by NHOrus** [comment]
Pip3 --user install requirements.txt27 февр. 2020 г. 0:03 пользователь soli18 <notifications@github.com> написал:Oh did it upgrade to use py3, was still using py2.
Anyway,
X@X:/Pixiv/PixivUtil2-20200226-beta1$ python3 PixivUtil2.py
Traceback (most recent call last):
File "PixivUtil2.py", line 19, in 
import mechanize
ModuleNotFoundError: No module named 'mechanize'
X@X:/Pixiv/PixivUtil2-20200226-beta1$ pip install requirements.txt
Collecting requirements.txt
Could not find a version that satisfies the requirement requirements.txt (from versions: )
No matching distribution found for requirements.txt

**Comment by soli18** [comment]
X-X:~/Pixiv/PixivUtil2-20200226-beta1$ pip3 install requirements.txt
Collecting requirements.txt
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python3/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 795, in get_page
    resp.raise_for_status()
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/requirements-txt/

**Comment by Nandaka** [comment]
`pip3 install -r requirements.txt`
