### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by rogerlhc** [Nandaka/PixivUtil2#68]
Log in using form.
Error at pixiv_login():(, ControlN
otFoundError(“no control matching name ‘pixiv_id'”,), )
Traceback (most recent call last):
File “PixivUtil2.py”, line 1718, in main
File “PixivBrowserFactory.pyc”, line 178, in loginHttp
File “mechanize\_form.pyc”, line 2780, in __setitem__
File “mechanize\_form.pyc”, line 3101, in find_control
File “mechanize\_form.pyc”, line 3185, in _find_control
ControlNotFoundError: no control matching name ‘pixiv_id’
press enter to exit.

========log file=======

2015-02-17 12:13:24,424 – PixivUtil20150121 – INFO – ###############################################################
2015-02-17 12:13:24,424 – PixivUtil20150121 – INFO – Starting…
2015-02-17 12:13:24,427 – PixivUtil20150121 – ERROR – Error at loadConfig()
Traceback (most recent call last):
File “PixivConfig.pyc”, line 90, in loadConfig
File “PixivHelper.pyc”, line 269, in OpenTextFile
File “codecs.pyc”, line 881, in open
IOError: [Errno 2] No such file or directory: u’D:\\softup\\pixivutil20150121\\config.ini’
2015-02-17 12:13:24,430 – PixivUtil20150121 – INFO – Setting log level to: DEBUG
2015-02-17 12:13:24,430 – PixivUtil20150121 – INFO – No default cookie jar available, creating…
2015-02-17 12:13:24,440 – PixivUtil20150121 – INFO – Only process member where day last updated >= 7
2015-02-17 12:13:33,026 – PixivUtil20150121 – INFO – Log in using form.
2015-02-17 12:13:34,118 – PixivUtil20150121 – ERROR – Error at pixiv_login():(, ControlNotFoundError(“no control matching name ‘pixiv_id'”,), )
2015-02-17 12:13:34,119 – PixivUtil20150121 – ERROR – Error at pixiv_login(): (, ControlNotFoundError(“no control matching name ‘pixiv_id'”,), )
Traceback (most recent call last):
File “PixivBrowserFactory.pyc”, line 178, in loginHttp
File “mechanize\_form.pyc”, line 2780, in __setitem__
File “mechanize\_form.pyc”, line 3101, in find_control
File “mechanize\_form.pyc”, line 3185, in _find_control
ControlNotFoundError: no control matching name ‘pixiv_id’
2015-02-17 12:13:34,121 – PixivUtil20150121 – ERROR – Unknown Error: no control matching name ‘pixiv_id’
Traceback (most recent call last):
File “PixivUtil2.py”, line 1718, in main
File “PixivBrowserFactory.pyc”, line 178, in loginHttp
File “mechanize\_form.pyc”, line 2780, in __setitem__
File “mechanize\_form.pyc”, line 3101, in find_control
File “mechanize\_form.pyc”, line 3185, in _find_control
ControlNotFoundError: no control matching name ‘pixiv_id’

**Comment by vampiricwulf** [comment]
Not to but in, but:
No such file or directory: u’D:\softup\pixivutil20150121\config.ini’

**Comment by rogerlhc** [comment]
I use a clean pixivUtil,so there's no config.ini.
And this {No such file or directory: u’D:\softup\pixivutil20150121\config.ini’} is not an error.

try to login ,don't use keepsignedin.

**Comment by vampiricwulf** [comment]
Oh, I see, for a quick work around, log in on the website, look at your cookies and copy the value of ```PHPSESSID```.
then paste it in: ```cookie = ``` in the config.ini and set ```keepsignedin = 1```

Here's my error from my log:
```
2015-02-17 18:06:38,548 - PixivUtil20150121 - ERROR - Error at pixiv_login():(<class 'mechanize._form.ControlNotFoundError'>, ControlNotFoundError("no control matching name 'pixiv_id'",), <traceback object at 0x105ba6440>)
2015-02-17 18:06:38,548 - PixivUtil20150121 - ERROR - Error at pixiv_login(): (<class 'mechanize._form.ControlNotFoundError'>, ControlNotFoundError("no control matching name 'pixiv_id'",), <traceback object at 0x105ba6440>)
Traceback (most recent call last):
  File "/Applications/PixivUtil/PixivBrowserFactory.py", line 178, in loginHttp
    self['pixiv_id'] = username
  File "/usr/local/lib/python2.7/site-packages/mechanize/_form.py", line 2780, in __setitem__
    control = self.find_control(name)
  File "/usr/local/lib/python2.7/site-packages/mechanize/_form.py", line 3101, in find_control
    return self._find_control(name, type, kind, id, label, predicate, nr)
  File "/usr/local/lib/python2.7/site-packages/mechanize/_form.py", line 3185, in _find_control
    raise ControlNotFoundError("no control matching "+description)
ControlNotFoundError: no control matching name 'pixiv_id'
2015-02-17 18:06:38,572 - PixivUtil20150121 - ERROR - Unknown Error: no control matching name 'pixiv_id'
Traceback (most recent call last):
  File "/Applications/PixivUtil/PixivUtil2.py", line 1718, in main
    result = PixivBrowserFactory.getBrowser(config=__config__).loginHttp(username, password)
  File "/Applications/PixivUtil/PixivBrowserFactory.py", line 178, in loginHttp
    self['pixiv_id'] = username
  File "/usr/local/lib/python2.7/site-packages/mechanize/_form.py", line 2780, in __setitem__
    control = self.find_control(name)
  File "/usr/local/lib/python2.7/site-packages/mechanize/_form.py", line 3101, in find_control
    return self._find_control(name, type, kind, id, label, predicate, nr)
  File "/usr/local/lib/python2.7/site-packages/mechanize/_form.py", line 3185, in _find_control
    raise ControlNotFoundError("no control matching "+description)
ControlNotFoundError: no control matching name 'pixiv_id'
```

**Comment by rogerlhc** [comment]
Thanks.
I'm using keepsignedin = 1,and it's working.
I think PixivUtil need an update to fix this.

**Comment by rogerlhc** [comment]
Thanks for the update.已发红包，查一下paypal吧 :)，恭喜发财~~~
