### ISSUE TITLE
Error when trying to download by tag 

### ISSUE THREAD

**Issue by VoidPrompt** [Nandaka/PixivUtil2#697]
```
PixivDownloader2 version 202000502
https://github.com/Nandaka/PixivUtil2/releases
Donate at https://bit.ly/PixivUtilDonation
1. Download by member_id
2. Download by image_id
3. Download by tags
4. Download from list
5. Download from bookmarked artists (/bookmark.php?type=user)
6. Download from bookmarked images (/bookmark.php)
7. Download from tags list
8. Download new illust from bookmarked members (/bookmark_new_illust.php)
9. Download by Title/Caption
10. Download by Tag and Member Id
11. Download Member Bookmark (/bookmark.php?id=)
12. Download by Group Id
------------------------
f1. Download from supported artists (FANBOX)
f2. Download by artist/creator id (FANBOX)
f3. Download by post id (FANBOX)
f4. Download from followed artists (FANBOX)
------------------------
b. Batch Download from batch_job.json (experimental)
------------------------
d. Manage database
e. Export online bookmark
m. Export online user bookmark
i. Import list file
r. Reload config.ini
p. Print config.ini
x. Exit
Input: 3
Tags: Arknights
Bookmark Count:
Use Partial Match (s_tag) [y/n]: n
Oldest first[y/n]: n
Start Page (default=1): 1
End Page (default=0, 0 for no limit): 1
Start Date [YYYY-MM-DD]:
End Date [YYYY-MM-DD]:
Search type [a-all|i-Illustration and Ugoira|m-manga: a
Reading D:\pixivutil20200502\config.ini ...
done.
Searching for: (Arknights) Arknights
Using Full Match (s_tag_full)
Error at process_tags() at page 1: (<class 'TypeError'>, TypeError("'>' not supported between instances of 'NoneType' and 'int'"), <traceback object at 0x0C352A48>)
Traceback (most recent call last):
  File "PixivUtil2.py", line 1577, in main
  File "PixivUtil2.py", line 1283, in main_loop
  File "PixivUtil2.py", line 726, in menu_download_by_tags
  File "PixivUtil2.py", line 191, in process_tags
  File "PixivTagsHandler.pyc", line 70, in process_tags
  File "PixivBrowserFactory.pyc", line 741, in getSearchTagPage
  File "PixivHelper.pyc", line 719, in generate_search_tag_url
TypeError: '>' not supported between instances of 'NoneType' and 'int'
press enter to exit.
```

I tried updating from 20200307 version and I can't download anymore with the option 3. 
Since no one mentioned this error yet I'm probably doing something wrong (I got the same error with the previous beta versions). 
I also tried with a clean installation but the error persists.

**Comment by Nandaka** [comment]
try https://github.com/Nandaka/PixivUtil2/releases/tag/v20200603-beta1

**Comment by VoidPrompt** [comment]
It works now. Thank you.
