### ISSUE TITLE
Missing attributes in module 'PixivException' when timeout occurs?

### ISSUE THREAD

**Issue by mugi-jiichan** [Nandaka/PixivUtil2#700]
### Prerequisites

* [  ] Did you read FAQ section? _yes_
* [  ] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ? _release_

### Description

Hi,

I did a clean upgrade yesterday. I removed all former files of the v20200424 and copy in all the new files of v20200502 while keeping blacklists and config files. However, whenever I pause a download with the pause key or there's a minor timeout in the internet connection (for example upon DSL reconnecting which happens each 24h at my location), PixivUtil2 now errors out since the new version.

### Steps to Reproduce

1. Clean install/upgrade and run PixivUtil2
2. Start download a larger number of files by either artist, tag or taglist etc.
3. Press the pause key at some point in order to simulate a short disconnect or timeout
4. Release the pause with any other key on the keyboard (if you hit Enter, the window may close)

**Expected behavior:** If the Pause key is pausing an actual download, PixivUtil2 restarts the download. If the Pause key is hit inbetween downloads, PixivUtil2 should work without issues.

**Actual behavior:** PixivUtil2 doesn't find the exception handles and exits to prompt with these Tracebacks:

```
Traceback (most recent call last):
  File "PixivDownloadHandler.pyc", line 136, in download_image
  File "PixivDownloadHandler.pyc", line 261, in perform_download
  File "PixivHelper.pyc", line 616, in download_image
  File "mechanize\_response.pyc", line 204, in read
  File "socket.pyc", line 669, in readinto
  File "http\client.pyc", line 498, in readinto
  File "socket.pyc", line 669, in readinto
  File "ssl.pyc", line 1241, in recv_into
  File "ssl.pyc", line 1099, in read
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PixivDownloadHandler.pyc", line 214, in download_image
AttributeError: module 'PixivException' has no attribute 'DOWNLOAD_FAILED_IO'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PixivImageHandler.pyc", line 205, in process_image
  File "PixivDownloadHandler.pyc", line 227, in download_image
AttributeError: module 'PixivException' has no attribute 'DOWNLOAD_FAILED_OTHER'
Error at process_image(): 8661195
Exception: (<class 'AttributeError'>, AttributeError("module 'PixivException' has no attribute 'DOWNLOAD_FAILED_OTHER'"), <traceback object at 0x00C11828>)
Dumping html to: Error medium page for image 8661195.html
Error at process_tags() at page 10: (<class 'AttributeError'>, AttributeError("module 'PixivException' has no attribute 'DOWNLOAD_FAILED_OTHER'"), <traceback object at 0x00C11EC8>)
Dumping html to: Error page for search tags %E3%83%89%E3%83%A9%E3%82%B4%E3%83%B3%E3%83%9C%E3%83%BC%E3%83%AB at page 10.html
Error at process_tags_list(): (<class 'AttributeError'>, AttributeError("module 'PixivException' has no attribute 'DOWNLOAD_FAILED_OTHER'"), <traceback object at 0x00C113E8>)
Traceback (most recent call last):
  File "PixivDownloadHandler.pyc", line 136, in download_image
  File "PixivDownloadHandler.pyc", line 261, in perform_download
  File "PixivHelper.pyc", line 616, in download_image
  File "mechanize\_response.pyc", line 204, in read
  File "socket.pyc", line 669, in readinto
  File "http\client.pyc", line 498, in readinto
  File "socket.pyc", line 669, in readinto
  File "ssl.pyc", line 1241, in recv_into
  File "ssl.pyc", line 1099, in read
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PixivDownloadHandler.pyc", line 214, in download_image
AttributeError: module 'PixivException' has no attribute 'DOWNLOAD_FAILED_IO'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PixivUtil2.py", line 1577, in main
  File "PixivUtil2.py", line 1291, in main_loop
  File "PixivUtil2.py", line 895, in menu_download_from_tags_list
  File "PixivUtil2.py", line 215, in process_tags_list
  File "PixivUtil2.py", line 191, in process_tags
  File "PixivTagsHandler.pyc", line 126, in process_tags
  File "PixivImageHandler.pyc", line 205, in process_image
  File "PixivDownloadHandler.pyc", line 227, in download_image
AttributeError: module 'PixivException' has no attribute 'DOWNLOAD_FAILED_OTHER'
press enter to exit.
```

### Versions

PixivDownloader2 version 202000502

**Comment by AgentThirteen** [comment]
Getting the same issue with the latest release, every timeout will fatal due to the missing exception handle (if you also happen to be affected by #686 this will make pixivutil unusable).

**Comment by Nandaka** [comment]
my fault, wrong import :P
