### ISSUE TITLE
Process fatals with PermissionError when accidentally fetching twice simultaneously instead of retrying and continuing

### ISSUE THREAD

**Issue by AgentThirteen** [Nandaka/PixivUtil2#702]
This may be the result of a previous fix. Potential enhancement if not a bug.

### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Process fatals with `PermissionError` instead of putting the file on hold and retrying as it was before.
Retrying still is in the code (see arrows) and there are cascading errors so this may still be a bug.

No keyboard interrupt command was sent. Cascading process fatal happened on its own.
```
Traceback (most recent call last):
  File "*\PixivDownloadHandler.py", line 136, in download_image
    (downloadedSize, filename_save) = perform_download(url, remote_file_size, filename_save, overwrite, config, referer)
  File "*\PixivDownloadHandler.py", line 261, in perform_download
    (downloadedSize, filename) = PixivHelper.download_image(url, filename, res, file_size, overwrite)
  File "*\PixivHelper.py", line 656, in download_image
    os.rename(filename + '.pixiv', filename)
PermissionError: [WinError 32] * Error at download_image(): (<class 'PermissionError'>, PermissionError(13, '*'), <traceback object at 0x0000012DEA29DE40>) at * (9001)
Retrying <--

Traceback (most recent call last):
  File "*\PixivDownloadHandler.py", line 136, in download_image
    (downloadedSize, filename_save) = perform_download(url, remote_file_size, filename_save, overwrite, config, referer)
  File "*\PixivDownloadHandler.py", line 261, in perform_download
    (downloadedSize, filename) = PixivHelper.download_image(url, filename, res, file_size, overwrite)
  File "*\PixivHelper.py", line 656, in download_image
    os.rename(filename + '.pixiv', filename)
PermissionError: [WinError 32] *

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "*\PixivImageHandler.py", line 205, in process_image
    (result, filename) = PixivDownloadHandler.download_image(caller,
  File "*\PixivDownloadHandler.py", line 236, in download_image
    PixivHelper.print_delay(config.retryWait, notification_handler)
  File "*\PixivHelper.py", line 559, in print_delay
    notification_handler(None, t, newline=False)
  File "*\PixivHelper.py", line 447, in print_and_log
    safePrint(msg, newline, end)
  File "*\PixivHelper.py", line 253, in safePrint
    for msgToken in msg.split(' '):
AttributeError: 'int' object has no attribute 'split' <--
 [1]... Error at process_image(): * <--
Exception: (<class 'AttributeError'>, AttributeError("'int' object has no attribute 'split'"), <traceback object at 0x0000012DEA2EA4C0>) <--
Dumping html to: Error medium page for image *.html
Error at process_new_illust_from_bookmark(): (<class 'AttributeError'>, AttributeError("'int' object has no attribute 'split'"), <traceback object at 0x0000012DEA2EA940>) <--
Traceback (most recent call last):
  File "*\PixivDownloadHandler.py", line 136, in download_image
    (downloadedSize, filename_save) = perform_download(url, remote_file_size, filename_save, overwrite, config, referer)
  File "*\PixivDownloadHandler.py", line 261, in perform_download
    (downloadedSize, filename) = PixivHelper.download_image(url, filename, res, file_size, overwrite)
  File "*\PixivHelper.py", line 656, in download_image
    os.rename(filename + '.pixiv', filename)
PermissionError: [WinError 32] *

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pixivutil2.py", line 1577, in main
    np_is_valid, op_is_valid, selection = main_loop(ewd, op_is_valid, selection, np_is_valid, args)
  File "pixivutil2.py", line 1293, in main_loop
    menu_download_new_illust_from_bookmark(op_is_valid, args)
  File "pixivutil2.py", line 907, in menu_download_new_illust_from_bookmark
    process_new_illust_from_bookmark(page_num, end_page_num)
  File "pixivutil2.py", line 426, in process_new_illust_from_bookmark
    result = process_image(artist=None, image_id=int(image_id))
  File "pixivutil2.py", line 177, in process_image
    return PixivImageHandler.process_image(sys.modules[__name__],
  File "*\PixivImageHandler.py", line 205, in process_image
    (result, filename) = PixivDownloadHandler.download_image(caller,
  File "*\PixivDownloadHandler.py", line 236, in download_image
    PixivHelper.print_delay(config.retryWait, notification_handler)
  File "*\PixivHelper.py", line 559, in print_delay
    notification_handler(None, t, newline=False)
  File "*\PixivHelper.py", line 447, in print_and_log
    safePrint(msg, newline, end)
  File "*\PixivHelper.py", line 253, in safePrint
    for msgToken in msg.split(' '):
AttributeError: 'int' object has no attribute 'split' <--
```
### Steps to Reproduce

1. Running two processes that will accidentally call for the same file at some point
2. Process fatals on `PermissionError`

**Expected behavior:** Lock process, skip (ideal) or leave behind a .pixiv duplicate file (previous behavior) and continue running

**Actual behavior:** Process fatals with cascading errors and exits while dumping a html file

### Versions

`20200503-beta1` 2900838

I am not sure when this started but the latest commit itself is not responsible for this of course.

**Comment by AgentThirteen** [comment]
This also applies to timeouts so I will revert to the last known working version for the time being.
The dump looks very similar (see AttributeError).

**Comment by Nandaka** [comment]
can you try latest commit?

**Comment by AgentThirteen** [comment]
Haha, I edited the title right after you committed. Okay thanks Nandaka, going to try and report back.

**Comment by Nandaka** [comment]
based on the logging, the root cause is due to `PixivHelper.safePrint()` method handling for `print_delay()` method, as it try to split `int` type due to refactoring the code, other than that no changes on the error handling.

**Comment by AgentThirteen** [comment]
Ah thank you for the thorough explanation Nandaka.

I can confirm the error handling is now working as intended and properly resumes on a timeout (it took about 3 hours and 6 MB of full debug logging for a timeout to finally happen even below 10KB/s).
