### ISSUE TITLE
Fatal exception on VPN disconnect when downloading from fanbox

### ISSUE THREAD

**Issue by NHOrus** [Nandaka/PixivUtil2#709]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

When I disconnected from VPN in the middle of downloading from Fanbox, I got terminal exception and PixivUtil2 shut down

### Steps to Reproduce

1. Start downloading from fanbox
2. Turn off VPN
3. Look at pixivutil

**Expected behavior:** [What you expected to happen]

Same as with normal Pixiv download, correctly managed exceptions, download resumes

**Actual behavior:** [What actually happened]

```
2020-05-10 13:30:07,226 - PixivUtil202000501-beta3 - ERROR - Traceback (most recent call last):
  File "mechanize\_urllib2_fork.pyc", line 1229, in do_open
  File "http\client.pyc", line 1230, in request
  File "http\client.pyc", line 1276, in _send_request
  File "http\client.pyc", line 1225, in endheaders
  File "http\client.pyc", line 1004, in _send_output
  File "http\client.pyc", line 944, in send
  File "http\client.pyc", line 1399, in connect
  File "ssl.pyc", line 500, in wrap_socket
  File "ssl.pyc", line 1040, in _create
  File "ssl.pyc", line 1309, in do_handshake
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PixivDownloadHandler.pyc", line 136, in download_image
  File "PixivDownloadHandler.pyc", line 252, in perform_download
  File "mechanize\_mechanize.pyc", line 237, in open_novisit
  File "mechanize\_mechanize.pyc", line 283, in _mech_open
  File "mechanize\_opener.pyc", line 193, in open
  File "mechanize\_urllib2_fork.pyc", line 425, in _open
  File "mechanize\_urllib2_fork.pyc", line 414, in _call_chain
  File "mechanize\_urllib2_fork.pyc", line 1276, in https_open
  File "mechanize\_urllib2_fork.pyc", line 1233, in do_open
urllib.error.URLError: <urlopen error [WinError 10054] Удаленный хост принудительно разорвал существующее подключение>

2020-05-10 13:30:07,291 - PixivUtil202000501-beta3 - ERROR - Unknown Error: module 'PixivException' has no attribute 'DOWNLOAD_FAILED_OTHER'
Traceback (most recent call last):
  File "mechanize\_urllib2_fork.pyc", line 1229, in do_open
  File "http\client.pyc", line 1230, in request
  File "http\client.pyc", line 1276, in _send_request
  File "http\client.pyc", line 1225, in endheaders
  File "http\client.pyc", line 1004, in _send_output
  File "http\client.pyc", line 944, in send
  File "http\client.pyc", line 1399, in connect
  File "ssl.pyc", line 500, in wrap_socket
  File "ssl.pyc", line 1040, in _create
  File "ssl.pyc", line 1309, in do_handshake
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PixivDownloadHandler.pyc", line 136, in download_image
  File "PixivDownloadHandler.pyc", line 252, in perform_download
  File "mechanize\_mechanize.pyc", line 237, in open_novisit
  File "mechanize\_mechanize.pyc", line 283, in _mech_open
  File "mechanize\_opener.pyc", line 193, in open
  File "mechanize\_urllib2_fork.pyc", line 425, in _open
  File "mechanize\_urllib2_fork.pyc", line 414, in _call_chain
  File "mechanize\_urllib2_fork.pyc", line 1276, in https_open
  File "mechanize\_urllib2_fork.pyc", line 1233, in do_open
urllib.error.URLError: <urlopen error [WinError 10054] Удаленный хост принудительно разорвал существующее подключение>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PixivDownloadHandler.pyc", line 207, in download_image
AttributeError: module 'PixivException' has no attribute 'DOWNLOAD_FAILED_NETWORK'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PixivUtil2.py", line 1566, in main
    else:
  File "PixivUtil2.py", line 1307, in main_loop
    raise
  File "PixivUtil2.py", line 1001, in menu_fanbox_download_from_artist
    continue
  File "PixivUtil2.py", line 1042, in processFanboxArtist
    gc.collect()
  File "PixivUtil2.py", line 1137, in processFanboxImages
    print("Image #" + str(image_count))
  File "PixivUtil2.py", line 96, in download_image
    dfilename = ""
  File "PixivDownloadHandler.pyc", line 227, in download_image
AttributeError: module 'PixivException' has no attribute 'DOWNLOAD_FAILED_OTHER'
```

### Versions
PixivUtil202000501-beta3

**Comment by Nandaka** [comment]
can try the latest releases? https://github.com/Nandaka/PixivUtil2/releases

**Comment by NHOrus** [comment]
Closing it, will reopen if repeats.

**Comment by NHOrus** [comment]
```
Start downloading... [download_image()] URL Error: <urlopen error [Errno 11004] getaddrinfo failed> at https://downloads.fanbox.cc/images/post/95786/8eV0maYx59FNj7Ai3NYaM4Wf.jpeg
Traceback (most recent call last):
  File "mechanize\_urllib2_fork.pyc", line 1229, in do_open
  File "http\client.pyc", line 1230, in request
  File "http\client.pyc", line 1276, in _send_request
  File "http\client.pyc", line 1225, in endheaders
  File "http\client.pyc", line 1004, in _send_output
  File "http\client.pyc", line 944, in send
  File "http\client.pyc", line 1392, in connect
  File "http\client.pyc", line 915, in connect
  File "socket.pyc", line 787, in create_connection
  File "socket.pyc", line 914, in getaddrinfo
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PixivDownloadHandler.pyc", line 136, in download_image
  File "PixivDownloadHandler.pyc", line 252, in perform_download
  File "mechanize\_mechanize.pyc", line 237, in open_novisit
  File "mechanize\_mechanize.pyc", line 283, in _mech_open
  File "mechanize\_opener.pyc", line 193, in open
  File "mechanize\_urllib2_fork.pyc", line 425, in _open
  File "mechanize\_urllib2_fork.pyc", line 414, in _call_chain
  File "mechanize\_urllib2_fork.pyc", line 1276, in https_open
  File "mechanize\_urllib2_fork.pyc", line 1233, in do_open
urllib.error.URLError: <urlopen error [Errno 11004] getaddrinfo failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PixivDownloadHandler.pyc", line 207, in download_image
AttributeError: module 'PixivException' has no attribute 'DOWNLOAD_FAILED_NETWORK'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PixivUtil2.py", line 1577, in main
    except BaseException:
  File "PixivUtil2.py", line 1318, in main_loop
    if process_external:
  File "PixivUtil2.py", line 1004, in menu_fanbox_download_from_artist
    try:
  File "PixivUtil2.py", line 1045, in processFanboxArtist
    choice = input("Keyboard Interrupt detected, continue to next image (Y/N)").rstrip("\r")
  File "PixivUtil2.py", line 1144, in processFanboxImages
    raise
  File "PixivUtil2.py", line 96, in download_image
    dfilename = ""
  File "PixivDownloadHandler.pyc", line 227, in download_image
AttributeError: module 'PixivException' has no attribute 'DOWNLOAD_FAILED_OTHER'
press enter to exit.
```

**Comment by Nandaka** [comment]
which version is that one?

**Comment by NHOrus** [comment]
20200503-beta1

**Comment by Nandaka** [comment]
Try latest releases?
