### ISSUE TITLE
Escape sequence CTRL+C doesn't stop Fanbox download

### ISSUE THREAD

**Issue by photonometric** [Nandaka/PixivUtil2#744]
[release 2020-07-12, windows 7]

This is related to an old bug/feature **Escape sequence doesn't always stop process #92**

Fanbox downloading seems to behave similarly to the description in the first post of #92, of how main pixiv downloading once worked. Hitting CTRL+C _only cancels the current image download_. The program then immediately goes on to the next download. Hitting CTRL+C again repeats this. Even hitting repeatedly doesn't stop it....one has to press C rapidly like 6-7 times.

```
2020-07-24 04:40:02,927 - PixivUtil20200712 - ERROR - Downloaded file incomplete!    876544 of   2691319 Bytes
2020-07-24 04:40:02,937 - PixivUtil20200712 - ERROR - Traceback (most recent call last):
  File "PixivHelper.pyc", line 625, in download_image
  File "mechanize\_response.pyc", line 204, in read
  File "socket.pyc", line 669, in readinto
  File "http\client.pyc", line 498, in readinto
  File "socket.pyc", line 669, in readinto
  File "ssl.pyc", line 1241, in recv_into
  File "ssl.pyc", line 1099, in read
KeyboardInterrupt

The log shows this error, situated at the first press of CTRL+C (although it isn't displayed in the program until successfully spamming very quicly 6 times or so):

2020-07-24 04:40:02,937 - PixivUtil20200712 - ERROR - Filename = [file]
2020-07-24 04:40:02,937 - PixivUtil20200712 - ERROR - Traceback (most recent call last):
  File "PixivHelper.pyc", line 625, in download_image
  File "mechanize\_response.pyc", line 204, in read
  File "socket.pyc", line 669, in readinto
  File "http\client.pyc", line 498, in readinto
  File "socket.pyc", line 669, in readinto
  File "ssl.pyc", line 1241, in recv_into
  File "ssl.pyc", line 1099, in read
KeyboardInterrupt

2020-07-24 04:40:02,947 - PixivUtil20200712 - ERROR - URL      = [URL]
2020-07-24 04:40:02,947 - PixivUtil20200712 - ERROR - Traceback (most recent call last):
  File "PixivHelper.pyc", line 625, in download_image
  File "mechanize\_response.pyc", line 204, in read
  File "socket.pyc", line 669, in readinto
  File "http\client.pyc", line 498, in readinto
  File "socket.pyc", line 669, in readinto
  File "ssl.pyc", line 1241, in recv_into
  File "ssl.pyc", line 1099, in read
KeyboardInterrupt

2020-07-24 04:40:02,947 - PixivUtil20200712 - INFO - Aborted by user request => Ctrl-C
2020-07-24 04:40:02,947 - PixivUtil20200712 - DEBUG - Download None result: 9999
```

The log then shows cycles of this equal to the number of CTRL+C necessary to close the program:
```
2020-07-24 04:40:23,719 - PixivUtil20200712 - DEBUG - Sanitized Filename: [next file]
2020-07-24 04:40:23,729 - PixivUtil20200712 - INFO - Using Referer: [next URL]
2020-07-24 04:40:24,039 - PixivUtil20200712 - INFO - Aborted by user request => Ctrl-C
2020-07-24 04:40:24,049 - PixivUtil20200712 - DEBUG - Download None result: 9999
```

Ideally, the first CTRL+C would bring up the prompt `Keyboard Interrupt detected, continue to next image (Y/N)` as when using the main pixiv site ^^

**Comment by bluerthanever** [comment]
will work on that.

**Comment by bluerthanever** [comment]
Forgot to update here. This should have been fixed already.
