### ISSUE TITLE
HTTP Error 401: Unauthorized error when trying to download bookmarks.

### ISSUE THREAD

**Issue by AHairyGameDev** [Nandaka/PixivUtil2#762]
### Prerequisites

* [X ] Did you read FAQ section?
* [X ] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Error at process_image_bookmark(): (<class 'mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib.error.HTTPError instance) at 0xc600580 whose wrapped object = <HTTPError 401: 'Unauthorized'>>, <traceback object at 0x0C8BD548>)
Traceback (most recent call last):
  File "PixivUtil2.py", line 1476, in main
  File "PixivUtil2.py", line 1183, in main_loop
  File "PixivUtil2.py", line 894, in menu_download_from_online_image_bookmark
  File "PixivUtil2.py", line 246, in process_image_bookmark
  File "PixivUtil2.py", line 300, in get_image_bookmark
  File "mechanize\_mechanize.pyc", line 253, in open
  File "mechanize\_mechanize.pyc", line 309, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 401: Unauthorized

### Steps to Reproduce
1.  Login
2. Use option 6 with default options

**Expected behavior:** Download my bookmarks

**Actual behavior:** An unauthorized error was thrown

### Versions

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by Nandaka** [comment]
any issue with other option?

**Comment by AHairyGameDev** [comment]
> 
> 
> any issue with other option? also, upload the log file.

I went to try just downloading via ID and got this:
>


>Error at processing Artist Info: (<class 'json.decoder.JSONDecodeError'>, JSONDecodeError('Expecting value: line 1 column 1 (char 0)'), <traceback object at 0x0C2FC4E8>)

Repeated over and over for each image. Followed by picking a user with only a few images which seemed to be fine... but downloaded nothing. And sorry, here is the log file
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/5060141/pixivutil.log)

**Comment by Nandaka** [comment]
```
2020-08-11 17:49:14,890 - PixivUtil20200726 - INFO - Logged in using cookie
2020-08-11 17:49:14,892 - PixivUtil20200726 - INFO - Unable to get User Id
2020-08-11 17:49:14,894 - PixivUtil20200726 - INFO - Premium User: False.
2020-08-11 17:49:14,894 - PixivUtil20200726 - INFO - Locale = 
```

most likely the cookie invalid because it cannot get your account info that's why it return 401 Unauthorize. Double check your cookies?

**Comment by AHairyGameDev** [comment]
I went and copied the cookie again and that fixed it. Somehow I missed a character.
