### ISSUE TITLE
[20150427] Problem: Getting logged out in the process?

### ISSUE THREAD

**Issue by reyaz006** [Nandaka/PixivUtil2#77]
My list.txt is quite long, and sometimes during batch-downloading PixivUtil2 stops downloading anything properly at all - first it shows some error in mid-downloading an image:
<pre>Error at download_image(): (<class 'PixivException.PixivException'>, PixivException(), <traceback object at 0x031647B0>) at http://... (9000)</pre>then it retries to download the same image, finds a broken file (half-downloaded before that error) and surprisingly downloads it properly but it takes around 10 minutes. After that, however, it fails to process any further images for current member:<pre>2015-05-03 17:38:07,309 - PixivUtil20150427 - INFO - Image ID (...): 'NoneType' object has no attribute 'findAll'</pre>and then fails to process all further members in the list. I think it's because somehow cookies get invalidated (for whatever reason - I could login with other app or browser for example) - at this point client needs to login again, but it doesn't happen.

The log looks like this for each such failed member:
<pre>2015-05-03 17:38:38,448 - PixivUtil20150427 - INFO - Processing Member Id: 182493
2015-05-03 17:38:38,490 - PixivUtil20150427 - INFO - Member Url: http://www.pixiv.net/member_illust.php?id=182493&p=1
2015-05-03 17:38:46,552 - PixivUtil20150427 - ERROR - Error at process_member(): (<type 'exceptions.AttributeError'>, AttributeError("'NoneType' object has no attribute 'findAll'",), <traceback object at 0x02F7BE90>)
2015-05-03 17:38:46,552 - PixivUtil20150427 - ERROR - Error at process_member(): 182493
Traceback (most recent call last):
  File "PixivUtil2.py", line 272, in process_member
  File "PixivModel.pyc", line 48, in __init__
  File "PixivModel.pyc", line 96, in ParseImages
AttributeError: 'NoneType' object has no attribute 'findAll'
2015-05-03 17:38:46,556 - PixivUtil20150427 - ERROR - Dumping html to: Error page for member 182493.html</pre>

What can be done in my opinion:
1. Do not save a file under its final name if there was an error during the process of downloading it.
2. If there is an error during the process of retrieving information for image that was already put into the queue for current member, or during the process of retrieving image list for some member page - check if client is properly logged in (e.g. usual pages like msgbox.php should not redirect anywhere), and if it is not - try to login again.
3. If logging in again fails for 3-5 times straight, maybe it's better to stop processing the whole list and let the user acknowledge the error.

**Comment by Nandaka** [comment]
try to delete the cookies and set keepSignedIn=True on config.ini ?

**Comment by reyaz006** [comment]
Sorry, my bad. I see it is already in readme.
