### ISSUE TITLE
Pixiv Update - Basically nothing works anymore

### ISSUE THREAD

**Issue by mugi-jiichan** [Nandaka/PixivUtil2#774]
### Prerequisites

* [ x ] Did you read FAQ section?
* [ x ] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ? release

### Description

Hi,

apparently pixiv has changed its API within the last 36 hours. I had to relog into Pixiv via browser and had to change my "insecure" password. My account is not blocked or anything. I can access and surf on the site, look at images, use search etc.

### Steps to Reproduce

1. Start any option and proceed as intended with any option

**Expected behavior:** [What you expected to happen]

pixivUtil parses API/Website and starts to process/download.

**Actual behavior:** [What actually happened]

"1. Download by member_id" turns into an infinite loop:

Traceback (most recent call last):
  File "PixivArtistHandler.pyc", line 77, in process_member
  File "PixivBrowserFactory.pyc", line 723, in getMemberPage
  File "PixivBrowserFactory.pyc", line 615, in getMemberInfoWhitecube
  File "json\__init__.pyc", line 357, in loads
  File "json\decoder.pyc", line 337, in decode
  File "json\decoder.pyc", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Error at processing Artist Info: (<class 'json.decoder.JSONDecodeError'>, JSONDecodeError('Expecting value: line 1 column 1 (char 0)'), <traceback object at 0x00D96DC8>)

'2. Download by image_id' stops with an error, but returns to the menu:

Image ID (69900869): Expecting value: line 1 column 1 (char 0)
Stack Trace: (<class 'json.decoder.JSONDecodeError'>, JSONDecodeError('Expecting value: line 1 column 1 (char 0)'), <traceback object at 0x0B93B4A8>)
Traceback (most recent call last):
  File "PixivImageHandler.pyc", line 71, in process_image
  File "PixivBrowserFactory.pyc", line 586, in getImagePage
  File "PixivBrowserFactory.pyc", line 615, in getMemberInfoWhitecube
  File "json\__init__.pyc", line 357, in loads
  File "json\decoder.pyc", line 337, in decode
  File "json\decoder.pyc", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Both '5. Download from bookmarked artists (/bookmark.php?type=user)' and '8. Download new illust from bookmarked members (/bookmark_new_illust.php)' stop and exit the tool:
Image ID (69900869): Expecting value: line 1 column 1 (char 0)
Stack Trace: (<class 'json.decoder.JSONDecodeError'>, JSONDecodeError('Expecting value: line 1 column 1 (char 0)'), <traceback object at 0x0DF55428>)
Traceback (most recent call last):
  File "PixivUtil2.py", line 662, in process_image
  File "PixivBrowserFactory.pyc", line 471, in getImagePage
  File "PixivBrowserFactory.pyc", line 500, in getMemberInfoWhitecube
  File "json\__init__.pyc", line 357, in loads
  File "json\decoder.pyc", line 337, in decode
  File "json\decoder.pyc", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I haven't tested '3. Download by tags' nor '7. Download from tags list' which were my other to-go options.

### Versions

20200824
202000424

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by Nandaka** [comment]
looks good from my side, try to update your cookies?

**Comment by mugi-jiichan** [comment]
Hi. I did that because I had to relog with the browser. The config file has the current PHPSESSION id. But I try again and clear the pixiv cookie first.

**Comment by mugi-jiichan** [comment]
Shoot... I copied a very cookie from an old local Firefox profile using a 3rd party tool after I reset the password in the Portable Firefox from the flash drive ... typical PEBKAC error. >_________________<

Thank you for the quick response. Sorry for making a fuss.
