### ISSUE TITLE
Download from tags list error

### ISSUE THREAD

**Issue by forrenren** [Nandaka/PixivUtil2#778]
### Prerequisites

* [Y] Did you read FAQ section?
* [Y] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description
Version 20200824
I choose "7. Download from tags list", it will report error after config.

Version 20200726 does NOT have this problem, so I roll back to 20200726.

[LOG]
===log from screen===
Input: 7
Tags list filename [tags.txt]: 0.txt
Use Wildcard[y/n]: y
Oldest first[y/n]: n
Bookmark Count:
Start Page (default=1):
End Page (default=0, 0 for no limit):
Start Date [YYYY-MM-DD]:
End Date [YYYY-MM-DD]:
Reading: 0.txt
Reading x:\pixiv\config.ini ...
Configuration loaded.
Error at process_tags() at page 1: (<class 'AttributeError'>, AttributeError("'list' object has no attribute 'startswith'"), <traceback object at 0x0B972E28>)
Error at process_tags_list(): (<class 'AttributeError'>, AttributeError("'list' object has no attribute 'startswith'"), <traceback object at 0x0B979208>)
Traceback (most recent call last):
  File "PixivUtil2.py", line 1555, in main
  File "PixivUtil2.py", line 1259, in main_loop
  File "PixivUtil2.py", line 942, in menu_download_from_tags_list
  File "PixivUtil2.py", line 184, in process_tags_list
  File "PixivTagsHandler.pyc", line 48, in process_tags
  File "PixivHelper.pyc", line 992, in decode_tags
AttributeError: 'list' object has no attribute 'startswith'
press enter to exit.
===end log from screen===

==log from file===
2020-08-27 14:21:30,241 - PixivUtil20200824 - INFO - Premium User: False.
2020-08-27 14:21:30,241 - PixivUtil20200824 - INFO - Locale = 
2020-08-27 14:21:32,222 - PixivUtil20200824 - INFO - Taglist mode (7).
2020-08-27 14:21:40,597 - PixivUtil20200824 - ERROR - Error at process_tags() at page 1: (<class 'AttributeError'>, AttributeError("'list' object has no attribute 'startswith'"), <traceback object at 0x0B972E28>)
2020-08-27 14:21:40,597 - PixivUtil20200824 - ERROR - Traceback (most recent call last):
  File "PixivTagsHandler.pyc", line 48, in process_tags
  File "PixivHelper.pyc", line 992, in decode_tags
AttributeError: 'list' object has no attribute 'startswith'

2020-08-27 14:21:40,600 - PixivUtil20200824 - ERROR - Error at process_tags_list(): (<class 'AttributeError'>, AttributeError("'list' object has no attribute 'startswith'"), <traceback object at 0x0B979208>)
2020-08-27 14:21:40,600 - PixivUtil20200824 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 184, in process_tags_list
  File "PixivTagsHandler.pyc", line 48, in process_tags
  File "PixivHelper.pyc", line 992, in decode_tags
AttributeError: 'list' object has no attribute 'startswith'

2020-08-27 14:21:40,605 - PixivUtil20200824 - ERROR - Unknown Error: 'list' object has no attribute 'startswith'
Traceback (most recent call last):
  File "PixivUtil2.py", line 1555, in main
  File "PixivUtil2.py", line 1259, in main_loop
  File "PixivUtil2.py", line 942, in menu_download_from_tags_list
  File "PixivUtil2.py", line 184, in process_tags_list
  File "PixivTagsHandler.pyc", line 48, in process_tags
  File "PixivHelper.pyc", line 992, in decode_tags
AttributeError: 'list' object has no attribute 'startswith'
===end log from file===

**Comment by Nandaka** [comment]
yep, got typo when migrating....

**Comment by Nandaka** [comment]
can try: https://github.com/Nandaka/PixivUtil2/releases/tag/v20200827-beta1

**Comment by forrenren** [comment]
okay, will do, thank you so much.

**Comment by forrenren** [comment]
v20200827-beta1 is okay, thank you so much.
