### ISSUE TITLE
Time out errors

### ISSUE THREAD

**Issue by GerhardSauer** [Nandaka/PixivUtil2#792]
Following versions were tested:
v20200824
v20200827-beta1
v20200915 (latest)

I have seen no new commits and no issue with the topic.
config values
timeout = 60
retry = 3
retrywait = 5
downloaddelay = 3

logs indicate, this started 09.09.2020

### Description

I get timeout errors and the pictures are not downloaded.
I observed this since yesterday and it is the same today.

There are different scenarios, either the script stops after the first time out:
Source URL: https://www.pixiv.net/bookmark_new_illust.php?p=1
Error at process_new_illust_from_bookmark(): (<class 'socket.timeout'>, timeout('The read operation timed out'), <traceback object at 0x0C6FFC88>)
Traceback (most recent call last):
  File "PixivUtil2.py", line 1146, in main
  File "PixivUtil2.py", line 863, in main_loop
  File "PixivUtil2.py", line 551, in menu_download_new_illust_from_bookmark
  File "PixivBookmarkHandler.pyc", line 115, in process_new_illust_from_bookmark
  File "mechanize\_response.pyc", line 199, in read
  File "socket.pyc", line 669, in readinto
  File "http\client.pyc", line 488, in readinto
  File "http\client.pyc", line 593, in _readinto_chunked
  File "http\client.pyc", line 616, in _safe_readinto
  File "socket.pyc", line 669, in readinto
  File "ssl.pyc", line 1241, in recv_into
  File "ssl.pyc", line 1099, in read
socket.timeout: The read operation timed out
press enter to exit.

Or the script runs through while some pictures are downloaded and others are not.
Processing Image Id: 84370433
Image ID (84370433): The read operation timed out
Stack Trace: (<class 'socket.timeout'>, timeout('The read operation timed out'), <traceback object at 0x00D6D0A8>)
Traceback (most recent call last):
  File "PixivImageHandler.pyc", line 75, in process_image
  File "PixivBrowserFactory.pyc", line 550, in getImagePage
  File "PixivBrowserFactory.pyc", line 235, in getPixivPage
  File "mechanize\_response.pyc", line 199, in read
  File "socket.pyc", line 669, in readinto
  File "http\client.pyc", line 488, in readinto
  File "http\client.pyc", line 583, in _readinto_chunked
  File "http\client.pyc", line 551, in _get_chunk_left
  File "http\client.pyc", line 511, in _read_next_chunk_size
  File "socket.pyc", line 669, in readinto
  File "ssl.pyc", line 1241, in recv_into
  File "ssl.pyc", line 1099, in read
socket.timeout: The read operation timed out
Wait for 2.46s
Image #108

Or the script closes directly with an error.

### Steps to Reproduce

with parameters as well as interactive, the timeout occurs.
I use option 8, download latest from bookmarks

### Log entries

2020-09-09 18:18:02,201 - PixivUtil20200726 - ERROR - Image ID (84269486): The read operation timed out
2020-09-09 18:18:02,232 - PixivUtil20200726 - ERROR - Traceback (most recent call last):
  File "PixivImageHandler.pyc", line 71, in process_image
  File "PixivBrowserFactory.pyc", line 549, in getImagePage
  File "PixivBrowserFactory.pyc", line 234, in getPixivPage
  File "mechanize\_response.pyc", line 199, in read
  File "socket.pyc", line 669, in readinto
  File "http\client.pyc", line 488, in readinto
  File "http\client.pyc", line 593, in _readinto_chunked
  File "http\client.pyc", line 616, in _safe_readinto
  File "socket.pyc", line 669, in readinto
  File "ssl.pyc", line 1241, in recv_into
  File "ssl.pyc", line 1099, in read
socket.timeout: The read operation timed out

2020-09-09 18:18:02,232 - PixivUtil20200726 - ERROR - Stack Trace: (<class 'socket.timeout'>, timeout('The read operation timed out'), <traceback object at 0x0C4354A8>)
2020-09-09 18:18:02,232 - PixivUtil20200726 - ERROR - Traceback (most recent call last):
  File "PixivImageHandler.pyc", line 71, in process_image
  File "PixivBrowserFactory.pyc", line 549, in getImagePage
  File "PixivBrowserFactory.pyc", line 234, in getPixivPage
  File "mechanize\_response.pyc", line 199, in read
  File "socket.pyc", line 669, in readinto
  File "http\client.pyc", line 488, in readinto
  File "http\client.pyc", line 593, in _readinto_chunked
  File "http\client.pyc", line 616, in _safe_readinto
  File "socket.pyc", line 669, in readinto
  File "ssl.pyc", line 1241, in recv_into
  File "ssl.pyc", line 1099, in read
socket.timeout: The read operation timed out

___

2020-09-15 09:53:33,372 - PixivUtil20200827-beta1 - ERROR - Error at process_new_illust_from_bookmark(): (<class 'socket.timeout'>, timeout('The read operation timed out'), <traceback object at 0x0140AE28>)
2020-09-15 09:53:33,388 - PixivUtil20200827-beta1 - ERROR - Traceback (most recent call last):
  File "PixivBookmarkHandler.pyc", line 115, in process_new_illust_from_bookmark
  File "mechanize\_response.pyc", line 199, in read
  File "socket.pyc", line 669, in readinto
  File "http\client.pyc", line 488, in readinto
  File "http\client.pyc", line 588, in _readinto_chunked
  File "http\client.pyc", line 616, in _safe_readinto
  File "socket.pyc", line 669, in readinto
  File "ssl.pyc", line 1241, in recv_into
  File "ssl.pyc", line 1099, in read
socket.timeout: The read operation timed out

2020-09-15 09:53:33,403 - PixivUtil20200827-beta1 - ERROR - Unknown Error: The read operation timed out
Traceback (most recent call last):
  File "PixivUtil2.py", line 1144, in main
  File "PixivUtil2.py", line 861, in main_loop
  File "PixivUtil2.py", line 549, in menu_download_new_illust_from_bookmark
  File "PixivBookmarkHandler.pyc", line 115, in process_new_illust_from_bookmark
  File "mechanize\_response.pyc", line 199, in read
  File "socket.pyc", line 669, in readinto
  File "http\client.pyc", line 488, in readinto
  File "http\client.pyc", line 588, in _readinto_chunked
  File "http\client.pyc", line 616, in _safe_readinto
  File "socket.pyc", line 669, in readinto
  File "ssl.pyc", line 1241, in recv_into
  File "ssl.pyc", line 1099, in read
socket.timeout: The read operation timed out
2020-09-15 09:53:33,419 - PixivUtil20200827-beta1 - INFO - EXIT: -1
___

2020-09-15 10:03:29,304 - PixivUtil20200915 - ERROR - Error at process_new_illust_from_bookmark(): (<class 'socket.timeout'>, timeout('The read operation timed out'), <traceback object at 0x0C6FFC88>)
2020-09-15 10:03:29,304 - PixivUtil20200915 - ERROR - Traceback (most recent call last):
  File "PixivBookmarkHandler.pyc", line 115, in process_new_illust_from_bookmark
  File "mechanize\_response.pyc", line 199, in read
  File "socket.pyc", line 669, in readinto
  File "http\client.pyc", line 488, in readinto
  File "http\client.pyc", line 593, in _readinto_chunked
  File "http\client.pyc", line 616, in _safe_readinto
  File "socket.pyc", line 669, in readinto
  File "ssl.pyc", line 1241, in recv_into
  File "ssl.pyc", line 1099, in read
socket.timeout: The read operation timed out

2020-09-15 10:03:29,319 - PixivUtil20200915 - ERROR - Unknown Error: The read operation timed out
Traceback (most recent call last):
  File "PixivUtil2.py", line 1146, in main
  File "PixivUtil2.py", line 863, in main_loop
  File "PixivUtil2.py", line 551, in menu_download_new_illust_from_bookmark
  File "PixivBookmarkHandler.pyc", line 115, in process_new_illust_from_bookmark
  File "mechanize\_response.pyc", line 199, in read
  File "socket.pyc", line 669, in readinto
  File "http\client.pyc", line 488, in readinto
  File "http\client.pyc", line 593, in _readinto_chunked
  File "http\client.pyc", line 616, in _safe_readinto
  File "socket.pyc", line 669, in readinto
  File "ssl.pyc", line 1241, in recv_into
  File "ssl.pyc", line 1099, in read
socket.timeout: The read operation timed out

**Comment by Nandaka** [comment]
> socket.timeout: The read operation timed out

check your internet?

**Comment by GerhardSauer** [comment]
well, what should I check?
what is different by the script compared to the website?

Internet is working, with several PCs, all connections are wired. No ping and packet loss problems.
Pixiv website is working in firefox and edge chromium.
Some pictures are downloaded (but it seems rnd which work and which not). running it again and again, slowly completes timeout downloads.

All "routing" devices were restarted, result is the same.
I don't see problems in other applications, like voice chat or games.

**Comment by Nandaka** [comment]
Is it blocked by your firewall? else try to run from the python script directly?

**Comment by GerhardSauer** [comment]
no firewall issue, but I will check running it with python directly.

**Comment by GerhardSauer** [comment]
Ok, I have a first indication for the problem.
It seems not related to the tool.
Longer term validation of packet loss shows some times packet loss of 0.2%.
So it seems almost not measurable, but could cause the issue in the script.
I contacted my  provider to verify this.
When I have a result, I will update this post. 
For the moment, don't pay attention to it.

Thank you for the support.

**Comment by GerhardSauer** [comment]
Is related to the internet provider, but it was strange that the "only" visible malfunction are timeouts in the script.
