### ISSUE TITLE
Error when creating png file of a particular image.

### ISSUE THREAD

**Issue by polujm9** [Nandaka/PixivUtil2#796]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

I'm downloading images as usual and a problem appeared when downloading particular image (stop when creating apng file).

I had try to upgrade PixivUtil2 to v20200915 and re-download ffmpeg.exe and not working.

### Steps to Reproduce

1. download image id = 72778077

**Expected behavior:** Create files successfully

**Actual behavior:** Stopped when creating png file

### Versions

Logs in pixivutil.log :
```
2020-09-16 13:48:42,476 - PixivUtil20200915 - INFO - ###############################################################
2020-09-16 13:48:42,476 - PixivUtil20200915 - INFO - Starting with argument: [E:\Downloads\PixivUtil2.exe].
2020-09-16 13:48:42,480 - PixivUtil20200915 - INFO - Setting log level to: DEBUG
2020-09-16 13:48:42,480 - PixivUtil20200915 - INFO - No default cookie jar available, creating... 
2020-09-16 13:48:42,988 - PixivUtil20200915 - INFO - Using default DB Path: E:\Downloads\db.sqlite
2020-09-16 13:48:42,994 - PixivUtil20200915 - INFO - Only process members where the last update is >= 7 days ago
2020-09-16 13:48:43,855 - PixivUtil20200915 - INFO - Using Username: zxczxc123456789
2020-09-16 13:48:43,855 - PixivUtil20200915 - INFO - Trying to log in with saved cookie
2020-09-16 13:48:44,126 - PixivUtil20200915 - INFO - Logging in, return url: https://www.pixiv.net/
2020-09-16 13:48:44,126 - PixivUtil20200915 - INFO - Login successful.
2020-09-16 13:48:44,127 - PixivUtil20200915 - INFO - Logged in using cookie
2020-09-16 13:48:44,128 - PixivUtil20200915 - INFO - My User Id: 3753063.
2020-09-16 13:48:44,129 - PixivUtil20200915 - INFO - Premium User: False.
2020-09-16 13:48:44,129 - PixivUtil20200915 - INFO - Locale = 
2020-09-16 13:48:50,811 - PixivUtil20200915 - INFO - Tags mode (3).
2020-09-16 13:49:16,215 - PixivUtil20200915 - INFO - Searching for: (洗脳) %E6%B4%97%E8%84%B3
2020-09-16 13:49:16,216 - PixivUtil20200915 - INFO - Looping... for https://www.pixiv.net/ajax/search/artworks/%E6%B4%97%E8%84%B3?word=%E6%B4%97%E8%84%B3&p=170&s_mode=s_tag&type=all&order=date_d
2020-09-16 13:49:17,144 - PixivUtil20200915 - DEBUG - Getting image page: 72778077
2020-09-16 13:49:17,431 - PixivUtil20200915 - DEBUG - New UI Mode
2020-09-16 13:49:17,797 - PixivUtil20200915 - DEBUG - using webrpc: https://www.pixiv.net/rpc/get_work.php?id=72778077
2020-09-16 13:49:18,722 - PixivUtil20200915 - DEBUG - Sanitized Filename: E:\Downloads\HissatsuNeko (15295498)\72778077_ugoira1920x1080 - Daddy's Sluts (slide show).zip
2020-09-16 13:49:18,724 - PixivUtil20200915 - INFO - Filename  : E:\Downloads\HissatsuNeko (15295498)\72778077_ugoira1920x1080 - Daddy's Sluts (slide show).zip
2020-09-16 13:49:18,911 - PixivUtil20200915 - INFO - 
Local file exists: E:\Downloads\HissatsuNeko (15295498)\72778077_ugoira1920x1080 - Daddy's Sluts (slide show).zip
2020-09-16 13:49:18,915 - PixivUtil20200915 - INFO - processing ugoira to apng...
2020-09-16 13:49:21,915 - PixivUtil20200915 - ERROR - Error at process_image(): 72778077
2020-09-16 13:49:21,915 - PixivUtil20200915 - ERROR - Traceback (most recent call last):
  File "PixivImageHandler.pyc", line 298, in process_image
  File "PixivDownloadHandler.pyc", line 328, in handle_ugoira
  File "PixivHelper.pyc", line 864, in ugoira2apng
  File "apng\__init__.pyc", line 512, in save
  File "apng\__init__.pyc", line 390, in to_bytes
  File "apng\__init__.pyc", line 292, in to_bytes
struct.error: 'H' format requires 0 <= number <= 65535

2020-09-16 13:49:21,917 - PixivUtil20200915 - ERROR - Exception: (<class 'struct.error'>, error("'H' format requires 0 <= number <= 65535"), <traceback object at 0x07E84CA8>)
2020-09-16 13:49:21,918 - PixivUtil20200915 - ERROR - Traceback (most recent call last):
  File "PixivImageHandler.pyc", line 298, in process_image
  File "PixivDownloadHandler.pyc", line 328, in handle_ugoira
  File "PixivHelper.pyc", line 864, in ugoira2apng
  File "apng\__init__.pyc", line 512, in save
  File "apng\__init__.pyc", line 390, in to_bytes
  File "apng\__init__.pyc", line 292, in to_bytes
struct.error: 'H' format requires 0 <= number <= 65535

2020-09-16 13:49:21,919 - PixivUtil20200915 - DEBUG - Sanitized Filename: Error medium page for image 72778077.html
2020-09-16 13:49:21,941 - PixivUtil20200915 - ERROR - Dumping html to: Error medium page for image 72778077.html
2020-09-16 13:49:21,942 - PixivUtil20200915 - ERROR - Traceback (most recent call last):
  File "PixivImageHandler.pyc", line 298, in process_image
  File "PixivDownloadHandler.pyc", line 328, in handle_ugoira
  File "PixivHelper.pyc", line 864, in ugoira2apng
  File "apng\__init__.pyc", line 512, in save
  File "apng\__init__.pyc", line 390, in to_bytes
  File "apng\__init__.pyc", line 292, in to_bytes
struct.error: 'H' format requires 0 <= number <= 65535

2020-09-16 13:49:21,944 - PixivUtil20200915 - ERROR - Error at process_tags() at page 170: (<class 'struct.error'>, error("'H' format requires 0 <= number <= 65535"), <traceback object at 0x07E84DC8>)
2020-09-16 13:49:21,945 - PixivUtil20200915 - ERROR - Traceback (most recent call last):
  File "PixivTagsHandler.pyc", line 127, in process_tags
  File "PixivImageHandler.pyc", line 298, in process_image
  File "PixivDownloadHandler.pyc", line 328, in handle_ugoira
  File "PixivHelper.pyc", line 864, in ugoira2apng
  File "apng\__init__.pyc", line 512, in save
  File "apng\__init__.pyc", line 390, in to_bytes
  File "apng\__init__.pyc", line 292, in to_bytes
struct.error: 'H' format requires 0 <= number <= 65535

2020-09-16 13:49:21,945 - PixivUtil20200915 - DEBUG - Sanitized Filename: Error page for search tags %E6%B4%97%E8%84%B3 at page 170.html
2020-09-16 13:49:22,006 - PixivUtil20200915 - ERROR - Dumping html to: Error page for search tags %E6%B4%97%E8%84%B3 at page 170.html
2020-09-16 13:49:22,007 - PixivUtil20200915 - ERROR - Traceback (most recent call last):
  File "PixivTagsHandler.pyc", line 127, in process_tags
  File "PixivImageHandler.pyc", line 298, in process_image
  File "PixivDownloadHandler.pyc", line 328, in handle_ugoira
  File "PixivHelper.pyc", line 864, in ugoira2apng
  File "apng\__init__.pyc", line 512, in save
  File "apng\__init__.pyc", line 390, in to_bytes
  File "apng\__init__.pyc", line 292, in to_bytes
struct.error: 'H' format requires 0 <= number <= 65535

2020-09-16 13:49:22,016 - PixivUtil20200915 - ERROR - Unknown Error: 'H' format requires 0 <= number <= 65535
Traceback (most recent call last):
  File "PixivUtil2.py", line 1146, in main
  File "PixivUtil2.py", line 853, in main_loop
  File "PixivUtil2.py", line 336, in menu_download_by_tags
  File "PixivTagsHandler.pyc", line 127, in process_tags
  File "PixivImageHandler.pyc", line 298, in process_image
  File "PixivDownloadHandler.pyc", line 328, in handle_ugoira
  File "PixivHelper.pyc", line 864, in ugoira2apng
  File "apng\__init__.pyc", line 512, in save
  File "apng\__init__.pyc", line 390, in to_bytes
  File "apng\__init__.pyc", line 292, in to_bytes
struct.error: 'H' format requires 0 <= number <= 65535
2020-09-16 13:50:51,227 - PixivUtil20200915 - INFO - EXIT: -1
2020-09-16 13:50:51,227 - PixivUtil20200915 - INFO - ###############################################################
```

**Comment by Nandaka** [comment]
create aPNG feature is provided by apng library, not ffmpeg. Let me upgrade to latest and check.

**Comment by Nandaka** [comment]
will try to use ffmpeg to convert, just need to find the command line...

**Comment by Nandaka** [comment]
updated the command so it able to use png extension.

`./ffmpeg.exe -i ./source/i.ffconcat -c:v apng -plays 0 -vf "setpts=PTS-STARTPTS,hqdn3d=1.5:1.5:6:6" out.png`
