### ISSUE TITLE
Index out of Range issue when downloading bookmarks

### ISSUE THREAD

**Issue by master117** [Nandaka/PixivUtil2#800]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [release]

### Description
I tried "Download from bookmarked artists" option 5 including private bookmarks.
And got this error:

```
Processing Member Id: 1878082
Page
Member Url: https://www.pixiv.net/ajax/user/1878082/profile/all
Member Name  : モ誰
Member Avatar: https://i.pximg.net/user-profile/img/2017/05/28/10/22/13/12617028_87b55fbaa96afb7b49d7745ace59068a.jpg
Member Token : mogoon
Member Background : no_background
Processing images from 1 to 112 of 112
Traceback (most recent call last):
  File "PixivArtistHandler.pyc", line 119, in process_member
  File "PixivHelper.pyc", line 393, in create_avabg_filename
IndexError: list index out of range
Error at process_member(): (<class 'IndexError'>, IndexError('list index out of range'), <traceback object at 0x0BB9D0A8>)
Dumping html to: Error page for member 1878082 at page 1.html
Error at process_bookmark(): (<class 'IndexError'>, IndexError('list index out of range'), <traceback object at 0x0BB9D108>)
Traceback (most recent call last):
  File "PixivUtil2.py", line 1146, in main
  File "PixivUtil2.py", line 857, in main_loop
  File "PixivUtil2.py", line 453, in menu_download_from_online_user_bookmark
  File "PixivBookmarkHandler.pyc", line 39, in process_bookmark
  File "PixivArtistHandler.pyc", line 119, in process_member
  File "PixivHelper.pyc", line 393, in create_avabg_filename
IndexError: list index out of range
```

https://i.imgur.com/Q3PznX7.png

### Steps to Reproduce

As in Description

### Version

v20200915

**Comment by Nandaka** [comment]
should be already fixed in 3ae9128b76207c85ed8340529bfc2ed751a7bd52 but not yet released.

**Comment by Nandaka** [comment]
related to #795

**Comment by Nandaka** [comment]
try https://github.com/Nandaka/PixivUtil2/releases/tag/20200926-beta1

**Comment by master117** [comment]
Yeah, the beta fixed it. Thanks.
