### ISSUE TITLE
v20201006 Fanbox f1~f5 Bug_(:з」∠)_

### ISSUE THREAD

**Issue by ee092884** [Nandaka/PixivUtil2#806]
No matter what you enter, it's a direct error
But 20200926-beta1 can be executed normally _(:з」∠)_

Input: f1
End Page =
Traceback (most recent call last):
  File "PixivUtil2.py", line 1252, in main
  File "PixivUtil2.py", line 993, in main_loop
  File "PixivUtil2.py", line 672, in menu_fanbox_download_from_list
ValueError: invalid literal for int() with base 10: ''
press enter to exit.

Input: f2
Artist/Creator IDs =
End page =
Traceback (most recent call last):
  File "PixivUtil2.py", line 1252, in main
  File "PixivUtil2.py", line 995, in main_loop
  File "PixivUtil2.py", line 744, in menu_fanbox_download_by_id
ValueError: invalid literal for int() with base 10: ''
press enter to exit.

Input: f3
Post ids =
Trying to log in FANBOX with saved cookie
FANBOX Login successful.
Traceback (most recent call last):
  File "PixivUtil2.py", line 1252, in main
  File "PixivUtil2.py", line 997, in main_loop
  File "PixivUtil2.py", line 721, in menu_fanbox_download_by_post_id
  File "PixivBrowserFactory.pyc", line 941, in fanboxGetPostById
  File "PixivBrowserFactory.pyc", line 963, in fanboxGetPostJsonById
  File "PixivBrowserFactory.pyc", line 205, in open_with_retry
  File "mechanize\_mechanize.pyc", line 253, in open
  File "mechanize\_mechanize.pyc", line 309, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 400: Bad Request
press enter to exit.

Input: f4
End Page =
Traceback (most recent call last):
  File "PixivUtil2.py", line 1252, in main
  File "PixivUtil2.py", line 999, in main_loop
  File "PixivUtil2.py", line 672, in menu_fanbox_download_from_list
ValueError: invalid literal for int() with base 10: ''
press enter to exit.

Input: f5
End Page =
Traceback (most recent call last):
  File "PixivUtil2.py", line 1252, in main
  File "PixivUtil2.py", line 1001, in main_loop
  File "PixivUtil2.py", line 672, in menu_fanbox_download_from_list
ValueError: invalid literal for int() with base 10: ''
press enter to exit.

[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/5335764/pixivutil.log)

**Comment by Nandaka** [comment]
Looks like you didn't key in the required parameter, at least for f2 (Artist/Creator IDs =) and f3 (Post ids =)

For endpage, you need to key in something for now.

@bluerthanever I think this is because the endpage processing is one liner now.
https://github.com/Nandaka/PixivUtil2/compare/20200926-beta1...v20201006#diff-7a612caa8f02f7c30e49d68a8c1ab43fR739

**Comment by bluerthanever** [comment]
hmm. sorry. will be on it.

**Comment by bluerthanever** [comment]
Can I ask what did you feed the program for menu f3?

**Comment by bluerthanever** [comment]
PR: #808 
sorry those were some dumb mistakes.

**Comment by ee092884** [comment]
Sorry to use duplicate content
Please help delete the duplicates #809 and #806

**Comment by Nandaka** [comment]
should be updated in https://github.com/Nandaka/PixivUtil2/releases/tag/v20201009-beta1
