### ISSUE TITLE
v20201006 Fanbox f2 Bug

### ISSUE THREAD

**Issue by ee092884** [Nandaka/PixivUtil2#809]
No matter what you enter, it's a direct error
But 20200926-beta1 can be executed normally
Can such a demonstration be?

Input: f2
Artist/Creator IDs = 3590927
End page =
Traceback (most recent call last):
  File "PixivUtil2.py", line 1252, in main
  File "PixivUtil2.py", line 995, in main_loop
  File "PixivUtil2.py", line 744, in menu_fanbox_download_by_id
ValueError: invalid literal for int() with base 10: ''
press enter to exit.

Input: f2
Artist/Creator IDs = haymer
End page =
Traceback (most recent call last):
  File "PixivUtil2.py", line 1252, in main
  File "PixivUtil2.py", line 995, in main_loop
  File "PixivUtil2.py", line 744, in menu_fanbox_download_by_id
ValueError: invalid literal for int() with base 10: ''
press enter to exit.

[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/5339683/pixivutil.log)

**Comment by Nandaka** [comment]
key in the end page for now, else you can pull the latest commit and run from source code.

dupes with https://github.com/Nandaka/PixivUtil2/issues/806

**Comment by ee092884** [comment]
Sorry to use duplicate content
Please help delete the duplicates #809 and #806
