### ISSUE TITLE
[20150427] Null pointer exceptions when downloading images

### ISSUE THREAD

**Issue by NHOrus** [Nandaka/PixivUtil2#81]
Sample:
```
Processing Image Id: 8682952
Title: ????
Tags : ????? ??? ????? puyopix
Date : 2010-02-10 00:02:00
Mode : bigNew
Image URL : http://i4.pixiv.net/img16/img/a_ka_ji/8682952.gif
Filename  : E:\conf\pixiv\251370\8682952 - ????????
Start downloading... Using Referer: http://www.pixiv.net/member_illust.php?mode=medium&illust_id=8682952
      3322 of      3322 BytesTraceback (most recent call last):
  File "PixivUtil2.py", line 115, in download_image
  File "PixivHelper.pyc", line 512, in downloadImage
  File "PixivHelper.pyc", line 323, in speedInStr
ZeroDivisionError: float division by zero
 Error at download_image(): (<type 'exceptions.ZeroDivisionError'>, ZeroDivisionError('float division by zero',), <traceback object at 0x0324CC60>) a http://i4.pixiv.net/img16/img/a_ka_ji/8682952.gif (9000)
Retrying [1]...
1 2 3 4
Start downloading... Using Referer: http://www.pixiv.net/member_illust.php?mode=medium&illust_id=8682952
        File exist! (Identical Size)
```
So things get downloaded, but there is retry and delay.

**Comment by NHOrus** [comment]
I think it may be downloading too fast, so total_time is 0 and thing kindly crashes a little?

**Comment by Nandaka** [comment]
updated: https://nandaka.wordpress.com/2015/06/05/pixiv-downloader-20150605/
