### ISSUE TITLE
I dont download files fanbox appears error 1108 [SSL issue]

### ISSUE THREAD

**Issue by KohicSimp** [Nandaka/PixivUtil2#810]
When I try to download any file from fanbox the appears error <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)> 1 2 3 4
Error at open_with_retry(): (<class 'urllib.error.URLError'>, URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')), <traceback object at 0x03C96F68>)
How to resolve this issue?

**Comment by bluerthanever** [comment]
I encounter this problem lately every time....
For god know why my python doesn't resolve DNS properly with socks5 proxies now, which had been fine before.
My solution for now is to turn on Simple DNSCrypt.

Not sure if you are using proxies.

**Comment by Nandaka** [comment]
Are you able to open the website from the browser without any error/warning/proxy?

Last resort solution: set `enablesslverification = False` in `config.ini`.

Please be aware that this might allow someone to spy on your connection as it turn off the validation for the certificate.

**Comment by bluerthanever** [comment]
For me, I can not open the website from browser without proxy, but there would be no error or warning with proxy on and I can access the website.
Setting `enablesslverification` to `False` does not help me here.

But actually for me I got the following errors with socks5 proxy and ssl verification on:

```
<urlopen error EOF occurred in violation of protocol (_ssl.c:1124)> 1 2
<urlopen error EOF occurred in violation of protocol (_ssl.c:1124)> 1 2
<urlopen error EOF occurred in violation of protocol (_ssl.c:1124)> 1 2
<urlopen error EOF occurred in violation of protocol (_ssl.c:1124)> 1 2
<urlopen error EOF occurred in violation of protocol (_ssl.c:1124)> 1 2
<urlopen error EOF occurred in violation of protocol (_ssl.c:1124)> 1 2
<urlopen error EOF occurred in violation of protocol (_ssl.c:1124)> 1 2
<urlopen error EOF occurred in violation of protocol (_ssl.c:1124)> 1 2
<urlopen error EOF occurred in violation of protocol (_ssl.c:1124)> 1 2
<urlopen error EOF occurred in violation of protocol (_ssl.c:1124)> 1 2
Error at open_with_retry(): (<class 'urllib.error.URLError'>, URLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1124)')), <traceback object at 0x00000174339776C0>)
Error at doLogin(): (<class 'PixivException.PixivException'>, PixivException('Failed to get page: https://www.pixiv.net/, please check your internet connection/firewall/antivirus.'), <traceback object at 0x00000174339187C0>)
```

in log:
```
2020-10-13 00:01:05,655 - PixivUtil20201006 - ERROR - Error at doLogin(): (<class 'PixivException.PixivException'>, PixivException('Failed to get page: https://www.pixiv.net/, please check your internet connection/firewall/antivirus.'), <traceback object at 0x00000174339187C0>)
2020-10-13 00:01:05,655 - PixivUtil20201006 - ERROR - Traceback (most recent call last):
  File "C:\Users\Jacob\AppData\Roaming\Python\Python38\site-packages\mechanize\_urllib2_fork.py", line 1229, in do_open
    h.request(str(req.get_method()), str(req.get_selector()), req.data,
  File "C:\Program Files\Python38\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files\Python38\lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python38\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python38\lib\http\client.py", line 1010, in _send_output
    self.send(msg)
  File "C:\Program Files\Python38\lib\http\client.py", line 950, in send
    self.connect()
  File "C:\Program Files\Python38\lib\http\client.py", line 1424, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\Program Files\Python38\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Program Files\Python38\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Program Files\Python38\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1124)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\PixivUtil2-master\PixivBrowserFactory.py", line 205, in open_with_retry
    return self.open(url, data, timeout)
  File "C:\Users\Jacob\AppData\Roaming\Python\Python38\site-packages\mechanize\_mechanize.py", line 257, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
  File "C:\Users\Jacob\AppData\Roaming\Python\Python38\site-packages\mechanize\_mechanize.py", line 287, in _mech_open
    response = UserAgentBase.open(self, request, data)
  File "C:\Users\Jacob\AppData\Roaming\Python\Python38\site-packages\mechanize\_opener.py", line 193, in open
    response = urlopen(self, req, data)
  File "C:\Users\Jacob\AppData\Roaming\Python\Python38\site-packages\mechanize\_urllib2_fork.py", line 425, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\Jacob\AppData\Roaming\Python\Python38\site-packages\mechanize\_urllib2_fork.py", line 414, in _call_chain
    result = func(*args)
  File "C:\Users\Jacob\AppData\Roaming\Python\Python38\site-packages\mechanize\_urllib2_fork.py", line 1276, in https_open
    return self.do_open(conn_factory, req)
  File "C:\Users\Jacob\AppData\Roaming\Python\Python38\site-packages\mechanize\_urllib2_fork.py", line 1233, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:1124)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PixivUtil2.py", line 1047, in doLogin
    result = __br__.loginUsingCookie()
  File "E:\PixivUtil2-master\PixivBrowserFactory.py", line 316, in loginUsingCookie
    res = self.open_with_retry('https://www.pixiv.net/')
  File "E:\PixivUtil2-master\PixivBrowserFactory.py", line 223, in open_with_retry
    raise PixivException("Failed to get page: {0}, please check your internet connection/firewall/antivirus."
PixivException.PixivException: 9005 Failed to get page: https://www.pixiv.net/, please check your internet connection/firewall/antivirus., hasDumpPage=N, pageData=None

2020-10-13 00:01:05,656 - PixivUtil20201006 - ERROR - Cannot Login!
2020-10-13 00:01:05,656 - PixivUtil20201006 - ERROR - Traceback (most recent call last):
  File "C:\Users\Jacob\AppData\Roaming\Python\Python38\site-packages\mechanize\_urllib2_fork.py", line 1229, in do_open
    h.request(str(req.get_method()), str(req.get_selector()), req.data,
  File "C:\Program Files\Python38\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files\Python38\lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python38\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python38\lib\http\client.py", line 1010, in _send_output
    self.send(msg)
  File "C:\Program Files\Python38\lib\http\client.py", line 950, in send
    self.connect()
  File "C:\Program Files\Python38\lib\http\client.py", line 1424, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\Program Files\Python38\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Program Files\Python38\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Program Files\Python38\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1124)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\PixivUtil2-master\PixivBrowserFactory.py", line 205, in open_with_retry
    return self.open(url, data, timeout)
  File "C:\Users\Jacob\AppData\Roaming\Python\Python38\site-packages\mechanize\_mechanize.py", line 257, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
  File "C:\Users\Jacob\AppData\Roaming\Python\Python38\site-packages\mechanize\_mechanize.py", line 287, in _mech_open
    response = UserAgentBase.open(self, request, data)
  File "C:\Users\Jacob\AppData\Roaming\Python\Python38\site-packages\mechanize\_opener.py", line 193, in open
    response = urlopen(self, req, data)
  File "C:\Users\Jacob\AppData\Roaming\Python\Python38\site-packages\mechanize\_urllib2_fork.py", line 425, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\Jacob\AppData\Roaming\Python\Python38\site-packages\mechanize\_urllib2_fork.py", line 414, in _call_chain
    result = func(*args)
  File "C:\Users\Jacob\AppData\Roaming\Python\Python38\site-packages\mechanize\_urllib2_fork.py", line 1276, in https_open
    return self.do_open(conn_factory, req)
  File "C:\Users\Jacob\AppData\Roaming\Python\Python38\site-packages\mechanize\_urllib2_fork.py", line 1233, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:1124)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PixivUtil2.py", line 1047, in doLogin
    result = __br__.loginUsingCookie()
  File "E:\PixivUtil2-master\PixivBrowserFactory.py", line 316, in loginUsingCookie
    res = self.open_with_retry('https://www.pixiv.net/')
  File "E:\PixivUtil2-master\PixivBrowserFactory.py", line 223, in open_with_retry
    raise PixivException("Failed to get page: {0}, please check your internet connection/firewall/antivirus."
PixivException.PixivException: 9005 Failed to get page: https://www.pixiv.net/, please check your internet connection/firewall/antivirus., hasDumpPage=N, pageData=None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PixivUtil2.py", line 1248, in main
    result = doLogin(password, username)
  File "PixivUtil2.py", line 1054, in doLogin
    raise PixivException("Cannot Login!", PixivException.CANNOT_LOGIN)
PixivException.PixivException: 0 Cannot Login!, hasDumpPage=N, pageData=None
```

**Comment by Nandaka** [comment]
that's weird, because no special handling if ssl verification is enabled (it just use default python ssl lib).

https://github.com/Nandaka/PixivUtil2/blob/master/PixivBrowserFactory.py#L167
https://github.com/Nandaka/PixivUtil2/blob/master/PixivOAuth.py#L127 (OAuth uses requests lib)

Can you check if using requests library with your proxy can fix the error? If yes, maybe I will change url request to requests library from Mechanize...

**Comment by bluerthanever** [comment]
like this?
w Simple DNSCrypt off:
```
>>> import requests
>>> proxies = {"http": "socks5://127.0.0.1:8080", "https": "socks5://127.0.0.1:8080"}
>>> requests.get(url, proxies=proxies)
Traceback (most recent call last):
  File "C:\Users\Jacob\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Jacob\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Jacob\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "C:\Users\Jacob\AppData\Roaming\Python\Python38\site-packages\urllib3\connection.py", line 362, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\Jacob\AppData\Roaming\Python\Python38\site-packages\urllib3\util\ssl_.py", line 384, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Program Files\Python38\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Program Files\Python38\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Program Files\Python38\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1124)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jacob\AppData\Roaming\Python\Python38\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\Jacob\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "C:\Users\Jacob\AppData\Roaming\Python\Python38\site-packages\urllib3\util\retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: SOCKSHTTPSConnectionPool(host='www.pixiv.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1124)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Jacob\AppData\Roaming\Python\Python38\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Jacob\AppData\Roaming\Python\Python38\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Jacob\AppData\Roaming\Python\Python38\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Jacob\AppData\Roaming\Python\Python38\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Jacob\AppData\Roaming\Python\Python38\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: SOCKSHTTPSConnectionPool(host='www.pixiv.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1124)')))
```

turn DNSCrypt on and:
```
>>> requests.get(url, proxies=proxies)
<Response [200]>
>>>
```

btw, url = "https://www.pixiv.net".

but if I turn off DNSCrypt:
```
>>> proxies2 = {"http": "127.0.0.1:8081", "https": "127.0.0.1:8081"}
>>> requests.get(url, proxies=proxies2)
<Response [200]>
>>>
```

looks like it may be because of socket??

**Comment by Nandaka** [comment]
I suppose, somehow the socket or the proxy conflicting with the ssl implementation in python?

**Comment by bluerthanever** [comment]
Anyways, I will just be using Simple DNSCrypt until better solutions.
Sometimes I would also get errors like KohicSimp , but I forgot how to repeat it. Maybe it's when I use python to scrape twitter?
But please tell us your Network settings? @KohicSimp
