### ISSUE TITLE
Unable to Download.  Logged in, but no images found to grab.

### ISSUE THREAD

**Issue by Osprey-Hawk** [Nandaka/PixivUtil2#823]
### Prerequisites

* [Y] Did you read FAQ section?
* [Y] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Unable to download.  User ID returns as not having any entries to download even though that is clearly false.
Program then lists errors in Python code which results in two instances of HTTP 404.
This happens with three builds, including the 20201009-beta1
User ID, Pass, and SessionID work and allow for login, but I am unable to actually download anything including the meager image I uploaded to my own account to test.
I have attached the log of the incident

### Steps to Reproduce

1. Set up Program with proper User/PAss,SessID, etc.
2. Once loaded, I did option 1, then used my ID (292554), followed by 1, 0, and n
3. When started, it gives this error string
2020-10-16 04:31:46,236 - PixivUtil20201009-beta1 - INFO - No image found for: 292554
2020-10-16 04:31:46,237 - PixivUtil20201009-beta1 - INFO - Member_id: 292554 completed: no images were found.
2020-10-16 04:31:46,238 - PixivUtil20201009-beta1 - INFO - Member Url: https://www.pixiv.net/ajax/user/292554/profile/all
2020-10-16 04:31:46,239 - PixivUtil20201009-beta1 - DEBUG - b'{"error":false,"message":"","body":{"illusts":[],"manga":[],"novels":[],"mangaSeries":[],"novelSeries":[],"pickup":[],"bookmarkCount":{"public":{"illust":1,"novel":0},"private":{"illust":0,"novel":0}},"externalSiteWorksStatus":{"booth":false,"sketch":false,"vroidHub":false},"request":{"showRequestTab":false,"postWorks":{"artworks":[],"novels":[]}}}}'
2020-10-16 04:31:46,246 - PixivUtil20201009-beta1 - INFO - Using OAuth to retrieve member info for: 292554
2020-10-16 04:31:46,266 - PixivUtil20201009-beta1 - DEBUG - Getting sketch artist detail from https://sketch.pixiv.net/api/users/@self
2020-10-16 04:31:47,184 - PixivUtil20201009-beta1 - ERROR - Error at process_sketch_artists(): self
2020-10-16 04:31:47,185 - PixivUtil20201009-beta1 - ERROR - Traceback (most recent call last):
  File "PixivBrowserFactory.pyc", line 240, in getPixivPage
  File "PixivBrowserFactory.pyc", line 206, in open_with_retry
  File "mechanize\_mechanize.pyc", line 253, in open
  File "mechanize\_mechanize.pyc", line 309, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PixivSketchHandler.pyc", line 42, in process_sketch_artists
  File "PixivBrowserFactory.pyc", line 998, in sketch_get_posts_by_artist_id
  File "PixivBrowserFactory.pyc", line 249, in getPixivPage
PixivException.PixivException: 9005 Failed to get page: https://sketch.pixiv.net/api/users/@self => HTTP Error 404: Not Found, hasDumpPage=N, pageData=None

2020-10-16 04:31:47,189 - PixivUtil20201009-beta1 - ERROR - Exception: (<class 'PixivException.PixivException'>, PixivException('Failed to get page: https://sketch.pixiv.net/api/users/@self => HTTP Error 404: Not Found'), <traceback object at 0x0329DDE8>)
2020-10-16 04:31:47,190 - PixivUtil20201009-beta1 - ERROR - Traceback (most recent call last):
  File "PixivBrowserFactory.pyc", line 240, in getPixivPage
  File "PixivBrowserFactory.pyc", line 206, in open_with_retry
  File "mechanize\_mechanize.pyc", line 253, in open
  File "mechanize\_mechanize.pyc", line 309, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PixivSketchHandler.pyc", line 42, in process_sketch_artists
  File "PixivBrowserFactory.pyc", line 998, in sketch_get_posts_by_artist_id
  File "PixivBrowserFactory.pyc", line 249, in getPixivPage
PixivException.PixivException: 9005 Failed to get page: https://sketch.pixiv.net/api/users/@self => HTTP Error 404: Not Found, hasDumpPage=N, pageData=None

[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/5390647/pixivutil.log)

**Comment by Nandaka** [comment]
when it try to download your own id, pixiv doesn't return any images from the api call.

Try again now? I notice you upload 1 image in your own gallery (user id = 292554)

Option 1 require you to key in other user id, not yours...

also 404 for pixiv sketch is normal if the artist doesn't have Pixiv Sketch account.

**Comment by Osprey-Hawk** [comment]
Okay.  I tried it with a different artist I never downloaded with this software, Edmol (23746), and I get this error now (using latest beta) that loops forever.

![Screenshot 2020-10-16 22 51 24](https://user-images.githubusercontent.com/45588123/96327815-ae965980-1002-11eb-8971-f02daa7af4a7.png)

Is there a setting I'm missing?
