### ISSUE TITLE
file reading error on v20150427 while 2 processes working

### ISSUE THREAD

**Issue by sabearcher** [Nandaka/PixivUtil2#83]
$ python pixivUtilPicsRedownload.py -f --er
picId: None
memberId: 2147813
run: "D:\Program Files\pixivutil20150427\PixivUtil2.exe" -x -s 1 2147813
del: D:\Program Files\pixivutil20150427\errs\Error page for member 2147813.html
PixivDownloader2 version 20150427
https://nandaka.wordpress.com/tag/pixiv-downloader/
Traceback (most recent call last):
  File "logging\handlers.pyc", line 77, in emit
  File "logging\handlers.pyc", line 142, in doRollover
WindowsError: [Error 32]
Logged from file PixivUtil2.py, line 1656
Traceback (most recent call last):
  File "logging\handlers.pyc", line 77, in emit
  File "logging\handlers.pyc", line 142, in doRollover
WindowsError: [Error 32]
Logged from file PixivUtil2.py, line 1657
Reading D:\Program Files\pixivutil20150427\config.ini ...
done.
Traceback (most recent call last):
  File "logging\handlers.pyc", line 77, in emit
  File "logging\handlers.pyc", line 142, in doRollover
WindowsError: [Error 32]
Logged from file PixivHelper.pyc, line 43
Traceback (most recent call last):
  File "logging\handlers.pyc", line 77, in emit
  File "logging\handlers.pyc", line 142, in doRollover
WindowsError: [Error 32]
Logged from file PixivBrowserFactory.pyc, line 251
Traceback (most recent call last):
  File "logging\handlers.pyc", line 77, in emit
  File "logging\handlers.pyc", line 142, in doRollover
WindowsError: [Error 32]
Logged from file PixivBrowserFactory.pyc, line 65
Creating database... done.
Only process member where day last updated >= 7
Traceback (most recent call last):
  File "logging\handlers.pyc", line 77, in emit
  File "logging\handlers.pyc", line 142, in doRollover
WindowsError: [Error 32]
Logged from file PixivHelper.pyc, line 365
Using Username: 5556661234
Traceback (most recent call last):
  File "logging\handlers.pyc", line 77, in emit
  File "logging\handlers.pyc", line 142, in doRollover
WindowsError: [Error 32]
Logged from file PixivUtil2.py, line 1735
Trying to log with saved cookie
Traceback (most recent call last):
  File "logging\handlers.pyc", line 77, in emit
  File "logging\handlers.pyc", line 142, in doRollover
WindowsError: [Error 32]
Logged from file PixivHelper.pyc, line 365

**Comment by Nandaka** [comment]
you run multiple instance on the same folder? I suspect this is because the log file is being accessed by multiple process at the same time (one is writing, the other rename the file to roll over the log).

multiple process is not supported by RotatingFileHandler.

Either you run the the instance from different folder, or you delete the log file.

**Comment by reyaz006** [comment]
I recommend setting up several copies of PixivUtil2 in separate folders. That's how it works for me.
