### ISSUE TITLE
Cannot Login/Cannot Download

### ISSUE THREAD

**Issue by xAmbiguityx** [Nandaka/PixivUtil2#835]
I can't log in on the latest normal and beta releases if I use the PHPSSESID cookie after logging into Pixiv. I have tried multiple pixiv accounts with their respective cookie IDs. If I use the cookie I get **before** I log in, PixivUtil2 will work, however, it will give me infinite errors when trying to download images.

This is the error it gives me if I try to log in with the normal cookie:
```
Error at doLogin(): (<class 'mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib.error.HTTPError instance) at 0x36b9a48 whose wrapped object = <HTTPError 403: 'Forbidden'>>, <traceback object at 0x036C9EE8>)
Cannot Login!
```

These are the infinite errors I get if I use the pre-login cookie and try to download something:
```
2020-10-20 14:43:30,047 - PixivUtil20201006 - INFO - Premium User: False.
2020-10-20 14:43:30,047 - PixivUtil20201006 - INFO - Locale = 
2020-10-20 14:43:38,849 - PixivUtil20201006 - INFO - Member id mode (1).
2020-10-20 14:43:54,690 - PixivUtil20201006 - INFO - Member IDs: [31147264]
2020-10-20 14:43:54,692 - PixivUtil20201006 - INFO - [33m[1mProcessing Member Id: 31147264[0m
2020-10-20 14:43:54,700 - PixivUtil20201006 - INFO - Member Url: https://www.pixiv.net/ajax/user/31147264/profile/all
2020-10-20 14:43:55,457 - PixivUtil20201006 - DEBUG - b'{"error":false,"message":"","body":{"illusts":{"85048554":null,"83826031":null,"82953631":null,"82273102":null,"81509715":null,"80736558":null,"80090403":null,"80090344":null,"73634096":null,"72739374":null,"72240681":null,"71258639":null,"70821821":null,"70349033":null,"69278537":null,"68244415":null},"manga":[],"novels":[],"mangaSeries":[],"novelSeries":[],"pickup":[],"bookmarkCount":{"public":{"illust":0,"novel":0},"private":{"illust":0,"novel":0}},"externalSiteWorksStatus":{"booth":false,"sketch":false,"vroidHub":false},"request":{"showRequestTab":false,"postWorks":{"artworks":[],"novels":[]}}}}'
2020-10-20 14:43:55,462 - PixivUtil20201006 - DEBUG - using webrpc: https://www.pixiv.net/rpc/get_work.php?id=85048554
2020-10-20 14:43:56,559 - PixivUtil20201006 - ERROR - Error at processing Artist Info: (<class 'json.decoder.JSONDecodeError'>, JSONDecodeError('Expecting value: line 1 column 1 (char 0)'), <traceback object at 0x044D4D88>)
2020-10-20 14:43:56,560 - PixivUtil20201006 - ERROR - Traceback (most recent call last):
  File "PixivArtistHandler.pyc", line 77, in process_member
  File "PixivBrowserFactory.pyc", line 727, in getMemberPage
  File "PixivBrowserFactory.pyc", line 620, in getMemberInfoWhitecube
  File "json\__init__.pyc", line 357, in loads
  File "json\decoder.pyc", line 337, in decode
  File "json\decoder.pyc", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Nandaka** [comment]
use latest beta and see #814
