### ISSUE TITLE
Release 20201024 crashes on start => FileNotFoundError: [Errno 2] No such file or directory: '<path>\\browsers.json'

### ISSUE THREAD

**Issue by fengberd** [Nandaka/PixivUtil2#840]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Release 20201024 crashes on start. Seems like some library conflicts with the packer.

Tested on Windows 10 (1607) and Windows Server 2019 (1809)

### Steps to Reproduce

1. Download `pixivutil20201024.zip` [from here](https://github.com/Nandaka/PixivUtil2/releases/tag/v20201024) and extract it to somewhere
2. (Optional) Copy & paste config.ini from previous version
3. Run PixivUtil2.exe

**Expected behavior:**
It works properly

**Actual behavior:**
It crashes. With the following stack trace:
```
R:\pixivutil20201024>PixivUtil2.exe
Traceback (most recent call last):
  File "PixivUtil2.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "PixivArtistHandler.pyc", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "PixivBrowserFactory.pyc", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "PixivOAuth.pyc", line 15, in <module>
  File "PixivOAuth.pyc", line 24, in PixivOAuth
  File "cloudscraper\__init__.pyc", line 748, in create_scraper
  File "cloudscraper\__init__.pyc", line 136, in __init__
  File "cloudscraper\user_agent\__init__.pyc", line 20, in __init__
  File "cloudscraper\user_agent\__init__.pyc", line 74, in loadUserAgent
FileNotFoundError: [Errno 2] No such file or directory: 'R:\\pixivutil20201024\\library.zip\\cloudscraper\\user_agent\\browsers.json'
```

### Versions
~~You can get this information from executing `PixivUtil2.py --help`.~~
The help parameter won't work too, it simply crashes.
I just downloaded it several minutes ago so it should be 20201024 anyway.

**Comment by byjtje** [comment]
Have you got cloudscraper installed? https://pypi.org/project/cloudscraper/

**Comment by Nandaka** [comment]
packaging issue, he is running the compiled version.

**Comment by Nandaka** [comment]
crap, cannot just adding the missing json file to the library.zip

**Comment by Nandaka** [comment]
updated the zip file, please redownload.

**Comment by Nandaka** [comment]
need to modify the library source code to check it is frozen or not.

**Comment by fengberd** [comment]
Thanks for the fast patching, I can confirm the latest zip works fine.
I'm not familiar with python, thus I'm not sure the proper way to fix [this](https://github.com/VeNoMouS/cloudscraper/blob/133166ebc195b6f9b60db06d56829dbf6bd574c4/cloudscraper/user_agent/__init__.py#L74), hope someone open PR to fix it.

**Comment by Nandaka** [comment]
yeah, I just make a quick hack for py2exe to works. There should be a proper way to handle this (looking certify library, it also uses external file cacert.pem, but it able to handle the import from library.zip).

This code will check if the library is frozen to library.zip, and the just load the browser.json from current dir (provided it is copied over to the current folder).
```
        default_browser_json = os.path.join(os.path.dirname(__file__), 'browsers.json')
        if hasattr(sys, "frozen"):
            default_browser_json = 'browsers.json'

        with open(default_browser_json, 'r') as fp:
            user_agents = json.load(
                fp,
                object_pairs_hook=OrderedDict
            )
```

**Comment by gnarf1975** [comment]
It's not easy with this program. Especially because Pixiv changes something more often. Hats off, and thanks for the work you do.
