### ISSUE TITLE
Some problem download fanbox

### ISSUE THREAD

**Issue by cocokakao** [Nandaka/PixivUtil2#842]
Unknown Error: (<class 'OSError'>, OSError('Could not find a suitable TLS CA certificate bundle, invalid path: C:\\Users\\Public\\Documents\\ESTsoft\\CreatorTemp\\cacert.pem'), <traceback object at 0x04865EE8>)
press enter to exit.
----------------------------
I change the cookies and log in, but I see an error above.

**Comment by Nandaka** [comment]
> C:\Users\Public\Documents\ESTsoft\CreatorTemp\cacert.pem

is the file exists in that folder? it should be exists in the zip file.

**Comment by cocokakao** [comment]
it work normal download but not worked in fanbox download

**Comment by Nandaka** [comment]
is the file: `C:\Users\Public\Documents\ESTsoft\CreatorTemp\cacert.pem` exists or not?

**Comment by cocokakao** [comment]
> is the file: `C:\Users\Public\Documents\ESTsoft\CreatorTemp\cacert.pem` exists or not?

exists

**Comment by Nandaka** [comment]
what about using the previous version (beta-4), is it working?

**Comment by cocokakao** [comment]
> what about using the previous version (beta-4), is it working?

No, that version doesn't work either, but it requires CAPTCHA certification. That's strange. I've entered a new cookie.

**Comment by cocokakao** [comment]
There is a type difference between the pixiv cookie value and the fanbox cookie value. Is this the cause of the problem?

**Comment by Nandaka** [comment]
it is different, because fanbox is hosted on different site (fanbox.cc), not under pixiv.net

**Comment by cocokakao** [comment]
> There is a type difference between the pixiv cookie value and the fanbox cookie value. Is this the cause of the problem?

![image](https://user-images.githubusercontent.com/50015639/97087080-5f83a080-1662-11eb-9f44-87be4456a862.png)

**Comment by Nandaka** [comment]
that one should be ok, fanbox still uses the old format. 

I tried to run the latest compiled version and I don't get any issue. Try to extract it to `C:\pixivutil` directly?

**Comment by cocokakao** [comment]
> > There is a type difference between the pixiv cookie value and the fanbox cookie value. Is this the cause of the problem?
> 
> ![image](https://user-images.githubusercontent.com/50015639/97087080-5f83a080-1662-11eb-9f44-87be4456a862.png)

2020-10-25 01:36:48,248 - PixivUtil20201024 - INFO - Member IDs: f[]
2020-10-25 01:36:59,716 - PixivUtil20201024 - INFO - Download FANBOX Supporting list mode (f1/f4/f5).
2020-10-25 01:36:59,853 - PixivUtil20201024 - INFO - Trying to log in FANBOX with saved cookie
2020-10-25 01:37:00,201 - PixivUtil20201024 - INFO - Logging in with cookit to Fanbox, return url: https://www.fanbox.cc
2020-10-25 01:37:00,201 - PixivUtil20201024 - INFO - FANBOX Login successful.
2020-10-25 01:37:00,202 - PixivUtil20201024 - INFO - Getting supporting artists from https://api.fanbox.cc/plan.listSupporting
2020-10-25 01:37:00,531 - PixivUtil20201024 - INFO - Found 3 artist(s) in supporting list
2020-10-25 01:37:00,576 - PixivUtil20201024 - INFO - Getting artist information from https://api.fanbox.cc/creator.get?userId=133745
2020-10-25 01:37:00,822 - PixivUtil20201024 - INFO - Member Url: https://www.pixiv.net/ajax/user/133745/profile/all
2020-10-25 01:37:01,172 - PixivUtil20201024 - DEBUG - b'{"error":false,"message":"","body":{"illusts":[],"manga":[],"novels":[],"mangaSeries":[],"novelSeries":[],"pickup":[{"type":"fanbox","deletable":false,"draggable":true,"userName":"\\u3061\\u3083\\u3046","userImageUrl":"https:\\/\\/i.pximg.net\\/user-profile\\/img\\/2011\\/01\\/19\\/15\\/52\\/54\\/2642901_6685bc8491475bf72160075eed3f3b72_170.png","contentUrl":"https:\\/\\/www.pixiv.net\\/fanbox\\/creator\\/133745?utm_campaign=www_profile\\u0026utm_medium=site_flow\\u0026utm_source=pixiv","description":"\\u25c6job\\uff1a\\u30a2\\u30cb\\u30e1\\u30fc\\u30bf\\u30fc\\u3001\\u6f14\\u51fa\\u3001etc\\u2026\\r\\n\\u300c\\u843d\\u66f8\\u304d\\u300d\\u3084\\u300c\\u8003\\u3048\\u3066\\u3044\\u308b\\u4e8b\\u300d\\u300c\\u6a5f\\u6750\\u3084\\u30bd\\u30d5\\u30c8\\u306e\\u4e8b\\u300d\\u306a\\u3069\\u30af\\u30ed\\u30fc\\u30ba\\u30c9\\u306a\\u7a7a\\u9593\\u3060\\u304b\\u3089\\u3053\\u305d\\u306e\\u6c17\\u697d\\u3055\\u3067\\u66f4\\u65b0\\u3057\\u3066\\u3044\\u3053\\u3046\\u3068\\u601d\\u3063\\u3066\\u307e\\u3059\\u3002\\r\\n\\u66f4\\u65b0\\u983b\\u5ea6\\u306f\\u9ad8\\u304f\\u3042\\u308a\\u307e\\u305b\\u3093\\u306e\\u3067\\u305d\\u306e\\u3064\\u3082\\u308a\\u3067\\u898b\\u3066\\u3044\\u305f\\u3060\\u3051\\u308b\\u3068\\u5e78\\u3044\\u3067\\u3059\\u3002","imageUrl":"https:\\/\\/pixiv.pximg.net\\/c\\/520x280_90_a2_g5\\/fanbox\\/public\\/images\\/creator\\/133745\\/cover\\/6H4yOYavNLW4dUKvYCyIPphg.jpeg","imageUrlMobile":"https:\\/\\/pixiv.pximg.net\\/c\\/520x280_90_a2_g5\\/fanbox\\/public\\/images\\/creator\\/133745\\/cover\\/6H4yOYavNLW4dUKvYCyIPphg.jpeg","hasAdultContent":true}],"bookmarkCount":{"public":{"illust":1,"novel":0},"private":{"illust":0,"novel":0}},"externalSiteWorksStatus":{"booth":true,"sketch":false,"vroidHub":false},"request":{"showRequestTab":true,"postWorks":{"artworks":[],"novels":[]}}}}'
2020-10-25 01:37:01,183 - PixivUtil20201024 - INFO - Using OAuth to retrieve member info for: 133745
2020-10-25 01:37:01,183 - PixivUtil20201024 - DEBUG - Getting member information: 133745
2020-10-25 01:37:01,183 - PixivUtil20201024 - INFO - Login to OAuth using refresh token.
2020-10-25 01:37:01,187 - PixivUtil20201024 - ERROR - Unknown Error: (<class 'OSError'>, OSError('Could not find a suitable TLS CA certificate bundle, invalid path: C:\\Users\\Public\\Documents\\ESTsoft\\CreatorTemp\\cacert.pem'), <traceback object at 0x04539168>)
2020-10-25 01:37:01,187 - PixivUtil20201024 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 1326, in main
  File "PixivUtil2.py", line 1064, in main_loop
  File "PixivUtil2.py", line 750, in menu_fanbox_download_from_list
  File "PixivFanboxHandler.pyc", line 19, in process_fanbox_artist_by_id
  File "PixivBrowserFactory.pyc", line 904, in fanboxGetArtistById
  File "PixivBrowserFactory.pyc", line 730, in getMemberPage
  File "PixivBrowserFactory.pyc", line 637, in getMemberInfoWhitecube
  File "PixivOAuth.pyc", line 99, in login
  File "requests\sessions.pyc", line 578, in post
  File "cloudscraper\__init__.pyc", line 263, in request
  File "cloudscraper\__init__.pyc", line 182, in perform_request
  File "requests\sessions.pyc", line 530, in request
  File "requests\sessions.pyc", line 643, in send
  File "requests\adapters.pyc", line 416, in send
  File "requests\adapters.pyc", line 227, in cert_verify
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: C:\Users\Public\Documents\ESTsoft\CreatorTemp\cacert.pem
-----------------
Here is log history

**Comment by Nandaka** [comment]
download the file and overwrite the cacert.pem from the one inside the zip file?
[cacert.zip](https://github.com/Nandaka/PixivUtil2/files/5433307/cacert.zip)

**Comment by cocokakao** [comment]
I changed the folder path and file you gave me, but there is still the same error. I'll attach the log history below.

-------

2020-10-25 01:47:32,757 - PixivUtil20201024 - INFO - Download FANBOX by post id mode (f3).
2020-10-25 01:47:35,398 - PixivUtil20201024 - INFO - Trying to log in FANBOX with saved cookie
2020-10-25 01:47:35,642 - PixivUtil20201024 - INFO - Logging in with cookit to Fanbox, return url: https://www.fanbox.cc
2020-10-25 01:47:35,642 - PixivUtil20201024 - INFO - FANBOX Login successful.
2020-10-25 01:47:35,642 - PixivUtil20201024 - DEBUG - Getting post detail from https://api.fanbox.cc/post.info?postId=1527291
2020-10-25 01:47:36,172 - PixivUtil20201024 - DEBUG - {"body":{"id":"1527291","title":"\u9b54\u5973","coverImageUrl":"https:\/\/pixiv.pximg.net\/c\/1200x630_90_a2_g5\/fanbox\/public\/images\/post\/1527291\/cover\/jKNG3rqbGladCEvQtvjr21Wi.jpeg","feeRequired":300,"publishedDatetime":"2020-10-24T22:28:08+09:00","updatedDatetime":"2020-10-24T22:28:55+09:00","type":"article","body":{"blocks":[{"type":"p","text":""},{"type":"image","imageId":"WXwrZX7D1moWGDf1t53Dbv78"},{"type":"p","text":"\u25a0\u30ea\u30af\u30a8\u30b9\u30c8\u5185\u5bb9\u300c\u3061\u3083\u3046\u3055\u3093\u7684\u30cf\u30ed\u30a6\u30a3\u30f3\u9b54\u5973\u3092\u81ea\u7531\u306b\u63cf\u3044\u3066\u3082\u3089\u3044\u305f\u3044\u300d","styles":[{"type":"bold","offset":9,"length":25}]},{"type":"p","text":"\u30de\u30ec\u30d5\u30a3\u30bb\u30f3\u30c8\u306e\u30c7\u30b6\u30a4\u30f3\u3092\u610f\u8b58\u3057\u305f\u306e\u3067\u30cf\u30ed\u30a6\u30a3\u30f3\u306e\u30ab\u30b8\u30e5\u30a2\u30eb\u3063\u307d\u3055\uff1f\u304c\u6e1b\u9000\u3057\u305f\u611f\u304c\u5426\u3081\u307e\u305b\u3093\u304c\u3001\u597d\u307f\u512a\u5148\u3067\u81ea\u7531\u306b\u304b\u304b\u305b\u3066\u3044\u305f\u3060\u304d\u307e\u3057\u305f\u3002"},{"type":"p","text":"\u8da3\u5473\u306b\u7247\u5bc4\u308a\u307e\u3057\u305f\u304c\u697d\u3057\u304b\u3063\u305f\u3067\u3059\uff01"},{"type":"p","text":""},{"type":"p","text":"\u30ea\u30af\u30a8\u30b9\u30c8\u3001\u30e1\u30c3\u30bb\u30fc\u30b8\u3042\u308a\u304c\u3068\u3046\u3054\u3056\u3044\u307e\u3057\u305f\uff01"},{"type":"p","text":"pixiv\u5be9\u67fb\u304c\u5b8c\u4e86\u6b21\u7b2c\u30ae\u30d5\u30c8\u30d5\u30a1\u30a4\u30eb\u9001\u308a\u307e\u3059\u306e\u3067\u5c11\u3005\u304a\u5f85\u3061\u304f\u3060\u3055\u3044\u301c\ud83d\ude47\u200d\u2642\ufe0f"}],"imageMap":{"WXwrZX7D1moWGDf1t53Dbv78":{"id":"WXwrZX7D1moWGDf1t53Dbv78","extension":"jpeg","width":1021,"height":1207,"originalUrl":"https:\/\/downloads.fanbox.cc\/images\/post\/1527291\/WXwrZX7D1moWGDf1t53Dbv78.jpeg","thumbnailUrl":"https:\/\/downloads.fanbox.cc\/images\/post\/1527291\/w\/1200\/WXwrZX7D1moWGDf1t53Dbv78.jpeg"}},"fileMap":{},"embedMap":{}},"tags":[],"excerpt":"\u25a0\u30ea\u30af\u30a8\u30b9\u30c8\u5185\u5bb9\u300c\u3061\u3083\u3046\u3055\u3093\u7684\u30cf\u30ed\u30a6\u30a3\u30f3\u9b54\u5973\u3092\u81ea\u7531\u306b\u63cf\u3044\u3066\u3082\u3089\u3044\u305f\u3044\u300d\n\u30de\u30ec\u30d5\u30a3\u30bb\u30f3\u30c8\u306e\u30c7\u30b6\u30a4\u30f3\u3092\u610f\u8b58\u3057\u305f\u306e\u3067\u30cf\u30ed\u30a6\u30a3\u30f3\u306e\u30ab\u30b8\u30e5\u30a2\u30eb\u3063\u307d\u3055\uff1f\u304c\u6e1b\u9000\u3057\u305f\u611f\u304c\u5426\u3081\u307e\u305b\u3093\u304c\u3001\u597d\u307f\u512a\u5148\u3067\u81ea\u7531\u306b\u304b\u304b\u305b\u3066\u3044\u305f\u3060\u304d\u307e\u3057\u305f\u3002\n\u8da3\u5473\u306b\u7247\u5bc4\u308a\u307e\u3057\u305f\u304c\u697d\u3057\u304b\u3063\u305f\u3067\u3059\uff01\n\u30ea\u30af\u30a8\u30b9\u30c8\u3001\u30e1\u30c3\u30bb\u30fc\u30b8\u3042\u308a\u304c\u3068\u3046\u3054\u3056\u3044\u307e\u3057\u305f\uff01\npixiv...","isLiked":false,"likeCount":5,"commentCount":2,"restrictedFor":null,"user":{"userId":"133745","name":"\u3061\u3083\u3046","iconUrl":"https:\/\/pixiv.pximg.net\/c\/160x160_90_a2_g5\/fanbox\/public\/images\/user\/133745\/icon\/Zq4TQxWtFYQ07glXnX4Amob4.jpeg"},"creatorId":"chau","hasAdultContent":true,"status":"published","commentList":{"items":[{"id":"1183215","parentCommentId":"0","rootCommentId":"0","body":"\u3042\u308a\u304c\u3068\u3046\u3054\u3056\u3044\u307e\u3059\uff01\u6307\u5b9a\u304c\u5927\u96d1\u628a\u3059\u304e\u3066\u3001\u304b\u3048\u3063\u3066\u3084\u308a\u3065\u3089\u3044\u304b\u3068\u601d\u3044\u307e\u3057\u305f\u304c\u3001\u671f\u5f85\u5024\u3092\u8d85\u3048\u3066\u304f\u308b\u6240\u304c\u3084\u3063\u3071\u308a\u30d7\u30ed\u3060\u306a\u3041\u3068\u601d\u3044\u307e\u3057\u305f\uff3e\uff3e","createdDatetime":"2020-10-24T22:50:44+09:00","likeCount":1,"isLiked":false,"isOwn":false,"user":{"userId":"2690244","name":"\u30d2\u30ed7","iconUrl":null},"replies":[{"id":"1183290","parentCommentId":"1183215","rootCommentId":"1183215","body":"\u3044\u3048\u3044\u3048\u3001\u30b7\u30f3\u30d7\u30eb\u306a\u304a\u984c\u3082\u5185\u5bb9\u8003\u3048\u308b\u306e\u304c\u697d\u3057\u304b\u3063\u305f\u3067\u3059\uff01\n\u559c\u3093\u3067\u3044\u305f\u3060\u3051\u305f\u306a\u3089\u5e78\u3044\u3067\u3059\u003E\u003C","createdDatetime":"2020-10-24T23:14:26+09:00","likeCount":1,"isLiked":false,"isOwn":false,"user":{"userId":"133745","name":"\u3061\u3083\u3046","iconUrl":"https:\/\/pixiv.pximg.net\/c\/160x160_90_a2_g5\/fanbox\/public\/images\/user\/133745\/icon\/Zq4TQxWtFYQ07glXnX4Amob4.jpeg"}}]}],"nextUrl":null},"nextPost":null,"prevPost":{"id":"1506413","title":"\uff7c\uff6e\uff70\uff84","publishedDatetime":"2020-10-17 21:54:51"},"imageForShare":"https:\/\/pixiv.pximg.net\/c\/1200x630_90_a2_g5\/fanbox\/public\/images\/post\/1527291\/cover\/jKNG3rqbGladCEvQtvjr21Wi.jpeg"}}
2020-10-25 01:47:36,199 - PixivUtil20201024 - INFO - Getting artist information from https://api.fanbox.cc/creator.get?userId=133745
2020-10-25 01:47:36,444 - PixivUtil20201024 - INFO - Member Url: https://www.pixiv.net/ajax/user/133745/profile/all
2020-10-25 01:47:36,581 - PixivUtil20201024 - DEBUG - b'{"error":false,"message":"","body":{"illusts":[],"manga":[],"novels":[],"mangaSeries":[],"novelSeries":[],"pickup":[{"type":"fanbox","deletable":false,"draggable":true,"userName":"\\u3061\\u3083\\u3046","userImageUrl":"https:\\/\\/i.pximg.net\\/user-profile\\/img\\/2011\\/01\\/19\\/15\\/52\\/54\\/2642901_6685bc8491475bf72160075eed3f3b72_170.png","contentUrl":"https:\\/\\/www.pixiv.net\\/fanbox\\/creator\\/133745?utm_campaign=www_profile\\u0026utm_medium=site_flow\\u0026utm_source=pixiv","description":"\\u25c6job\\uff1a\\u30a2\\u30cb\\u30e1\\u30fc\\u30bf\\u30fc\\u3001\\u6f14\\u51fa\\u3001etc\\u2026\\r\\n\\u300c\\u843d\\u66f8\\u304d\\u300d\\u3084\\u300c\\u8003\\u3048\\u3066\\u3044\\u308b\\u4e8b\\u300d\\u300c\\u6a5f\\u6750\\u3084\\u30bd\\u30d5\\u30c8\\u306e\\u4e8b\\u300d\\u306a\\u3069\\u30af\\u30ed\\u30fc\\u30ba\\u30c9\\u306a\\u7a7a\\u9593\\u3060\\u304b\\u3089\\u3053\\u305d\\u306e\\u6c17\\u697d\\u3055\\u3067\\u66f4\\u65b0\\u3057\\u3066\\u3044\\u3053\\u3046\\u3068\\u601d\\u3063\\u3066\\u307e\\u3059\\u3002\\r\\n\\u66f4\\u65b0\\u983b\\u5ea6\\u306f\\u9ad8\\u304f\\u3042\\u308a\\u307e\\u305b\\u3093\\u306e\\u3067\\u305d\\u306e\\u3064\\u3082\\u308a\\u3067\\u898b\\u3066\\u3044\\u305f\\u3060\\u3051\\u308b\\u3068\\u5e78\\u3044\\u3067\\u3059\\u3002","imageUrl":"https:\\/\\/pixiv.pximg.net\\/c\\/520x280_90_a2_g5\\/fanbox\\/public\\/images\\/creator\\/133745\\/cover\\/6H4yOYavNLW4dUKvYCyIPphg.jpeg","imageUrlMobile":"https:\\/\\/pixiv.pximg.net\\/c\\/520x280_90_a2_g5\\/fanbox\\/public\\/images\\/creator\\/133745\\/cover\\/6H4yOYavNLW4dUKvYCyIPphg.jpeg","hasAdultContent":true}],"bookmarkCount":{"public":{"illust":1,"novel":0},"private":{"illust":0,"novel":0}},"externalSiteWorksStatus":{"booth":true,"sketch":false,"vroidHub":false},"request":{"showRequestTab":true,"postWorks":{"artworks":[],"novels":[]}}}}'
2020-10-25 01:47:36,591 - PixivUtil20201024 - INFO - Using OAuth to retrieve member info for: 133745
2020-10-25 01:47:36,591 - PixivUtil20201024 - DEBUG - Getting member information: 133745
2020-10-25 01:47:36,591 - PixivUtil20201024 - INFO - Login to OAuth using refresh token.
2020-10-25 01:47:36,594 - PixivUtil20201024 - ERROR - Unknown Error: (<class 'OSError'>, OSError('Could not find a suitable TLS CA certificate bundle, invalid path: C:\\Users\\Public\\Documents\\ESTsoft\\CreatorTemp\\cacert.pem'), <traceback object at 0x03DCBC88>)
2020-10-25 01:47:36,595 - PixivUtil20201024 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 1326, in main
  File "PixivUtil2.py", line 1068, in main_loop
  File "PixivUtil2.py", line 769, in menu_fanbox_download_by_post_id
  File "PixivBrowserFactory.pyc", line 950, in fanboxGetPostById
  File "PixivBrowserFactory.pyc", line 904, in fanboxGetArtistById
  File "PixivBrowserFactory.pyc", line 730, in getMemberPage
  File "PixivBrowserFactory.pyc", line 637, in getMemberInfoWhitecube
  File "PixivOAuth.pyc", line 99, in login
  File "requests\sessions.pyc", line 578, in post
  File "cloudscraper\__init__.pyc", line 263, in request
  File "cloudscraper\__init__.pyc", line 182, in perform_request
  File "requests\sessions.pyc", line 530, in request
  File "requests\sessions.pyc", line 643, in send
  File "requests\adapters.pyc", line 416, in send
  File "requests\adapters.pyc", line 227, in cert_verify
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: C:\Users\Public\Documents\ESTsoft\CreatorTemp\cacert.pem

**Comment by Nandaka** [comment]
yeah, it said cannot find the cacert.pem (not the zip file), make sure it can read file, as I can access it after I copy it the path (in my case, it was pointing to `\AppData\\Local\\Temp\\cacert.pem`

**Comment by cocokakao** [comment]
I solved this issue. Thank you for your help and patience.

**Comment by Nandaka** [comment]
yeah, I'll find a way to automate this.

**Comment by Nandaka** [comment]
latest version should resolve based on the exe location
