### ISSUE TITLE
No such file or directory: 'browsers.json'

### ISSUE THREAD

**Issue by GerhardSauer** [Nandaka/PixivUtil2#846]
### Prerequisites

* [X] Did you read FAQ section?
* [X] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description
newest versions looks for browser.json not in main directory but the working directory of the command window ( in my case the downloadlistdirectory)

When I copy the browser.json to my downloadlistdirectory ( which is the working directory), then it works. But I guess it should work when the file is with the other program files.

[Description of the bug or feature]

### Steps to Reproduce
probably just starting pixivdownloader from a different working directory

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]
pixiv starts normal

**Actual behavior:** [What actually happened]
error
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "PixivArtistHandler.pyc", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "PixivBrowserFactory.pyc", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "PixivOAuth.pyc", line 16, in <module>
  File "PixivOAuth.pyc", line 30, in PixivOAuth
  File "cloudscraper\__init__.pyc", line 748, in create_scraper
  File "cloudscraper\__init__.pyc", line 136, in __init__
  File "cloudscraper\user_agent\__init__.pyc", line 20, in __init__
  File "cloudscraper\user_agent\__init__.pyc", line 78, in loadUserAgent
FileNotFoundError: [Errno 2] No such file or directory: 'browsers.json'

### Versions
PixivDownloader2 version 20201025

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by Nandaka** [comment]
it should have a file called browser.json in the pixivutil folder. 
If you running using script/batch file. ensure you change the current active directory to the pixivutil folder.

**Comment by GerhardSauer** [comment]
The browser.json file is in the pixivutil folder, but I'm not in this directory, when calling the pixivutil. From the past, I had better results, when calling pixivutil from download list folder. I just copied the file to this directory.

**Comment by Nandaka** [comment]
yeah, I need to use additional library called cloudscraper so it can pass the cloudflare for oAuth login.
If you are calling using shortcut, ensure `Start In` is configured to your pixivutil folder.
![image](https://user-images.githubusercontent.com/836867/97111583-a1701d80-171a-11eb-95f2-4a986bf3f941.png)

if you are using batch file, put `cd your_pixiv_folder` before calling the exe

**Comment by theChrisliebaer** [comment]
Would it be possible to restore the old behavior that allowed calling the pixivutil binary from any path via the PATH variable? It's really clusmy to have absolute paths everywhere. Would be greatly appraciated :)

**Comment by Nandaka** [comment]
If you run from source code, then yes. It is limitation of the library if compiled using py2exe.

**Comment by Nandaka** [comment]
can you try the latest version, I tried to patch the lib so it will resolve the browser.json from the executable location
