### ISSUE TITLE
HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by charlesdai2003** [Nandaka/PixivUtil2#850]
I am encountering HTTP Error 403: Forbidden when using the newest version. The log file reads:

`
2020-10-26 18:06:32,809 - PixivUtil20201025 - ERROR - Cannot Login!
2020-10-26 18:06:32,809 - PixivUtil20201025 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 1119, in doLogin
  File "PixivBrowserFactory.pyc", line 313, in loginUsingCookie
  File "PixivBrowserFactory.pyc", line 205, in open_with_retry
  File "mechanize\_mechanize.pyc", line 257, in open
  File "mechanize\_mechanize.pyc", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PixivUtil2.py", line 1323, in main
  File "PixivUtil2.py", line 1126, in doLogin
PixivException.PixivException: 0 Cannot Login!, hasDumpPage=N, pageData=None
`

I can access pixiv through my browser fine and the program is using cookie values from my browser. I have also turned off userrobots so that is not the issue either. Does anyone know how I can fix this problem?

**Comment by Nandaka** [comment]
see https://github.com/Nandaka/PixivUtil2/issues/814

**Comment by ee092884** [comment]
You try to https://github.com/Nandaka/PixivUtil2/issues/814#issuecomment-711182644
