### ISSUE TITLE
Error while trying to download from bookmarked members (/bookmark_new_illust.php)

### ISSUE THREAD

**Issue by jacobpewit** [Nandaka/PixivUtil2#859]
### Prerequisites

* [X] Did you read FAQ section?
* [X] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

When I try to download new illusts from bookmarked members (option 8) I get the following output:
```
Processing New Illust from bookmark
Page #1
Source URL: https://www.pixiv.net/bookmark_new_illust.php?p=1
Error at process_new_illust_from_bookmark(): (<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'findAll'"), <traceback object at 0x1D168800>)
Traceback (most recent call last):
  File "PixivUtil2.py", line 1604, in main
    np_is_valid, op_is_valid, selection = main_loop(ewd, op_is_valid, selection, np_is_valid, args)
  File "PixivUtil2.py", line 1320, in main_loop
    menu_download_new_illust_from_bookmark(op_is_valid, args)
  File "PixivUtil2.py", line 921, in menu_download_new_illust_from_bookmark
    process_new_illust_from_bookmark(page_num, end_page_num, r18)
  File "PixivUtil2.py", line 419, in process_new_illust_from_bookmark
    pb = PixivNewIllustBookmark(parsed_page)
  File "l:\PixivUtil2Python\PixivBookmark.py", line 102, in __init__
    self.__ParseNewIllustBookmark(page)
  File "l:\PixivUtil2Python\PixivBookmark.py", line 120, in __ParseNewIllustBookmark
    result = page.find(attrs={'class': '_image-items autopagerize_page_element'}).findAll('a')
AttributeError: 'NoneType' object has no attribute 'findAll'
press enter to exit.
```

Downloading by member_id and image_id seem to be working fine however.

**Comment by Nandaka** [comment]
can you upload the html page from the given url in the logging? it should try to find `js-mount-point-latest-following` in script tag.

**Comment by jacobpewit** [comment]
Strangely, after changing my password & updating the cookie string back to the old cookie format used by pixiv, everything started working normally again.
