### ISSUE TITLE
Some Fanbox Files cannot be downloaded due to OSError: [WinError 225]

### ISSUE THREAD

**Issue by b000408** [Nandaka/PixivUtil2#864]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

When downloading from supported artist, error flagged out and appeared to be OSError: [WinError 225], which it says "the file contains virus(I'm not a native English user so in the system it appeared in my mother language), and the program stopped forcing to exit.

### Steps to Reproduce

1. [Re-Open Pixivutil]
2. [Try download the specific Pixiv Fanbox artwork failed previously]
3. [Try download the whole artist's works which contained the failed-to-be-downloaded artwork]

**Expected behavior:** [OSError: [WinError 225] occur and program ask to exit]

**Actual behavior:** [OSError: [WinError 225] occur and program ask to exit]

### Versions

v20201031

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by Nandaka** [comment]
Looks like it is being blocked by anti virus. Do you have the log file? most likely what it can be done is just skip that specific post.

**Comment by b000408** [comment]
I'll clean the files and try making a "specific" log file for the problematic artwork later when I return to my computer. As I can pin down the exact artwork which have this problem.

**Comment by b000408** [comment]
I do created a specific file log. However I do wonder is there any way to disable the anti virus...

log as follow

---

2020-11-10 16:28:22,962 - PixivUtil20201031 - DEBUG - Getting post detail from https://api.fanbox.cc/post.info?postId=571194
2020-11-10 16:28:23,303 - PixivUtil20201031 - DEBUG - {"body":{"id":"571194","title":"old old works","coverImageUrl":null,"feeRequired":500,"publishedDatetime":"2019-09-24T04:32:52+09:00","updatedDatetime":"2019-09-24T04:32:52+09:00","type":"file","body":{"text":"","files":[{"id":"BcwQEvrOFzsINGEGBm6JIWnz","name":"old old works1","extension":"zip","size":141269699,"url":"https:\/\/downloads.fanbox.cc\/files\/post\/571194\/BcwQEvrOFzsINGEGBm6JIWnz.zip"},{"id":"BGaRVHd458GoTypuWvlmJT6q","name":"old old works2","extension":"zip","size":125047341,"url":"https:\/\/downloads.fanbox.cc\/files\/post\/571194\/BGaRVHd458GoTypuWvlmJT6q.zip"},{"id":"YovgDUAar1SstVdwPG0Fv1IE","name":"old old works3","extension":"zip","size":158663869,"url":"https:\/\/downloads.fanbox.cc\/files\/post\/571194\/YovgDUAar1SstVdwPG0Fv1IE.zip"},{"id":"TKjjxTFlIwFe1t52Tsr0il4W","name":"old old works4","extension":"zip","size":103325394,"url":"https:\/\/downloads.fanbox.cc\/files\/post\/571194\/TKjjxTFlIwFe1t52Tsr0il4W.zip"},{"id":"ghbCQ39PnnNwALTKmUBDIiot","name":"old old works5","extension":"zip","size":157907512,"url":"https:\/\/downloads.fanbox.cc\/files\/post\/571194\/ghbCQ39PnnNwALTKmUBDIiot.zip"},{"id":"M49AElLzXpd81cIlejiDvMVY","name":"old old works6","extension":"zip","size":73757459,"url":"https:\/\/downloads.fanbox.cc\/files\/post\/571194\/M49AElLzXpd81cIlejiDvMVY.zip"},{"id":"FcSvFGhf97In0R1cTOZtYMyy","name":"old old works7","extension":"zip","size":155892480,"url":"https:\/\/downloads.fanbox.cc\/files\/post\/571194\/FcSvFGhf97In0R1cTOZtYMyy.zip"},{"id":"BrauhHLcH1yjccWQ8Reh31i0","name":"old old works8","extension":"zip","size":100421336,"url":"https:\/\/downloads.fanbox.cc\/files\/post\/571194\/BrauhHLcH1yjccWQ8Reh31i0.zip"},{"id":"BoliYaP5TefAQbxlSznD3giH","name":"old old works9","extension":"zip","size":99575049,"url":"https:\/\/downloads.fanbox.cc\/files\/post\/571194\/BoliYaP5TefAQbxlSznD3giH.zip"},{"id":"cJI5DeUR5jtQDfZY6SgYFvsz","name":"old old works10","extension":"zip","size":90706559,"url":"https:\/\/downloads.fanbox.cc\/files\/post\/571194\/cJI5DeUR5jtQDfZY6SgYFvsz.zip"},{"id":"QVQFPPmwxfwkMdrzi0lttW8e","name":"old old works11","extension":"zip","size":111319995,"url":"https:\/\/downloads.fanbox.cc\/files\/post\/571194\/QVQFPPmwxfwkMdrzi0lttW8e.zip"},{"id":"dqcfEy22TyFGwKNvN5LdgO76","name":"old old works12","extension":"zip","size":37268909,"url":"https:\/\/downloads.fanbox.cc\/files\/post\/571194\/dqcfEy22TyFGwKNvN5LdgO76.zip"}]},"tags":[],"excerpt":"","isLiked":false,"likeCount":30,"commentCount":1,"restrictedFor":null,"user":{"userId":"17151277","name":"mamimi","iconUrl":"https:\/\/pixiv.pximg.net\/c\/160x160_90_a2_g5\/fanbox\/public\/images\/user\/17151277\/icon\/gef1I0qIQH7JerQTPnf8tWv3.jpeg"},"creatorId":"mamimi","hasAdultContent":true,"status":"published","commentList":{"items":[{"id":"338658","parentCommentId":"0","rootCommentId":"0","body":"\u3042\u308a\u304c\u3068\u3046\u3054\u3056\u3044\u307e\u3059\u3002\n\u898b\u305f\u304b\u3063\u305f\u7d75\u306a\u3069\u3082\u3042\u3063\u305f\u306e\u3067\n\u3068\u3066\u3082\u5b09\u3057\u3044\u3067\u3059\u3002","createdDatetime":"2019-09-24T07:49:55+09:00","likeCount":3,"isLiked":false,"isOwn":false,"user":{"userId":"20989700","name":"\u7530\u4e2d","iconUrl":null},"replies":[]}],"nextUrl":null},"nextPost":{"id":"578831","title":"Musume (complete)","publishedDatetime":"2019-09-29 05:52:16"},"prevPost":{"id":"569699","title":"Mamako (complete)","publishedDatetime":"2019-09-23 09:11:49"},"imageForShare":"https:\/\/pixiv.pximg.net\/c\/1200x630_90_a2_g5\/fanbox\/public\/images\/creator\/17151277\/cover\/XHTOv3kP3OkzgJC0g0UgSxCP.jpeg"}}
2020-11-10 16:28:23,334 - PixivUtil20201031 - INFO - Getting artist information from https://api.fanbox.cc/creator.get?userId=17151277
2020-11-10 16:28:23,579 - PixivUtil20201031 - INFO - Member Url: https://www.pixiv.net/ajax/user/17151277/profile/all
2020-11-10 16:28:23,930 - PixivUtil20201031 - DEBUG - b'{"error":false,"message":"","body":{"illusts":{"85527682":null,"85466516":null,"85385177":null,"85264952":null,"85199422":null,"85159966":null,"85076867":null,"85002148":null,"84912790":null,"84844888":null,"84777046":null,"84726147":null,"84663050":null,"84545388":null,"84454641":null,"84329568":null,"84243425":null,"84139104":null,"84083096":null,"83944454":null,"83823667":null,"83798219":null,"83704874":null,"83564635":null,"83453380":null,"83375793":null,"83366013":null,"83223911":null,"83129081":null,"83017503":null,"82921045":null,"82834668":null,"82712030":null,"82603417":null,"82523500":null,"82443425":null,"82371711":null,"82266789":null,"82160395":null,"82045679":null,"81958659":null,"81719867":null,"81584663":null,"81473746":null,"81352374":null,"81223793":null,"81083320":null,"80959252":null,"80817395":null,"80677531":null,"80545499":null,"80486755":null,"80320113":null,"80247115":null,"80085910":null,"79961906":null,"79851304":null,"79815178":null,"79567877":null,"79341581":null,"79223865":null,"79210389":null,"79061835":null,"78983085":null,"78915162":null,"78824494":null,"78800940":null,"78700193":null,"78412771":null,"78358271":null,"78261988":null,"78244202":null,"78136841":null,"78083682":null,"77958640":null,"77935533":null,"77856511":null,"77787475":null,"77711449":null,"77615028":null,"77607158":null,"77443556":null,"77366482":null,"77211222":null,"77060309":null,"76995624":null,"76790864":null,"76660763":null,"76484269":null,"76218100":null,"76039479":null,"75851133":null,"75715011":null,"75695305":null,"75501689":null,"75264155":null,"75240567":null,"75227883":null,"75193823":null,"75122805":null,"75105534":null,"75051977":null,"75018908":null,"75000928":null,"74908876":null,"74890786":null,"74806335":null,"74786945":null,"74638660":null,"74391862":null,"74284290":null,"74211974":null,"74083149":null,"74059994":null,"73866655":null,"73845866":null,"73726895":null,"73604301":null,"73595090":null,"73477710":null,"73342224":null,"73231063":null,"73188717":null},"manga":[],"novels":[],"mangaSeries":[],"novelSeries":[],"pickup":[{"type":"fanbox","deletable":false,"draggable":true,"userName":"mamimi","userImageUrl":"https:\\/\\/i.pximg.net\\/user-profile\\/img\\/2020\\/03\\/23\\/08\\/16\\/46\\/18165424_e84453ea3aa8d870b4b56807934f32ea_170.png","contentUrl":"https:\\/\\/www.pixiv.net\\/fanbox\\/creator\\/17151277?utm_campaign=www_profile\\u0026utm_medium=site_flow\\u0026utm_source=pixiv","description":"Thank you for your support. I will always do my best. Your sponsorship is used for better quality drawings and stable production environments. (It will operate in the same way as patreon)","imageUrl":"https:\\/\\/pixiv.pximg.net\\/c\\/520x280_90_a2_g5\\/fanbox\\/public\\/images\\/creator\\/17151277\\/cover\\/XHTOv3kP3OkzgJC0g0UgSxCP.jpeg","imageUrlMobile":"https:\\/\\/pixiv.pximg.net\\/c\\/520x280_90_a2_g5\\/fanbox\\/public\\/images\\/creator\\/17151277\\/cover\\/XHTOv3kP3OkzgJC0g0UgSxCP.jpeg","hasAdultContent":true},{"id":"83129081","title":"Dildo","illustType":0,"xRestrict":1,"restrict":0,"sl":6,"url":"https:\\/\\/i.pximg.net\\/c\\/288x288_80_a2\\/custom-thumb\\/img\\/2020\\/07\\/21\\/23\\/37\\/50\\/83129081_p0_custom1200.jpg","description":"\\u003Ca href=\\u0022https:\\/\\/mamimi.fanbox.cc\\/posts\\/1238477\\u0022 target=\\u0022_blank\\u0022\\u003Ehttps:\\/\\/mamimi.fanbox.cc\\/posts\\/1238477\\u003C\\/a\\u003E","tags":["R-18","\\u53e4\\u898b\\u3055\\u3093\\u306f\\u3001\\u30b3\\u30df\\u30e5\\u75c7\\u3067\\u3059\\u3002","\\u53e4\\u898b\\u785d\\u5b50","\\u30c7\\u30a3\\u30eb\\u30c9","\\u53e4\\u898b\\u3055\\u309310000users\\u5165\\u308a","\\u5927\\u4eba\\u306e\\u304a\\u3082\\u3061\\u3083"],"userId":"17151277","userName":"mamimi","width":4000,"height":6128,"pageCount":2,"isBookmarkable":true,"bookmarkData":null,"alt":"#\\u53e4\\u898b\\u3055\\u3093\\u306f\\u3001\\u30b3\\u30df\\u30e5\\u75c7\\u3067\\u3059\\u3002 Dildo - mamimi\\u7684\\u63d2\\u756b","isAdContainer":false,"titleCaptionTranslation":{"workTitle":"","workCaption":""},"createDate":"2020-07-21T23:37:50+09:00","updateDate":"2020-07-21T23:37:50+09:00","isUnlisted":false,"urls":{"250x250":"https:\\/\\/i.pximg.net\\/c\\/250x250_80_a2\\/custom-thumb\\/img\\/2020\\/07\\/21\\/23\\/37\\/50\\/83129081_p0_custom1200.jpg","360x360":"https:\\/\\/i.pximg.net\\/c\\/360x360_70\\/custom-thumb\\/img\\/2020\\/07\\/21\\/23\\/37\\/50\\/83129081_p0_custom1200.jpg","540x540":"https:\\/\\/i.pximg.net\\/c\\/540x540_70\\/custom-thumb\\/img\\/2020\\/07\\/21\\/23\\/37\\/50\\/83129081_p0_custom1200.jpg"},"type":"illust","deletable":true,"draggable":true,"contentUrl":"https:\\/\\/www.pixiv.net\\/artworks\\/83129081"},{"id":"82921045","title":"Komi-san\\u0027s skirt","illustType":0,"xRestrict":1,"restrict":0,"sl":6,"url":"https:\\/\\/i.pximg.net\\/c\\/288x288_80_a2\\/custom-thumb\\/img\\/2020\\/07\\/12\\/13\\/00\\/04\\/82921045_p0_custom1200.jpg","description":"Waiting for Tadano\\u003Cbr \\/\\u003E\\u003Cbr \\/\\u003E\\u003Ca href=\\u0022https:\\/\\/mamimi.fanbox.cc\\/posts\\/1211237\\u0022 target=\\u0022_blank\\u0022\\u003Ehttps:\\/\\/mamimi.fanbox.cc\\/posts\\/1211237\\u003C\\/a\\u003E\\u003Cbr \\/\\u003E\\u003Ca href=\\u0022\\/jump.php?https%3A%2F%2Fwww.patreon.com%2Fposts%2F39217513\\u0022 target=\\u0022_blank\\u0022\\u003Ehttps:\\/\\/www.patreon.com\\/posts\\/39217513\\u003C\\/a\\u003E","tags":["R-18","\\u53e4\\u898b\\u3055\\u3093\\u306f\\u3001\\u30b3\\u30df\\u30e5\\u75c7\\u3067\\u3059\\u3002","\\u53e4\\u898b\\u785d\\u5b50","\\u8336\\u5dfe\\u7e1b\\u308a","\\u63c9\\u307f\\u3057\\u3060\\u304d\\u305f\\u3044\\u4e73","\\u53e4\\u898b\\u3055\\u309310000users\\u5165\\u308a"],"userId":"17151277","userName":"mamimi","width":3400,"height":7300,"pageCount":2,"isBookmarkable":true,"bookmarkData":null,"alt":"#\\u53e4\\u898b\\u3055\\u3093\\u306f\\u3001\\u30b3\\u30df\\u30e5\\u75c7\\u3067\\u3059\\u3002 Komi-san\\u0027s skirt - mamimi\\u7684\\u63d2\\u756b","isAdContainer":false,"titleCaptionTranslation":{"workTitle":"","workCaption":""},"createDate":"2020-07-12T13:00:04+09:00","updateDate":"2020-07-12T13:00:04+09:00","isUnlisted":false,"urls":{"250x250":"https:\\/\\/i.pximg.net\\/c\\/250x250_80_a2\\/custom-thumb\\/img\\/2020\\/07\\/12\\/13\\/00\\/04\\/82921045_p0_custom1200.jpg","360x360":"https:\\/\\/i.pximg.net\\/c\\/360x360_70\\/custom-thumb\\/img\\/2020\\/07\\/12\\/13\\/00\\/04\\/82921045_p0_custom1200.jpg","540x540":"https:\\/\\/i.pximg.net\\/c\\/540x540_70\\/custom-thumb\\/img\\/2020\\/07\\/12\\/13\\/00\\/04\\/82921045_p0_custom1200.jpg"},"type":"illust","deletable":true,"draggable":true,"contentUrl":"https:\\/\\/www.pixiv.net\\/artworks\\/82921045"}],"bookmarkCount":{"public":{"illust":1,"novel":0},"private":{"illust":0,"novel":0}},"externalSiteWorksStatus":{"booth":false,"sketch":false,"vroidHub":false},"request":{"showRequestTab":false,"postWorks":{"artworks":[],"novels":[]}}}}'
2020-11-10 16:28:23,980 - PixivUtil20201031 - DEBUG - using webrpc: https://www.pixiv.net/rpc/get_work.php?id=85527682
2020-11-10 16:28:24,282 - PixivUtil20201031 - DEBUG - Getting post detail from https://api.fanbox.cc/post.info?postId=571194
2020-11-10 16:28:24,541 - PixivUtil20201031 - DEBUG - {"body":{"id":"571194","title":"old old works","coverImageUrl":null,"feeRequired":500,"publishedDatetime":"2019-09-24T04:32:52+09:00","updatedDatetime":"2019-09-24T04:32:52+09:00","type":"file","body":{"text":"","files":[{"id":"BcwQEvrOFzsINGEGBm6JIWnz","name":"old old works1","extension":"zip","size":141269699,"url":"https:\/\/downloads.fanbox.cc\/files\/post\/571194\/BcwQEvrOFzsINGEGBm6JIWnz.zip"},{"id":"BGaRVHd458GoTypuWvlmJT6q","name":"old old works2","extension":"zip","size":125047341,"url":"https:\/\/downloads.fanbox.cc\/files\/post\/571194\/BGaRVHd458GoTypuWvlmJT6q.zip"},{"id":"YovgDUAar1SstVdwPG0Fv1IE","name":"old old works3","extension":"zip","size":158663869,"url":"https:\/\/downloads.fanbox.cc\/files\/post\/571194\/YovgDUAar1SstVdwPG0Fv1IE.zip"},{"id":"TKjjxTFlIwFe1t52Tsr0il4W","name":"old old works4","extension":"zip","size":103325394,"url":"https:\/\/downloads.fanbox.cc\/files\/post\/571194\/TKjjxTFlIwFe1t52Tsr0il4W.zip"},{"id":"ghbCQ39PnnNwALTKmUBDIiot","name":"old old works5","extension":"zip","size":157907512,"url":"https:\/\/downloads.fanbox.cc\/files\/post\/571194\/ghbCQ39PnnNwALTKmUBDIiot.zip"},{"id":"M49AElLzXpd81cIlejiDvMVY","name":"old old works6","extension":"zip","size":73757459,"url":"https:\/\/downloads.fanbox.cc\/files\/post\/571194\/M49AElLzXpd81cIlejiDvMVY.zip"},{"id":"FcSvFGhf97In0R1cTOZtYMyy","name":"old old works7","extension":"zip","size":155892480,"url":"https:\/\/downloads.fanbox.cc\/files\/post\/571194\/FcSvFGhf97In0R1cTOZtYMyy.zip"},{"id":"BrauhHLcH1yjccWQ8Reh31i0","name":"old old works8","extension":"zip","size":100421336,"url":"https:\/\/downloads.fanbox.cc\/files\/post\/571194\/BrauhHLcH1yjccWQ8Reh31i0.zip"},{"id":"BoliYaP5TefAQbxlSznD3giH","name":"old old works9","extension":"zip","size":99575049,"url":"https:\/\/downloads.fanbox.cc\/files\/post\/571194\/BoliYaP5TefAQbxlSznD3giH.zip"},{"id":"cJI5DeUR5jtQDfZY6SgYFvsz","name":"old old works10","extension":"zip","size":90706559,"url":"https:\/\/downloads.fanbox.cc\/files\/post\/571194\/cJI5DeUR5jtQDfZY6SgYFvsz.zip"},{"id":"QVQFPPmwxfwkMdrzi0lttW8e","name":"old old works11","extension":"zip","size":111319995,"url":"https:\/\/downloads.fanbox.cc\/files\/post\/571194\/QVQFPPmwxfwkMdrzi0lttW8e.zip"},{"id":"dqcfEy22TyFGwKNvN5LdgO76","name":"old old works12","extension":"zip","size":37268909,"url":"https:\/\/downloads.fanbox.cc\/files\/post\/571194\/dqcfEy22TyFGwKNvN5LdgO76.zip"}]},"tags":[],"excerpt":"","isLiked":false,"likeCount":30,"commentCount":1,"restrictedFor":null,"user":{"userId":"17151277","name":"mamimi","iconUrl":"https:\/\/pixiv.pximg.net\/c\/160x160_90_a2_g5\/fanbox\/public\/images\/user\/17151277\/icon\/gef1I0qIQH7JerQTPnf8tWv3.jpeg"},"creatorId":"mamimi","hasAdultContent":true,"status":"published","commentList":{"items":[{"id":"338658","parentCommentId":"0","rootCommentId":"0","body":"\u3042\u308a\u304c\u3068\u3046\u3054\u3056\u3044\u307e\u3059\u3002\n\u898b\u305f\u304b\u3063\u305f\u7d75\u306a\u3069\u3082\u3042\u3063\u305f\u306e\u3067\n\u3068\u3066\u3082\u5b09\u3057\u3044\u3067\u3059\u3002","createdDatetime":"2019-09-24T07:49:55+09:00","likeCount":3,"isLiked":false,"isOwn":false,"user":{"userId":"20989700","name":"\u7530\u4e2d","iconUrl":null},"replies":[]}],"nextUrl":null},"nextPost":{"id":"578831","title":"Musume (complete)","publishedDatetime":"2019-09-29 05:52:16"},"prevPost":{"id":"569699","title":"Mamako (complete)","publishedDatetime":"2019-09-23 09:11:49"},"imageForShare":"https:\/\/pixiv.pximg.net\/c\/1200x630_90_a2_g5\/fanbox\/public\/images\/creator\/17151277\/cover\/XHTOv3kP3OkzgJC0g0UgSxCP.jpeg"}}
2020-11-10 16:28:24,584 - PixivUtil20201031 - INFO - No Cover Image for post: 571194.
2020-11-10 16:28:24,585 - PixivUtil20201031 - DEBUG - Sanitized Filename: D:\Download\Pixivutil\pixivutil20201031(Fanbox II)\mamimi (17151277)\571194_p0_BcwQEvrOFzsINGEGBm6JIWnz - old old works.zip
2020-11-10 16:28:24,588 - PixivUtil20201031 - INFO - Creating directory: D:\Download\Pixivutil\pixivutil20201031(Fanbox II)\mamimi (17151277)
2020-11-10 16:28:24,590 - PixivUtil20201031 - INFO - Using Referer: https://www.pixiv.net/fanbox/creator/17151277/post/571194
2020-11-10 16:28:24,937 - PixivUtil20201031 - INFO - Using Referer: https://www.pixiv.net/fanbox/creator/17151277/post/571194
2020-11-10 16:28:54,712 - PixivUtil20201031 - ERROR - Error at download_image(): (<class 'OSError'>, OSError(22, '因為檔案包含病毒或潛在的垃圾軟體，所以作業未順利完成。'), <traceback object at 0x03788F88>) at https://downloads.fanbox.cc/files/post/571194/BcwQEvrOFzsINGEGBm6JIWnz.zip (9001)
2020-11-10 16:28:54,713 - PixivUtil20201031 - ERROR - Traceback (most recent call last):
  File "PixivDownloadHandler.pyc", line 151, in download_image
  File "PixivDownloadHandler.pyc", line 276, in perform_download
  File "PixivHelper.pyc", line 730, in download_image
OSError: [WinError 225] 因為檔案包含病毒或潛在的垃圾軟體，所以作業未順利完成。: 'D:\\Download\\Pixivutil\\pixivutil20201031(Fanbox II)\\mamimi (17151277)\\571194_p0_BcwQEvrOFzsINGEGBm6JIWnz - old old works.zip.pixiv' -> 'D:\\Download\\Pixivutil\\pixivutil20201031(Fanbox II)\\mamimi (17151277)\\571194_p0_BcwQEvrOFzsINGEGBm6JIWnz - old old works.zip'

**Comment by Nandaka** [comment]
if you are using windows, maybe you can exclude the download directory from scanning? 
If you are using windows defender in win10 https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26

**Comment by Nandaka** [comment]
then upload the downloaded file to virustotal just to be sure if it real virus or not.

**Comment by b000408** [comment]
Probably Windows defender cause the problem, as I manual downloaded the files from artwork page it works just fine.
I'll try disable windows defender to see if it works.
