### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by NHOrus** [Nandaka/PixivUtil2#87]
getting following error:
```
2015-07-15 17:23:00,375 - PixivUtil20150711 - INFO - ###############################################################
2015-07-15 17:23:00,375 - PixivUtil20150711 - INFO - Starting...
2015-07-15 17:23:00,375 - PixivUtil20150711 - INFO - Setting log level to: DEBUG
2015-07-15 17:23:00,375 - PixivUtil20150711 - INFO - No default cookie jar available, creating... 
2015-07-15 17:23:00,375 - PixivUtil20150711 - INFO - Using Username: nhorus
2015-07-15 17:23:00,375 - PixivUtil20150711 - INFO - Trying to log with saved cookie
2015-07-15 17:23:02,923 - PixivUtil20150711 - INFO - Failed to login using cookie, returned page: http://www.pixiv.net/
2015-07-15 17:23:02,923 - PixivUtil20150711 - INFO - Cookie already expired/invalid.
2015-07-15 17:23:02,923 - PixivUtil20150711 - INFO - Log in using form.
2015-07-15 17:23:05,717 - PixivUtil20150711 - ERROR - Error at pixiv_login():(<class 'mechanize._mechanize.FormNotFoundError'>, FormNotFoundError('no form matching predicate <function <lambda> at 0x03095DF0>',), <traceback object at 0x03240120>)
2015-07-15 17:23:05,717 - PixivUtil20150711 - ERROR - Error at pixiv_login(): (<class 'mechanize._mechanize.FormNotFoundError'>, FormNotFoundError('no form matching predicate <function <lambda> at 0x03095DF0>',), <traceback object at 0x03240120>)
Traceback (most recent call last):
  File "PixivBrowserFactory.pyc", line 177, in loginHttp
  File "mechanize\_mechanize.pyc", line 524, in select_form
FormNotFoundError: no form matching predicate <function <lambda> at 0x03095DF0>
2015-07-15 17:23:05,717 - PixivUtil20150711 - ERROR - Error at doLogin(): (<class 'mechanize._mechanize.FormNotFoundError'>, FormNotFoundError('no form matching predicate <function <lambda> at 0x03095DF0>',), <traceback object at 0x03240E90>)
2015-07-15 17:23:05,717 - PixivUtil20150711 - ERROR - Cannot Login!
2015-07-15 17:23:07,982 - PixivUtil20150711 - INFO - EXIT: 1005
2015-07-15 17:23:07,982 - PixivUtil20150711 - INFO - ###############################################################
```
Attempts to put cookie value into config from browser did not work. Flipping usessl changes nothing.

Have they changed login system?

**Comment by Nandaka** [comment]
most likely

**Comment by Nandaka** [comment]
Try: http://www.mediafire.com/download/js3ycgqxe25277b/pixivutil20150715.7z

**Comment by NHOrus** [comment]
It appears to be working for my intended usage.

Thanks!

... I definitely need to donate to you again for your support of the PixivUtil.
