### ISSUE TITLE
Fanbox: Downloading from working fanbox fails if user is suspended on Pixiv

### ISSUE THREAD

**Issue by NHOrus** [Nandaka/PixivUtil2#873]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

If an artist is suspended on Pixiv, his Fanbox continues to work and art could be seen. Most likely - until artist is removed. In this case, Pixiv fails to get updates or other data from artist's Fanbox page

### Steps to Reproduce

1. Support a suspended artist
2. Start downloading their art with f1 or f2 functions.

**Expected behavior:** [What you expected to happen]

Updates since last download are on my HDD, with data that's unavailable from Pixiv is replaced with data from database or with placeholder, if needed. In my use case, only Artist ID is needed and it is retrieved from fanbox itself

**Actual behavior:** [What actually happened]

Warning: artist is R18-G

```
2020-12-01 08:01:35,844 - PixivUtil20201130 - INFO - ###############################################################
2020-12-02 09:01:59,166 - PixivUtil20201130 - DEBUG - Running from executable version for PixivOAuth
2020-12-02 09:01:59,181 - PixivUtil20201130 - DEBUG - browser.json location = E:\conf\pixiv\pixivutil\browsers.json
2020-12-02 09:01:59,369 - PixivUtil20201130 - INFO - ###############################################################
2020-12-02 09:01:59,369 - PixivUtil20201130 - INFO - Starting with argument: [E:\conf\pixiv\pixivutil\PixivUtil2.exe].
2020-12-02 09:01:59,371 - PixivUtil20201130 - INFO - Setting log level to: DEBUG
2020-12-02 09:01:59,371 - PixivUtil20201130 - INFO - No default cookie jar available, creating... 
2020-12-02 09:01:59,755 - PixivUtil20201130 - INFO - Using default DB Path: E:\conf\pixiv\pixivutil\db.sqlite
2020-12-02 09:01:59,784 - PixivUtil20201130 - INFO - Using Username: nhorus
2020-12-02 09:01:59,784 - PixivUtil20201130 - INFO - Trying to log in with saved cookie
2020-12-02 09:02:01,739 - PixivUtil20201130 - INFO - Logging in, return url: https://www.pixiv.net/en/
2020-12-02 09:02:01,740 - PixivUtil20201130 - INFO - Login successful.
2020-12-02 09:02:01,740 - PixivUtil20201130 - INFO - Logged in using cookie
2020-12-02 09:02:01,741 - PixivUtil20201130 - INFO - My User Id: XXXXXXXXXXX
2020-12-02 09:02:01,741 - PixivUtil20201130 - INFO - Premium User: False.
2020-12-02 09:02:01,742 - PixivUtil20201130 - INFO - Locale = /en
2020-12-02 09:02:04,724 - PixivUtil20201130 - INFO - Download FANBOX by Artist or Creator ID mode (f2).
2020-12-02 09:02:07,797 - PixivUtil20201130 - INFO - Member IDs: ['iuui']
2020-12-02 09:02:07,809 - PixivUtil20201130 - INFO - Trying to log in FANBOX with saved cookie
2020-12-02 09:02:09,300 - PixivUtil20201130 - INFO - Logging in with cookit to Fanbox, return url: https://www.fanbox.cc
2020-12-02 09:02:09,301 - PixivUtil20201130 - INFO - FANBOX Login successful.
2020-12-02 09:02:09,302 - PixivUtil20201130 - INFO - Getting artist information from https://api.fanbox.cc/creator.get?creatorId=iuui
2020-12-02 09:02:11,777 - PixivUtil20201130 - INFO - Member Url: https://www.pixiv.net/ajax/user/7484613/profile/all
2020-12-02 09:02:12,131 - PixivUtil20201130 - DEBUG - b'{"error":false,"message":"","body":{"illusts":{"85925004":null,"85910537":null,"85864893":null,"85794638":null,"85749853":null,"85605070":null,"85581159":null,"85477616":null,"85429733":null,"85352879":null,"85266369":null,"85140471":null,"85033150":null,"84907334":null,"84726265":null,"84628363":null,"84567626":null,"84535302":null,"84506422":null,"84475642":null,"84398815":null,"84329502":null,"84277976":null,"84256170":null,"84220464":null,"84178097":null,"84169644":null,"84117483":null,"84057350":null,"83983859":null,"83983840":null,"83949013":null,"83941173":null,"83845618":null,"83837336":null,"83799945":null,"83761284":null,"83756977":null,"83670870":null,"83667835":null,"83618866":null,"83599215":null,"83477855":null,"83472937":null,"83457279":null,"83415664":null,"83326865":null,"83298388":null,"83272822":null,"83200391":null,"83147461":null,"83138758":null,"83047596":null,"83047553":null,"83047513":null,"83021991":null,"83021963":null,"83021936":null,"82981716":null,"82798638":null,"82729644":null,"82699956":null,"82664259":null,"82438336":null,"82326471":null,"82262877":null,"82158097":null,"82031273":null,"81905263":null,"81846820":null,"81708458":null,"81654308":null,"81442738":null,"81084368":null,"80874049":null,"80799933":null,"80666028":null,"80548072":null,"80441454":null,"80414038":null,"80299068":null,"80212546":null,"80112681":null,"79942495":null,"79859263":null,"79847844":null,"79568357":null,"79568204":null,"79327719":null,"79174908":null,"79014824":null,"78677419":null,"78656920":null,"78596880":null,"78595884":null,"78576873":null,"78574416":null,"78457557":null,"78406733":null,"78220291":null},"manga":[],"novels":[],"mangaSeries":[],"novelSeries":[],"pickup":[{"type":"fanbox","deletable":false,"draggable":true,"userName":"\\u30a4\\u30a6\\u30a6\\u30a446278405 \\u65b0\\u53f7","userImageUrl":"https:\\/\\/i.pximg.net\\/user-profile\\/img\\/2020\\/05\\/04\\/19\\/21\\/14\\/18476843_74e4e704b56a01e5d5656e6a1da795a6_170.jpg","contentUrl":"https:\\/\\/www.pixiv.net\\/fanbox\\/creator\\/7484613?utm_campaign=www_profile\\u0026utm_medium=site_flow\\u0026utm_source=pixiv","description":"Welcome\\ud83d\\udc95","imageUrl":"https:\\/\\/pixiv.pximg.net\\/c\\/520x280_90_a2_g5\\/fanbox\\/public\\/images\\/creator\\/7484613\\/cover\\/qwFEmYfTlnFEq8L4JkKQjx9A.jpeg","imageUrlMobile":"https:\\/\\/pixiv.pximg.net\\/c\\/520x280_90_a2_g5\\/fanbox\\/public\\/images\\/creator\\/7484613\\/cover\\/qwFEmYfTlnFEq8L4JkKQjx9A.jpeg","hasAdultContent":true}],"bookmarkCount":{"public":{"illust":1,"novel":1},"private":{"illust":0,"novel":0}},"externalSiteWorksStatus":{"booth":false,"sketch":false,"vroidHub":false},"request":{"showRequestTab":false,"postWorks":{"artworks":[],"novels":[]}}}}'
2020-12-02 09:02:12,197 - PixivUtil20201130 - DEBUG - using webrpc: https://www.pixiv.net/rpc/get_work.php?id=85925004
2020-12-02 09:02:14,650 - PixivUtil20201130 - ERROR - Error data: 

 b'{"error":true,"message":"This user account has been suspended.","body":[]}'
2020-12-02 09:02:14,652 - PixivUtil20201130 - ERROR - Error gettting FANBOX artist by id: iuui ==> This user account has been suspended.
2020-12-02 09:02:14,652 - PixivUtil20201130 - ERROR - Traceback (most recent call last):
  File "PixivBrowserFactory.pyc", line 658, in getMemberInfoWhitecube
  File "PixivBrowserFactory.pyc", line 205, in open_with_retry
  File "mechanize\_mechanize.pyc", line 257, in open
  File "mechanize\_mechanize.pyc", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PixivFanboxHandler.pyc", line 19, in process_fanbox_artist_by_id
  File "PixivBrowserFactory.pyc", line 906, in fanboxGetArtistById
  File "PixivBrowserFactory.pyc", line 732, in getMemberPage
  File "PixivBrowserFactory.pyc", line 684, in getMemberInfoWhitecube
PixivException.PixivException: 1002 This user account has been suspended., hasDumpPage=Y, pageData=b'{"error":true,"message":"This user account has been suspended.","body":[]}'
```

### Versions

20201130

**Comment by bluerthanever** [comment]
hmm. i don't think this is too hard to fix, simply stopping retrieving artist information from pixiv.net would do.
but this also means some of the filename format syntax/placeholders don't share between pixiv and fanbox anymore. which is also not a big problem i guess?

but sorry that i don't quite get what you mentioned in `Expected behavior`.

**Comment by NHOrus** [comment]
If needed information is in db.sqlite, get it from there, like %artist% being name. Only other information what's needed is %member_token%, save it in database, too.

**Comment by byjtje** [comment]
Unrelated to your issue, but that artist isn't suspended from Pixiv, you can still access his stuff. I assume this is related to https://github.com/Nandaka/PixivUtil2/issues/869 ?

**Comment by bluerthanever** [comment]
> If needed information is in db.sqlite, get it from there, like %artist% being name. Only other information what's needed is %member_token%, save it in database, too.

well, i think you have to also think about situations where a user download from a fanbox artist for the first time but their pixiv is already suspended, or that a user has never downloaded from pixiv thus no information is stored in db. (currently fanbox functions don't store artist information in db). also some values might change, 

but also, i don't think this user is suspended either, at least not now. just for some reason her contents are no longer accessible, and pixivutil can't get them so it's set to throw a error like that. i just tried to use f2 to download from `iuui` and it went on fine.... do you mind checking again?

@Nandaka i though this was related to #827 , and  i changed it back to the old method, and it seems to be working again now. i'll keep monitoring, i guess?

**Comment by NHOrus** [comment]
> Unrelated to your issue, but that artist isn't suspended from Pixiv, you can still access his stuff. I assume this is related to #869 ?

He was unsuspended. Hence everything going fine..

Waiting for next suspension, then.

**Comment by Nandaka** [comment]
@bluerthanever need to find for other suspended artist to test if the webrpc can return information when the artist being suspended or not...

**Comment by bluerthanever** [comment]
hmm. i found a user whose account is suspended. "該当ユーザーのアカウントは停止されています。" was shown on his page and i guess that means suspended. but his fanbox page is fine.
and the old api doesn't seem able to retrieve data from  pixiv either.

**Comment by bluerthanever** [comment]
well. looks like the old api is back online, we could probably change it back?

as for **THIS** issue, which occurs when the creator's account is suspended on pixiv.net side, should we:
1. simply not retrieving info from pixiv?
2. put the retrieving part in a try... except... so we can skip this part when it throws an error
3. store and use creator information in db
4. store creator information in db, and when retrieving fails, use the data in db

for option 1 and 2, the problem could be that there would be some invalid strings, like empty strings or 'self's in generated paths/filenames, and for option 3 it is just weird since none of the functions so far seem to be working in this way. option 4 is kinda like a mix of 3 and 4, also more complicated...
what do you think?

**Comment by Nandaka** [comment]
Well, it is used mainly to get the artist name and token.
https://github.com/Nandaka/PixivUtil2/blob/master/PixivBrowserFactory.py#L916-L917

We can add 1 more column just to store the artist token, as the artist name already in `pixiv_master_member`.
If there is no entry or null value, then throw an error. There is still a risk of stale data.

**Comment by bluerthanever** [comment]
that was fast....
i think i will do my part tomorrow. XD

**Comment by bluerthanever** [comment]
Shoot. I totally forgot. Now the creator's pixiv account is not suspended anymore.

**Comment by bluerthanever** [comment]
I kinda found a suspended user on pixiv and used Fiddle breakpoints to test, and changed the codes to pull a new request.
