### ISSUE TITLE
KeyError('isAdContainer') when downloading by tag

### ISSUE THREAD

**Issue by polujm9** [Nandaka/PixivUtil2#878]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Always get KeyError('isAdContainer') when trying to download by tag.
I had tried some tags and all of them have this problem.

### Steps to Reproduce

1. 3(download by tags)
2. use Partial Match
3. search type a-all
4. get the Error

**Expected behavior:** [What you expected to happen]

Start download

**Actual behavior:** [What actually happened]

Got an Error and stopped.

### Versions

v20201130

logs:

```
2020-12-07 11:20:37,299 - PixivUtil20201130 - INFO - Premium User: False.
2020-12-07 11:20:37,299 - PixivUtil20201130 - INFO - Locale = 
2020-12-07 11:20:38,305 - PixivUtil20201130 - INFO - Tags mode (3).
2020-12-07 11:20:51,635 - PixivUtil20201130 - INFO - Searching for: (Hypnosis) Hypnosis
2020-12-07 11:20:51,638 - PixivUtil20201130 - INFO - Looping... for https://www.pixiv.net/ajax/search/artworks/Hypnosis?word=Hypnosis&s_mode=s_tag&type=all&order=date_d
2020-12-07 11:20:52,005 - PixivUtil20201130 - DEBUG - Sanitized Filename: Dump for SearchTags Hypnosis.html
2020-12-07 11:20:52,067 - PixivUtil20201130 - ERROR - Error at process_tags() at page 1: (<class 'KeyError'>, KeyError('isAdContainer'), <traceback object at 0x03CA4248>)
2020-12-07 11:20:52,068 - PixivUtil20201130 - ERROR - Traceback (most recent call last):
  File "PixivTagsHandler.pyc", line 70, in process_tags
  File "PixivBrowserFactory.pyc", line 796, in getSearchTagPage
  File "PixivTags.pyc", line 56, in parseTags
KeyError: 'isAdContainer'

2020-12-07 11:20:52,070 - PixivUtil20201130 - ERROR - Unknown Error: (<class 'KeyError'>, KeyError('isAdContainer'), <traceback object at 0x03CA42E8>)
2020-12-07 11:20:52,071 - PixivUtil20201130 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 1325, in main
  File "PixivUtil2.py", line 1026, in main_loop
  File "PixivUtil2.py", line 374, in menu_download_by_tags
  File "PixivTagsHandler.pyc", line 70, in process_tags
  File "PixivBrowserFactory.pyc", line 796, in getSearchTagPage
  File "PixivTags.pyc", line 56, in parseTags
KeyError: 'isAdContainer'
```

**Comment by ConsciousMachines** [comment]
I had this issue a few days ago, and it went away 6 hours later. Now I'm having it again.

**Comment by RedTestament** [comment]
Confirmed, I had the same error trying to download by tags

**Comment by Tarried** [comment]
Same; I'm using batch job option 3, which I believe is the download by tags equivalent.

**Comment by Nandaka** [comment]
can you upload the json file from `https://www.pixiv.net/ajax/search/artworks/Hypnosis?word=Hypnosis&s_mode=s_tag&type=all&order=date_d` ?

**Comment by polujm9** [comment]
I can't drag json file here directly so I package it as zip file.
[Hypnosis.zip](https://github.com/Nandaka/PixivUtil2/files/5652829/Hypnosis.zip)

**Comment by Nandaka** [comment]
try https://github.com/Nandaka/PixivUtil2/releases/tag/v20201207-beta1

**Comment by polujm9** [comment]
Works fine at v20201207-beta1
Thank you.
