### ISSUE TITLE
Possible Ugoira change

### ISSUE THREAD

**Issue by NHOrus** [Nandaka/PixivUtil2#90]
Examples:

```
2015-08-12 05:12:58,838 - PixivUtil20150715 - INFO - Member Url: http://www.pixiv.net/member_illust.php?id=2735977&p=2
2015-08-12 05:13:06,970 - PixivUtil20150715 - DEBUG - Sanitized Filename: E:\conf\pixiv\2735977\44335582 - うごテス.zip
2015-08-12 05:13:06,970 - PixivUtil20150715 - INFO - Using Referer: http://www.pixiv.net/member_illust.php?mode=medium&illust_id=44335582
2015-08-12 05:14:07,308 - PixivUtil20150715 - ERROR - [download_image()] URL Error: <urlopen error timed out> at http://i3.pixiv.net/img-zip-ugoira/img/2014/06/27/02/47/10/44335582_ugoira1920x1080.zip
2015-08-12 05:14:07,308 - PixivUtil20150715 - ERROR - Error at download_image(): (<class 'urllib2.URLError'>, URLError(timeout('timed out',),), <traceback object at 0x02EA8D50>) at http://i3.pixiv.net/img-zip-ugoira/img/2014/06/27/02/47/10/44335582_ugoira1920x1080.zip (9002)
```
and

```
2015-08-12 08:27:57,779 - PixivUtil20150715 - DEBUG - Sanitized Filename: E:\conf\pixiv\5575104\44474657 - 【うごイラ】江ちゃんの衛士強化装備を脱着させてみた.zip
2015-08-12 08:27:57,779 - PixivUtil20150715 - INFO - Using Referer: http://www.pixiv.net/member_illust.php?mode=medium&illust_id=44474657
2015-08-12 08:28:58,454 - PixivUtil20150715 - ERROR - [download_image()] URL Error: <urlopen error timed out> at http://i2.pixiv.net/img-zip-ugoira/img/2014/07/03/19/38/54/44474657_ugoira1920x1080.zip
2015-08-12 08:28:58,454 - PixivUtil20150715 - ERROR - Error at download_image(): (<class 'urllib2.URLError'>, URLError(timeout('timed out',),), <traceback object at 0x02EC1440>) at http://i2.pixiv.net/img-zip-ugoira/img/2014/07/03/19/38/54/44474657_ugoira1920x1080.zip (9002)
2015-08-12 08:29:02,510 - PixivUtil20150715 - INFO - Using Referer: http://www.pixiv.net/member_illust.php?mode=medium&illust_id=44474657
2015-08-12 08:30:02,851 - PixivUtil20150715 - ERROR - [download_image()] URL Error: <urlopen error timed out> at http://i2.pixiv.net/img-zip-ugoira/img/2014/07/03/19/38/54/44474657_ugoira1920x1080.zip
2015-08-12 08:30:02,851 - PixivUtil20150715 - ERROR - Error at download_image(): (<class 'urllib2.URLError'>, URLError(timeout('timed out',),), <traceback object at 0x02EC19E0>) at http://i2.pixiv.net/img-zip-ugoira/img/2014/07/03/19/38/54/44474657_ugoira1920x1080.zip (9002)
2015-08-12 08:30:06,907 - PixivUtil20150715 - INFO - Using Referer: http://www.pixiv.net/member_illust.php?mode=medium&illust_id=44474657
2015-08-12 08:31:07,549 - PixivUtil20150715 - ERROR - [download_image()] URL Error: <urlopen error timed out> at http://i2.pixiv.net/img-zip-ugoira/img/2014/07/03/19/38/54/44474657_ugoira1920x1080.zip
2015-08-12 08:31:07,549 - PixivUtil20150715 - ERROR - Error at download_image(): (<class 'urllib2.URLError'>, URLError(timeout('timed out',),), <traceback object at 0x02EC1C38>) at http://i2.pixiv.net/img-zip-ugoira/img/2014/07/03/19/38/54/44474657_ugoira1920x1080.zip (9002)
2015-08-12 08:31:11,605 - PixivUtil20150715 - INFO - Using Referer: http://www.pixiv.net/member_illust.php?mode=medium&illust_id=44474657
2015-08-12 08:32:11,943 - PixivUtil20150715 - ERROR - [download_image()] URL Error: <urlopen error timed out> at http://i2.pixiv.net/img-zip-ugoira/img/2014/07/03/19/38/54/44474657_ugoira1920x1080.zip
2015-08-12 08:32:11,943 - PixivUtil20150715 - ERROR - Error at download_image(): (<class 'urllib2.URLError'>, URLError(timeout('timed out',),), <traceback object at 0x02EC1DF0>) at http://i2.pixiv.net/img-zip-ugoira/img/2014/07/03/19/38/54/44474657_ugoira1920x1080.zip (9002)
2015-08-12 08:32:11,943 - PixivUtil20150715 - ERROR - Giving up url: http://i2.pixiv.net/img-zip-ugoira/img/2014/07/03/19/38/54/44474657_ugoira1920x1080.zip
2015-08-12 08:32:11,943 - PixivUtil20150715 - ERROR - Error when download_image(): http://i2.pixiv.net/img-zip-ugoira/img/2014/07/03/19/38/54/44474657_ugoira1920x1080.zip
Traceback (most recent call last):
  File "PixivUtil2.py", line 593, in process_image
  File "PixivUtil2.py", line 70, in download_image
  File "mechanize\_mechanize.pyc", line 199, in open_novisit
  File "mechanize\_mechanize.pyc", line 230, in _mech_open
  File "mechanize\_opener.pyc", line 193, in open
  File "mechanize\_urllib2_fork.pyc", line 344, in _open
  File "mechanize\_urllib2_fork.pyc", line 332, in _call_chain
  File "mechanize\_urllib2_fork.pyc", line 1142, in http_open
  File "mechanize\_urllib2_fork.pyc", line 1118, in do_open
URLError: <urlopen error timed out>
```

Or is it because of possible pixiv-side throttle down?

**Comment by NHOrus** [comment]
Well, I tried to report this too soon. It's cause of pixiv-side timeout, there was one downloaded animation after aforementioned two. Still...

**Comment by NHOrus** [comment]
False alarm, everything appears to be working.
