### ISSUE TITLE
Issue downloading from Fanbox (HTTP Error 502: Bad Gateway)

### ISSUE THREAD

**Issue by prozifro** [Nandaka/PixivUtil2#905]
I wanted to download images and gifs from fanbox, but I keep getting this error:
ERROR - Traceback (most recent call last):
  File "PixivDownloadHandler.pyc", line 78, in download_image
  File "PixivDownloadHandler.pyc", line 294, in get_remote_filesize
  File "mechanize\_mechanize.pyc", line 241, in open_novisit
  File "mechanize\_mechanize.pyc", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 502: Bad Gateway

I'm using the latest version PixivUtil20210128

**Comment by bluerthanever** [comment]
hey. 
1. does this only happen with fanbox?
2. do you have any problem viewing posts with browsers? do you need to use a proxy?
