### ISSUE TITLE
Fanbox OAuth issue: The grant type is unauthorized for this client_id

### ISSUE THREAD

**Issue by fengberd** [Nandaka/PixivUtil2#907]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

The latest release (20210128) tries to retrieve fanbox member info via OAuth, which fails with error and unable to download.
In comparison, an earlier version seems to use another approach and works fine.

### Steps to Reproduce

1. Run the app, login as usual
2. Command `f1`, max page `1` for fanbox downloading

**Expected behavior:**
Checkout to `v20201130` and it works perfectly
```
Getting artist information from https://api.fanbox.cc/creator.get?userId=XXXXXXX
Member Url: https://www.pixiv.net/ajax/user/XXXXXXX/profile/all
Processing FanboxArtist(XXXXXXX, YYYYYYY, ZZZZZZZ), page 1
Getting posts from https://api.fanbox.cc/post.listCreator?userId=XXXXXXX&limit=10

* Starts download normally *
```

**Actual behavior:**
When I checkout to `20210128`, error occured:
```
Using OAuth to retrieve member info for: XXXXXXX
The grant type is unauthorized for this client_id
Error getting FANBOX artist by id: XXXXXXX ==> Failed to login using OAuth
```

### Versions

Tested the following versions:
 - 20210128
 - v20201130

### Another tiny issue (Unrelated to this one, but don't worth a new issue)
Old versions of cloudscraper may fail to verify the ssl certificate when doing fanbox OAuth, disabling ssl verify will throw another error. Seems to be complicated, so I didn't dig too much, just update cloudscraper.
IMO the `requirements.txt` should specify the version of cloudscraper (1.2.56 worked for me) to prevent this

**Comment by bluerthanever** [comment]
urr.. really sorry about that. i think i changed that back to the way before what was used in `v20201130`
but i tested on my side and it works fine....

did you leave the `username` and `password` options empty or incorrect in configuration? the method for getting fanbox artist information in this version needs those two options set correctly.

**Comment by fengberd** [comment]
> urr.. really sorry about that. i think i changed that back to the way before what was used in `v20201130`
> but i tested on my side and it works fine....
> 
> did you leave the `username` and `password` options empty or incorrect in configuration? the method for getting fanbox artist information in this version needs those two options set correctly.

Just checked both options and I'm sure they're all set correctly (`username`, `password`, `cookie`). The `cookiefanbox` was set automatically and `refresh_token` was empty for some unknown reason, I remember PixivUtil will set that automatically too (back to sometime earlier), but it didn't set for me this time.

**Comment by bluerthanever** [comment]
hmm... i tried again here and it had nothing wrong getting artist information.
could you provide a log file, please?

**Comment by fengberd** [comment]
Log Config:
```ini
[Debug]
loglevel = DEBUG
enabledump = True
skipdumpfilter = 
dumpmediumpage = False
dumptagsearchpage = False
debughttp = True
```

Output:
```
┌──────────────────────────────────────────────────────────┐
│ PixivDownloader2 version 20210108-beta4                  │
│ https://github.com/Nandaka/PixivUtil2/releases           │
│ Donate at https://bit.ly/PixivUtilDonation               │
└──────────────────────────────────────────────────────────┘
Reading C:\PixivUtil2\config.ini ...
Configuration loaded.
send: b'GET /Nandaka/PixivUtil2/master/PixivConstant.py HTTP/1.1\r\nAccept-Encoding: identity\r\nUser-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36\r\nAccept-Charset: utf-8\r\nHost: raw.githubusercontent.com\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Connection: close
header: Content-Length: 1934
header: Content-Type: text/plain; charset=utf-8
header: Cache-Control: max-age=300
header: Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
header: ETag: "LOL"
header: Strict-Transport-Security: max-age=31536000
header: X-Content-Type-Options: nosniff
header: X-Frame-Options: deny
header: X-XSS-Protection: 1; mode=block
header: X-GitHub-Request-Id: LOL
header: Accept-Ranges: bytes
header: Date: Wed, 10 Feb 2021 14:02:15 GMT
header: Via: 1.1 varnish
header: X-Served-By: cache-itm18820-ITM
header: X-Cache: HIT
header: X-Cache-Hits: 1
header: X-Timer: S1612965736.611492,VS0,VE1
header: Vary: Authorization,Accept-Encoding, Accept-Encoding
header: Access-Control-Allow-Origin: *
header: X-Fastly-Request-ID: LOL
header: Expires: Wed, 10 Feb 2021 14:07:15 GMT
header: Source-Age: 207
Using default DB Path: C:\PixivUtil2\db.sqlite
Creating database... done.
Only process members where the last update is >= 7 days ago
Using Username: fengberd
Trying to log in with saved cookie
send: b'GET / HTTP/1.1\r\nAccept-Encoding: identity\r\nUser-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36\r\nAccept-Charset: utf-8\r\nHost: www.pixiv.net\r\nCookie: PHPSESSID=HereIsMyCookie\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 302 Found\r\n'
header: Date: Wed, 10 Feb 2021 14:02:17 GMT
header: Content-Type: text/html; charset=UTF-8
header: Content-Length: 0
header: Connection: close
header: Set-Cookie: __cfduid=Nope.; expires=Fri, 12-Mar-21 14:02:17 GMT; path=/; domain=.pixiv.net; HttpOnly; SameSite=Lax; Secure
header: Vary: X-UserId
header: X-Host-Time: 132
header: X-XSS-Protection: 1; mode=block
header: Content-Security-Policy-Report-Only: object-src 'none'; base-uri 'self' 'report-sample'; block-all-mixed-content; frame-ancestors 'self';
header: Expires: Thu, 19 Nov 1981 08:52:00 GMT
header: Cache-Control: no-store, no-cache, must-revalidate
header: Pragma: no-cache
header: X-UserId: HereIsMyUserId
header: Location: /en/
header: Strict-Transport-Security: max-age=31536000
header: X-Frame-Options: SAMEORIGIN
header: CF-Cache-Status: DYNAMIC
header: cf-request-id: LOL
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Set-Cookie: first_visit_datetime_pc=2021-02-10+23%3A02%3A17; expires=Fri, 10-Feb-2023 14:02:17 GMT; Max-Age=63072000; path=/; secure
header: Set-Cookie: LOL; path=/; expires=Wed, 10-Feb-21 14:32:17 GMT; domain=.pixiv.net; HttpOnly; Secure; SameSite=None
header: Server: cloudflare
header: CF-RAY: LOL
send: b'GET /en/ HTTP/1.1\r\nAccept-Encoding: identity\r\nUser-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36\r\nAccept-Charset: utf-8\r\nHost: www.pixiv.net\r\nCookie: PHPSESSID=HereIsMyCookie; __cfduid=Nope.; LOL\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Wed, 10 Feb 2021 14:02:19 GMT
header: Content-Type: text/html; charset=UTF-8
header: Transfer-Encoding: chunked
header: Connection: close
header: Vary: X-UserId,Accept-Encoding
header: X-Host-Time: 144
header: X-XSS-Protection: 1; mode=block
header: Content-Security-Policy-Report-Only: object-src 'none'; base-uri 'self' 'report-sample'; block-all-mixed-content; frame-ancestors 'self';
header: Expires: Thu, 19 Nov 1981 08:52:00 GMT
header: Cache-Control: no-store, no-cache, must-revalidate
header: Pragma: no-cache
header: X-UserId: HereIsMyUserId
header: Set-Cookie: p_ab_id=0; expires=Mon, 09-Feb-2026 14:02:19 GMT; Max-Age=157680000; path=/; domain=.pixiv.net; secure
header: Set-Cookie: p_ab_id_2=7; expires=Mon, 09-Feb-2026 14:02:19 GMT; Max-Age=157680000; path=/; domain=.pixiv.net; secure
header: Set-Cookie: p_ab_d_id=Yup; expires=Mon, 09-Feb-2026 14:02:19 GMT; Max-Age=157680000; path=/; domain=.pixiv.net; secure
header: Strict-Transport-Security: max-age=31536000
header: X-Frame-Options: SAMEORIGIN
header: CF-Cache-Status: DYNAMIC
header: cf-request-id: LOL
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Server: cloudflare
header: CF-RAY: LOL-TPE
Login successful.
My User Id: HereIsMyUserId.
Premium User: True.
┌──────────────────────────────────────────────────────────┐
│ PixivDownloader2 version 20210108-beta4                  │
│ https://github.com/Nandaka/PixivUtil2/releases           │
│ Donate at https://bit.ly/PixivUtilDonation               │
└──────────────────────────────────────────────────────────┘
── Pixiv ───────────────────────────────────────────────────
 1.  Download by member_id
 2.  Download by image_id
 3.  Download by tags
 4.  Download from list
 5.  Download from bookmarked artists (/bookmark.php?type=user)
 6.  Download from bookmarked images (/bookmark.php)
 7.  Download from tags list
 8.  Download new illust from bookmarked members (/bookmark_new_illust.php)
 9.  Download by Title/Caption
 10. Download by Tag and Member Id
 11. Download Member Bookmark (/bookmark.php?id=)
 12. Download by Group Id
 13. Download by Manga Series Id
── FANBOX ──────────────────────────────────────────────────
 f1. Download from supporting list (FANBOX)
 f2. Download by artist/creator id (FANBOX)
 f3. Download by post id (FANBOX)
 f4. Download from following list (FANBOX)
 f5. Download from custom list (FANBOX)
── Sketch ──────────────────────────────────────────────────
 s1. Download by creator id (Sketch)
 s2. Download by post id (Sketch)
── Batch Download ──────────────────────────────────────────
 b. Batch Download from batch_job.json (experimental)
── Others ──────────────────────────────────────────────────
 d. Manage database
 e. Export online bookmark
 m. Export online user bookmark
 i. Import list file
 r. Reload config.ini
 p. Print config.ini
 x. Exit
Input: f2
Artist/Creator IDs = ninoseyasunori
End page = 1
Member IDs: ['ninoseyasunori']
Reading C:\PixivUtil2\config.ini ...
Configuration loaded.
Trying to log in FANBOX with saved cookie
send: b'GET / HTTP/1.1\r\nAccept-Encoding: identity\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8\r\nOrigin: https://www.fanbox.cc\r\nUser-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36\r\nAccept-Charset: utf-8\r\nHost: www.fanbox.cc\r\nCookie: FANBOXSESSID=YAY\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server: nginx
header: Date: Wed, 10 Feb 2021 14:02:25 GMT
header: Content-Type: text/html; charset=UTF-8
header: Content-Length: 3616
header: Connection: close
header: X-Host-Time: 032
header: Content-Security-Policy: frame-ancestors 'self' https://*.fanbox.cc
header: Expires: Thu, 19 Nov 1981 08:52:00 GMT
header: Cache-Control: no-store, no-cache, must-revalidate
header: Pragma: no-cache
header: X-UserId: HereIsMyUserId
header: Vary: X-UserId,Accept-Encoding
header: Set-Cookie: p_ab_id=1; expires=Mon, 09-Feb-2026 14:02:25 GMT; Max-Age=157680000; path=/; domain=.fanbox.cc; secure
header: Set-Cookie: p_ab_id_2=3; expires=Mon, 09-Feb-2026 14:02:25 GMT; Max-Age=157680000; path=/; domain=.fanbox.cc; secure
header: Set-Cookie: p_ab_d_id=WhatIsThis; expires=Mon, 09-Feb-2026 14:02:25 GMT; Max-Age=157680000; path=/; domain=.fanbox.cc; secure
header: X-Frame-Options: SAMEORIGIN
FANBOX Login successful.
Getting artist information from https://api.fanbox.cc/creator.get?creatorId=ninoseyasunori
send: b'GET /creator.get?creatorId=ninoseyasunori HTTP/1.1\r\nAccept-Encoding: identity\r\nAccept: application/json, text/plain, */*\r\nReferer: https://www.fanbox.cc/@ninoseyasunori\r\nOrigin: https://www.fanbox.cc\r\nUser-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36\r\nAccept-Charset: utf-8\r\nHost: api.fanbox.cc\r\nCookie: FANBOXSESSID=YAY; p_ab_id=1; p_ab_id_2=3; p_ab_d_id=WhatIsThis\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server: nginx
header: Date: Wed, 10 Feb 2021 14:02:26 GMT
header: Content-Type: application/json; charset=utf-8
header: Transfer-Encoding: chunked
header: Connection: close
header: X-Host-Time: 140
header: Content-Security-Policy: frame-ancestors 'self' https://*.fanbox.cc
header: Vary: X-UserId,Accept-Encoding
header: Access-Control-Allow-Origin: https://www.fanbox.cc
header: Access-Control-Allow-Headers: Content-Type, X-CSRF-Token
header: Access-Control-Allow-Credentials: true
header: Expires: Thu, 19 Nov 1981 08:52:00 GMT
header: Cache-Control: no-store, no-cache, must-revalidate
header: Pragma: no-cache
header: X-UserId: HereIsMyUserId
header: X-Content-Type-Options: nosniff
header: X-Frame-Options: SAMEORIGIN
Using OAuth to retrieve member info for: 14684068
Invalid grant_type parameter or parameter missing
Error getting FANBOX artist by id: ninoseyasunori ==> Failed to login using OAuth
```

**Comment by bluerthanever** [comment]
hmm... do you have the log file under program folder to provide? the name should be `pixivutil.log`

**Comment by fengberd** [comment]
Oops, sorry, I never know there's such a file...
```
2021-02-10 22:02:14,179 - PixivUtil20210108-beta4 - INFO - ###############################################################
2021-02-10 22:02:14,179 - PixivUtil20210108-beta4 - INFO - Starting with argument: [C:\PixivUtil2\PixivUtil2.py].
2021-02-10 22:02:14,179 - PixivUtil20210108-beta4 - INFO - Setting log level to: DEBUG
2021-02-10 22:02:14,179 - PixivUtil20210108-beta4 - INFO - No default cookie jar available, creating... 
2021-02-10 22:02:14,179 - PixivUtil20210108-beta4 - INFO - Using SOCKS5 Proxy= 10.0.1.1:1082
2021-02-10 22:02:14,179 - PixivUtil20210108-beta4 - INFO - Debug HTTP enabled.
2021-02-10 22:02:15,710 - PixivUtil20210108-beta4 - INFO - Using default DB Path: C:\PixivUtil2\db.sqlite
2021-02-10 22:02:15,725 - PixivUtil20210108-beta4 - INFO - Only process members where the last update is >= 7 days ago
2021-02-10 22:02:15,725 - PixivUtil20210108-beta4 - INFO - Using Username: fengberd
2021-02-10 22:02:15,725 - PixivUtil20210108-beta4 - INFO - Trying to log in with saved cookie
2021-02-10 22:02:19,819 - PixivUtil20210108-beta4 - INFO - Logging in, return url: https://www.pixiv.net/en/
2021-02-10 22:02:19,819 - PixivUtil20210108-beta4 - INFO - Login successful.
2021-02-10 22:02:19,819 - PixivUtil20210108-beta4 - INFO - Logged in using cookie
2021-02-10 22:02:19,819 - PixivUtil20210108-beta4 - INFO - My User Id: 17798296.
2021-02-10 22:02:19,819 - PixivUtil20210108-beta4 - INFO - Premium User: True.
2021-02-10 22:02:19,819 - PixivUtil20210108-beta4 - INFO - Locale = /en
2021-02-10 22:02:23,054 - PixivUtil20210108-beta4 - INFO - Download FANBOX by Artist or Creator ID mode (f2).
2021-02-10 22:02:24,804 - PixivUtil20210108-beta4 - INFO - Member IDs: ['ninoseyasunori']
2021-02-10 22:02:24,804 - PixivUtil20210108-beta4 - INFO - Trying to log in FANBOX with saved cookie
2021-02-10 22:02:25,303 - PixivUtil20210108-beta4 - INFO - Logging in with cookit to Fanbox, return url: https://www.fanbox.cc
2021-02-10 22:02:25,319 - PixivUtil20210108-beta4 - INFO - FANBOX Login successful.
2021-02-10 22:02:25,319 - PixivUtil20210108-beta4 - INFO - Getting artist information from https://api.fanbox.cc/creator.get?creatorId=ninoseyasunori
2021-02-10 22:02:26,616 - PixivUtil20210108-beta4 - INFO - Using OAuth to retrieve member info for: 14684068
2021-02-10 22:02:26,616 - PixivUtil20210108-beta4 - DEBUG - Getting member information: 14684068
2021-02-10 22:02:26,616 - PixivUtil20210108-beta4 - INFO - Login to OAuth using username and password.
2021-02-10 22:02:27,772 - PixivUtil20210108-beta4 - DEBUG - 400: {"has_error":true,"errors":{"system":{"message":"Invalid grant_type parameter or parameter missing","code":1508}},"error":"invalid_grant"}
2021-02-10 22:02:27,772 - PixivUtil20210108-beta4 - ERROR - Invalid grant_type parameter or parameter missing
2021-02-10 22:02:27,772 - PixivUtil20210108-beta4 - ERROR - NoneType: None

2021-02-10 22:02:27,788 - PixivUtil20210108-beta4 - ERROR - Error getting FANBOX artist by id: ninoseyasunori ==> Failed to login using OAuth
2021-02-10 22:02:27,788 - PixivUtil20210108-beta4 - ERROR - Traceback (most recent call last):
  File "C:\PixivUtil2\PixivFanboxHandler.py", line 19, in process_fanbox_artist_by_id
    artist = br.fanboxGetArtistById(artist_id)
  File "C:\PixivUtil2\PixivBrowserFactory.py", line 914, in fanboxGetArtistById
    self.getMemberInfoWhitecube(artist.artistId, pixivArtist)
  File "C:\PixivUtil2\PixivBrowserFactory.py", line 642, in getMemberInfoWhitecube
    login_response = self._oauth_manager.login()
  File "C:\PixivUtil2\PixivOAuth.py", line 238, in login
    raise PixivException("Failed to login using OAuth", PixivException.OAUTH_LOGIN_ISSUE)
PixivException.PixivException: 0 Failed to login using OAuth, hasDumpPage=N, pageData=None
```

**Comment by fengberd** [comment]
Hmm, I remember one thing: Pixiv always requires reCaptcha when I tries to login with username/password, so I have to set the cookie manually.
Can that be related to IP address or something? I'm using default UA so that shouldn't be the problem.

**Comment by bluerthanever** [comment]
hmm. i just realized that i had my `refresh_token` filled, and i tried again with it erased.
and i got the same error. i think they might have changed the `oauth` api.... let me see what i can do.

**Comment by bluerthanever** [comment]
looks like pixiv did something to the api... seems kinda complicated, and could not found a solution yet.
 maybe it's better to change the method back to B....

**Comment by bluerthanever** [comment]
https://github.com/upbit/pixivpy/issues/158

**Comment by fengberd** [comment]
Okay, I digged in a bit and found the AUTHOR.fanbox.cc uses `grant_type=code` to login. Since we are logging in via cookie instead of normal username/password procedure, go back to method B can be a good choice...

**Comment by Erementsuna** [comment]
I am having the same issue. While trying to fix it I noticed I was unsure of what is meant my method B.

I am using 20219128

I receive the error with the username, pass, cookie,  & cookieFB filled with my info and refresh token blank.

Could someone confirm since the last post if Method B fixed the problem?

**Comment by bluerthanever** [comment]
yes i have confirmed that method B works. you can get the fanbox artist information without errors. i will pull a request to change it back.

**Comment by fengberd** [comment]
Fixed in https://github.com/Nandaka/PixivUtil2/commit/dc4f9e8ba75f2eb4d3ce265ba600ebeaff2b40bd, closing this issue.
Thank you @bluerthanever.

**Comment by bluerthanever** [comment]
nah. that's the least i can do.
=)
