### ISSUE TITLE
Docker crashes without -t

### ISSUE THREAD

**Issue by Lachee** [Nandaka/PixivUtil2#912]
### Prerequisites

* [X] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [X] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [X] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

When using the following command, the processes crashes (without docker's `-t`):
`sudo docker run -i --rm -v $(pwd):/workdir -w /workdir pixivutil2 /bin/bash -c "python PixivUtil2.py -s 2 $1 -x"`

with the error
```
Traceback (most recent call last):
  File "PixivUtil2.py", line 1419, in <module>
    main()
  File "PixivUtil2.py", line 1221, in main
    set_console_title()
  File "PixivUtil2.py", line 933, in set_console_title
    PixivHelper.set_console_title(set_title)
  File "/workdir/PixivHelper.py", line 346, in set_console_title
    sys.stdout.write(f"\x1b]2;{title}\x07")
  File "/usr/local/lib/python3.8/site-packages/colorama/ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "/usr/local/lib/python3.8/site-packages/colorama/ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "/usr/local/lib/python3.8/site-packages/colorama/ansitowin32.py", line 184, in write_and_convert
    text = self.convert_osc(text)
  File "/usr/local/lib/python3.8/site-packages/colorama/ansitowin32.py", line 257, in convert_osc
    winterm.set_title(params[1])
AttributeError: 'NoneType' object has no attribute 'set_title'

```

### Steps to Reproduce

1. Run utility with docker
2. Remove the `-it` because you plan to run this as a child process of another program
3. Notice crash

**Expected behavior:** 
I expect the program to work as normally, not requiring any form of input.

**Actual behavior:** 
It crashes

### Versions

`PixivDownloader2 version **20210215-beta1`

**Comment by Lachee** [comment]
This is an issue with node.js, not this library.

` child_process.execFileSync(downloadsh, [ id ], { cwd: process.env.PIXIV2UTIL_DIR, stdio: 'inherit' });`

the `stdio` needs to be specified, as per https://github.com/shelljs/shelljs/wiki/FAQ#running-interactive-programs-with-exec
