### ISSUE TITLE
Unable to run, if console is not present

### ISSUE THREAD

**Issue by FluffyDiscord** [Nandaka/PixivUtil2#962]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

I am unable to call the script from a PHP app. I guess it want's a console, but none is present, obviously. It fails with the following:

```log
Traceback (most recent call last):
  File "/var/www/music/bin/PixivUtil2/PixivUtil2.py", line 1419, in <module>
    main()
  File "/var/www/music/bin/PixivUtil2/PixivUtil2.py", line 1221, in main
    set_console_title()
  File "/var/www/music/bin/PixivUtil2/PixivUtil2.py", line 928, in set_console_title
    PixivHelper.set_console_title(set_title)
  File "/var/www/music/bin/PixivUtil2/PixivHelper.py", line 376, in set_console_title
    sys.stdout.write(f'\33]0;{title}\a')
  File "/usr/local/lib/python3.7/dist-packages/colorama/ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "/usr/local/lib/python3.7/dist-packages/colorama/ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "/usr/local/lib/python3.7/dist-packages/colorama/ansitowin32.py", line 184, in write_and_convert
    text = self.convert_osc(text)
  File "/usr/local/lib/python3.7/dist-packages/colorama/ansitowin32.py", line 257, in convert_osc
    winterm.set_title(params[1])
AttributeError: 'NoneType' object has no attribute 'set_title'
```

### Steps to Reproduce

Raspberry Pi 4, with Raspbian OS (linux)

1. get php 7.4
2. run snippet bellow:
```php
<?php

shell_exec("/usr/bin/python3 /pathToPixivUtil2/PixivUtil2.py -s 8 -p y --sp=1 --ep=1");
```
3. get the error above

**Expected behavior:** run

**Actual behavior:** fail :)

### Versions

20210421

**Comment by Nandaka** [comment]
well it supposed to be run from console. I don't use linux so I have no idea how to fix it.

**Comment by FluffyDiscord** [comment]
I think you can reproduce it on a windows machine as well.

**Comment by Nandaka** [comment]
windows won't even hit that line
https://github.com/Nandaka/PixivUtil2/blob/master/PixivHelper.py#L369-L377
