### ISSUE TITLE
Unable to download "OSError('Truncated File Read')" on certain images

### ISSUE THREAD

**Issue by PatrickL546** [Nandaka/PixivUtil2#977]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

As title says. 9001 = Download Failed: Harddisk related.
But don't know how to fix it

### Steps to Reproduce

1. Select 2.  Download by image_id
2. Enter 41318178

**Expected behavior:** Downloads the file

**Actual behavior:**
 ```
Image invalid, deleting...
Traceback (most recent call last):
  File "C:\Users\Redacted\AppData\Local\Programs\Python\Python39\lib\site-packages\PIL\PngImagePlugin.py", line 940, in load_end
    self.png.call(cid, pos, length)
  File "C:\Users\Redacted\AppData\Local\Programs\Python\Python39\lib\site-packages\PIL\PngImagePlugin.py", line 187, in call
    return getattr(self, "chunk_" + cid.decode("ascii"))(pos, length)
AttributeError: 'PngStream' object has no attribute 'chunk_   I'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Redacted\PixivDownloadHandler.py", line 190, in download_image
    img.load()
  File "C:\Users\Redacted\AppData\Local\Programs\Python\Python39\lib\site-packages\PIL\ImageFile.py", line 266, in load
    self.load_end()
  File "C:\Users\Redacted\AppData\Local\Programs\Python\Python39\lib\site-packages\PIL\PngImagePlugin.py", line 949, in load_end
    s = ImageFile._safe_read(self.fp, length)
  File "C:\Users\Redacted\AppData\Local\Programs\Python\Python39\lib\site-packages\PIL\ImageFile.py", line 568, in _safe_read
    raise OSError("Truncated File Read")
OSError: Truncated File Read
Error at download_image(): (<class 'OSError'>, OSError('Truncated File Read'), <traceback object at 0x000001A2254E7E40>) at https://i.pximg.net/img-original/img/2014/02/01/17/28/23/41318178_p0.png (9001)
```

### Versions 
20210702 Running from source

**Comment by Nandaka** [comment]
set `verifyimage = False` in config.ini, looks like the author upload corrupted png file

**Comment by PatrickL546** [comment]
> set `verifyimage = False` in config.ini, looks like the author upload corrupted png file

It works. Thanks
